### ISSUE TITLE
[V2ex-Enhanced] 希望添加查看at的人回复内容

### ISSUE THREAD

**Issue by otakustay** [XIU2/UserScript#114]
阅读一个比较长的讨论时，往往看到一个at他人的回复，却不知道at的那个人说了啥，是比较难受的。某个Chrome插件有这个功能

<img width="385" alt="CleanShot 2021-11-01 at 16 22 48@2x" src="https://user-images.githubusercontent.com/639549/139642817-52ef070a-8401-4f1b-98e7-7474c7a57cef.png">

不过如果能用user script实现类似的效果，会更友好（比如支持Safari等）

我简单写了一个“鼠标移到at内容上找到对应的回复文本”的脚本（几乎未考虑浏览器兼容性），还缺把它显示在页面上的popover等交互，不知是否有意将此功能添加到这个脚本中

```js
const replyListElement = document.querySelectorAll('#Main > .box')[1];

const isFromUser = user => element => {
    const label = element.querySelector('strong > a.dark');
    return label && label.innerText.trim() === user;
};

replyListElement.addEventListener(
    'mouseover',
    e => {
        if (e.target.nodeName !== 'A') {
            return;
        }

        const href = new URL(e.target.href, document.URL);

        if (!href.pathname.startsWith('/member/')) {
            return;
        }

        const user = href.pathname.split('/').pop();
        const currentReplyElement = e.target.closest('div.cell');
        const replyElements = [...replyListElement.children];
        const previousReplyElements = replyElements.slice(0, replyElements.indexOf(currentReplyElement)).reverse();
        const nearestReplyElement = previousReplyElements.find(isFromUser(user));
        const replyContent = nearestReplyElement.querySelector('.reply_content').innerText.trim();
        // replyContent
    }
);
```

**Comment by otakustay** [comment]
> 一个是如果被 at 的用户回复内容在其他页怎么办？

不显示任何内容，鼠标移上去没有任何额外交互。配合这个脚本的

> 比如用户 A 发了好几个回复，用户 B 回复用户 A 时，别人并不知道到底回复的是用户 A 的哪条内容。

只显示看看好用不最近的一条

功能非常死，没什么特别情况的考虑。我也是试了一下发现v2ex各种DOM上都缺标记精确定位，确实很烦。如果作者没有兴趣，我想也很正常，可以关闭issue

**Comment by XIU2** [comment]
我觉得要搞就要搞完美，否则就太别扭了~
然而这些问题都没有完美解决方案。。。
因此当初我收到需求后，研究半天最后还是选择放弃了。

**Comment by liebkne** [comment]
这是不是有点完美主义…因噎废食…我觉得firefox上的就挺好的，虽然没有你说的那么完美…但至少能看，不用一条一条翻
