### ISSUE TITLE
【知乎增强】 显示不完整

### ISSUE THREAD

**Issue by wangliangliang2** [XIU2/UserScript#115]
<img width="885" alt="image" src="https://user-images.githubusercontent.com/20638550/139999560-41a489f7-98ee-482e-b347-3966970784ce.png">
 如图，在Safari上功能点太多，无法滚动导致上面的【一键收起】功能点之上都看不到，希望有空的时候能改进下？

**Comment by XIU2** [comment]
对于 Safari 的问题无法解决，这属于 Safari 浏览器的问题~
甚至大部分 Safari 版本都无法在知乎上运行油猴脚本呢（参考 #107 ）

**Comment by wangliangliang2** [comment]
啊，你这么着急把issue关掉作啥呢？
CSP的问题，我研究把这个响应头去掉了，应该不存在这个https://github.com/XIU2/UserScript/issues/107 这个问题的

**Comment by wangliangliang2** [comment]
> 对于 Safari 的问题无法解决，这属于 Safari 浏览器的问题~
> 甚至大部分 Safari 版本都无法在知乎上运行油猴脚本呢（参考 #107 ）

啊，你这么着急把issue关掉作啥呢？
我已经利用VPN把这个知乎响应头的CSP去掉了，应该已经不存在 #107 这个问题的

**Comment by XIU2** [comment]
我**没有 MAC 设备**，因此也**没有 Safari 浏览器**，无法针对性优化。

用 Safari 浏览器的人相比其他本来就少，再加上 CSP 这个大坑。。。
而你说的这个解决 CSP 的方法显然无法普及到大部分人，因此最终能在 Safari 上用到我这个知乎增强脚本的人寥寥无几。

因此没有折腾的动力~

**Comment by wangliangliang2** [comment]
哎，只能说谢谢开发插件了。另外 没有 MAC 设备 其实可以装虚拟机解决。
另外，你好像没看我问题，太着急着回答了，上面的问题好像是因为油猴本身的显示没有加scrollview来容纳开发者的插件导致的。
我在chrome上测试了下是可以滚动的。

**Comment by XIU2** [comment]
虚拟机？没兴趣折腾，毕竟我一年也用不到几次。

你这个问题是 Tampermonkey 的问题吧，缺少滚动条。
如果我去解决该问题，那就只能去**重写脚本菜单功能**，放弃脚本自带的脚本菜单功能，自己实现一套插入到网页中才行，但是比较费时间，且影响的用户太少，所以懒得搞。。。
我脚本选项是多了点，但选项多的脚本也很多，你总不能**遇到一个就让脚本作者去改一个**吧。

因此最好的解决方法是向 Tampermonkey 作者反馈该问题，让其修复。

或者你可以尝试在脚本 `[存储]` 选项卡中手动修改脚本配置文件（各功能的开关什么的）：
![01](https://user-images.githubusercontent.com/54703944/140023085-bbb5088c-2f32-45b4-aa03-0b533d5ef648.png)
