### ISSUE TITLE
[自动无缝翻页] 希望漫画页能加个间隔，不然看起来有点乱，分不清

### ISSUE THREAD

**Issue by huaqianghua** [XIU2/UserScript#116]
![QQ截图20211105183310](https://user-images.githubusercontent.com/9127005/140497521-b39fd5ff-daff-4be8-899b-bd5627ee7ca9.png)

**Comment by XIU2** [comment]
中间不是有缝吗？
而且我这个脚本叫做 “自动无缝翻页” 欧~

**Comment by huaqianghua** [comment]
好吧 那个缝是调了之后的效果，我是想如果脚本加上的话，那我以后更新就不用再改了

**Comment by XIU2** [comment]
就像我说的，你装个 Stylus 扩展就行了，对这些漫画网站添加一些自定义 CSS 样式来控制间隔。

**Comment by huaqianghua** [comment]
好的 谢谢！
