### ISSUE TITLE
吾爱签到脚本无法自动签到了

### ISSUE THREAD

**Issue by kudoushinichi6671** [XIU2/UserScript#117]
最近在360浏览器发现自动签到脚本不能签到了，希望能够修复下

**Comment by XIU2** [comment]
已经更新修复了。

吾爱论坛前几天改了签到机制，做了一些特殊处理（签到页面 JS 加密什么的），导致直接后台访问签到页面的方案失效。
前天就发现了，不过因为一天只能签到一次的原因，为了测试几种新方案，直到今天才完成最后一次验证性测试。
