### ISSUE TITLE
[吾爱破解论坛增强 - 自动签到、翻页]自动签到功能已失效

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#118]
win10 chrome92上，油猴4.13打开脚本后，提示无法自动签到。上个星期还行的。

**Comment by XIU2** [comment]
问题重复了，今天早上已经更新脚本了。

**Comment by lyjhyjyes** [comment]
> 问题重复了( #117 )，今天早上已经更新脚本了。

哦哦，前天想反馈，忘了。谢谢

**Comment by XIU2** [comment]
前天我就发现了，不过因为一天只能签到一次，导致我每次测试都有 1 天的冷却时间。。。
