### ISSUE TITLE
[自动无痕翻页] 希望添加翻页网站

### ISSUE THREAD

**Issue by ye0015** [XIU2/UserScript#119]

**Comment by ye0015** [comment]
http://www.wendangku.net/topics/10/ 文档网,谢谢

**Comment by XIU2** [comment]
是要文章内的翻页吗？

**Comment by XIU2** [comment]
已添加支持~

**Comment by ye0015** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        thanks
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                1811724317
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年11月7日 ***@***.***> 写道： 




已添加支持~



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
