### ISSUE TITLE
请求做一个艾泼热网站的无缝翻页

### ISSUE THREAD

**Issue by clayl** [XIU2/UserScript#12]
你好，如果方便的话，望能够一个像423down那样的艾泼热网站的无缝翻页。网址https://apphot.cc/，是原烈火汉化主页。现在改名了！谢谢！

**Comment by XIU2** [comment]
我把 [423down 增强] 脚本改名为 [自动无缝翻页] 了。
对于只需要 自动无缝翻页 功能的网站，以后专门放到该脚本里。

- 已新增 [Apphot(原烈火汉化)] 支持。

https://greasyfork.org/zh-CN/scripts/419215

**Comment by clayl** [comment]
NICE。谢谢！目前423down和烈火汉化完美支持!谢谢！
