### ISSUE TITLE
[知乎增强] 支持一下 GreaseMonkey？

### ISSUE THREAD

**Issue by lilydjwg** [XIU2/UserScript#120]
GreaseMonkey 现已没有 GM_* 系列对象，取而代之的是 [GM.* 系列对象](https://wiki.greasespot.net/Greasemonkey_Manual:API)。请求兼容一下？

**Comment by XIU2** [comment]
我讨厌兼容~
懒得搞，现在还有人在用 GreaseMonkey 么？
我平时见到的基本上都是 Tampermonkey、Violentmonkey 了。
