### ISSUE TITLE
[自动无缝翻页] 显示总页数

### ISSUE THREAD

**Issue by seiuneko** [XIU2/UserScript#121]
脚本体验很棒，赞一个先，谢谢作者。
<br>
有时候刷论坛时，如果楼太高会不想爬了，这时候旁边如果有总页数显示就不用回到顶部查看了。

**Comment by XIU2** [comment]
我不想做，因为要实现这样的效果，我需要对目前三百多个规则分别补充一个 [总页数] 规则（总页数所在元素，用来获得总页数）。
就像我当初加当前页码时，只做出了显示翻了几页的效果，而不是真实页码（比如直接打开第 3 页，左下角页码依然显示的是 1，没翻 1 页就 +1），就是因为要实现真实页码，就需要对每个规则补充一个 [当前页数] 规则（当前页码所在元素），而这个工作量太大了。
