### ISSUE TITLE
[自动无缝翻页] 当Google中含有youtube视频时，预览页面会覆盖整个条目

### ISSUE THREAD

**Issue by NextAlone** [XIU2/UserScript#123]
如图所示，并且在灰色叠加层区域点击会跳转视频
![image](https://user-images.githubusercontent.com/12210746/142738859-a27b9caa-0304-4bc3-97b7-78e4639ebeba.png)

**Comment by XIU2** [comment]
已修复~

**Comment by NextAlone** [comment]
感谢
