### ISSUE TITLE
[知乎美化] 未打开暗黑模式但在文章编辑界面仍出现阴影

### ISSUE THREAD

**Issue by bjyh345** [XIU2/UserScript#124]
大佬你好，昨天我在GreasyFork上反馈了这个问题，今天上去却发现我被封号了，说我发送垃圾信息- -
我上次没说清楚，是在创作中心->内容管理->编辑已发布的文章时出现阴影。我只装了知乎美化和知乎增强两个脚本，关闭知乎美化脚本后就恢复正常。
图片如下：
![内容管理](https://user-images.githubusercontent.com/71574698/142745237-a97a6c98-5acc-4b55-a849-7c7bd9e8d291.png)
![阴影](https://user-images.githubusercontent.com/71574698/142745244-2a92abc6-8a68-400b-9181-f90d785f1246.png)

**Comment by XIU2** [comment]
你那个反馈，我昨天就回复你了，不过几十分钟后突然就没了。。。也不知道你看到没有。

你说的情况我无法复现，暗黑模式 1 打开 与 关闭：
![01](https://user-images.githubusercontent.com/54703944/142745735-c89a2f8a-3841-41aa-a5f9-7976bcb7ff0e.png)

![02](https://user-images.githubusercontent.com/54703944/142745736-bbabf63e-7522-4940-adcc-66de67275d6f.png)

**Comment by XIU2** [comment]
你这个只需要右键检查一下元素样式应该就能知道原因了，如果你不懂这方面的话，我可以远程协助帮你看看。

**Comment by bjyh345** [comment]
今天下午重新试了下发现又正常了- -好奇怪
下次再出现的话我发样式给你，麻烦了
