### ISSUE TITLE
[知乎增强]希望添加「一键展开所有回答」的功能

### ISSUE THREAD

**Issue by LoneFireBlossom** [XIU2/UserScript#125]
目前脚本有「一键收起所有回答」，希望能添加一个「一键展开所有回答」，无论是新按钮，还是复用「收起」的按钮我觉得都可以。
使用场景是，很多时候我都想保存网页到本地，这个需求是越来越强烈，收藏夹是越来越不可靠了。如果是看上了两个以上的长回答，为了保存，我肯定得把回答都展开才行；目前就得点击油猴-插件里选择关掉「默认收起回答」再刷新，再等一会儿网页加载，然后才能保存。保存完之后再把功能打开。这样显然是有点儿麻烦，所以希望能添加这样一个功能。

**Comment by XIU2** [comment]
我都是各种想办法给收起回答。。。
你这个需求的话，不需要油猴脚本，一小段代码就行了，我给你写下，你加到书签里，需要的时候点一下就会全部展开了。

**Comment by XIU2** [comment]
试了试，应该满足你的要求了。
添加书签，地址就写下面这行 JavaScript 代码，需要的时候点一下就会全部展开当前网页下的回答。
```
javascript:(function(){document.querySelectorAll('button.ContentItem-rightButton.ContentItem-expandButton').forEach(function(one){one.click();})})()
```

**Comment by LoneFireBlossom** [comment]
试了试确实可以（Safari也能用），谢谢开发者大大
