### ISSUE TITLE
github增强脚本 好像只能提高下载速度，并不能提高github的访问速度

### ISSUE THREAD

**Issue by voynich-chen** [XIU2/UserScript#127]
github增强脚本 好像只能提高下载速度，并不能提高github的访问速度；
有没有方便快速打开github的脚本，现在本地换host太不方便，而且并不稳定；有时改完host当时能打开，过几天又废了

**Comment by XIU2** [comment]
当然不可能实现啦。
因为油猴脚本只有在网页打开后才会运行，怎么可能反向去影响网页访问速度呢。。。

访问不稳定是因为 Github 今年初被**随机 SNI 干扰**了，具体情况我在 [V2EX](https://www.v2ex.com/t/758568) 里说过。
免翻的解决方法是：https://github.com/docmirror/dev-sidecar （我在 greasyfork 脚本介绍页也写了）。
