### ISSUE TITLE
[UAC白名单v1.8]win10下使用uac白名单，系统反而提示UAC白名单需要权限，感觉怪怪

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#129]
比如QQ.exe生成快捷方式，都会弹出uac白名单需要权限，点击确定。才能生成QQ.exe快捷方式。
感觉每次唤醒UAC白名单需要权限，反而不太科学

**Comment by XIU2** [comment]
请在 [相关项目](https://github.com/XIU2/UACWhitelistTool) 下发 Issues。

**Comment by lyjhyjyes** [comment]
> 请在 [相关项目](https://github.com/XIU2/UACWhitelistTool) 下发 Issues。
> 
> 打开 UAC 白名单小工具是必须要有**管理员权限**的，这是系统限制（否则无法创建系统计划任务），但是打开通过 UAC 白名单小工具生成的**快捷方式是不需要管理员权限**的，因此你可以**把 UAC 白名单小工具自身加入白名单**。

明白
