### ISSUE TITLE
建议更换 GitHub icon 地址

### ISSUE THREAD

**Issue by ivysrono** [XIU2/UserScript#13]
https://github.githubassets.com/favicon.ico 可能无法获取，建议换个国内镜像。

**Comment by XIU2** [comment]
emmm  
这只是 Tampermonkey 脚本管理器里显示的脚本图标而已，显示不显示都没什么影响。

**Comment by ivysrono** [comment]
我知道，但Violentmonkey会报错，看得烦

**Comment by XIU2** [comment]
那你为什么不用 Tampermonkey 呢？
目前这三个脚本管理器，作为脚本开发者，我认为 Tampermonkey 是最好的。
所以我不会去特意兼容其他的脚本管理器。

**Comment by XIU2** [comment]
Greasemonkey 是最早的脚本管理器，但是已经过时了。
Violentmonkey 则取巧兼容 Greasemonkey 和 Tampermonkey，结果反而搞得不伦不类。。。
Tampermonkey 是我认为现在最好的脚本管理器了。

**Comment by ivysrono** [comment]
原因很多啦。随便说几个。
TM不开源——不清楚近况。
TM不支持Onedrive同步。
VM作者是国人，反馈问题比较方便。
而且也没有必须用TM才能实现的功能吧。
主要是我觉得icon这种事既然大家都兼容那就兼容大家。
而且这个脚本本来就是为了加速的，用一个无法访问的地址就与目的冲突了。
当然你是作者，尊重你的意见。

**Comment by XIU2** [comment]
那你提供个国内镜像地址吧。
我访问是正常的，而且也仅仅是个图标罢了。

**Comment by ivysrono** [comment]
直接用GitHub官方的地址呢 https://github.com/fluidicon.png

**Comment by XIU2** [comment]
都是官方的地址，有什么区别么。。。

**Comment by ivysrono** [comment]
你去看看某著名列表，github.com 是可以直接访问的，github.githubassets.com 就在列表内。
如果 github.com 都被干了……

**Comment by XIU2** [comment]
我找了找，改成 https://github.com/favicon.ico 这个图标吧，1.8 KB 大小。

**Comment by ivysrono** [comment]
谢谢啦。
话说你觉得VM比TM差在哪里呢。

**Comment by XIU2** [comment]
不知道，我都没用过 Violentmonkey。
最早用的是 Greasemonkey，结果坑很多，就改用 Tampermonkey 了。  

到后来我自给自足写脚本的时候，就直接用 Tampermonkey 了，当时查了查用哪个好，大家都推荐使用 Tampermonkey，我也就一直用着 Tampermonkey 了。

****

脚本已经更新了，不过这点小事就没有递增版本号，你可能需要重新安装一下才行，或者你直接手动修改脚本内的图标 URL。

**Comment by ivysrono** [comment]
其实这么久了，我碰到的只兼容TM的脚本也就一个：https://github.com/xxxily/h5player/issues/67
话说我也自己写了一堆乱七八糟的自用脚本，维护的时候碰到一个困扰：究竟是按照网站分类还是按照功能分类。
既要考虑到别人使用时只想要在个别网站生效，又不想自用时安装一大堆。
我看你都是按照网站来的？

**Comment by XIU2** [comment]
我写的这些脚本，一开始都是自用的，但是我这个人喜欢分享，所以我后来不知道分享什么，就突然想起来我还写过一些油猴脚本，就整理规范了一下就公开了。
因为一开始都是自用的，都写得很随意，功能也不多，也是后来大家反馈才变成现在这样。

我觉得分功能还是分网站，要取决于脚本功能。

比如前段时间给一个软件分享站写了个自动无缝翻页脚本，本来是只针对这个网站的，结果另一个同类网站看到了也想要，我就给做成一个脚本了，而不是傻傻的每个网站写一个脚本，毕竟除了翻页规则外，其他脚本内容是完全一样的。

像这种就是按功能分类，一个脚本负责一些功能，覆盖一些网站。

**Comment by XIU2** [comment]
还有就是那些我写的常去论坛的增强脚本，不同论坛功能上有差异，这种最好是分开比较好，这样脚本结构比较简单。

**Comment by ivysrono** [comment]
那看来我们的操作差不多。
欢迎指导哈：https://github.com/ivysrono/iWebExtension
其实还有个办法是做个选项，不想要用的可以禁用。
