### ISSUE TITLE
[自动无缝翻页] 希望添加steam搜索无限翻页的功能

### ISSUE THREAD

**Issue by whyjxz14** [XIU2/UserScript#130]
steam搜索页

> https://store.steampowered.com/search/?term=

开启实验室的

> https://store.steampowered.com/account/preferences/
启用搜索时无限滚动后。需要无限翻页功能
尤其是安装了Augmented Steam插件以后

> https://chrome.google.com/webstore/detail/dnhpnfgdlenaccegplpojghhmaamnnfp
就更加需要了

**Comment by XIU2** [comment]
启用搜索时无限滚动，这不是已经自带了吗？而且还是默认开启的好像（反正我没改过这个设置）。

**Comment by whyjxz14** [comment]
> Steam 不是已经自带 [启用搜索时无限滚动] 功能了吗？而且好像还是默认开启的（反正我没改过这个设置，都不知道）。

他只是往下滚无限滚动翻页。没有自动帮你一直翻。尤其是开了Augmented Steam，用了筛选。有时候整页都被筛选掉了。自己转半天一个也看不到。这个页面最好能自动帮你翻一定页数

**Comment by XIU2** [comment]
`他只是往下滚无限滚动翻页。没有自动帮你一直翻。`
这不是一个意思吗？
无限滚动不就是无限加载更多内容吗？

**Comment by XIU2** [comment]
而且你开了 Augmented Steam 导致 Steam 原生自动无缝翻页功能失效的话，你不应该去找 Augmented Steam 作者反馈吗？

这明显是 Augmented Steam 自身设计与 Steam 兼容性的问题。

**Comment by whyjxz14** [comment]
> `他只是往下滚无限滚动翻页。没有自动帮你一直翻。` 这不是一个意思吗？ 无限滚动不就是无限加载更多内容吗？这不就是自动无缝翻页吗？本质是一样的呀。

他是你滚下去帮你加载。现在要不往下滚的时候就一直帮你加载。不然的话。开了虽然他帮你加载了一页。但是都不符合你在Augmented Steam设置的筛选所以都被隐藏了。所以都没出来。你就要滚到最下面然后滚他才能继续加载。
所以现在最好能不用你滚下去就一直让他滚和加载。无限加载或者加载个20页左右再停。这样。

**Comment by XIU2** [comment]
但是我的脚本实现的原理和效果和 Steam 的一样呀。

我们都是，监听滚动条，当滚动条到指定距离时，获取下一页内容并插入本页底部。

既然你非要用 Augmented Steam ，而且这个问题也是 Augmented Steam 导致的问题，那么不去找 Augmented Steam 作者反馈就很奇怪。。。

**Comment by whyjxz14** [comment]
> 但是我的脚本实现的原理和效果和 Steam 的一样呀。
> 
> 我们都是，监听滚动条，当滚动条到指定距离时，获取下一页内容并插入本页底部。
> 
> 既然你非要用 Augmented Steam ，而且这个问题也是 Augmented Steam 导致的问题，那么不去找 Augmented Steam 作者反馈就很奇怪。。。

我知道。但是。我是说steam自带的这个只先帮你滚了3页。然后当你滚到最后一页再帮你自动滚一页。太少了。
最好能多滚几页。然后在你往下滚到倒数3-5页就开始帮你继续滚。这样用起来更方便。因为steam搜索不像知乎。看起来很快。只滚一页太少了不够。最好能优化一下

**Comment by XIU2** [comment]
Steam 已经自带了**自动无缝翻页**功能，因此我不可能费力不讨好的再去实现一遍。
我费力半天只是为了帮 Augmented Steam 作者解决这个问题么？。。。图啥呢~

**Comment by whyjxz14** [comment]
> Steam 已经自带了**自动无缝翻页**功能，因此我不可能费力不讨好的再去实现一遍。 我费力半天只是为了帮 Augmented Steam 作者解决这个问题么？。。。图啥呢~

即使没有augmented steam。他自带的这个到最后一页才开始滚也太慢了。经常需要等他加载。因为图片比较多。

**Comment by XIU2** [comment]
这就不管我的事情啦。
我不会重复造轮子的，对于一个已经支持自动无缝翻页的网站，我不可能再去实现一遍的。

而且我实现的效果也不会比 Steam 自带的更完美，比如：
- 可能会导致一些事件缺失（比如添加到愿望单等按钮，悬浮显示游戏截图信息等），
- 加载速度相比可能会慢一点（因为是访问完整的下一页，再截取主体内容，而 Steam 只是访问现成的 API 接口），
- 唯一的好处就是可以把加载触发线调的更高。
