### ISSUE TITLE
[自动无缝翻页] 自动无限翻页在feedback页面最好不要生效

### ISSUE THREAD

**Issue by whyjxz14** [XIU2/UserScript#131]
自动无限翻页在feedback页面最好不要生效或者将发表评价、评论或提问加载在前面。
例如在
[自动无缝翻页](https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5/feedback)
不然的话反馈太多要翻好久才能到评论的地方。

**Comment by XIU2** [comment]
你可以点击左下角的页码，可以暂停翻页的。
