### ISSUE TITLE
[自动无缝翻页 ]  Xiuno BBS 帖内翻页问题

### ISSUE THREAD

**Issue by rcyggdra** [XIU2/UserScript#132]
https://bbs.oldmanemu.net/thread-12323.htm
浏览帖内评论时，自动翻页会把首页的20层留言放在了最底下，而不是接着20层之后再拼接翻页
![image](https://user-images.githubusercontent.com/8652464/143870216-f5c6ebfd-da59-4dd8-825a-a52fdc113867.png)

**Comment by XIU2** [comment]
我这边好像正常？
![01](https://user-images.githubusercontent.com/54703944/143875967-75fe6407-52c0-448c-8a9e-bc6e6eeda90e.png)

**Comment by XIU2** [comment]
难道是因为我没有登录账号？
或许登录账号后，网页元素发生了变化？

**Comment by XIU2** [comment]
我尝试优化了下选择元素的规则，你更新脚本后再试试。

**Comment by rcyggdra** [comment]
确实，没登录显示正常；
更新了脚本，问题还在，会不会是那个登录后回复框的元素问题？

**Comment by XIU2** [comment]
回复框的元素类目和结构和上面的帖子回复区元素是很相似的，出现这种问题说明是把插入位置选作回复框元素的后面了，而正常情况下应该是在帖子回复区元素的后面。

你右键这个回复框，选择 **检查**，然后把弹出的开发者工具拉大一点（免得我看不完整）截图给我看看。

**Comment by XIU2** [comment]
你看，这个结构是很相似的，应该是登录后这个样式变了，导致把回复框元素也识别成帖子回复区元素了。
![01](https://user-images.githubusercontent.com/54703944/143893697-5578bff0-1e41-40c0-979e-9b9db807f8d1.png)

**Comment by XIU2** [comment]
我看了下这网站注册很随便，我找个临时邮箱进去看看吧~

**Comment by XIU2** [comment]
看了下，解决了，已更新脚本~
