### ISSUE TITLE
[自动无缝翻页] 自动翻页功能失效

### ISSUE THREAD

**Issue by epoweripione** [XIU2/UserScript#133]
自动无缝翻页 3.9.1 运行出错：`TypeError: GM_getValue(...).indexOf is not a function`
![image](https://user-images.githubusercontent.com/16471398/143972606-32148dde-e71e-49c1-a62f-14e45b4772b5.png)
![image](https://user-images.githubusercontent.com/16471398/143972659-520084fc-128e-4c72-a1c6-b9d5e3a941e9.png)

跟踪了一下 `GM_getValue('menu_disable')` 返回了一个 `object` 对象而不是数组，不清楚为何，可否优化为如下代码？
```javascript
let list = GM_getValue('menu_disable');
if (!Array.isArray(list)) list = Object.values(list);
``` 

运行环境：
Windows 10 21H2 19044.1387（64位）
Chrome canary 98.0.4736.0
Tampermonkey BETA 4.14.6147

**Comment by XIU2** [comment]
这是 Tampermonkey BETA v4.14.6147 的 BUG，v4.14.6148 已经修复了。

**Comment by XIU2** [comment]
昨天有个人也遇到了这个问题，我也是研究半天才发现是 BUG，Chrome 商店里的还没有更新到最新版本。
https://greasyfork.org/zh-CN/scripts/419215/discussions/107079

**Comment by epoweripione** [comment]
收到，我也是研究了半天，被坑了！！😂😂
辛苦了，谢谢！👍👍
