### ISSUE TITLE
[知乎增强] Tampermonkey BETA v4.14.6147 BUG

### ISSUE THREAD

**Issue by Hamakaze1s** [XIU2/UserScript#134]
RT，视频/文章均无法屏蔽，尝试重新安装无效。

**Comment by XIU2** [comment]
没有失效，我这边测试一切正常，如果失效的话，首页最少有一个视频。
![01](https://user-images.githubusercontent.com/54703944/144061517-942b5449-9d58-4c42-86fd-fbf3f742a5f6.png)

**Comment by XIU2** [comment]
因此请提供更多信息，比如：
浏览器是什么？脚本管理器是哪个？版本号是多少？

**Comment by Hamakaze1s** [comment]
Chrome  96.0.4664.45
TamperMonkey Beta v4.14.6147
![image](https://user-images.githubusercontent.com/50857024/144062290-0eaaa3f2-bfda-4be9-80f4-13cf9bb2bf54.png)

**Comment by XIU2** [comment]
这个是 Tampermonkey BETA 的 BUG 导致的，这两天四五个人反馈脚本报错，都是因为这个 v4.14.6147 版本导致的。

**Comment by XIU2** [comment]
比如 #133 、https://greasyfork.org/zh-CN/scripts/419215/discussions/107079

这是 Tampermonkey BETA v4.14.6147 的 BUG，v4.14.6148 已经修复了（官网更新日志写了）。
因此不建议使用 BETA 版本，太多问题了~

```
Fix GM_getValue with array type values
```

https://www.tampermonkey.net/changelog.php?ext=dhdg&show=gcal

**Comment by Hamakaze1s** [comment]
更换稳定版后问题解决，谢谢

**Comment by XIU2** [comment]
这么多人用 Tampermonkey BETA 版本吗？我以前用过一次当时就碰到一个 BUG，然后就改回正式版了。。。
而且 Tampermonkey 在商店页面介绍里用中文写了可能会存在错误的提示。

我觉得我有必要单独发个 Issues 并置顶说明一下，免得源源不断的有人不知情的。。。
