### ISSUE TITLE
[自动无缝翻页] Pixiv 用户的作品页失效

### ISSUE THREAD

**Issue by H4M5TER** [XIU2/UserScript#137]
我访问的网页： https://www.pixiv.net/users/648285/illustrations
预期行为：插画正常滚动
问题行为：直接把下一页从头到尾拼接在底部了

**Comment by XIU2** [comment]
我试了下没什么问题呀，本来就是这样设计的，动态加载内容的网站只能这样实现。

**Comment by XIU2** [comment]
为了实现不同网站的自动无缝翻页功能，我前前后后做了 6 个翻页模式：
```
1 = 由脚本实现自动无缝翻页（适用于：静态加载内容网站，常规模式）
2 = 只需要点击下一页按钮（适用于：网站自带了 自动无缝翻页 功能）
3 = 依靠 [基准元素] 与 [浏览器可视区域底部] 之间的距离缩小来触发翻页（适用于：主体元素下方内容太多 且 高度不固定时）
4 = 动态加载类网站（适用于：简单的动态加载内容网站）
5 = 插入 iframe 方式来加载下一页，无限套娃（适用于：部分动态加载内容的网站，需要允许 iframe 且支持通过 GET/POST 直接打开下一页）
6 = 通过 iframe 获取下一页动态加载内容插入本页，只有一个娃（适用于：部分动态加载内容的网站，与上面不同的是，该模式适合简单的网页，没有复杂事件什么的）
```

一开始我是为 Pixiv 设计了翻页模式 6，但是最终效果不太好，各 Tag 页面可能会出现加载图片失败的情况，而用户作品页更是完全无法加载图片，最后还是改用翻页模式 5 了。
但是这个翻页模式 6 后续在其他网站上还是发挥其作用了，例如： https://www.vilipix.com

对于**动态加载内容**的网站，想要实现自动无缝翻页**非常麻烦**，翻页模式 4 只适用于简单的网站（如漫画阅读页这种只是一些图片的），翻页模式 5、6 的虽然能解决部分动态加载内容的网站，但是要求比较严格，只适用于**少数网站**。

总的来说，对于动态加载内容的网站，**绝大部分**依然是**无法添加支持**的。

**Comment by H4M5TER** [comment]
我把插件关了试了下，感觉这个页面它现在的动态加载也算是很可以接受的，那么脚本可不可以配置对某些网页禁用

**Comment by XIU2** [comment]
对当前网站禁用，就点击脚本菜单里的 `[已启用 (点击对当前网站禁用)]` 选项。
对当前网页禁用，这个需要在 Tampermonkey 里去设置，扩展中点脚本后面的 ` > ` ，点击 `编辑`，选择 `设置`，在用户排除中添加 `https://www.pixiv.net/users/*` 规则。

**Comment by H4M5TER** [comment]
感谢指导
