### ISSUE TITLE
[Zhihu Enhance] 希望添加屏蔽页面侧边广告以及问题详情页的视频回答功能

### ISSUE THREAD

**Issue by stark-zhang** [XIU2/UserScript#138]
1. 页面侧边广告，很难用Adblock等插件屏蔽，如图中红线处
![image](https://user-images.githubusercontent.com/17326718/144638908-e1f6e1d2-3048-461f-b497-592c17352e7d.png)

2. 问题详情页中的视频回答，如图
![image](https://user-images.githubusercontent.com/17326718/144639072-b61251c5-3729-403b-ad40-a97b899db88d.png)

希望可以增加针对这两种情形的屏蔽，谢谢

**Comment by XIU2** [comment]
我的脚本不会添加广告屏蔽功能，这个交给专业的广告屏蔽扩展会更好。
我看了下我这边首页侧边栏的广告都已经被屏蔽了，随便我也不知道是哪个订阅广告规则列表干的。。。
```
EasyList 就不说了，你试试这个乘风的规则：
https://raw.fastgit.org/xinggsf/Adblock-Plus-Rule/master/rule.txt
```

**Comment by XIU2** [comment]
已更新脚本，新增 [屏蔽指定类别] 对回答页视频回答的支持。

**Comment by stark-zhang** [comment]
> 我的脚本不会添加广告屏蔽功能，这个交给专业的广告屏蔽扩展会更好。 我看了下我这边首页侧边栏的广告都已经被屏蔽了，随便我也不知道是哪个订阅广告规则列表干的。。。
> 
> ```
> EasyList 就不说了，你试试这个乘风的规则：
> https://raw.fastgit.org/xinggsf/Adblock-Plus-Rule/master/rule.txt
> 还有 AdGuard Chinese 规则，但是这是 uBlock 内置的，我找不到 URL
> ```

帮大忙了，thanks
