### ISSUE TITLE
[Github增强] Tampermonkey导出脚本再导入，Github增强失效

### ISSUE THREAD

**Issue by DazzlingGalaxy** [XIU2/UserScript#140]
前段时间重装了系统，win10换win11。重装之前在chrome的Tampermonkey BETA的管理面板->实用工具->压缩包->导出，导出了压缩包，里面含有我装的所有脚本。同时我也导出了edge的Tampermonkey的所有脚本。当时Github增强的版本是1.6.7。

重装之后，将原来的压缩包分别导入回去，edge正常(用的Tampermonkey正式版)，chrome没怎么用，以为也正常，直到这几天用的时候发现chrome上Github增强脚本失效，release页不显示加速的链接。昨天才更新过扩展，所以可能不是BETA版4.14.6147的问题。

我做了以下测试：
        ①首先怀疑版本问题，脚本安装页点击重新安装不行，删除脚本(类似回收站的地方没删，如图1，后来才发现那里也得删，但此时未发现未删)再清空缓存再重启浏览器再安装最新版，不行，最后一步装的时候还纳闷为什么显示重新安装，我刚才明明已经删除了；
        ②然后怀疑Tampermonkey BETA的问题，换回正式版，导入压缩包并更新，不行；
        ③再怀疑和其他扩展及脚本冲突，扩展只开启Tampermonkey正式版和IDM，脚本只开启Github增强，不行；
        ④然后我删除所有的脚本(同样未发现那个类似回收站的图标)，清缓存重启浏览器，导入压缩包，只开启Github增强，在我选中脚本，准备点"触发一次更新"时，我看到"重置到出厂状态"(如图2)，以前从未用过它，抱着试试的态度用了一次，**可以了**，不过版本号还是旧的，再更新到最新版，依然正常；
        ⑤为了测试上一步是否真的能解决问题，我又删了所有脚本。在我准备再导入压缩包时，我看到了那个类似回收站的图标，想到这几次测试都看到它了，以前从来没见过，好奇它是什么就点进去了，一看全是我刚删的脚本，怪不得这几次测试时，明明删了脚本，再安装时都显示"重新安装"，而不是"安装"。在这个类似回收站的地方里真正删除所有脚本后，再安装，安装页显示"安装"，而不是前几次测试时的"重新安装"了。安装后**正常**。
        ⑥最后，再次删干净脚本(类似回收站的地方也删了)，再导入压缩包，分别测试前面发现的两种修复方案，**均可行**。

问题总结：
**1**.新装chrome，新装Tampermonkey，为什么导入"之前从Tampermonkey(无论是否是正式版)导出的压缩包"后，Github增强脚本失效？releaes页不显示加速的链接。edge也是导入的压缩包，只不过用的从edge导出的包，但它就正常，chrome就有问题。
**2**.为什么导入压缩包后，选中脚本做"重置到出厂状态"操作，就能解决问题1？重置到出厂状态意味着什么？它对被选中的脚本做了什么操作？
**3**.删除脚本，但类似回收站那里不删除，再去脚本安装页，显示"重新安装"，为什么点击重新安装后无法解决问题1？
**4**.我记得以前Tampermonkey删除脚本后好像没类似回收站的东西，可能是某个版本新加的功能吧，也可能是以前我删脚本后没注意过。现在"重置到出厂状态"可以解决问题1，从类似回收站的地方删除脚本再安装，也可以解决问题1，这两种方法在原理上的相同点和不同点是什么？

![3](https://user-images.githubusercontent.com/26514820/145594112-4c99d5a5-b9eb-4d5d-8dd8-73e26d04b6fa.jpg)

![4](https://user-images.githubusercontent.com/26514820/145594126-d68ba182-1589-41a6-91d1-ed15975d51a4.jpg)

**Comment by XIU2** [comment]
这和我脚本无关吧，显然是 Tampermonkey 自身问题（或设计机制），这种问题你去问 Tampermonkey 作者才对吧。。。

**Comment by DazzlingGalaxy** [comment]
> 这和我脚本无关吧，显然是 Tampermonkey 自身问题（或设计机制），这种问题你去问 Tampermonkey 作者才对吧。。。

但chrome里的其他脚本正常，真就和你的脚本无关？就算无关，以后再有人问，你现在知道解决方法了。我没魔法，只用了hosts，github一会儿能打开一会儿不行，那些测试花了好几个小时。

**Comment by XIU2** [comment]
不知道呀，一般重装都能解决~
只要记得彻底删除脚本就行了。

**Comment by DazzlingGalaxy** [comment]
> 不知道呀，一般重装都能解决~ 只要记得彻底删除脚本就行了。

这不是以前我从没见过那个类似回收站的图标嘛，所以不知道还得从那删除。你可以在脚本介绍页添加这条，帮助后面遇到问题需要重装的人。

**Comment by XIU2** [comment]
而且你也说了，Edge 的就正常，Chrome 的不正常。
如果单纯只是我的脚本问题，不应该在所有浏览器上都不正常么？为什么只有 Chrome 上不正常？

至于 Tampermonkey 重置到出厂设置和彻底删除重新安装有什么区别，我也不知道呀，毕竟 Tampermonkey 不是开源的，这个只能去问作者，你问我也没用~

**Comment by XIU2** [comment]
回收站提示我会后续加到介绍里的。

**Comment by DazzlingGalaxy** [comment]
不知道就算了，没怪你的意思，我的英语水平也不够把这个问题描述清楚。更新介绍页帮助后面的人就好，这也是最初我反馈的目的之一。
我的习惯是，遇到问题了先尝试自己解决，因为直接问别人，别人不一定有时间帮你，甚至不一定理你。如果自己没解决，问的时候说自己做了哪些尝试，得到什么结果，这样别人在帮我解决之后，有时我还能获得问题之外的意外收获。
另外，反馈软件问题，不得需要详细说明问题、产生的场景、能否复现、复现步骤，这样能帮助开发人员更快定位问题。所以我测试清楚了再反馈。
当然，有你这样能直接帮助解决甚至远程的开发者，解决用户的问题的效率是最高的 :)
感谢回复 ^_^

**Comment by XIU2** [comment]
主要是，如果文字交流去解决一个问题的话，可能来来回回要**折腾几个小时甚至几天**（主要是交流间隔时间太长）。
而如果我直接远程协助的话，往往**几分钟**就能解决（毕竟大部分都是小问题）。

所以我一遇到描述不清楚的反馈（或者我无法复现），就会提出**远程协助**解决，这样更高效、更节省双方时间~
另外，远程协助后，我也会顺便向对方简单解释一下该问题的原因是什么（虽然对方可能不大懂或不在意）。
