### ISSUE TITLE
[Github 增强 - 高速下载] 希望添加 显示该仓库大小的 功能

### ISSUE THREAD

**Issue by zhuibo66** [XIU2/UserScript#141]
本来想自己写下，然后就上Greasy Fork，搜索到你的插件，觉得你写的很好，毕竟你的插件名称叫Github 增强，想着要是能集成到该插件中，那该是有多好，当然了没有也没有关系的。

如果可以的话，下面是我目前已经收集到的资料：

查看仓库信息的API：
请求方法：GET
请求地址：https://api.github.com/repos/organization/repository

其中的
organization替换为项目的【所有者(组织)】
repository替换为【项目的名称】

返回的结果是JSON数据，其中的size字段即项目的大小，单位为kB。

也有对应的GIt仓库：https://github.com/harshjv/github-repo-size

**Comment by XIU2** [comment]
但是这有个问题，那就是会因为用户的操作而频繁请求 API。

**Comment by zhuibo66** [comment]
> 但是这有个问题，那就是会因为用户的操作而频繁请求 API。

秒回啊，确实，会存在这个问题，想解决的话，我能想到就是写缓存（万一来个用户一直刷，也顶不住啊），要么是用户主动触发去（合理）

谢谢回复。

**Comment by XIU2** [comment]
不太感兴趣，感觉需要这个的人似乎并不多（需求不够旺盛）。

**Comment by zhuibo66** [comment]
ok，谢谢
