### ISSUE TITLE
[知乎增强] 移除登录弹窗功能失效

### ISSUE THREAD

**Issue by KeungYik** [XIU2/UserScript#142]
Mac 知乎增强1.8.4，脚本有运行，但登录弹窗依然存在...
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/3352969/145925073-f382511e-280d-4c00-b45c-4f9ed3afa67f.png">

**Comment by XIU2** [comment]
你没看到我置顶的 Issues 吗？ #107  `关于在 Safari 浏览器上部分网站无法运行油猴脚本的问题说明`

这是 Safari 浏览器的问题，你截图里实际上脚本根本没有运行，如果运行的话，是会显示脚本菜单的。
具体我前面那个 Issues 里说的很清楚了。
