### ISSUE TITLE
吾爱破解论坛增强 - 自动签到、翻页

### ISSUE THREAD

**Issue by Loganaahhh** [XIU2/UserScript#143]
签到功能无法使用

**Comment by XIU2** [comment]
昨天就已经更新修复了，反馈前能不能先检查更新下？。。。

**Comment by Loganaahhh** [comment]
油猴没有更新提醒

**Comment by XIU2** [comment]
那你就重新安装。
![01](https://user-images.githubusercontent.com/54703944/146108011-8a4f9e84-c305-42ce-859a-329ea58b6a0e.png)
