### ISSUE TITLE
[Github 增强] 和 refined-github 插件冲突

### ISSUE THREAD

**Issue by JaimeZeng** [XIU2/UserScript#145]
- 设备： Windows 
- 浏览器： Edge 98.0.1093.6
- 问题：

refined-github 插件在浏览代码时在代码区右上角会有一个 copy 按钮，如下图所示。

![](https://cloud.githubusercontent.com/assets/170270/14453865/8abeaefe-00c1-11e6-8718-9406cee1dc0d.png)

单独使用时按钮显示正常。安装 [Github 增强] 脚本后，按钮挪到了网页右上角（star 按钮旁）

![Snipaste_2021-12-19_21-02-28](https://user-images.githubusercontent.com/78083448/146675986-dec8cb15-6ff3-4745-a828-9bb4f53748e1.png)

**Comment by XIU2** [comment]
我不会去解决**脚本冲突**类问题的，因为是无穷无尽的，事实证明一直兼容下去的结果就是不伦不类~

**Comment by JaimeZeng** [comment]
代码区上部的按钮可以和 repo 页的按钮设计成折叠的应该能解决这种问题

**Comment by JaimeZeng** [comment]
👌

**Comment by XIU2** [comment]
考虑到以前我一直兼容这兼容那的最后结果，后续再遇到类似冲突性问题，我都直接拒绝了事。

今天和这个冲突，**我修改代码去兼容**，明天和那个冲突，**我修改代码去兼容**，最后折腾半天发现，脚本里可能一半的代码都是各种兼容别人的脚本/扩展的，这真的是。。。图啥呢？
