### ISSUE TITLE
[自动无缝翻页] 这个链接自动翻页无效

### ISSUE THREAD

**Issue by 759852125** [XIU2/UserScript#147]
https://github.com/github/feedback/discussions/categories/copilot-feedback

**Comment by XIU2** [comment]
已更新规则。  
这几个月 Github 在陆陆续续的更新各个页面的网页框架/样式什么的，这段时间我已经陆陆续续更新了好几次了。。。

**Comment by 759852125** [comment]
> Github

如何应用新的规则?更新插件吗?

**Comment by XIU2** [comment]
更新脚本就行了，或者你去 https://greasyfork.org/zh-CN/scripts/419215 点击升级也许。
