### ISSUE TITLE
[自动无缝翻页] 无法回滚到第一页

### ISSUE THREAD

**Issue by China-Huanghe** [XIU2/UserScript#148]
例如在第5页内容点击某个页面进去后，再退出来往前翻不到第1页，好像是会停在第3页

**Comment by XIU2** [comment]
没明白。

**Comment by haowu16** [comment]
同遇到这个问题，就是自动翻页之后不能往回翻，比如我先翻到第8页，然后想回到第一页，发现倒不回去了。复现：google搜索torch detach，先翻到第8页，然后看能否回到第一页

**Comment by XIU2** [comment]
@hwucn 在不同网站后退事件不太一样。
我试了下，谷歌搜索，翻到第 8 页（翻了 7 次），然后按下浏览器的后退按钮，此时浏览器的滚动条会向上回滚到上一页位置。
没毛病呀。

**Comment by hwucn** [comment]
明白了，我意思是继续用鼠标往上滚动，这样回不去，用浏览器的后退确实可以，谢谢！ @XIU2

**Comment by XIU2** [comment]
@hwucn 没理解你的意思，怎么就鼠标滚动不上去了？我这边滚动正常呀。。。
所有页的搜索结果内容都在当前网页内呀，往上翻就行了呀，滚动条无法移动吗？

![02](https://user-images.githubusercontent.com/54703944/147090264-8396de35-e611-4a9d-b02f-1b3cd471b055.png)
![04](https://user-images.githubusercontent.com/54703944/147090413-1009f1b4-3c68-42f1-8d28-75cb57a94b2c.png)
![03](https://user-images.githubusercontent.com/54703944/147090268-b0562304-91a4-4beb-acae-7b9a50dfc691.png)

**Comment by hwucn** [comment]
这会可以了，可能我网络的问题，谢谢！ @XIU2

**Comment by China-Huanghe** [comment]
是你比如在第5页点进某一个内容（不能是新标签页打开），然后再退出来就不能回到第一页了。

**Comment by XIU2** [comment]
@China-Huanghe 可是谷歌搜索默认就是新标签页打开呀？

**Comment by XIU2** [comment]
@China-Huanghe 我把搜索结果链接改成当前页打开，试了下，依然可以通过后退按钮回到第一页呀，当然你需要多点几下。

### 如果你的预取效果是：
翻了 5 次（即当前网页中累计了 5 页的搜索结果内容），然后在当前页打开某个搜索结果网站后，点击浏览器后退按钮返回到谷歌搜索结果页，此时应该和打开搜索结果网站前一样（即当前网页中累计 5 页的搜索结果内容）。

那这是无法实现的，因为这个是受网页/浏览器控制的，由它们觉得后退时是否要重新加载原先网页，分为三种情况：
```
1. 如果重新加载，那么后退后就会重新加载原先网页的 URL（内容就是那一页的内容）
2. 如果不重新加载，那么后退后就会和原先网页内容一样（累计 5 页搜索结果内容）
3. 什么也不干
```

### 目前的现状是：
翻了 5 次（即当前网页中累计了 5 页的搜索结果内容），然后在当前页打开某个搜索结果网站后，点击浏览器后退按钮返回到谷歌搜索结果页，此时当前网页就是第 6 页（1+5，等于说重新加载了原先的 URL），当前网页内容也只有第 6 页的内容。
但是你可以继续点击后退回到前面的第 5 页、第 3 页、第 1 页（当然也可以前进）。

**Comment by China-Huanghe** [comment]
好的，那我了解了，主要是有些内容是不会新标签页打开的

**Comment by China-Huanghe** [comment]
谢谢了 @XIU2
