### ISSUE TITLE
[知乎增强] 屏蔽视频功能失效

### ISSUE THREAD

**Issue by LiXin-Link** [XIU2/UserScript#149]
知乎增强脚本1.8.6在Chrome版本 96.0.4664.110（正式版本）（64 位）中失效
截图显示已经设置屏蔽视频，但是在首页中仍然有视频出来
![image.png](https://s2.loli.net/2021/12/31/ZqAnOMiJuTw8plQ.png)

**Comment by XIU2** [comment]
你反馈慢了，我 20 分钟前就已经更新脚本了。。。

**Comment by LiXin-Link** [comment]
哈哈哈哈，感谢🤣
我刚发现的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XIU2/UserScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月31日(星期五) 下午5:19
***@***.***&gt;;
抄送:&nbsp;" ***@***.******@***.***&gt;;
主题:&nbsp;Re: [XIU2/UserScript] [知乎增强] 屏蔽视频功能失效 (Issue #149)





 
你反馈慢了，我 20 分钟前就已经更新脚本了。。。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
