### ISSUE TITLE
centbrowser百分浏览器用不了

### ISSUE THREAD

**Issue by Giter-t** [XIU2/UserScript#15]
不知道是浏览器的原因还是chromium内核版本不是最新的原因，Github增强这个脚本在百分浏览器不能生效，但是在Edge浏览器可以用

**Comment by XIU2** [comment]
我用的就是百分浏览器（CentBrower），目前该脚本功能一切正常。
请确保你用的是 Tampermonkey 脚本管理器扩展。

**Comment by Giter-t** [comment]
抱歉抱歉，我把脚本删了重新安装就能用了

**Comment by XIU2** [comment]
好吧，那我关闭该 Issues 了。

以前也有一些人反馈过类似问题（某某浏览器无法使用，但是某某浏览器可以用巴拉巴拉），但是我去测试（版本完全一致）都能用。。。我也不清楚它们是什么情况。
