### ISSUE TITLE
[新标签页打开链接 ] 使用后无法登录谷歌账号，能否添加下白名单？

### ISSUE THREAD

**Issue by huantian233** [XIU2/UserScript#150]
使用后无法登录谷歌账号，能否添加下白名单

**Comment by XIU2** [comment]
白名单？你要说的是黑名单吧？
这个自己排除下就行了，点击右上角 Tampermonkey 扩展图标，[新标签页打开链接] 右边的 ` > ` 按钮，然后选择 `排除 xxx` 即可。
