### ISSUE TITLE
[自动无缝翻页] 请求网站支持 www.ykmh.com

### ISSUE THREAD

**Issue by guokai0818** [XIU2/UserScript#151]
**自动翻页脚本不支持此网站，反馈一下**
www.ykmh.com/

**Comment by XIU2** [comment]
其实这类已经自带 **上下滚动阅读** 功能的漫画站没有那么必要加上自动无缝翻页。。。
右上角的齿轮设置里可以改。

**Comment by XIU2** [comment]
好吧，不吭声，那我还是给添加支持了吧。。。

**Comment by guokai0818** [comment]
感谢你的回复，跟您说一声对不起，我不经常登陆这个邮箱，没有及时回复，当时那个网站也是没有仔细查看，没有留意到可以自己设置的。给您添麻烦了。

XIU2 ***@***.***> 于2022年1月3日周一 17:39写道：
