### ISSUE TITLE
[自动无缝翻页] fsou出现残影BUG

### ISSUE THREAD

**Issue by qhq** [XIU2/UserScript#152]
浏览器Edge
fsou搜索后，下滚，会出现文字叠加，并且在顶部出现页码

![Snipaste_2022-01-04_13-21-49](https://user-images.githubusercontent.com/3319385/148013483-a3188810-0f05-4f07-91d2-ccfca9ff2961.png)
![Snipaste_2022-01-04_13-23-32](https://user-images.githubusercontent.com/3319385/148013485-d7f2424b-d297-4d29-8bd0-125892109085.png)

**Comment by XIU2** [comment]
我试了下，显示正常，你把 URL 发给我看看。

**Comment by qhq** [comment]
https://fsou.cc/search?q=esxi&tbn=all&pageIndex=2
就前一两页会产生问题，后面的页码没事儿

**Comment by XIU2** [comment]
试了下无法复现（截图中是 1 -> 2 也的交界线处）
![02](https://user-images.githubusercontent.com/54703944/148013924-ca74841d-916f-4838-acad-81a6f2972591.png)

**Comment by XIU2** [comment]
又看了下，发现那个顶部出现页码的我这边也有，但是没有搜索结果内容重复的问题。

**Comment by qhq** [comment]
这就很奇怪了，我也是试着只开了这一个脚本。肯定能复现。
![1](https://user-images.githubusercontent.com/3319385/148014236-50133333-97d3-46ef-aa9a-d6201124fb59.gif)

**Comment by XIU2** [comment]
我估计和顶部显示页码是一样的，我先去尝试解决这个页码问题，或许搜索结果的问题也顺便解决了呢。

**Comment by qhq** [comment]
是的，很可能是页码出现在顶部的时候，后面页面的内容也被带上去，一瞬间显示出重影的问题。

**Comment by XIU2** [comment]
你更新脚本后，再试试是否还出现该问题，如果没了的话就关闭 Issues 吧~

**Comment by qhq** [comment]
BUG解决了，感谢
