### ISSUE TITLE
[知乎增强] 希望在知乎用户的文章列表页面添加发布时间、编辑时间

### ISSUE THREAD

**Issue by NavisLab** [XIU2/UserScript#154]
请问作者大佬，是否可以在[知乎增强脚本](https://greasyfork.org/zh-CN/scripts/419081-知乎增强)添加如下功能：
**在知乎用户的文章列表页面，添加文章发布、编辑时间显示。**

其余页面都有时间显示，文章列表页面如果也可以加上就更和谐了:)
类似这个脚本的功能 https://greasyfork.org/zh-CN/scripts/393177-知乎

![图片](https://user-images.githubusercontent.com/53592572/148188599-c69ca9a4-0dcc-4871-9713-2670d9dc1fd0.png)

**Comment by XIU2** [comment]
文章列表页 和 回答列表页 一样，只要展开就会在内容顶部显示发布时间/编辑时间的。

而且既然你说的这个脚本已经实现了你的需求，那么你直接用不就行啦？。。。

**Comment by NavisLab** [comment]
额，只是一个建议而已。
不同脚本同时使用可能会有冲突问题。
不同意该建议就拉倒
