### ISSUE TITLE
希望制作一个更改gitee背景图功能的脚本

### ISSUE THREAD

**Issue by XuJieYa** [XIU2/UserScript#155]
gitee中的界面貌似只有白色，
比较单一，希望作者有能力可以开发一个
更改界面背景的插件脚本

**Comment by XIU2** [comment]
不感兴趣。。。
我压根都不用 Gitee。。。

**Comment by wangliang181230** [comment]
@XIU2 作者大大，你好，我是 `dev-sidecar` 的源码贡献者。
我在 https://github.com/docmirror/dev-sidecar/issues/86 里给你留过言。
希望你能在gitee上，建一个自动同步的镜像仓库，方便我们自动更新脚本。非常感谢。

**Comment by Nobodies123** [comment]
@wangliang181230 据我所知，ds以前有个gitee库但是后来挂了，所以再建一个我觉得依旧过不去审核。如果要更新脚本的话为什么不直接改成github上的地址呢（虽然我也不知道在哪）

**Comment by wangliang181230** [comment]
> @wangliang181230 据我所知，ds以前有个gitee库但是后来挂了，所以再建一个我觉得依旧过不去审核。如果要更新脚本的话为什么不直接改成github上的地址呢（虽然我也不知道在哪）

@Nobodies123 不是建DS的镜像库，而是建UserScript的镜像库。例：https://gitee.com/XIU2/UserScript

**Comment by XIU2** [comment]
@wangliang181230 是不会考虑再 Gitee 等国内代码托管平台建立镜像仓库的，毕竟国内审核过于抽象。

我这个 Github 脚本里不是提供了各个加速源么，你挑一个稳定的 Raw 加速源作为脚本的更新地址不就行啦？
另外，我还有个 Bitbucket 的备用镜像仓库，相对于脚本内的加速源会更可靠一些，你也可以当作更新地址用：

- https://bitbucket.org/xiu2/userscript/raw/master/GithubEnhanced-High-Speed-Download.user.js
