### ISSUE TITLE
[脚本名称] 希望添加关于网站的无缝翻页功能

### ISSUE THREAD

**Issue by Sucgz** [XIU2/UserScript#156]
https://nhentai.net/   2022/1/8  请求添加无缝翻页

**Comment by XIU2** [comment]
本脚本不会对「NSFW」网站添加支持（判断标准为：只发布成人内容 + 大量露点）。

**Comment by Sucgz** [comment]
好吧

**Comment by XIU2** [comment]
因为要求的人太多，所以我后来整了个 `自定义翻页规则`、`外置翻页规则`，并同意制作 NSFW 网站翻页规则了。

你提的这个网站，几个月前添加支持了，今天翻 Issues 看到顺便跟你说一下~
