### ISSUE TITLE
[知乎美化]和[知乎增强] 阅读评论的回复 功能失效

### ISSUE THREAD

**Issue by topbardon** [XIU2/UserScript#157]
当知乎回答的评论中，一条评论的回复比较多的时候，正常情况下应该会弹出该评论的所有回复，然而脚本会让弹出的回复闪退
<img width="731" alt="image" src="https://user-images.githubusercontent.com/95011132/148646423-99494632-8464-4e46-b04d-7a5cc4c898ec.png">

**Comment by XIU2** [comment]
经过测试，无法复现。  
请你关闭所有扩展后重试，类似情况有好几个人反馈过了，最后排查都是 **广告屏蔽扩展** 中某条 AdGuard 规则误伤导致的。

**Comment by topbardon** [comment]
Thank you for your answer. I'll try to do it.

**Comment by XIU2** [comment]
长时间不回复视为已解决。

**Comment by XIU2** [comment]
经过测试，我这边一切正常。

**Comment by topbardon** [comment]
我经过排查，确认我自己遇到的问题应该是加载了[一个脚本](https://greasyfork.org/zh-CN/scripts/417303-%E9%9A%90%E8%97%8F%E7%9F%A5%E4%B9%8E%E7%99%BB%E5%BD%95%E6%A1%86-%E9%93%BE%E6%8E%A5%E6%97%A0%E7%BC%9D%E8%B7%B3%E8%BD%AC "隐藏知乎登录框&链接无缝跳转")，再关闭这个脚本后就不再遇到弹出闪退了。顺便问一下**知乎美化**和**知乎增强**能否实现无缝跳转链接，即解除2知乎的重定向？

**Comment by XIU2** [comment]
知乎增强 有个功能 [默认站外直链] 应该是你说的这个，即点击链接时不会显示知乎的跳转提示，而是直接打开链接。

**Comment by topbardon** [comment]
谢谢你的帮助，我已经在 [Greasy Fork](https://greasyfork.org/zh-CN/scripts/419081-%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA#:~:text=%23%20%E9%BB%98%E8%AE%A4%E7%AB%99%E5%A4%96,%E7%9A%84%E8%B7%B3%E8%BD%AC%EF%BC%89%E3%80%82 "# 默认站外直链
知乎会把回答、文章中的站外链接改为知乎跳转链接，脚本会将其改回原本的直链（即直接访问而不需要经过一层额外的跳转）") 上已经看到了。
