### ISSUE TITLE
希望制作一个 XX 功能的脚本（ simple script ）

### ISSUE THREAD

**Issue by stickerx** [XIU2/UserScript#158]
Hello, I hope everything is ok
I need a simple script for steam inventory 
when I click on a specific card on the inventory display how many cards has that game 

display number of cards location:   beside tag or view in community market or name of the card or best place you can choose

thank you so much in advance

**Comment by XIU2** [comment]
I do not understand.
Please take a screenshot to illustrate the location of the card.

**Comment by stickerx** [comment]
when I click on any specific card from inventory or while trading display how many cards have the badge 

example  from card Detroit: Become Human  
the game has

![2022-01-14_150546](https://user-images.githubusercontent.com/41187653/149530659-c765b5e5-1e42-450b-9112-f8b3b62c16e4.jpg)
 9 cards

![2022-01-14_150435](https://user-images.githubusercontent.com/41187653/149530640-c67f09ae-922a-4435-b48a-53b4cfdb3fce.jpg)

this is script useful for traders and also me 

will be grateful for this

**Comment by XIU2** [comment]
I don't usually play Steam Cards, so I don't know much about it.
Where can I see the number of cards?

**Comment by stickerx** [comment]
I want the script to do that work 

to display me the number of cards


any location you choose

**Comment by XIU2** [comment]
. . .
My English is not good.

I mean, where can I find out the number of cards (9)?
How do I go about getting this amount.

**Comment by stickerx** [comment]
for example, this websites gives all information about games
https://barter.vg/i/120444/?
https://steamdb.info/app/1222140/communityitems/
https://www.steamcardexchange.net/index.php?gamepage-appid-1222140

**Comment by XIU2** [comment]
Browser security policy does not allow cross-domain access.

Do you mean, the total number of cards in a series? (8 in the picture below)
![01](https://user-images.githubusercontent.com/54703944/149535570-b6e985be-d414-4eb0-afb5-96c83c53e252.png)

**Comment by stickerx** [comment]
yes, script to display the total number of cards in a series,  when I click on a card inventory or while trading

**Comment by stickerx** [comment]
there must be some way to do it , how this websites know this game has a 8 cards like that
https://barter.vg/i/237/

**Comment by XIU2** [comment]
I didn't find the total number of cards in the current series under the inventory page, which means that if you want to implement your function, you need to go to the badge progress page to get it.
This means that after clicking on the card, it takes a certain delay before the total is displayed (the script background accesses the badge progress page).

**Comment by stickerx** [comment]
the script  calculate just the total cards in series

example: Left 4 Dead 2, when I click on one that card in inventory script calculate and display  8 cards has that game 


don't need to calculate how many cards have in inventory

delay not important for me just if you can creat him

**Comment by stickerx** [comment]
so that script takes time or is easy to write?

**Comment by XIU2** [comment]
I am writing a simple script.

**Comment by XIU2** [comment]
This is the initial beta version.
Currently only the inventory page is supported.
> https://steamcommunity.com/id/xxxx/inventory

When a card is clicked, the total is displayed (as shown in the image below).
In order to improve efficiency, I designed a caching mechanism. After clicking the card for the first time to get the total number, the script will remember it, and the next time the card is clicked, it will be read directly from the script configuration.

![01](https://user-images.githubusercontent.com/54703944/149552981-fdc2980b-a6bf-4791-b7bd-838d74a465f7.png)

I don't know much about the market, please tell me what other pages need to add support, preferably with an example URL.

``` JavaScript
// ==UserScript==
// @name         Steam shows the total number of cards
// @version      1.0.0
// @author       X.I.U
// @description  Steam shows the total number of cards
// @match        https://steamcommunity.com/id/*/inventory
// @icon         data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAALfElEQVRYhX2Xe3Bd1XXGf3vvc859X+nq6nUlW5Yly7JlI2xsYzAwtnk4ATpAxkNTHm0mnaTT/gHTTvrIBDLTpp1JUoZppqHQls5AKTR2INOWJJQSXF4x2BhsJCRZ8kuWZckPSVf3/Trn7N3RVTFpQrNn1l97n7O/vda31reWMKMPcmUJA9U8vrwHGdqCHn4HPzePaIxhVSoYbYRXrn7BeMVbCUduF6kVUXHwvQP+6amDaqDnoIompmQytaBnTmB8H5lowrjgFss48SBeI/hUEEZeudLi1ywhJEIJdL6Q8rzal/1a5SGC4XZrYBvWwEZobMdLdH6RH+z/Io1taEeh52fe8tOZbysl/ouWFvANYP7fSz4DgAEBBIL4xiS8ubmnVcTZK68aRK29Dtm8dgnZJydRW+/E2nrnp19nz+7U77+60zt0qMz07J/KxuQTwrIw4rMBCDP6wC+FIIcO34eudDdXf/7jD52Opi772lugY3AZr++hp06gz48j+waRqTWYmVHcS+chEMFeuw1hBzBzY7g/fQE9fmqBYPzBQKrpVa/R4OkCAnXlSvXnX9sIllk220BE4Z8OdHoj54YCK6Od1i2/iUmuRyDRk6NUn3+M0pv/hnf0AE40jEjEqP3oe6Rf/CGOWUTNjFKby2MP7EBtugURFWFxfOhB4+o4yfhrGAdZsxHaqZt6dNce9KXYFSPfGWS68JFqTXSqO7+MCaTqETGTwxSeeoRCOoPT2YUIhFC2jbQF/uwUatU6rPbVUM5T+OfHUO3dWKv6kSsGUIOD6PEPr+fswnanpecFZYVQhFAyjPS9Tj4xw2rcU+pJApEutWsvRjaBW8NUShilkE1JIqlUPfi6VMLNFTBVr+7KYKqJ8uEjlM+dJrR5K0L7eB+9hTd2CFrWYt33h0jH3O5Nj37TBGtgZUBkUN/6q4dQ7UmsnlW450//gU5PPRq460uQXAu+j//i99A/+UdUMoXqbMNkz2OnUkixlF4u9spe/HMTULyEaA7jXkoT2fEbQIXi838DJ4cRDXHkEjc2b0MPHdptZubGpBUbM0UfKQpBRDmKWRSD3tTMk87gddA2WGe4+dkzMD0CyQ5qP/4XVDCAvfkaLMvHamzEClpQzGDF46iuJOH1CaKr2tDZRfzhQ0Ru24NYsYrCM4/jDb+FiHdi3XU/0s3vr7WsGKxcfyPSy+bxi0UqJ8f/IriiE2vrnuWsLefQk8NoO4AMBBB9/XjDI6hQCjdTxq9WCaQ6ULaDFrIeKr3oIlv70Olz2K1xlAVaSUQojD786nKi9e5A3LBHMHn0W+LUUaS1FI9q+iZZWLhHdq/FxFbWSSfsIDIQwVw4g/GK2OuuhloNMzaCaF+DNBJtQfX8LFYigElX0OkQtZKHVy3jqwDlqWncCzPI3nU4t+2FWrH+OLHzHpRl3109memTOhqDi9NfkefHEKvWLTO+VKD68Qf4G27CueFWhJ/Df+0lVFcXJOJYnobm1ZjsJUxuFjyDjK/GNK2gND4ESuDPXcCOSaI7thPqX0ft8OtUn/oTKOQgkET39KJU4RbpZXOtNRW717p+FyRSdYT+v36H4u/fQXbfc3iRDkT3FsTGjWAWEU0OZKfAU9CyEdXVD2lQPduplmo4jkBEbMzK1VgDu5EVTe3gm1RHx6Bcxpz6YLkEO0lMYeFGi6z7eVMqhkT/ZrCb0LNT+NMTRH/nt/BLRdy3X8Nv68Lu6cZEHURjE6K3hirYeLRhDWyA4jxzH40RXJwkeuM29MpN+JcziEsz+Avz6GgcW1pYbUlEQCyHwYpSyxS7rGo+v8man4ZMATrAHf+QSt7FTkWR4QbsjlbIX8IMH0VuuAqj4piGAbhmEPPzI/injnNxMUPuwOtseOIxKKTJ7/8BTBxDdXcjO9sJdTeg01VqH4wg3CDB9bshHMKORbGolVOmeRW09dVdUxkbp3ruNM7GXnS1hK5OYSoSbBDZBcxCBtF3DcUzk6hkhGA0RmtHKx1rOkE04lbzWC1tqMRt1CZHUafPIs8H6/JsNTcgN+9YFq1qgbBUFUvnK9qrVghXCvWN8MBmivueJDtylqaeBKWJaXR4JZEtNyBWrkGt6AJboCZO4J49Rc64xGIhcgtZgm6egKhgtUQQto17WeHOLqCNj5Vowbr7q4j+Lcs1JhhEphcXLTebd0jPwpkx6Lwa++bbCR95ALecp5a6BrvrJoLdHajmMOTnKb3+BrVMntjARpzeFbz8jcfpa22gGm+kMJlm95Zu9M9+iI5G0G3d6EgIUSnjzs/gv/Icgd6rqcvz0IeYWnXc8pEtYnEe8gtXNL7xz74LehHSE3DqNP7EIdx3p5DSh7JNJePiBE/gN3Uz8NWHae5sRJYXqKQvU+raQPg7L6L3/QNMHcfp6EREGjC5LDp9GaOs5VQ/NQI93YctOxFPlwniDh/C3n47JHvrQPTBl3DHjiIDQUQ4jGhOYcqaQFuE0Nl53OnLRHfsZV33KsTxd6GlHeaP477zMl5uAWv7dkyLg6kZREsb+vgCcvPOuoaYuWNQWERs3jAuQ6nooXK6TH566cXnrjQK7uwFaoseWA3oJf2WEhEJUjm/gMgXCfdvQlFFv/R3uCND6FIRv7MfMnOIiaPoI/8NEb2kWAhfoLbdjLr2jmUv/8f+pVbkHRGNnZHum2/udxxtCn4j/vgEIjNTD4O9upfIprUYoxBKo9Z14jumTq7YYD9WayvuR++hs1lkshmha4iuNeDYiIAFMoCevIi+cJHaa29gmvsRTUn0R29g9u1D7bxxv+jrRnpD56cCkdjfV9NzpA+8A5VlLojWAczlGVTAYKXimIU8MlsjtKEXgiF0aRGdm8cEYnXm+O+/gdAGuWsP3shhTHoOEYqCCEF2DsrF5f+e/xiikUldrT6l3z+GevSaTahaZdRY6uFqxRXR1sRyzU/21Gu6OTOMfzmPd6kI8TgiX8B4imouj1QCKmVUNITJ59AnR1F77kH4ZaRnQFroMyeRW3egdt6DwIX391Gshv+4LK2jtcuLqK9t7ALjZXzH1uVM/mb/7BTRnjZEex+idQ2EAnjjR/BdF1PIoV2Bae/F/fh9dL5IYE0XUmpMNo+ev4AINSJWb0UPHa63Z7SvRN3/CHJpFHj2G4iZzAuBbTu+GWpIEGxrQ/3RnlvxG5M4kYa3Lc2u4uyFblnIE+xfAbF2RMtqZGsn/uTYUgHH+dz9eFMnqYx8gO+CEwkjhcDPF/DLHurSaeTm3RiWMsDHeuDrSFvBv3+bi08+N1Vwuj/vZWtu+dwclZlFrESoeZmZysJXoTsCjnVk8dDQBuN+n8RDD9fbcdG7leBX1iOkQjhBOHmQfKGAHW3CS6fR+QClmYuYMyPY265DtPVgtfctiw4V/GcfYfGNQzj3/u4DqlormUoZEQwuc0I//eSnY4G0wPJjmdGhw+mh0fWxNZ0037cXccPd1MXgk+GjNE/tR3+Le+YEyg5TnT6LXlwgcu1u7C99HZlsv3K2+vjvkTs2RvDe3747tm7Dy1SKvzSYPP/MLwxFAkIKEzEye2zswOXX395lJyK0fOFzRHfuglQfqPin59Nn0RNDuJk09vprkd0brmx5H7xCbfgQbrZ83OkfvN1pj0+ZmkBYNhjzCwCeffr/AsBDJyU6kqBwbPzRuTcP/GXV82lYlaJpfQ+BjVdhXX0tNKTAjvzKqKXPTeC++1NKY0c9kVz1SGzb9X8tjIdfzSFCDfUw/noA0scPuxBrwcvmmH3rQIvMm3/y0XdJS4JfIpiIUG9g+wcg6KDnZpGZNDQ0Ii5cSAtlPRHYct13axWvJNwadiiAli4iEP8VAJ89HQtR129TLiG1nos0Nt8dSOi12qi9lRq3utVqT/lirql24hW3vLBQi3d3XUqu73+PZOonBNR/WnbYSMeGTO5/Xf6ZtwDwPwtFRezQVs+sAAAAAElFTkSuQmCC
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-end
// @namespace    https://github.com/XIU2/UserScript
// @supportURL   https://github.com/XIU2/UserScript
// @homepageURL  https://github.com/XIU2/UserScript
// ==/UserScript==

(function() {
    'use strict';
    var cardData = JSON.parse(GM_getValue('cardData', '{}'));
    mutationObserver();

    function mutationObserver() {
        const callback = (mutationsList, observer) => {
            for (const mutation of mutationsList) {
                for (const target of mutation.addedNodes) {
                    if (target.nodeType != 1) break
                    if (target.tagName === 'A' && target.href.indexOf('/gamecards/') > -1) {
                        let id = /(?<=gamecards\/)\d+/.exec(target.href)[0];
                        if (cardData[id]) {
                            //console.log('1', id, cardData[id])
                            addNum(cardData[id], id, target);
                        } else {
                            //console.log(target.href, id);
                            getPageElems(target, id);
                        }
                    }
                }
            }
        };
        const observer = new MutationObserver(callback);
        observer.observe(document, { childList: true, subtree: true });
    }


    function getPageElems(target, id) {
        GM_xmlhttpRequest({
            url: target.href,
            method: 'GET',
            headers: {'Referer': location.href},
            timeout: 5000,
            onload: function (response) {
                try {
                    let html = createDocumentByString(response.responseText),
                        num = html.querySelectorAll('img.gamecard').length;
                    //console.log(num, id, target)
                    cardData = JSON.parse(GM_getValue('cardData', '{}'));
                    cardData[id] = num;
                    GM_setValue('cardData', JSON.stringify(cardData).replaceAll('"','\"'));
                    if (document.querySelector('.inventory_iteminfo:not([style*="display: none"]) .item_owner_actions > a').href === target.href) {
                        addNum(num, id, target);
                    }
                } catch (e) {
                    console.log(e);
                }
            }
        });
    }
    function addNum(num, id, target) {
        //console.log(num, id, target)
        if (target) target.insertAdjacentHTML('afterend', `<span data-id="${id}"><b>Total: ${num}</b></span>`);
    }
    function createDocumentByString(e) {
        if (e) {
            if ('HTML' !== document.documentElement.nodeName) return (new DOMParser).parseFromString(e, 'application/xhtml+xml');
            var t;
            try { t = (new DOMParser).parseFromString(e, 'text/html');} catch (e) {}
            if (t) return t;
            if (document.implementation.createHTMLDocument) {
                t = document.implementation.createHTMLDocument('ADocument');
            } else {
                try {((t = document.cloneNode(!1)).appendChild(t.importNode(document.documentElement, !1)), t.documentElement.appendChild(t.createElement('head')), t.documentElement.appendChild(t.createElement('body')));} catch (e) {}
            }
            if (t) {
                var r = document.createRange(),
                    n = r.createContextualFragment(e);
                r.selectNodeContents(document.body);
                t.body.appendChild(n);
                for (var a, o = { TITLE: !0, META: !0, LINK: !0, STYLE: !0, BASE: !0}, i = t.body, s = i.childNodes, c = s.length - 1; c >= 0; c--) o[(a = s[c]).nodeName] && i.removeChild(a);
                return t;
            }
        } else console.error('No string found to convert to DOM');
    }
})();
```

**Comment by stickerx** [comment]
thank you so much, sir

 but still didn't display number of cards

![2022-01-14_194852](https://user-images.githubusercontent.com/41187653/149569093-154c1856-1016-44ba-bf57-f6f3d6757c6b.jpg)



even I change  that still does not work

`// @include     *://steamcommunity.com/id/*/inventory*
// @include     *://steamcommunity.com/profiles/*/inventory*`





`// ==UserScript==
// @name         Steam shows the total number of cards
// @version      1.0.0
// @author       X.I.U
// @description  Steam shows the total number of cards
// @include     *://steamcommunity.com/id/*/inventory*
// @include     *://steamcommunity.com/profiles/*/inventory*
// @icon         https://store.steampowered.com/favicon.ico
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-end
// @namespace    https://github.com/XIU2/UserScript
// @supportURL   https://github.com/XIU2/UserScript
// @homepageURL  https://github.com/XIU2/UserScript
// ==/UserScript==

(function() {
    'use strict';
    var cardData = JSON.parse(GM_getValue('cardData', '{}'));
    mutationObserver();


    // Listen event
    function mutationObserver() {
        const callback = (mutationsList, observer) => {
            for (const mutation of mutationsList) {
                for (const target of mutation.addedNodes) {
                    if (target.nodeType != 1 || !(target.tagName === 'A' && target.href.indexOf('/gamecards/') > -1)) break
                    let id = /(?<=gamecards\/)\d+/.exec(target.href)[0];
                    if (cardData[id]) {addNum(cardData[id], id, target);} else {getPageElems(target, id);}
                }
            }
        };
        const observer = new MutationObserver(callback);
        observer.observe(document, { childList: true, subtree: true });
    }


    // Get data
    function getPageElems(target, id) {
        GM_xmlhttpRequest({
            url: target.href,
            method: 'GET',
            headers: {'Referer': location.href},
            timeout: 5000,
            onload: function (response) {
                try {
                    let num = response.responseText.match(/\<img class\=\"gamecard\"/g).length;
                    //console.log(num, id, target)
                    cardData = JSON.parse(GM_getValue('cardData', '{}')); cardData[id] = num; GM_setValue('cardData', JSON.stringify(cardData).replaceAll('"','\"'));
                    if (document.querySelector('.inventory_iteminfo:not([style*="display: none"]) .item_owner_actions > a').href === target.href) addNum(num, id, target);
                } catch (e) {
                    console.log(e);
                }
            }
        });
    }


    // Add to page
    function addNum(num, id, target) {
        //console.log(num, id, target)
        if (target) target.insertAdjacentHTML('afterend', `<span data-id="${id}"><b>Total: ${num}</b></span>`);
    }
})();`

**Comment by XIU2** [comment]
Currently the script only supports personal inventory pages.

> https://steamcommunity.com/id/YourUserName/inventory

Please tell me other page URLs that need to add support.

**Comment by stickerx** [comment]
its work thank you so  much, we hope to support all inventory  

page URLs that need to add support.

// @include     *://steamcommunity.com/id/*/inventory*
// @include     *://steamcommunity.com/profiles/*/inventory*
// @include     *://steamcommunity.com/market*
// @include     *://steamcommunity.com/tradeoffer*

**Comment by stickerx** [comment]
its work thank you so much, we hope to support all inventory

page URLs that need to add support.

// @include ://steamcommunity.com/id//inventory*
// @include ://steamcommunity.com/profiles//inventory*
// @include ://steamcommunity.com/tradeoffer

**Comment by XIU2** [comment]
Please provide a directly accessible URL so I can check.

**Comment by XIU2** [comment]
The second link turned out to be someone else's inventory.
I encountered a difficulty, I can easily get the card ID on my inventory page, but I can't find it on other people's inventory page. . .
The card ID is an important unique identifier, without which I cannot get the total number of cards.

**Comment by stickerx** [comment]
URL when want to send offer to someone but I think  does not work 

https://steamcommunity.com/my/tradeoffers/

that all 

Thank you very much you are a legendary person

**Comment by stickerx** [comment]
we hope to support all inventory

**Comment by XIU2** [comment]
> thank you so much, sir
> 
> but still didn't display the number of set or serie
> 
> ![2022-01-14_194852](https://user-images.githubusercontent.com/41187653/149569093-154c1856-1016-44ba-bf57-f6f3d6757c6b.jpg)

I randomly found a personal warehouse and found that our two screenshots are different.
I can't see "view in community market".

Maybe it's because I'm restricted from using the marketplace? (haven't purchased for a long time) 

![01](https://user-images.githubusercontent.com/54703944/149624406-2e28ea7f-d058-4368-9193-193bd7fe903e.png)

**Comment by stickerx** [comment]
https://steamcommunity.com/id/YourUserName/inventory/

i think you forget `/` at the end of the URL

we hope to find a way to support all inventory

This website has all The card ID 

https://steam.tools/cards/
https://www.steamcardexchange.net/index.php?gamepage-appid-550
https://steamdb.info/app/550/

**Comment by XIU2** [comment]
This link contains the card ID, which can be used to get the quantity.
![02](https://user-images.githubusercontent.com/54703944/149624628-19cb2151-5218-419b-b1e6-c848c5b243bf.png)

I need to know what the ID of that card is in order to get the total.
It is useless that you give me the IDs of all the cards, I only need the IDs of the current card.

**Comment by stickerx** [comment]
ID card series   like that

https://github.com/yaneony/steam-cardsets/blob/main/cardsets.json

**Comment by XIU2** [comment]
Although I can't see "view in community market", since you can see this option in other people's repositories, I have modified the script to support both my own repo + others' repositories.

- https://steamcommunity.com/id/YourUserName/inventory/
- https://steamcommunity.com/profiles/UserName/inventory/

``` JavaScript
// ==UserScript==
// @name         Steam shows the total number of cards
// @version      1.0.1
// @author       X.I.U
// @description  Steam shows the total number of cards
// @match        https://steamcommunity.com/id/*/inventory
// @match        https://steamcommunity.com/profiles/*/inventory
// @icon         https://store.steampowered.com/favicon.ico
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-end
// @namespace    https://github.com/XIU2/UserScript
// @supportURL   https://github.com/XIU2/UserScript
// @homepageURL  https://github.com/XIU2/UserScript
// ==/UserScript==

(function() {
    'use strict';
    var cardData = JSON.parse(GM_getValue('cardData', '{}'));
    mutationObserver();


    // Listen event
    function mutationObserver() {
        const callback = (mutationsList, observer) => {
            for (const mutation of mutationsList) {
                for (const target of mutation.addedNodes) {
                    if (target.nodeType != 1) break
                    let aHref = target.querySelector('a[href*="market/listings/"]');
                    //console.log(aHref)
                    if (!aHref) break
                    let id =/(?<=\/)\d+(?=-)/.exec(aHref.href)[0]
                    //console.log(id)
                    if (cardData[id]) {addNum(cardData[id], id, aHref);} else {getPageElems(`https://steamcommunity.com/my/gamecards/${id}/`, id, aHref);}
                }
            }
        };
        const observer = new MutationObserver(callback);
        observer.observe(document, { childList: true, subtree: true });
    }


    // Get data
    function getPageElems(url, id, aHref) {
        GM_xmlhttpRequest({
            url: url,
            method: 'GET',
            headers: {'Referer': location.href},
            timeout: 5000,
            onload: function (response) {
                try {
                    let num = response.responseText.match(/\<img class\=\"gamecard\"/g).length;
                    //console.log(num, id, aHref)
                    cardData = JSON.parse(GM_getValue('cardData', '{}')); cardData[id] = num; GM_setValue('cardData', JSON.stringify(cardData).replaceAll('"','\"'));
                    if (document.querySelector('.inventory_iteminfo:not([style*="display: none"]) .item_market_actions a[href*="market/listings/"]').href === aHref.href) addNum(num, id, aHref);
                } catch (e) {
                    console.log(e);
                }
            }
        });
    }


    // Add to page
    function addNum(num, id, aHref) {
        //console.log(num, id, aHref)
        if (aHref) aHref.insertAdjacentHTML('afterend', `<span style="margin-left: 10px;" data-id="${id}"><b>Total: ${num}</b></span>`);
    }
})();
```

**Comment by stickerx** [comment]
// @match    /^https?:\/\/steamcommunity\.com\/(?:id|profiles)\/.*\/inventory(\/$|\?|$)/
// @match     /^https?:\/\/steamcommunity\.com\/(?:id|profiles)\/[^\/]+(\/$|\?|$)/
// @match     /^https?:\/\/steamcommunity\.com\/(?:id|profiles)\/.*\/tradeoffers/
// @match     /^https?:\/\/steamcommunity\.com\/tradeoffer.*/

**Comment by stickerx** [comment]
1.0.1

not showing number total of serie

**Comment by XIU2** [comment]
No need to write so many regular expressions.
The script works fine on my inventory page.

**Comment by XIU2** [comment]
Change it to this:
```
// @match https://steamcommunity.com/id/*/inventory*
// @match https://steamcommunity.com/profiles/*/inventory*
```

**Comment by stickerx** [comment]
It works great now  

but the first version of the script was working on marketable cards and Not Marketable

Now not working with Not Marketable cards only  Marketable cards

**Comment by XIU2** [comment]
This can be solved, just separate it.
Use the old scheme in your own inventory, and use the new scheme in others' inventory.

**Comment by stickerx** [comment]
that work perfectly thank you so so much sir

God bless you

**Comment by XIU2** [comment]
``` JavaScript
// ==UserScript==
// @name         Steam shows the total number of cards
// @version      1.0.2
// @author       X.I.U
// @description  Steam shows the total number of cards
// @match        https://steamcommunity.com/id/*/inventory*
// @match        https://steamcommunity.com/profiles/*/inventory*
// @icon         https://store.steampowered.com/favicon.ico
// @grant        GM_xmlhttpRequest
// @grant        GM_getValue
// @grant        GM_setValue
// @run-at       document-end
// @namespace    https://github.com/XIU2/UserScript
// @supportURL   https://github.com/XIU2/UserScript
// @homepageURL  https://github.com/XIU2/UserScript
// ==/UserScript==

(function() {
    'use strict';
    var cardData = JSON.parse(GM_getValue('cardData', '{}')), style = '';
    mutationObserver();


    // Listen event
    function mutationObserver() {
        const callback1 = (mutationsList, observer) => {
            for (const mutation of mutationsList) {
                for (const target of mutation.addedNodes) {
                    if (target.nodeType != 1 || !(target.tagName === 'A' && target.href.indexOf('/gamecards/') > -1)) break
                    let id = /(?<=gamecards\/)\d+/.exec(target.href)[0];
                    if (cardData[id]) {addNum(cardData[id], id, target);} else {getPageElems(target.href, id, target, '.inventory_iteminfo:not([style*="display: none"]) .item_owner_actions > a');}
                }
            }
        };

        const callback2 = (mutationsList, observer) => {
            for (const mutation of mutationsList) {
                for (const target of mutation.addedNodes) {
                    if (target.nodeType != 1) break
                    let aHref = target.querySelector('a[href*="market/listings/"]');
                    if (!aHref) break
                    let id =/(?<=\/)\d+(?=-)/.exec(aHref.href)[0]
                    if (cardData[id]) {addNum(cardData[id], id, aHref);} else {getPageElems(`https://steamcommunity.com/my/gamecards/${id}/`, id, aHref, '.inventory_iteminfo:not([style*="display: none"]) .item_market_actions a[href*="market/listings/"]');}
                }
            }
        };
        let observer;
        if (location.pathname.indexOf('/profiles/') > -1) {
            observer = new MutationObserver(callback2); style = 'margin-left: 10px;'
        } else {
            observer = new MutationObserver(callback1);
        }
        observer.observe(document, { childList: true, subtree: true });
    }


    // Get data
    function getPageElems(url, id, target, css) {
        GM_xmlhttpRequest({
            url: url,
            method: 'GET',
            headers: {'Referer': location.href},
            timeout: 5000,
            onload: function (response) {
                try {
                    let num = response.responseText.match(/\<img class\=\"gamecard\"/g).length;
                    //console.log(num, id, target)
                    cardData = JSON.parse(GM_getValue('cardData', '{}')); cardData[id] = num; GM_setValue('cardData', JSON.stringify(cardData).replaceAll('"','\"'));
                    if (document.querySelector(css).href === target.href) addNum(num, id, target);
                } catch (e) {
                    console.log(e);
                }
            }
        });
    }


    // Add to page
    function addNum(num, id, target) {
        //console.log(num, id, target)
        if (target) target.insertAdjacentHTML('afterend', `<span style="${style}" data-id="${id}"><b>Total: ${num}</b></span>`);
    }
})();
```

**Comment by XIU2** [comment]
On the send offer page, I can't find the card ID (eg 550) near the card, so I can't add support.

I can only help you so far.

**Comment by stickerx** [comment]
the script on others' inventory does not support  [Not Marketable] Only  Marketable


Example; https://steamcommunity.com/id/arashtitan/inventory#753_6_15025012680


test to see

**Comment by XIU2** [comment]
Your request cannot be fulfilled because for me the other people's inventory page I see is incomplete.
The reason I have said above.

**Comment by heroboy** [comment]
这了一圈，就这个外国人你陪他折腾了那么久。
你是来联系英语的吗。
