### ISSUE TITLE
[GithubEnhanced] hub.fastgit.org blocked by GFW FinalEndPoint

### ISSUE THREAD

**Issue by richex-cn** [XIU2/UserScript#161]
https://t.me/fastgitchannel

![20220121_113840_SP](https://user-images.githubusercontent.com/25103518/150462267-e60a1a57-bdf9-4e30-9ae7-f65ac68ac1b7.png)

![20220121_113851_SP](https://user-images.githubusercontent.com/25103518/150462272-659c2d76-3895-4b2c-94d7-1c22dbf0f9a5.png)

![20220121_114706_SP](https://user-images.githubusercontent.com/25103518/150462274-99ea459b-3c52-4a83-82fb-2e7252d4acc8.png)

> Hi all,
> Today is 18/01/2022, it is destined to be a day like no other in FastGit history.
> We have confirmed that the one core component of FastGit (which is the hub if you want to know specifically) is blocked by GFW. This issue could be fixed by waiting until it is unblocked automatically, but it has a quite bare possibility. Our team is deliberating in order to figure out a feasible solution to handle this issue, but unfortunately, we do not have any planned solution currently.
> Apologise again for the inconvenience we caused. And really appreciate everyone's support and hard work.
> Finger cross to FastGit. And do not forget: today is 18/01/2022.
> 
> KevinZonda
> Director of FastGit UK
> Birmingham, England, UK

> We have set up a new alternate service so that you can still keep enjoy FastGit UK's service. But we have no idea when will this one be stopped.
> 
> Here is the address:
> hub.fastgit.xyz
> 
> FastGit UK Team
> Birmingham, United Kingdom

**Comment by XIU2** [comment]
检查了下，没有见到 DNS 污染，其他子域名均正常，只有 ` hub.fastgit.org ` 这个子域名似乎被 **SNI 阻断**了。
我认为之所以仅仅该子域名被阻断的原因，应该是其具有镜像站作用（可用来直接访问 Github 内容）。

官方更换域名并不能解决避免再次被封，正确的做法应该是将 clone 加速功能独立为子域名，放弃对国内提供 Github 网页的镜像服务，否则怕是换一个域名就封一个域名。。。

**Comment by richex-cn** [comment]
@KevinZonda Hey guy~

**Comment by KevinZonda** [comment]
FinalEndPoint 是一个用于解决一些无法被服务请求的一个方式，我可能在之后会做一个更清楚的解释。 

目前 SNI 阻断我们已经清楚（其仅出现在访问为 FastGit 正确后端+HTTPS才可能触发）。内部讨论的结果是可能触犯了自动化规则导致了不良后果。

我们已经设计了一个 ENF (Emergency Network Framework) 以应对未来可能的网络问题。尽管在封锁之前我们已经进行了 hosts 文件对应的设计与开发，但是这并不适用于目前的 SNI。

感谢大家对 FastGit 的支持与帮助。
