### ISSUE TITLE
[新标签页打开链接] GITHUB搜索会出现两个搜索结果界面

### ISSUE THREAD

**Issue by ChaunceyLong** [XIU2/UserScript#163]
这个可以改吗？我在github的搜索栏搜索会弹出两个结果界面

**Comment by XIU2** [comment]
对于一些使用 pajx 技术的网页，会出现你描述的情况，该问题无法解决。

pajx 你可以简单的理解为，点击链接并没有刷新/跳转网页，但是网页内容/ URL 却改变了。
