### ISSUE TITLE
[护眼模式] 希望修改一下模式3的样式

### ISSUE THREAD

**Issue by Dioooooooor** [XIU2/UserScript#164]
我个人比较喜欢黑色的背景，所以选择模式3进行使用，但是我感觉在模式3下，总有一种模糊的感觉，好像有一层雾蒙在上面，就跟下图一样，能不能修改成比较纯的黑色呢？
[![7oSUcq.png](https://s4.ax1x.com/2022/01/24/7oSUcq.png)](https://imgtu.com/i/7oSUcq)

**Comment by XIU2** [comment]
因为模式 3 就是在网页上加了一层反色负片滤镜，只能修改反色程度，无法随意改颜色。。。

**Comment by XIU2** [comment]
你可以在 Tampermonkey 右上角脚本菜单中点击 [自定义当前模式]，将反色程度从默认的 80 改为 90 效果如下：
![01](https://user-images.githubusercontent.com/54703944/150720134-cd8ba13a-e07b-48ba-8d05-ccf6f7b4f23e.png)

**Comment by Dioooooooor** [comment]
确实可以，个人觉得调到96非常不错
