### ISSUE TITLE
【建议】吾爱论坛美化

### ISSUE THREAD

**Issue by MarsTLBAD** [XIU2/UserScript#17]
参考
https://www.52pojie.cn/thread-1252714-1-1.html
https://www.52pojie.cn/thread-747305-1-1.html
https://attach.52pojie.cn/forum/202008/24/010234q8obujtmn7i9yu77.png
建议增加以下功能：【或者改为脚本按钮开关可选的”进阶美化“】
1.更进一步缩减回帖空白区域变成一行（隐藏回帖人的头像、主题-帖子-积分）
2.自动低亮度显示无意义水贴
个人建议：不隐藏楼主的”收听Ta“
感谢大佬的辛苦付出！

**Comment by XIU2** [comment]
emmm 这个脚本本身只是我自用的，也是按照我的喜好调整的。

你说的这两个功能我也不是很感兴趣。。。

**Comment by XIU2** [comment]
更新了下，只恢复显示了 [收听 TA] 按钮。
