### ISSUE TITLE
提供加速域名

### ISSUE THREAD

**Issue by feizhuqwq** [XIU2/UserScript#170]
# 这是我自己的部署加速域名，欢迎使用
# gh.feizhuqwq.com

如果可能的话，请放置我的博客地址 : https://www.feizhuqwq.com/

**Comment by XIU2** [comment]
OK 感谢提供~
在 Greasyfork 中也注明了你的博客。

**Comment by feizhuqwq** [comment]
感谢，很高兴我能为公益项目作出贡献

**Comment by feizhuqwq** [comment]
抱歉，请将[gh.feizhuqwq.com](https://gh.feizhuqwq.com/)更改为[ghgo.feizhuqwq.workers.dev](https://ghgo.feizhuqwq.workers.dev/)前者存在DNS记录传播问题，后者更稳定

**Comment by XIU2** [comment]
已更新。

**Comment by feizhuqwq** [comment]
好的，非常感谢，抱歉添麻烦了

**Comment by XIU2** [comment]
提醒一下，目前 `*.workers.dev` 域名均已被 DNS 污染，因此 workers 服务只能路由绑定自定义域名来访问了。
