### ISSUE TITLE
知乎增强 移除登录弹窗失效

### ISSUE THREAD

**Issue by jdAction** [XIU2/UserScript#171]
edge浏览器现在从任何外链进入知乎都会提示登录,我的脚本是打开的且是最新的
![image](https://user-images.githubusercontent.com/87454525/152928891-46ee063c-4130-4999-9238-ad459fded2f6.png)

**Comment by XIU2** [comment]
无法复现。
我在 Edge 最新版本中，未登录状态下 且 关闭了广告屏蔽扩展，分别访问了 **问题页、文章页**，均**没有**弹出登录框。
关闭 [知乎增强] 油猴脚本后，可以看到弹出的登录框，再打开后确实看不到了。

同样的浏览器、脚本、网站，结果不一样，那说明是**其他地方不一样**导致的，你尝试**关闭所有其他脚本、扩展**，只保留 [知乎增强] 油猴脚本再试试，顺便在**隐身模式**下也试试，最后告诉我结果，到时候实在不行我就远程协助去帮你排查。

**Comment by jdAction** [comment]
又好了,我当前是开启所有的插件,又不弹了

**Comment by XIU2** [comment]
关闭所有其他脚本、扩展，只保留 [知乎增强] 油猴脚本，是否弹出登录框？
