### ISSUE TITLE
希望定制一个模拟网页点击的功能的脚本

### ISSUE THREAD

**Issue by bingge12** [XIU2/UserScript#172]
大虾你好
第一眼就看中了你，喜欢你的简介😄
我的V呢，WGSelect
感谢🙏

运行环境ios15, safari浏览器

**Comment by XIU2** [comment]
我没有 IOS 设备/环境，而且我写脚本全看兴趣，不对某个人单独定制写脚本，而且不接受付费。
我只接受那些大众/不少人会用到的，有强烈需求的脚本，我不希望脚本写出来就几个人用，这样完全没有成就感。

**Comment by bingge12** [comment]
好的，那谢谢啦
