### ISSUE TITLE
Github high speed server no reacheable

### ISSUE THREAD

**Issue by tbfly** [XIU2/UserScript#173]
https://github.com/XIU2/UserScript/blob/30b3215fdd59ac144e3b34de909c2de002568232/GithubEnhanced-High-Speed-Download.user.js#L43-L46

Pls update new servers.
thx!

**Comment by XIU2** [comment]
updated.
Added these two addresses.

**Comment by KevinZonda** [comment]
It was caused by an unexpected server issue and has been fixed.
