### ISSUE TITLE
[Github 增强] 希望添加文件夹下载

### ISSUE THREAD

**Issue by zsz00** [XIU2/UserScript#178]
现在只能 单文件下载, 不能文件夹下载, 希望支持!!!

**Comment by XIU2** [comment]
不是我不支持，而是无法支持，至少我想不到有什么方式可以单靠油猴脚本实现这个需求。。。
油猴脚本无法将 Github 服务器上的文件打包下载。

**Comment by zsz00** [comment]
我现在是装了个 gitzip-for-github 插件实现的, 你看看 有没有参考性

https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn

**Comment by zsz00** [comment]
他扩展了个鼠标右键功能

**Comment by XIU2** [comment]
既然已经有现成的，直接用不就行啦？。。。
非必要我是不会重复造轮子的。

**Comment by zsz00** [comment]
这样就能集成到一起, 少装一个插件. 
现在光github, 我都得装3个插件了

**Comment by XIU2** [comment]
吃完饭顺便看了下，大概原理好像是，通过 Github API 获取并下载文件暂存到浏览器中，然后将其整理打包压缩后导出浏览器。
这实现方法总觉得有点。。。另外 API 也是限制次数及频率的，常用的可能还需要自己去后台申请令牌。

如果你说的 3 个扩展都是只针对 Github 的，那么将功能 3 合 1 为一个扩展 与 分开独立的三个扩展相比，性能并不会好多少，也不会少占用多少资源，而且仅你提到的这个 gitzip 扩展代码量就是我现在这个 Github 脚本的 3、4 倍，因此我不会费劲去重复造轮子的，时间和精力上划不来。
