### ISSUE TITLE
小需求

### ISSUE THREAD

**Issue by Bush2021** [XIU2/UserScript#18]
您好，我有用永硕E盘的需求，您能否写一个自动展开所有目录的脚本，谢谢

**Comment by XIU2** [comment]
这玩意我很多年没见过了，你发给我个有内容的网址我看下。

**Comment by Bush2021** [comment]
您好，您看下：http://2006b.ys168.com/

**Comment by XIU2** [comment]
你想要怎样实现 [自动展开所有目录] 功能？

打开网页后自动展开？

我看有的目录下也有目录，能套好几层，全都打开吗？

****

另外，我发现手动点击时，点开这个就会自动关闭其他的目录。
这意味着无法直接通过脚本遍历模拟点击目录来实现你想要的功能，这可能还需要研究下如何解决该问题。

****

另外，我还发现了很坑的机制，即使强行展开了所有目录了，这时候会发现只有最后一次点击（手动/模拟）打开的目录下的子目录是可以点击展开的，其他强行展开的目录下的子目录是点不了的。。。

**Comment by Bush2021** [comment]
您好，感谢您的耐心回复。
我是希望能展开所有目录及子目录，也不一定要用脚本，一段 JS 小书签也可以。
我看一个博主是实现了该功能，您可以参考一下:https://axutongxue.com，这是通过 HTML 保存的，不知道对您有没有帮助，谢谢

**Comment by XIU2** [comment]
额，脚本就是 JS 呀，只不过你说的 JS 书签是把脚本写成一行了，因此 JS 书签只能实现简单的功能。

**Comment by XIU2** [comment]
看了下，这个网址的实现方法已经**超出 JS 范畴**了。

****

这个网站的全部展开目录功能，其实就是修改目录样式 `style="display: block;"` 为 `style="display: none;"` 这很容易理解。

在我看到你的需求时，我第一时间也是这样想的，但是这个办法**只能在这个网站上使用**，而**无法在永硕E盘的网站上使用**。

****

这是因为永硕E盘是需要先点击一下目录，这时才会**动态加载目录下内容**并修改目录样式显示出来，如果直接自己修改目录样式，只能看到一片空白。

而你给的这个网站是提前把**所有目录手动点开加载**完毕后，复制 HTML 代码放到自己的网站（并进行了一定修改），后续更新完全不需要永硕E盘了，只需要在自己网站中按照格式修改 HTML 代码即可（这个网站放的都是网站链接，没有存储和下载之忧）。

经过详细分析，得出的结论就是这个网站的实现方法已经**超出了单纯 JS 的范畴**，因此**无法单纯使用 JS 来实现**。

****

很抱歉，目前为止我没有想到更好的方案去实现你想要的功能。
