### ISSUE TITLE
[Github 增强 - 高速下载] 希望添加一个新的Github Raw文件加速地址

### ISSUE THREAD

**Issue by hacamer** [XIU2/UserScript#181]
# 介绍

- **iQDNS提供**

- **免费 Github RAW 加速访问地址 高速稳定可靠**

- **由iQZone服务器提供驱动。**

https://raw.githubusercontent.com/ → https://raw.iqiq.io/

**将Github的raw地址域名替换成raw.iqiq.io即可**

**服务器是香港腾讯云，文件实时更新**

![image](https://user-images.githubusercontent.com/73057402/156879643-4977bf21-549d-4023-b421-56f7917c5577.png)

**Comment by XIU2** [comment]
感谢分享，已添加~

**Comment by XIU2** [comment]
该域名解析的 IP 被墙了。。。（国外通，国内不通
```
101.33.125.235
```

**Comment by hacamer** [comment]
> 该域名解析的 IP 被墙了。。。（国外通，国内不通
> ```
> 101.33.125.235
> ```
已联系开发者

![IMG_20220401_184236.jpg](https://user-images.githubusercontent.com/73057402/161248482-23bf5f22-7687-4070-925e-aaed0204e74f.jpg)

**Comment by hacamer** [comment]
> 感谢帮忙提醒加速源开发者~
> 
> 这种情况确实比较奇怪，为啥会墙 IP，对于网站现在一般不都是只墙域名的么。。。 毕竟只墙 IP 的话，换个 IP 就解决了，也没啥墙的意义。。。

开发者已更换新的IP，可正常使用
![Screenshot_2022-04-03-12-50com microsoft emmx](https://user-images.githubusercontent.com/73057402/161412051-257ee44c-8cab-4ef9-99f6-32b350cd74f9.jpg)

**Comment by XIU2** [comment]
感谢提醒~

**Comment by XIU2** [comment]
有挂掉拉，不过这次看起来是服务器挂了，全球都不通。。。

**Comment by hacamer** [comment]
> 又挂掉啦，不过这次看起来是服务器挂了，全球都不通。。。

昨晚已经通知开发者修复了😂可能还没睡醒

**Comment by XIU2** [comment]
@hacamer 过去一个星期了，是不是不再恢复了呀。。。
我看服务器 IP 是能 Ping 通的，说明服务器正在运行，但是 443 端口全球不通，因此应该是**网站程序挂了**或**被关闭**了。

**Comment by hacamer** [comment]
> @hacamer 过去一个星期了，是不是不再恢复了呀。。。 我看服务器 IP 是能 Ping 通的，说明服务器正在运行，但是 443 端口全球不通，因此应该是**网站程序挂了**或**被关闭**了。

开发者最近很忙，要不先移除吧，等他恢复了我就跟你讲

**Comment by XIU2** [comment]
@hacamer 我这边监测到已经恢复了~

**Comment by hacamer** [comment]
> 

嗯，我也看到了。IQ经常很忙，很多东西不能及时维修，我建议这个加速源加个提示吧

**Comment by XIU2** [comment]
这倒没有必要，毕竟用户也不傻，发现失效了自然会改用其他加速源，因此也没啥影响~

**Comment by XIU2** [comment]
@hacamer 又挂了，这次是证书到期了，今天刚到期。。。

**Comment by hacamer** [comment]
已通知开发者

**Comment by hacamer** [comment]
开发者已修好

**Comment by XIU2** [comment]
哈，感谢通知~

**Comment by XIU2** [comment]
好像又挂了，这次提示证书错误。。。

**Comment by hacamer** [comment]
> 好像又挂了，这次提示证书错误。。。 好像也都变成亚马逊的 IP 了？

没有喔，我这边正常
![图片](https://user-images.githubusercontent.com/73057402/209625380-a5905534-5099-41c3-a093-bf395394e67a.png)

---
btw 最近我发现我的 `Firefox Nightly for Windows 110.a1 (Built 2022/12/27)` `Tampermonkey 4.18.1` `脚本版本最新版` 这个脚本似乎没注入 不知道咋办 换Edge是正常的 有什么办法可以排查一下吗？
![图片](https://user-images.githubusercontent.com/73057402/209626085-201a6099-419f-47b1-9565-02de31903485.png)
![图片](https://user-images.githubusercontent.com/73057402/209626253-4c7dec2b-096e-4295-a902-9d02e747aca6.png)

**Comment by XIU2** [comment]
又测试了下，好像逐渐恢复了（还有部分地区存在 DNS 缓存，依然是亚马逊的 IP）。
估计是 iqiq 误操作改了什么导致域名被解析到了亚马逊的 IP，既然官方已经及时发现并解决了，那就行了~

![01](https://user-images.githubusercontent.com/54703944/209626604-b35397ae-34d5-4651-b98c-9076e7231d5e.png)

**Comment by XIU2** [comment]
至于 Github 增强 - 高速下载 油猴脚本。
我在 Firefox 108.0.1 (64 位) + Tampermonkey 4.18.1 + 最新脚本下测试，没有发现什么问题。

我只有这一个 Firefox 浏览器版本，专门用来测试脚本在该浏览器上兼容性的。

![02](https://user-images.githubusercontent.com/54703944/209627350-087ca66a-8a61-4c59-aa0c-79cda45725bc.png)
![03](https://user-images.githubusercontent.com/54703944/209627355-3e451c41-f0c8-4304-802e-c519959b7a4f.png)

**Comment by hacamer** [comment]
谢谢，重置了Tampermonkey就好了 ~不知道以前调了什么设置~
