### ISSUE TITLE
[V2EX 增强] 自动签到 功能失效

### ISSUE THREAD

**Issue by asnfohsdgfbkxcv** [XIU2/UserScript#182]
windows 10 LSTC 2021
X64
chrome 99

签到功能失效
100%复现

**Comment by XIU2** [comment]
确定吗？
我今天访问 V2EX 的时候，还正常签到成功了。。。

**Comment by XIU2** [comment]
刚刚访问 V2EX 的时候，特意截图了一下，自动签到功能一切正常。
![01](https://user-images.githubusercontent.com/54703944/156973399-805b1566-cfff-4ae2-a5b8-a80e5306167a.png)
