### ISSUE TITLE
[护眼模式] 自定义昼夜时间可以精确到分钟吗？或者用户在Dark Reader这个扩展里设置自己的经纬度来确定日出日落时间以此来设定昼夜时间

### ISSUE THREAD

**Issue by WrathGluttony** [XIU2/UserScript#184]
①请问自定义昼夜时间可以精确到分钟吗？不是6点到18点白天这样6|18，而是比如6:35|17:58这样昼夜时间精确到分钟
②当然也可以像Dark Reader这个扩展一样，用户在Dark Reader这个扩展里设置自己的经纬度，然后Dark Reader这个扩展就能按照该用户设置的经纬度来设定日出日落时间，根据日出日落时间来开启白天模式和夜晚模式

**Comment by XIU2** [comment]
可以，但我觉得并不是那么重要，做起来太麻烦，懒得做。

**Comment by WrathGluttony** [comment]
谢谢您开发这么好的脚本，第2个确实复杂，如果您有充足的开发时间，可以在后续的版本中考虑一下昼夜时间精确到分钟，其实这个脚本已经很好了，bow!

**Comment by XIU2** [comment]
精确到分钟这个功能，比较简单，今天稍后有空了我会给加上的，到时候会通知你。

**Comment by WrathGluttony** [comment]
太好了，谢谢作者大神！

**Comment by XIU2** [comment]
已更新脚本~

**Comment by WrathGluttony** [comment]
谢谢作者大神的无私付出
