### ISSUE TITLE
[知乎增强] 希望允许用户取消“点击空白处收起回答/评论”的功能

### ISSUE THREAD

**Issue by draftman9** [XIU2/UserScript#185]
首先，非常感谢作者开发出如此好用的脚本！
我在知乎编写评论时，不小心点击了一下空白处，导致评论被收起，等我再次打开时，我编写的内容全部消失了☹。我编写的评论通常较长，这正是我痛苦的主要原因。此外，我其实从未用过该功能，我看回答基本仅仅只看前几篇。所以我想问一问，是否有可能允许我取消该“点击空白处就收起”的功能。
再次感谢！😄

**Comment by XIU2** [comment]
你从来没有看过 脚本菜单 / 脚本功能介绍 吗？。。。
点击浏览器右上角的 Tampermonkey 扩展图标，在脚本菜单中点击 `✅ 快捷收起回答/评论 (点击两侧空白处)` 即可关闭该功能。
