### ISSUE TITLE
[知乎增强] 无法运行脚本

### ISSUE THREAD

**Issue by luotianyiismywife** [XIU2/UserScript#186]
首页打开，屏蔽视频失效无法设置，已更新最新版本。
win10，火狐98.0，油猴4.15.6154，脚本为2.0.1
![图片](https://user-images.githubusercontent.com/81459639/157410491-9b1f7502-7591-40da-8192-e05fd4a547f2.png)

**Comment by XIU2** [comment]
看截图的话，脚本没有运行，应该是报错了，我研究下。。。

**Comment by luotianyiismywife** [comment]
> 经过测试，脚本没有问题，测试环境中的各版本号和你的完全一致。 因此，应该是其他问题导致的，是否尝试过重装脚本？
> 
> 你按下 F12 选择 `控制台` 截图给我看看（截图全一些）。
> 
> 或者我**远程协助**帮你看看。 下载远程协助软件（这个是只有被控功能的单文件版，用完即删），告诉我你的**设备代码、临时密码**。 https://dl.todesk.com/windows/ToDesk_Lite.exe
> 
> ![01](https://user-images.githubusercontent.com/54703944/157413666-fb0d1198-bda4-4d52-a08f-25a9d3081a70.png) ![02](https://user-images.githubusercontent.com/54703944/157413677-9df20874-1c02-4a11-830f-b531a3d3d26a.png)
![图片](https://user-images.githubusercontent.com/81459639/157419463-bce41c7e-3f51-4a4e-b328-fffe6e4cc672.png)
![图片](https://user-images.githubusercontent.com/81459639/157419556-1976e1c6-aa3a-46e3-9fef-58fb0d042d41.png)
这些是控制台的报错。当然还有很多请问有什么导出的办法么

**Comment by luotianyiismywife** [comment]
> 我主要是看看有没有来自油猴脚本的报错，然后还需要进一步分析报错原因。
> 
> 这知乎网页的设计有问题，因此哪怕啥都不装只打开网页，控制台就能输出一堆错误，想在这么多错误里找到还是挺费劲的。
> 
> 干脆趁我有空，远程协助吧，可能几分钟就完事了，如果是图文交流怕是最少半天。。。

510 557 830 邀请您进行远程控制
ToDesk设备代码:510 557 830
临时密码:618470
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=wMuNxzMUb_doLYTMaMktF

**Comment by luotianyiismywife** [comment]
你走了之后就再次玄学了，哈哈哈哈

**Comment by XIU2** [comment]
那你再把 Tampermonkey 扩展允许隐私模式运行的选项打开看看。

在隐私模式下，打开知乎看看是否再次正常。

**Comment by luotianyiismywife** [comment]
试出来了，如果想要正常使用，需要更改一下扩展允许隐私模式运行的选项，不管原先是什么状态，更改一下就好了

**Comment by XIU2** [comment]
估计是 Tampermonkey 或 Firefox 两者之一存在小 BUG 吧。。。
不过我这边 Firefox 倒是一切正常。

**Comment by luotianyiismywife** [comment]
给tampermonkey的开发者交了个issue，顺便问了一下如何让回退，看看下个版本更新吧

**Comment by luotianyiismywife** [comment]
好家伙，打开了就好了发自我的手机-------- 原始邮件 --------发件人： XIU2 ***@***.***>日期： 2022年3月9日周三 18:48收件人： XIU2/UserScript ***@***.***>抄送： luotianyiismywife ***@***.***>, Author ***@***.***>主    题： Re: [XIU2/UserScript] [知乎增强] 无法运行脚本 (Issue #186)

那你再把 Tampermonkey 扩展允许隐私模式运行的选项打开看看。

在隐私模式下，打开知乎看看是否再次正常。
