### ISSUE TITLE
[自动翻页] 希望支持微信读书

### ISSUE THREAD

**Issue by mining-id** [XIU2/UserScript#188]
目前是只能在一章节内滑动，然后需要点击下一章才能继续滑动翻页
![image](https://user-images.githubusercontent.com/94845005/157620611-b7657814-2298-4284-a723-1834f4569817.png)

任何页面，比如https://weread.qq.com/web/reader/2ec3289071e128722ec7b71

感谢！

**Comment by mining-id** [comment]
@XIU2 感谢大大回复！
不大懂编程，但微信读书支持快捷键 ← → 翻页，所以是否可以判断无法翻页的时候，模拟下快捷键呢？

**Comment by XIU2** [comment]
1. 单纯 JavaScript 脚本是**无法模拟按键**的，因为受到浏览器的安全策略影响（否则就太容易被利用了）
2. 我这个脚本是将**下一页的内容衔接到当前网页底部**，而不是代替你去点击翻页按钮，这完全是两码事。
况且，脚本不知道你什么时候才看完，所以如果替你按下一页，那么你可能还没看完就被迫翻页看下一页了，这能忍？

**Comment by mining-id** [comment]
@XIU2 大概明白了，感谢您耐心解答
