### ISSUE TITLE
【反馈bug】吾爱增强自动翻页：倒数第二页无法自动翻页到最后一页

### ISSUE THREAD

**Issue by MarsTLBAD** [XIU2/UserScript#19]
反馈一个bug：吾爱增强自动翻页：倒数第二页无法自动翻页到最后一页，目测感觉可能是拼接函数的变量上界没有+1

**Comment by XIU2** [comment]
这个其实只是显示上的 BUG。

实际上已经翻页到底了，只是替换网页中的翻页按钮处出了一点问题，我很早就注意到了，不过一直懒得去查。。。

有空的时候，我研究下怎么修复这个替换失效的问题。

**Comment by XIU2** [comment]
简单研究了下，发现是因为要同时替换页数和那个底部的 [下一页] 按钮导致的，因为最后一页没有 [下一页] 按钮，导致没有正确替换。考虑到有了自动翻页，大家也根本用不上这个 [下一页] 按钮了，我就干脆把这个按钮隐藏了（只有开启 [帖子内自动翻页] 功能时，才会隐藏 [下一页] 按钮）。

#### 2021年02月16日，版本 v1.2.0
1. **修复** 帖子内自动翻页至最后一页时页数显示不正确的问题。
