### ISSUE TITLE
希望制作一个edge浏览器“点击链接，打开到新标签页，并且跳转”功能的脚本

### ISSUE THREAD

**Issue by miaomiao-222438** [XIU2/UserScript#193]
你好，我用的是edge浏览器。
平常打开页面会直接覆盖原页面。平常都是右键链接，“在新标签页中打开链接”比较麻烦。
想直接左键点击，直接打开链接到新的标签页，并且跳转。
希望看到可以帮我做一个，非常感谢。

**Comment by miaomiao-222438** [comment]
平常喜欢逛NGA，那个覆盖打开新页面用起来好不舒服。您看下这个网站可以改吗

**Comment by XIU2** [comment]
我写的有个 [新标签页打开链接](https://greasyfork.org/zh-CN/scripts/429714) 脚本。  

或者你可以选择用**鼠标中键**打开链接，或按住 **Ctrl + 鼠标左键**。
