### ISSUE TITLE
[Github 增强 - 高速下载] 对fastgit新域名的支持

### ISSUE THREAD

**Issue by whx1024** [XIU2/UserScript#194]
原 hub.fastgit.org 已失效，官方已更换新域名：hub.fastgit.xyz
见https://fastgit.org/

原文：
[hub.fastgit.xyz](https://hub.fastgit.xyz/)
Mirror of github.com, supports HTTPS clone. Previous one is dead, use new one!

**Comment by XIU2** [comment]
注意，只有 `hub.fastgit.org` 更换为 `hub.fastgit.xyz` 了，其他的加速域名都没变（我测试过了）。

因此在我脚本里，很早就改了 clone 加速源里的域名了。

**Comment by whx1024** [comment]
大约是这里，
// @match        *://github.com/*
// @match        *://hub.fastgit.org/*

**Comment by XIU2** [comment]
这里我倒是没注意到，已经更新修改了。

**Comment by lihugang** [comment]
请问现在还能上吗？
上海，电信
![屏幕截图 2022-08-31 222307](https://user-images.githubusercontent.com/94808542/187704923-17ff8440-0a97-437f-88a3-385df9ded828.png)

**Comment by XIU2** [comment]
@lihugang 该域名已经被墙了，昨天就更新脚本将其移除了。
