### ISSUE TITLE
新标签页打开链接1.0.7版本在Chrome（windows10）无法点击打开链接

### ISSUE THREAD

**Issue by EvatsugDnalloR** [XIU2/UserScript#195]
Chrome版本：99.0.4844.84
脚本版本：1.0.7
问题：在Chrome搜索界面点击链接没有任何反应，以及点击大部分可互动链接都没有反应
临时解决办法：降级至1.0.6版本
望作者下个版本修复......

**Comment by XIU2** [comment]
修复了，准确说是代码回退了（当然版本号还是递增了），上个版本的代码有点问题当初没发现，后续再慢慢研究吧。
