### ISSUE TITLE
那种本身是瀑布流的网页能不能增加一键到底功能

### ISSUE THREAD

**Issue by Cyiming** [XIU2/UserScript#198]
类似微博评论 使劲往下滑加载下一页那种  这种不识别 左下角也没有页码  如果能一键无限往下拖动就好了

**Comment by XIU2** [comment]
使劲往下滑？什么意思？

目前脚本内置的针对自带自动无缝翻页功能的网站（像那种 [加载更多] 之类的按钮），也有相应规则，但是比较保守，因为担心脚本识别错误误触。

**Comment by Cyiming** [comment]
微博只是举例哈 比如b站动态也是

**Comment by XIU2** [comment]
B 站动态页，不是翻到底部自动加载更多了吗？无需手动点击 [加载更多] 之类的按钮呀。

**Comment by XIU2** [comment]
没明白你到底要表达什么意思。。。

**Comment by Cyiming** [comment]
是啊 你得手动往下滑啊  举个极端的例子 今天是4月2号 我要翻到2019年的动态 需要手动滚动鼠标8个小时 如果有个功能一键到底 不停地**自动往下滑动** 直到划不动 就是我想要的功能  

我们把翻页变成瀑布流 更加顺畅 但是翻页也有优点就是跳转  如果能自动下滑 或者每加载一次记录为页码一  想滑动到第十页 输入10  自动滑十下

**Comment by XIU2** [comment]
你的需求和我脚本相悖，因此不会添加该功能的。。。

你的需求，写一句代码放到书签里应该能大概满足了。

**Comment by XIU2** [comment]
你添加两个书签，网址就分别写这两行代码，需要的时候点一下书签就行了：

开始循环滚动至网页底部（触发翻页），2000 是间隔时间，单位毫秒
``` JavaScript
javascript:(function(){window['sttt']=true; var sttt=setInterval(function(){if(window['sttt']){window.scrollTo(0,9999999)}else{clearInterval(sttt)}}, 2000);})()
```

这个是用来停止的。
``` JavaScript
javascript:(function(){window['sttt']=false;})()
```
