### ISSUE TITLE
关于去掉jQuery的依赖

### ISSUE THREAD

**Issue by woshoxxx** [XIU2/UserScript#20]
据我观察，这些脚本所作用的网站大多（也可能是全部）没有用到jQuery，而且这些脚本引用jQuery只是为了使用其中的一小部分功能，多加载一个js文件就需要多一点时间，对于网速慢的用户不友好。所以要不要去掉jQuery的依赖？😶

**Comment by XIU2** [comment]
影响不大吧？
像这种 JS 文件加载一次后，就直接缓存到本地了，除非你主动清除浏览器缓存，否则下次访问就直接读取本地缓存文件了。

**Comment by XIU2** [comment]
我的大部分脚本都没用到 jQuery，只有少数几个脚本才用到了，而且用的也是国内 CDN。

首次加载也只需要 77 毫秒。

![2](https://user-images.githubusercontent.com/54703944/109127288-35b1c600-7789-11eb-9c52-3e4f5cdd3785.png)

**Comment by XIU2** [comment]
[Github 增强] 已经在 v1.4.2 版本移除 JQuery 依赖。
[知乎增强] 的话稍后也会移除。

这两个脚本是我最开始学习 JavaScript 时写的，因此当时过于依赖 JQuery，好在后来我写其他脚本都坚持使用 JavaScript 原生~

**Comment by XIU2** [comment]
[知乎增强] 已经在 v1.3.4 版本移除 JQuery 依赖。

目前我的所有脚本，都已经移除了 JQuery 依赖（就这两个脚本）。
