### ISSUE TITLE
[蓝奏云网盘增强] 使用暴力猴不能自动下载

### ISSUE THREAD

**Issue by fsnhljz** [XIU2/UserScript#201]
使用edge+暴力猴插件
打开标签页后，未等到加载到下载，就会自动关闭标签页，导致不能下载。
window.top.close(); // 关闭该后台标签页
注释掉这行以后可以下载，但就不会关闭标签了。是暴力猴插件问题么？

或者在打开新标签页的时候，快速自己激活一下标签页，也能下载和关闭

**Comment by XIU2** [comment]
你把下面那个 10 毫秒，给改成 1000 毫秒（或更高，毕竟只是测试）后再试试。
```
}, 10);
```

**Comment by fsnhljz** [comment]
刚测试，还是会有机率失败，估计是暴力猴插件对未激活标签不友好吧，听作者话，用油猴。
只不过油猴同步脚本功能用不了所以才用暴力猴。能顺带问一下油猴插件里面同步脚本能用么？我填了webdav地址保存没反映。

**Comment by fsnhljz** [comment]
设置3000，一样3秒后关闭标签，但一样不会有导出下载的动作

> 你把下面那个 10 毫秒，给改成 1000 毫秒（或更高，毕竟只是测试）后再试试。
> 
> ```
> }, 10);
> ```

**Comment by XIU2** [comment]
这个我不清楚，我都没用过 Tampermonkey 的同步功能，毕竟我用的脚本都是我自己写的。。。

**Comment by XIU2** [comment]
试了下，延迟一小会儿再去关闭标签页就没事了。

```
setTimeout(function(){window.top.close();},200)
```

你试试这个 200 毫秒行不行，我这边 Violentmonkey 可以。

**Comment by XIU2** [comment]
已更新脚本，你更新试试吧。

**Comment by fsnhljz** [comment]
> 

感谢，更新脚本后在暴力猴下可以了。打开新标签后能有个刷新的动作然后下载了，非常感谢。
