### ISSUE TITLE
[无缝自动翻页]smzdm.com什么值得买网站非预期的跳转

### ISSUE THREAD

**Issue by esolk** [XIU2/UserScript#202]
脚本版本： 5.7.1
问题描述：smzdm.com中打开任意优惠的文章详情页，向下滚动时会自动跳转至商品信息页面
复现方法：
1. 使用浏览器打开smzdm.com，并点击首页任意一个优惠，跳转至文章详情页面
2. 向下滚动页面至评论区域，即能100%触发该Bug，自动跳转至商品信息wiki页面

**Comment by XIU2** [comment]
这是匹配到了脚本内置的 "部分 自带无缝翻页 网站" 通用规则。

**Comment by XIU2** [comment]
更新脚本排除了。
