### ISSUE TITLE
[自动无缝翻页] 网站支持

### ISSUE THREAD

**Issue by rcyggdra** [XIU2/UserScript#203]
「NSFW」https://www.loverslab.com/

**Comment by XIU2** [comment]
已添加支持~（贴子列表页、帖子内、搜索页

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

对于帖子内，如果要回帖，请点击左下角悬浮的页码按钮 `临时暂停翻页`，如果实在不习惯，可以在脚本菜单中把 `帖子内自动翻页` 功能关掉。

****

因为我同时还处理了另两个漫画网站，花了点时间，因此更新慢了点~
