### ISSUE TITLE
[知乎增强] 搜索页屏蔽盐选功能失效

### ISSUE THREAD

**Issue by liaanj** [XIU2/UserScript#208]
对脚本单独测试也能成功复现
![image](https://user-images.githubusercontent.com/98246557/163666395-198bb98f-ffc1-4154-8211-99f78f04e69d.png)
![image](https://user-images.githubusercontent.com/98246557/163666580-bbf563b9-9337-4d8b-87dd-0cd637938eee.png)

**Comment by XIU2** [comment]
没有失效。
失效的前提是曾经有效过，但问题是 `屏蔽盐选内容` 功能只适用于问题页（回答页）。。。
无论是首页、搜索页，这种信息流列表的页面，在展开回答前是无法分辨是否为盐选内容的，因此无法直接屏蔽。
