### ISSUE TITLE
[自动无缝翻页] 小众软件排版问题

### ISSUE THREAD

**Issue by kerna60** [XIU2/UserScript#209]
www.appinn.com
自动翻页后页面显示不全

**Comment by XIU2** [comment]
那里不全？我看了下没问题呀。

**Comment by XIU2** [comment]
我知道了，你应该是匹配到通用规则了。

出现这种情况，一般是因为你没有 `更新外置翻页规则` 导致的。

一般安装脚本后，第一次访问网页，脚本会自动后台去获取外置翻页规则（浏览器右下角正常来说会提示），但如果因为什么原因导致获取失败（或者还没获取完成，你就跳转、关闭网页了），那么就会缺失我写的 600+ 个网站规则。

你 `更新外置翻页规则` 试试吧（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

**Comment by XIU2** [comment]
我更新了下脚本，确保安装脚本后，第一次访问网页，大家能注意到首次获取 `外置翻页规则` 的提示。

**Comment by kerna60** [comment]
看到了，我更新了外置翻页规则，可以正常翻页，大佬辛苦，大佬牛逼
