### ISSUE TITLE
Github增强-高速插件无作用

### ISSUE THREAD

**Issue by perrogg** [XIU2/UserScript#21]
测试环境：M1 Macbook Air (Big Sur 11.2)；Intel MacBook Pro 2019 (Catalina 10.15.7)
浏览器 Safari 和 Microsoft Edge
均不起作用

Tampermonkey和脚本版本信息
<img width="1001" alt="截屏2021-02-27 23 13 17" src="https://user-images.githubusercontent.com/14990848/109391448-174af680-7952-11eb-8220-9bd00018985b.png">

打开页面效果，无高速下载链接（脚本已启用）
<img width="1224" alt="截屏2021-02-27 23 21 24" src="https://user-images.githubusercontent.com/14990848/109391579-c38cdd00-7952-11eb-8118-20daef76e326.png">
<img width="1064" alt="截屏2021-02-27 23 22 20" src="https://user-images.githubusercontent.com/14990848/109391583-c7206400-7952-11eb-9440-53b94fc8e366.png">

**Comment by XIU2** [comment]
Safari 我没有设备无法测试。

而 Edge 你指的是新版的吗？（Chromium 内核），**新版 Edge 是可以正常使用**的（刚刚又试了下）。
至于旧版本的 Edge，因为我这边旧版本也没了，也没办法测试。

**Comment by perrogg** [comment]
> Safari 我没有设备无法测试。
> 
> 而 Edge 你指的是新版的吗？（Chromium 内核），**新版 Edge 是可以正常使用**的（刚刚又试了下）。
> 至于旧版本的 Edge，因为我这边旧版本也没了，也没办法测试。
> 
> 另外，我用的是**正式版** v4.11 ，你的看起来好像是**测试版**吧。
> 你可以在 **Tampermonkey - 实用工具 - 文件**中，**导出**扩展数据文件，然后安装正式版 v4.11 再去**导入**。

Edge是Mac下的最新版，还是不行，很奇怪。Windows系统我没试过。
我看了Edge 的 Tampermonkey版本是最新的4.11啊。通过官方商店安装的。
<img width="339" alt="截屏2021-02-28 11 13 09" src="https://user-images.githubusercontent.com/14990848/109407086-15684e00-79b9-11eb-8de2-4da7006668a3.png">
<img width="530" alt="截屏2021-02-28 11 31 54" src="https://user-images.githubusercontent.com/14990848/109407087-17321180-79b9-11eb-8317-3b5947f1fb26.png">
<img width="702" alt="截屏2021-02-28 11 32 05" src="https://user-images.githubusercontent.com/14990848/109407088-17321180-79b9-11eb-936e-9233305cc004.png">

**Comment by XIU2** [comment]
我这边 Edge 新版浏览器一切正常。

![01](https://user-images.githubusercontent.com/54703944/109407192-bf47da80-79b9-11eb-80af-ba418ef27ae8.png)
![02](https://user-images.githubusercontent.com/54703944/109407193-c0790780-79b9-11eb-9d58-d87973a534c5.png)
![03](https://user-images.githubusercontent.com/54703944/109407194-c0790780-79b9-11eb-8546-67e4ddf9ea18.png)

**Comment by XIU2** [comment]
你在 Github 页面下，按下 `F12` 键选择 `Console` 截图给我看看，看看是否有该脚本的**报错内容**。

**Comment by perrogg** [comment]
> 你在 Github 页面下，按下 `F12` 键选择 `Console` 截图给我看看，看看是否有该脚本的**报错内容**。

您好！感谢您的回复。我又试了一下，Mac系统下Edge没问题了，奇怪昨天不行。

**另外苹果自带的Safari浏览器还是有问题（Tampermonkey是Safari下的最新版）**。调控制台出来看，错误如下

Catalina 10.15.7, Safari 14.0.2
<img width="1112" alt="截屏2021-02-28 12 31 38" src="https://user-images.githubusercontent.com/14990848/109409008-e73f3a00-79c9-11eb-90d2-688079de08ee.png">

Big Sur 11.2, Safari 14.0.3
<img width="1276" alt="截屏2021-02-28 12 37 11" src="https://user-images.githubusercontent.com/14990848/109409014-f58d5600-79c9-11eb-888a-ab15d5ca41ee.PNG">

**Comment by XIU2** [comment]
额，这些错误都是 Github 自身的错误，没有看到我的脚本报错。。。

**Comment by XIU2** [comment]
你对比一下 Safari 和 Edge 的 Console 差别。

**Comment by perrogg** [comment]
> 你对比一下 Safari 和 Edge 的 Console 差别。

Safari是报错；Edge 现在能用了，没有报错，只显示了两个小问题（如下图）。
<img width="1436" alt="截屏2021-02-28 13 58 23" src="https://user-images.githubusercontent.com/14990848/109409393-405c9d00-79cd-11eb-906f-17ac154f3f7a.png">

**Comment by XIU2** [comment]
你提供的 Safari 截图中，没有看到来自用户脚本（油猴脚本）的错误。。。

**Comment by perrogg** [comment]
> 你提供的 Safari 截图中，没有看到来自用户脚本（油猴脚本）的错误。。。
> 
> 这样的话，我也看不出问题出在哪里。

我启用/停用脚本，Safari都是一样报错。Safari设置里内容拦截器也关闭了，弹出式窗口也允许了，我也不知道咋回事。不过还是谢谢您！Edge能用。

**Comment by XIU2** [comment]
Safari 里其他脚本都正常吗？
会不会是 Safari 对用户脚本进行了一些限制什么的。。。

**Comment by perrogg** [comment]
> Safari 里其他脚本都正常吗？
> 
> 会不会是 Safari 对用户脚本进行了一些限制什么的？
> 还是说 Safari 的 JS 标准和其他浏览器不一样？
> 或者 Tampermonkey 在 Safari 上有什么限制？
> 
> 我没办法自己去测试就很难受。。。

我不是做这方面的，您说的问题我不清楚，可能有限制吧。

但我在Safari的tampermonkey下装了十来个脚本（和edge都一样），其他脚本Edge和Safari要么都能用，要么都不能用，总之使用效果基本一致的。

不知道其他人遇到这个问题没，可能本身mac用户就少，在Safari下用您脚本、遇到问题想到反馈的人少吧。

**Comment by XIU2** [comment]
这种情况，我也没办法去解决...
那就先关闭该 Issues 吧...

**Comment by XIU2** [comment]
最近又有个用 Safari 浏览器的无法使用的 Issues，所以如果你想要解决该问题的话，我可以尝试**远程协助**来帮你看看。

毕竟如果不能亲自上手检查，我是无法获取问题原因并解决的。

**Comment by XIU2** [comment]
刚才有个热心人士让我远程协助看了下 MAC，发现 Safari 是可以正常运行 [Github 增强] 脚本的呀~
- 用于测试的 Safari 版本号：15.0 (17612.1.26.1.3)

如果你依然无法使用，请在下面回复，我会重新开启该问题的。

**Comment by XIU2** [comment]
额，忘记了，MAC 的是这个：https://dl.todesk.com/macos/ToDesk_macOS_2.0.3.pkg
