### ISSUE TITLE
[自动无缝翻页]  豆瓣自动翻页无限触发

### ISSUE THREAD

**Issue by zxyyxzzxy** [XIU2/UserScript#211]
浏览器：Chrome浏览器100.0.4896.75（正式版本）
豆瓣电影翻页无限触发，会一直往下翻页，直到最后一页

**Comment by XIU2** [comment]
这个其实是豆瓣网站自身的问题。像选电影这些页面，下面自带的 `加载更多` 按钮被脚本识别到了，但是豆瓣这个按钮，点击后会**强制滚动网页**，很**反人类**的设计。。。

**Comment by XIU2** [comment]
这个问题我无法解决，我已经更新脚本，在匹配通用规则时将豆瓣排除了。

**Comment by zxyyxzzxy** [comment]
原来如此，其实豆瓣也是为了让体验更好才这么做的吧，稍微有点多此一举，不过习惯了还好，他滚动以后第一排完整显示的电影就是下一页的电影了

**Comment by XIU2** [comment]
我见过这么多网站，写了这么多规则，像豆瓣这样 [加载更多] 会**强制滚动网页**的，我只见过这一个。。。
不顺应**主流操作设计逻辑**，就可以算是反人类，因为大家都习惯了主流操作设计逻辑，突然来个不一样的，大家都不会习惯，也并不是所有用户都会坚持去习惯下来的，很多用户可能就会因此而流失~

虽然我只是个自学自给自足的业余程序员，但我也明白，不要对抗、逆转用户基本习惯，这样很容易让用户厌恶。。。

**Comment by zxyyxzzxy** [comment]
确实做得有点不伦不类，一般像这种瀑布流都是直接做成滚动自动加载，而不是让用户去点加载按钮然后自动滚动

**Comment by XIU2** [comment]
是啊，我也想不明白，很多网站都已经实现自动无缝加载的效果了，但是却偏偏非做个按钮，让用户点击一下再去加载。。。
感觉有点多此一举，这显然不是从用户体验角度出发设计的~

**Comment by XIU2** [comment]
最近发现豆瓣已经改版了 选电影/电视剧 的页面，已经不会强制滚动网页了，因此我已经将其添加支持了。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

**Comment by zxyyxzzxy** [comment]
豆瓣终于改过自新了，泪目。ps：虽然看不懂代码，但是感觉很优雅
