### ISSUE TITLE
[自动无缝翻页] 希望适配一下 AdGuard（软件，运行环境）

### ISSUE THREAD

**Issue by hacamer** [XIU2/UserScript#212]
我在AdGuard软件（安卓版）添加该脚本，使用起来非常顺手，非常好用  
但是近期发现一个问题，AdGuard里运行的脚本似乎无法获取外部资源  
每次打开网页都会显示弹窗，如图所示
![image](https://user-images.githubusercontent.com/73057402/163748296-bc56859d-5133-4b28-bf7c-ae3ee1a0a185.png)

希望大佬看一下

个人的想法是把翻页规则内置到脚本（独立出去，与原脚本分离，即新脚本=旧脚本+翻页规则，通过action运行时合并），不知道行不行

**Comment by XIU2** [comment]
我的脚本都是以 Tampermonkey 为基础设计的。

其他支持油猴的扩展/软件并不能完全兼容 Tampermonkey 的函数命令什么的。

我当初费劲把所有内置翻页规则都给手动格式化转到外置翻页规则里，将其分离，结果你又让我在合并回去。。。

**Comment by XIU2** [comment]
另外，这个提示弹窗是我昨天才加上的，你每次打开网页都会弹出这个，意味着根本就**没有**把获取到的外置翻页规则**存储**起来。

如果你以前一直在用我这个脚本，那说明以前你**每次打开网页**，脚本都会去**获取一次外置翻页规则**，然后再去重新匹配一次规则。。。所以问题并不是近期出现的，而是一直都存在，只是你没发现。

而正常情况下应该是，安装脚本后，首次打开网页，脚本会获取外置翻页规则，并存储到脚本配置中，下次打开网页**直接从本地读取**，间隔 2 天后，脚本才会后台更新外置翻页规则。

而你这个每次打开网页都在线获取外置翻页规则，属实把体验下降了一个等级，要知道在线获取可能需要好几秒才行。。。

**Comment by hacamer** [comment]
> 另外，这个提示弹窗是我昨天才加上的，你每次打开网页都会弹出这个，意味着根本就**没有**把获取到的外置翻页规则**存储**起来。
> 
> 如果你以前一直在用我这个脚本，那说明以前你**每次打开网页**，脚本都会去**获取一次外置翻页规则**，然后再去重新匹配一次规则。。。所以问题并不是近期出现的，而是一直都存在，只是你没发现。
> 
> 而正常情况下应该是，安装脚本后，首次打开网页，脚本会获取外置翻页规则，并存储到脚本配置中，下次打开网页**直接从本地读取**，间隔 2 天后，脚本才会后台更新外置翻页规则。
> 
> 而你这个每次打开网页都在线获取外置翻页规则，属实把体验下降了一个等级，要知道在线获取可能需要好几秒才行。。。

是哈，每次弹窗很烦，但是有些网站又能用

**Comment by hacamer** [comment]
> 我的脚本都是以 Tampermonkey 为基础设计的。
> 
> 其他支持油猴的扩展/软件可能**并不完全兼容** Tampermonkey 的函数命令什么的。
> 
> > 因为 Violentmonkey 几乎完全兼容 Tampermonkey，所以我的脚本在这两个油猴管理器上使用最好。
> 
> 因此其他支持油猴的扩展/软件，使用我的脚本，就会是**残缺**的，很多功能都等于被**阉割**了。
> 
> 比如你这个截图，本质上就是 AdGuard **缺少脚本配置存储**相关功能，导致脚本根本**存不住配置**。
> 
> 存不住配置，也就导致了很多问题，这个我无法兼容，否则需要大量修改脚本，把所有的配置都给**写死在脚本里**才行。。。
> 
> 我当初费劲把所有内置翻页规则都给手动格式化转到外置翻页规则里，将其分离，结果你又让我在合并回去。。。

不知道能不能整合到一个新脚本...

**Comment by XIU2** [comment]
我先研究下 AdGuard。

**Comment by hacamer** [comment]
> 我先研究下 AdGuard。

谢谢大佬

**Comment by XIU2** [comment]
我下了个 AdGuard 死活打不开。。。
一直正在启动，然后就没了，右下角软件图标变成黄色叹号了，左键点图标都没反应，右键点图标有菜单，但是也是点了没反应。。。

**Comment by hacamer** [comment]
> 我下了个 AdGuard 死活打不开。。。 一直正在启动，然后就没了，右下角软件图标变成黄色叹号了，左键点图标都没反应，右键点图标有菜单，但是也是点了没反应。。。

用手机版测试吧

**Comment by XIU2** [comment]
额，突然弹出来提示安装成功了什么鬼。。。
合着安装后第一次打开还需要安装一次。。。

**Comment by hacamer** [comment]
> 额，突然弹出来提示安装成功了什么鬼。。。 合着安装后第一次打开还需要安装一次。。。

你是在官网下载的吗？在github下离线包吧

https://github.com/AdguardTeam/AdguardForWindows/releases

**Comment by XIU2** [comment]
研究半天，最后发现其实是 AdGuard 不支持存储 JSON 格式的对象，需要转为 JSON 文本才行。

我研究研究是对 AdGuard 额外处理，还是全都改为 JSON 文本存储。。。

**Comment by XIU2** [comment]
擦，又卡住了。

不知道为啥，AdGuard 后台获取外置翻页规则老是失败，但是 Tampermonkey 什么的就正常。。。搞不懂

**Comment by XIU2** [comment]
放弃了，AdGuard 好像是限制了脚本配置存储的大小（长度）。

我测试了很多次，发现打开网页后，获取外置翻页规则并写入脚本配置成功，此时可以正常读取出来。

但是一旦刷新网页，脚本配置中的外置翻页规则就特么没了。。。

也就是说，想要完全支持 AdGuard 是没希望了，只能像你说的那样，单独整个 “离线版”。。。

**Comment by hacamer** [comment]
> 擦，又卡住了，死活无法进行下一步测试。
> 
> 不知道为啥，AdGuard 后台获取外置翻页规则老是失败，但是 Tampermonkey 什么的就正常。。。搞不懂

或許AdGuard不支持某些油猴脚本的API？https://lemon399.gitee.io/test/browser/monkeystat.html 這個可以參考一下

**Comment by XIU2** [comment]
我查过，是支持的：
https://kb.adguard.com/en/general/userscripts

**Comment by XIU2** [comment]
如果把脚本改成离线版，本身到不复杂，就是在脚本开头加一段代码就行了。
``` JavaScript
(function() {
    'use strict';
    const offlineRules = {
        翻页规则
    }
    GM_setValue('menu_rules', offlineRules);
    GM_setValue('menu_ruleUpdateTime', parseInt(+new Date()/1000));

...
```

**Comment by hacamer** [comment]
> 放弃了，AdGuard 好像是限制了**脚本配置存储的大小**（长度）。
> 
> 我测试了很多次，发现打开网页后，获取外置翻页规则并写入脚本配置项成功，此时也可以正常读取出来。
> 
> 但是一刷新网页，刚刚存进脚本配置中的 `外置翻页规则` 就特么没了（但其他配置项还在。。。
> 
> 也就是说，想要完全支持 AdGuard 是没希望了，只能像你说的那样，单独整个 “离线版”。。。
> 
> 但我对你说的 Github Action 完全不熟呀，而且听说这玩意对使用要求比较严格，但要是手动的话，我又懒得搞。。。

Github Action其實也沒那麽嚴格，不過我對脚本不太熟悉，一般來説可以用cat命令合并，然後就在action push到倉庫

主要是我對脚本不熟悉，不好操作

**Comment by XIU2** [comment]
我上面不是写了把脚本改成离线版的示例吗？

我怎么感觉你回复慢了半小时一样。。。你一直在回复我半小时前发的东西。

**Comment by hacamer** [comment]
> 我上面不是写了把脚本改成离线版的示例吗？
> 
> 我怎么感觉你回复慢了半小时一样。。。你一直在回复我半小时前发的东西。

我網頁半小時沒刷新哈哈

**Comment by XIU2** [comment]
从中午到现在，我愣是折腾了 5 个小时，最后发现还是白折腾了。。。

实在不行，你就先手动改改脚本（示例见上），凑活着用吧~

**Comment by hacamer** [comment]
> 如果把脚本改成离线版，本身到不复杂，就是在脚本开头加一段代码就行了。
> 
> ```js
> (function() {
>     'use strict';
>     const offlineRules = { // 直接把 外置翻页规则列表 内容复制到这里
>         "百度搜索": {
>             ...
>         }
>     }
>     GM_setValue('menu_rules', offlineRules); // 将翻页规则写入脚本配置
>     GM_setValue('menu_ruleUpdateTime', parseInt(+new Date()/1000)); // 写入当前时间戳，避免脚本去获取外置翻页规则
> 
> ...
> ```

可以是可以，但是幾千行文本複製再粘貼好像也不是一個好主意，而且容易出錯

**Comment by hacamer** [comment]
> 从中午到现在，我愣是折腾了 5 个小时，最后发现还是白折腾了。。。
> 
> 实在不行，你就先手动改改脚本（示例见上），凑活着用吧~

我把脚本中的那個彈窗刪了，凑合著用吧

**Comment by XIU2** [comment]
你确定这样做正确应用了翻页规则吗？
还是说 AdGuard 桌面版和手机版不一样？

****

我在 AdGuard 中安装该脚本后，打开网页，
有时候会提示获取翻页规则失败，这时候脚本是没有获取到外置翻页规则的。
有时候会获取成功，但是我如果刷新网页或打开新的网页，前面获取并写入脚本配置项的外置翻页规则就没了，脚本就会提示 `暂不支持当前网页` 。

因此整个体验下来，我发现虽然每次打开网页都会获取外置翻页规则，但是实际上我并没有用到外置翻页规则。

你那边是正常的吗？还是说你没发现这点。。。

**Comment by hacamer** [comment]
> 你确定这样做正确应用了翻页规则吗？ 还是说 AdGuard 桌面版和手机版不一样？
> 
> 我在 AdGuard 中安装该脚本后，打开网页， 有时候会提示获取翻页规则失败，这时候脚本是没有获取到外置翻页规则的。 有时候会获取成功，但是我如果刷新网页或打开新的网页，前面获取并写入脚本配置项的外置翻页规则就没了，脚本就会提示 `暂不支持当前网页` 。
> 
> 因此整个体验下来，我发现虽然每次打开网页都会获取外置翻页规则，但是实际上我并没有用到外置翻页规则。
> 
> 你那边是正常的吗？还是说你没发现这点。。。

我這邊是，能正常使用，谷歌和bing，最多就更新規則的彈窗，沒有出現獲取錯誤，能正常翻頁

**Comment by XIU2** [comment]
看来可能 AdGuard 桌面版 和 手机版 逻辑不一样。。。

**Comment by hacamer** [comment]
> 看来可能 AdGuard 桌面版 和 手机版 逻辑不一样。。。

很奇怪，我移除了那個彈窗后 有時不能獲取規則有時候又可以，這個bug還是反饋給adg官方吧

**Comment by XIU2** [comment]
我觉得和你移除弹窗没关系。。。这个问题应该是一直存在的，只不过你平时没注意到。

**Comment by hacamer** [comment]
> 我觉得和你移除弹窗没关系。。。这个问题应该是一直存在的，只不过你平时没注意到。

雖然沒關係 但好歹不會每次訪問網頁都彈窗😂

**Comment by XIU2** [comment]
我已经更新脚本，当油猴管理器为 AdGuard 时不再弹窗。
我在 AdGuard 桌面版上测试没问题，你更新试试吧。

**Comment by hacamer** [comment]
> 我已经更新脚本，当油猴管理器为 AdGuard 时不再弹出那个提醒。 我在 AdGuard 桌面版上测试没问题，你更新试试吧。

OK，謝謝大佬
