### ISSUE TITLE
[自动无缝翻页] 谷歌搜索自动翻页后，点击搜索按钮无反应

### ISSUE THREAD

**Issue by zvzl** [XIU2/UserScript#213]
谷歌搜索自动翻页后，再点击搜索按钮无反应。有百分之七八十概率复现，浏览器是最新的火狐。
![图片](https://user-images.githubusercontent.com/84430227/164145504-cbee5ff7-a32d-4c84-8bc5-d995b19318bb.png)

**Comment by XIU2** [comment]
“有百分之七八十概率复现” 不是 100%？

我这边完全无法复现。。。

**Comment by zvzl** [comment]
现在我也不能复现了，可能是网络的原因。
