### ISSUE TITLE
[自动无缝翻页] 希望添加该网站

### ISSUE THREAD

**Issue by tian11111** [XIU2/UserScript#214]
https://fsoufsou.com/

**Comment by XIU2** [comment]
没有账号，听说还需要邀请码什么的。

以前被封之前，旧域名时，添加支持过。

**Comment by XIU2** [comment]
等这个网站什么时候公测了，再来通知我吧~

**Comment by tian11111** [comment]
你好，网站无需邀请码即可搜索，希望添加，谢谢

**Comment by XIU2** [comment]
@tian11111 已添加支持~（包括手机版

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
