### ISSUE TITLE
[自动无缝翻页] 希望支持一下Github Action的翻頁

### ISSUE THREAD

**Issue by hacamer** [XIU2/UserScript#215]
如題所示
有時候github action的記錄要翻很多頁

舉例：
https://github.com/XIU2/UserScript/actions  
自動翻到下一頁
https://github.com/XIU2/UserScript/actions?page=2

希望大佬可以支持一下

**Comment by XIU2** [comment]
已添加支持~

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
