### ISSUE TITLE
[自动无缝翻页] 希望添加 极简壁纸自动翻页 功能（像彼岸图网一样）

### ISSUE THREAD

**Issue by 2909379601** [XIU2/UserScript#216]
https://bz.zzzmh.cn/index
这是 极简壁纸 的网址

**Comment by XIU2** [comment]
这个很早就有人提过，但是无法添加支持。

这个网站为了防爬取图片，做了很多反制措施，比如验证码、动态加载内容、禁止调试代码等等，这些都会阻碍我对其添加支持。

毕竟我这个脚本，本质上也是爬虫，虽然只是爬取下一页内容。
