### ISSUE TITLE
[自动无缝翻页] 百度贴吧回复问题

### ISSUE THREAD

**Issue by abc2283258119** [XIU2/UserScript#217]
尊敬的开发者你好！[自动无缝翻页]脚本在百度贴吧的表现很好，只是似乎在最近的更新中，在回复他人时，只要输入表情，那么浏览器就会立即打开一个名为“无标题”的空白新标签。感谢作者能在百忙之中看到。
![截图_20221726071711](https://user-images.githubusercontent.com/46117327/165288451-9446d0df-ebb6-4e19-a630-4c9e727fb49b.png)
页

**Comment by XIU2** [comment]
已更新规则修复了~

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
