### ISSUE TITLE
油管里的視頻也被蒙上白白的顏色很難看

### ISSUE THREAD

**Issue by jiatianxa** [XIU2/UserScript#218]
油管里的視頻也被蒙上白白的顏色很難看

**Comment by XIU2** [comment]
哪个脚本？护眼模式？
YouTube 自带了夜间模式，建议去开启，然后在脚本菜单中对 YouTube 禁用。

**Comment by jiatianxa** [comment]
明白了&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月28日(星期四) 上午9:51
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [XIU2/UserScript] 油管里的視頻也被蒙上白白的顏色很難看 (Issue #218)





 
哪个脚本？护眼模式？
 YouTube 自带了夜间模式，建议去开启，然后在脚本菜单中对 YouTube 禁用。
