### ISSUE TITLE
[Github 增强 - 高速下载] 希望添加选择加速源的功能

### ISSUE THREAD

**Issue by yzqdev** [XIU2/UserScript#219]
平时大多数人能用到的其实也就**国内下载**,像美国,韩国这些源也用不到,所以如果能选择加速源就更好了,每次点开clone或者下载出现一大堆很容易点错,(原谅我手残).

![image](https://user-images.githubusercontent.com/20037151/166092180-6768d4c7-d31a-4dcb-92b6-51f7c3d622dc.png)

**Comment by XIU2** [comment]
感觉设计起来比较麻烦，没兴趣折腾。。。

**Comment by yzqdev** [comment]
好的好的,感谢大佬回复,我也正准备自己改一下呢
