### ISSUE TITLE
请求增加gh-proxy支持

### ISSUE THREAD

**Issue by YulinChan** [XIU2/UserScript#22]
https://github.com/hunshcn/gh-proxy ，是一个利用cloudflare worker对github进行加速的项目。cloudfalre cdn非常稳，又可以自选ip，并且个人用户每天10w请求量完全够用。

所以我想请求增加gh-proxy 的支持，可以在油猴脚本的开头自定义一个示例变量（woker的url），然后大家安装脚本后可以修改油猴脚本，把脚本中的这个url改成自己worker对应的就可以了。

**Comment by XIU2** [comment]
那你直接把脚本 29 行的
```
        ['https://gh.api.99988866.xyz','美国'],
```
中的域名改成自己的域名就行了。

**Comment by YulinChan** [comment]
![image](https://user-images.githubusercontent.com/48314862/109407391-59f4e900-79bb-11eb-820d-32f6418b4840.png)
raw下载这里没有这这一项啊 https://gh.api.99988866.xyz

**Comment by XIU2** [comment]
因为 https://gh.api.99988866.xyz 的 Raw 加速，就是调用的 https://cdn.jsdelivr.net ，即中国国内 02。

**Comment by YulinChan** [comment]
不是的，可以设置不重定向的。
虽然jsdlivr非常快，但是我们学校网速限制了10兆，教育网则稍稍放开到50兆，使用教育网连接cf cdn 的ipv6节点非常快。

**Comment by XIU2** [comment]
我知道可以设置不重定向，因为脚本里有个加速源就是我用 gh-proxy 搭建的。

Raw 的话，你去替换第 45 行
```
            ['https://ghproxy.com','韩国首尔','']
```
中的域名改成自己的域名就行了。

**Comment by YulinChan** [comment]
好的，谢谢，我试试

**Comment by XIU2** [comment]
最主要的是，无论是按你说的，还是按我说的。
这些修改脚本的操作，一旦更新脚本，就会全都变回脚本默认内容。

因此既然结果都一样，那么还是按我说的**替换内置域名**比较方便。

****

要实现更新脚本保留用户自定义的加速源，当然可以实现。
但这意味着还需要做一套设置系统，来让用户可以添加自定义加速源，这无疑很麻烦。
最主要的是，该功能用的人太少太少，折腾半天写这个功能完全划不来。

**Comment by YulinChan** [comment]
确实，替换内置域名挺好，不麻烦。问题已经解决了，能正常使用啦，多谢您热心的回复。

**Comment by XIU2** [comment]
不过现在脚本功能稳定，也没什么 BUG，基本上只要 Github 不改样式什么的，很少会再更新了。

那我就先关闭该 Issues 了。

**Comment by XIU2** [comment]
@cylind 

新增 自定义加速源 功能（位于浏览器右上角 Tampermonkey 脚本菜单选项中，可自定义设置一个 Raw、Git Clone、Release/Code(ZIP) 加速源地址）

因为这功能用的人不多，所以我写的比较简陋，就是 3 个输入框来让你分别设置 Raw、Git Clone、Release/Code(ZIP) 的自定义加速源地址。

****

### \# `自定义加速源`

考虑到稳定性和速度等因素，部分人可能有自建加速源自用的需求，所以我就加了个简单的自定义加速源菜单选项。

点击浏览器右上角的 Tampermonkey 扩展图标 `#️⃣ 自定义加速源`，会弹出 3 次自定义加速源地址输入框，分别是 Raw、Git Clone、Release/Code(ZIP)，会显示当前设置值、示例、设置提示等内容，你可以输入加速源地址或留空（代表不设置），点击 `[确定]` 保存 并 继续设置下一个，点击 `[取消]` 不保存 并 终止后续设置。

你设置的自定义加速源，会默认添加到相应加速源按钮的**首位**并显示名称为**[自定义]**（ **`Raw 快捷下载 [ ☁ ]`** 除外，会排到第 1 个 **[Github 原生]** 的后面，即对应的数字是 1️⃣），另外，对于 Release/Code(ZIP) 因为需要限制数量避免网页位置不足，所以会将原先的**随机 6 个**加速源改为**自定义 1 个 + 随机 5 个**的组合（当然如果你没设置 Release/Code(ZIP) 自定义加速源，那么还是**默认随机 6 个**）。
