### ISSUE TITLE
[蓝奏云增强] 希望添加"文件夹排序"功能

### ISSUE THREAD

**Issue by D33274D7C6** [XIU2/UserScript#222]
蓝奏云无法按照文件名、时间、大小进行排序，查找资源很麻烦。
不知脚本能否实现按照文件名排序的功能？

**Comment by XIU2** [comment]
或许可以实现，但是做起来很麻烦。。。

**Comment by ywxt** [comment]
#267

**Comment by XIU2** [comment]
@ywxt 哈~ 感谢帮忙
我给细节优化了一下：
1. 文件名/夹 的排序按钮离文字太远，反而离 [大小] 文字太近了，刚刚装上测试时就感觉有点混乱，于是我把 文件名/夹 的排序按钮放到最左侧了，其他的保持不变。
2. 给每个排序按钮加了个 title 提示，鼠标指向时会显示 `按 文件大小 排序` 之类的话。
