### ISSUE TITLE
[知乎增强] 希望添加复制限制解除的功能

### ISSUE THREAD

**Issue by Alphabet1226** [XIU2/UserScript#224]
可以参考这个脚本： https://greasyfork.org/en/scripts/14146-%E7%BD%91%E9%A1%B5%E9%99%90%E5%88%B6%E8%A7%A3%E9%99%A4

**Comment by XIU2** [comment]
既然别人已经写好了，我就没必要折腾了。

**Comment by Alphabet1226** [comment]
> 既然别人已经写好了，我就没必要折腾了。

但是它这个脚本是对所有网站开启的，在许多网站上都会出现各种 bug，我希望它只在知乎上起作用。

**Comment by XIU2** [comment]
这个你去 Tampermonkey 里编辑脚本设置，取消勾选 [原始匹配]，手动添加 [用户匹配] 即可实现只在知乎运行这脚本。
