### ISSUE TITLE
[知乎增强] 希望屏蔽用户时按 uid 识别，来避免误伤

### ISSUE THREAD

**Issue by Alphabet1226** [XIU2/UserScript#226]
由于知乎不限制用户昵称重复，导致大量的人昵称一模一样。
我测试了一下目前的脚本屏蔽是按用户昵称识别的，这就会导致一个问题：当昵称重复时，所有这个昵称的人就都被误屏蔽了。
希望能修改一下屏蔽逻辑，按 uid 来识别。

**Comment by XIU2** [comment]
理论上可以，但我懒得费劲去搞了。

我现在基本不玩知乎了，这脚本是我当初玩知乎的时候写的，因此现在都没什么兴趣动力去更新功能了，仅仅是维护罢了。

**Comment by Alphabet1226** [comment]
理解理解，能做出这些优秀的脚本供大家免费使用，已经很感激了！
