### ISSUE TITLE
[自动无缝翻页] 希望添加功能: 在页面右下角插入一个返回顶部的按钮

### ISSUE THREAD

**Issue by VayneDy** [XIU2/UserScript#227]
提个建议: 自动翻页后, 如果想返回顶部, 有些网站在右下角是有返回顶部的按钮的, 有些网站没有, 这时候只能手动拖拽滚动条, 翻的页太多时往上拖拽滚动条太快时会导致页面卡顿. 能不能在页面右下角插入一个返回顶部的按钮图标, 点击返回顶部.

**Comment by XIU2** [comment]
鼠标右键点击左下角悬浮的页码按钮，即可回到顶部。
