### ISSUE TITLE
[自动无缝翻页] 翻页功能失效

### ISSUE THREAD

**Issue by lee-special** [XIU2/UserScript#228]
Chrome最新版，win10系统。
网页是：https://jobs.51job.com/。
在浏览职位时没有自动翻页，例如https://jobs.51job.com/all/co3230101.html

**Comment by XIU2** [comment]
这不叫失效，这叫没有添加支持。

我看了下，这个网页是动态加载内容的，无法添加支持。

**Comment by lee-special** [comment]
> 这不叫失效，这叫没有添加支持。
> 
> > 我的脚本是依靠 **部分通用规则 + 我写的翻页规则** 实现的，并没有覆盖全网。
> 
> 我看了下，这个网页是动态加载内容的，无法添加支持。

原来是这样，实在不好意思我还是个菜鸟，我只会用但是不知道原理。
