### ISSUE TITLE
[知乎增强] 菜单功能失效

### ISSUE THREAD

**Issue by 1174921706** [XIU2/UserScript#229]
如图：菜单没了，知乎的视频也阻挡不了，一些功能也都失效了

![image](https://user-images.githubusercontent.com/67858819/169428310-a1ffb5c6-0107-4295-abbb-b965ba960672.png)

**Comment by XIU2** [comment]
昨天有人反馈了，但是我这边一切正常，无法复现。

因此最大可能是其他因素导致脚本无法运行，昨天那个人我提远程协助没吭声。

下载远程协助软件（这个是只有被控功能的单文件版，用完即删），告诉我你的设备代码、临时密码。  
https://dl.todesk.com/windows/ToDesk_Lite.exe
