### ISSUE TITLE
想开发一个 YouTube 相关脚本，希望给予帮助

### ISSUE THREAD

**Issue by shimiaoyerin** [XIU2/UserScript#23]
我想自己亲手开发一个 YouTube 自动隐藏已在收藏列表的视频。

是这样的，因为 YouTube 的视频后缀名都是独立的，例如：
https://www.youtube.com/watch?v=lFoqAKOWEes 中的 `lFoqAKOWEes`

先下载保存播放列表里的所有视频的后缀名，然后打开 YouTube 网页的时候，会自动对比**当前页面**上的元素，如果核对后缀名，就会从**当前页面**上删除不可见。

但是嘛，我也不是程序员出身，只是个三维美工，目前还在学习阶段，如果能有个参考也是极好，或者帮我指条名灯。
多嘴问一句，谷歌还是油猴的运行效率高点？我的视频估计有10w部保守估计，如果利用插件实现这个功能，能做到在几秒中就实现这个效果吗？我不确定，也觉得很悬，谢谢。

**Comment by XIU2** [comment]
10万，这么多啊。

油猴脚本运行环境是脚本管理器扩展，而扩展运行环境是浏览器。
因此扩展的自由度更高、权限更高、效率应该也更高。

**Comment by shimiaoyerin** [comment]
谢啦，不知道那些搜索引擎是怎么索引的，一秒中就索引了好几十亿估计哈哈哈

**Comment by shimiaoyerin** [comment]
就多骂爹，已经实现了

**Comment by shimiaoyerin** [comment]
// ==UserScript==
// @name         写死脚本
// @namespace    http://tampermonkey.net/
// @version      1
// @description  最终脚本!
// @author       lixiaohua
// @match        https://www.youtube.com/*
// @require      https://libs.baidu.com/jquery/2.0.0/jquery.min.js
/* globals jQuery, $, waitForKeyElements */
// @grant        none
// ==/UserScript==

(function() {
    'use strict';



    $(document).ready(function(){
            var LIST = "/watch?v=uKcT1V29cvI";//将所有已有链接做成一个字符串
            var work = setInterval(function(){
                        var videos = $(".ytd-grid-video-renderer,.ytd-rich-item-renderer,.ytd-video-renderer"); //选取所有父级DIV元素
                        for(var i=0;i<videos.length;i++){//遍历元素
                            var URL = $(videos[i]).find(".yt-simple-endpoint").attr('href');//读取元素内包含 class指定值的href
                            var TITLE = $(videos[i]).find(".yt-simple-endpoint").attr('title');//读取元素内包含 class指定值的href
                            if(URL != null){
                                if(LIST.indexOf(URL) != -1){//如果URL在LIST里面
                                    console.log('删除成功,名称:'+TITLE+' 链接：'+URL);
                                    $(videos[i]).remove();//删除这个父级元素
                                }
                            }
                        };
            },3000);
        });





    // Your code here...
})();
