### ISSUE TITLE
[知乎美化] 暗黑模式没有纯黑吗？

### ISSUE THREAD

**Issue by CCCAUCHY** [XIU2/UserScript#230]
暗黑模式没有纯黑吗？
或者直接用知乎的暗黑模式？开了知乎美化脚本之后就不能用知乎的暗黑模式了

**Comment by XIU2** [comment]
# 暗黑模式（ 4 种）

- 样式一（默认）： 知乎自带的暗黑模式，颜色搭配、对比度都很辣眼，于是我就“稍微”调整优化了一下样式，看起来舒服多了~
- 样式二： 直接对网页进行负片反色（图片、视频除外），效果也不错，只不过部分颜色大家可能会不太适应。
- 样式三： 降低网页亮度，对网页颜色影响最小。
- 样式四： 降低网页亮度，并添加暖色滤镜（降低蓝光？），眼睛看起来比样式三舒服点。

你想用知乎自身的暗黑模式，请关掉脚本菜单的暗黑模式，自己去手动开启。
