### ISSUE TITLE
[Github 增强 - 高速下载] Releases 其他源下载功能失效

### ISSUE THREAD

**Issue by SikroYang** [XIU2/UserScript#231]
大佬
Releases页面不显示其他源下载按钮了
系统Win10
浏览器: Firefox、Edge
两种浏览器都试过，下面截图是Edge浏览器
![image](https://user-images.githubusercontent.com/20292353/171562705-cdfd2fb7-8eea-46f0-8b39-330d64fc3501.png)
![image](https://user-images.githubusercontent.com/20292353/171562758-6059a8a8-f3e1-43a3-9733-378ce322f175.png)

**Comment by XIU2** [comment]
我这边正常，请确保你是最新版本的脚本，前段时间脚本更新适配新版 Releases 页面了。

**Comment by SikroYang** [comment]
确实是没更新
多谢多谢
