### ISSUE TITLE
[知乎增强]屏蔽登录弹窗功能失效

### ISSUE THREAD

**Issue by rain-0** [XIU2/UserScript#232]
https://zhuanlan.zhihu.com/ 
全部知乎专栏的屏蔽弹窗功能均失效
浏览器为100.0.2 (64 位)
使用脚本猫0.9.1运行脚本

**Comment by XIU2** [comment]
经过测试，我这边工作正常，没有失效。

**Comment by rain-0** [comment]
只有专栏文章失效 
linux环境 无法使用上述远程软件 我晚上换Windows环境下看看吧

**Comment by rain-0** [comment]
又试了下应该单纯是脚本猫的问题 换了油猴就正常了
