### ISSUE TITLE
[全球主机交流论坛增强] 自动无缝翻页 功能失效

### ISSUE THREAD

**Issue by imtipi** [XIU2/UserScript#233]
显示在线状态 功能好像出现了错误
`let icon = (item.querySelector('[id^="userinfo"] > .i.y em').textContent === '当前在线') ? '🌝' : '🌚';`
这行报错了，导致自动翻页也用不了，控制台显示
`Uncaught (in promise) TypeError: Cannot read properties of null (reading 'textContent')`
自行注释掉显示在线状态功能后，翻页功能恢复正常

**Comment by XIU2** [comment]
看了下，发现是忘记考虑 匿名回帖没有头像 的问题了。。。

已经更新修复了。
- **修复** [显示是否在线] 遇到匿名时报错的问题
