### ISSUE TITLE
[知乎 增强] 首页屏蔽视频功能失效

### ISSUE THREAD

**Issue by kalac2232** [XIU2/UserScript#236]
可能从上周开始知乎web更新了新版。
<img width="1157" alt="image" src="https://user-images.githubusercontent.com/35256979/173273914-66d099d8-d44e-492c-9396-320bfc988bd4.png">
使用 chrome版本 102.0.5005.61（正式版本） (x86_64)

**Comment by XIU2** [comment]
但我一直正常能用。

**Comment by kalac2232** [comment]
取消勾选后，重新勾选正常

**Comment by XIU2** [comment]
你是安装脚本后，就不能用，还是某个时间突然就不能用了？

**Comment by kalac2232** [comment]
之前一直可以使用，大概上周就不好使了。
