### ISSUE TITLE
[Github 增强] 如何解决 Raw 加速源存在缓存的问题？

### ISSUE THREAD

**Issue by sasa146** [XIU2/UserScript#24]
现在我的Github项目是经常改变的，但是我使用加速源浏览Raw后，内容并不会改变，这是为什么，有什么解决方法吗

**Comment by XIU2** [comment]
这是因为目前的 Raw 加速源，基本上都有缓存机制。
一方面是为了节省 CDN 流量成本，另一方面就是为了减少回源访问 Github 资源的次数。

**Comment by XIU2** [comment]
如果你用的是 [中国国内 02] 加速源，那么可以把加速地址（域名）中的 `cdn` 换成 `purge` 去访问，就可以清除缓存了。

国内 02 默认缓存时间是 24 小时（即默认情况下 24 小时后才会自动重新获取），其他的加速源不太清楚缓存时间是多少。

**Comment by sasa146** [comment]
好的，谢谢大手子。
