### ISSUE TITLE
[知乎增强] 许多api失效

### ISSUE THREAD

**Issue by luotianyiismywife** [XIU2/UserScript#241]
在question界面，不论是关注问题和赞同回答。
![图片](https://user-images.githubusercontent.com/81459639/176406336-8dc6584c-18f2-4337-bce2-4c84fb6e983b.png)

![图片](https://user-image.githubusercontent.com/81459639/176406752-e2ecbaa6-74e6-4f2e-88a0-6c73a39a7036.png)
脚本版本2.1.2
![图片](https://user-images.githubusercontent.com/81459639/176407135-dcfa4586-8b4e-444e-bf84-d7e63f06060b.png)

**Comment by XIU2** [comment]
这你应该向知乎反馈。
我的脚本并没有调用知乎网页的 API，纯粹自己实现的。
