### ISSUE TITLE
[新标签页打开链接] bug 谷歌账号授权的登陆界面 无法点击账号

### ISSUE THREAD

**Issue by Penghaiku** [XIU2/UserScript#243]
任意网站使用google账号登录时，无法点击账号进行下一步登录，直接卡死，点击任何位置均无效。
以v2站为例，如下图 100%复现
![image](https://user-images.githubusercontent.com/46412151/176851851-00d10739-cf6c-4aed-b3c7-343fdb0ad686.png)
解决办法：
逐个脚本关闭验证bug，关闭新标签页打开链接脚本可以恢复正常，可以加入网址排除

**Comment by XIU2** [comment]
已更新脚本，默认排除了。
