### ISSUE TITLE
[护眼模式] 网页中的视频可选择开启或不开启护眼模式

### ISSUE THREAD

**Issue by Aopodo** [XIU2/UserScript#244]
现在视频会自动开启护眼模式，能否提供选项单独关闭视频的护眼功能？感谢oser的贡献

**Comment by XIU2** [comment]
护眼模式 脚本原理是利用 CSS 的 filter 滤镜样式，这个滤镜是针对整个网页的，模式 3 反色是需要将视频、图片等再添加一层反色将其反转回来，而无法直接让滤镜跳过视频、图片元素。

我平时主用 模式 2，这脚本只是我自用的，模式 3 问题太多。
