### ISSUE TITLE
如何把油猴脚本转换为正常的js, 可以在浏览器控制台直接运行的那种

### ISSUE THREAD

**Issue by FairyWorld** [XIU2/UserScript#245]
只有少部分手机浏览器支持chrome扩展, 所有很多手机无法使用油猴。

但是市面上很多手机浏览器都是支持的自定义脚本的，比如via, x浏览器等

我看了下这些浏览器是直接把油猴脚本的链接插入到document中, 但是由于油猴脚本有些东西是在注释里面声明的, 导致执行时缺少各种变量，想了解下怎么直接把油猴脚本转换为正常的js脚本

手机浏览器引入的方式如下:
```
// ==UserScript==
// @name         自动无缝翻页
// @source       https://greasyfork.org/scripts/419215
// ==/UserScript==

(function() {
    'use strict';

    var d=document;
    var s=d.createElement('script');
    s.setAttribute('src', 'https://greasyfork.org/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5/code/%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5.user.js');
    d.head.appendChild(s);
})();
```

![image](https://user-images.githubusercontent.com/32956212/177029054-7bb47be4-f649-48ce-9395-927d904e76b3.png)

**Comment by XIU2** [comment]
这只适用于 简单的油猴脚本，如果油猴脚本调用了油猴函数（油猴管理器内置），那么就无法运行了。

我的脚本只能运行在 Tampermonkey、Violentmonkey 油猴管理器扩展，或完整支持油猴功能的浏览器。
