### ISSUE TITLE
[知乎增强]在推荐页面，打开回答里的评论双击旁边空白回答不收起

### ISSUE THREAD

**Issue by tmbmyeue** [XIU2/UserScript#246]
点击回答旁边空白是能正常收起，但是点击评论旁边就不能了，多次实验都是如此，不知道是因为我的环境问题还是什么，先试着反馈大家看看是否都有此问题。

**Comment by XIU2** [comment]
https://greasyfork.org/zh-CN/scripts/419081/discussions/140011
https://greasyfork.org/zh-CN/scripts/419081/discussions/140288

**Comment by XIU2** [comment]
评论区改版，和评论区相关的功能都失效了，我暂时只修复了 [快捷收起评论] 功能。
