### ISSUE TITLE
在greasyfork反馈界面点击提问、发表评价，如果开启了无缝翻页，会不断加载下一页内容而把把评论框挤到到下面

### ISSUE THREAD

**Issue by SunshineboyZj** [XIU2/UserScript#247]
在greasyfork反馈界面点击提问、发表评价，如果开启了无缝翻页，会不断加载下一页内容而把把评论框挤到到下面

https://user-images.githubusercontent.com/81549837/177668039-022145b3-395e-4884-ab73-4c6253883d01.mp4

**Comment by XIU2** [comment]
点击左下角悬浮的 页码 按钮，即可临时暂停翻页。
