### ISSUE TITLE
提供加速源

### ISSUE THREAD

**Issue by feizhuqwq** [XIU2/UserScript#248]
[ghgo.feizhuqwq.workers.dev](https://ghgo.feizhuqwq.workers.dev/)因为 workers.dev 已经遭到大规模DNS污染和阻断无法访问
我使用另外一个域名重新搭建，国内测试正常
[ghdl.z-o.top](https://ghdl.z-o.top/)

**Comment by XIU2** [comment]
OK，我会更新域名的。

两个月前 `*.workers.dev` 域名被 DNS 污染后，我还提醒你了一下 #170 ~

**Comment by feizhuqwq** [comment]
抱歉，当时没有看到，还有那个时候可能我这里是企业网的原因，还没有被DNS污染，我是最近半个月才访问不了的
正好有没用的域名，所以又搭建了一下

**Comment by feizhuqwq** [comment]
cf默认分配的域名似乎丢包极其严重，现已使用自选节点IP，表现较好
