### ISSUE TITLE
[自动无缝翻页] pixiv、百度贴吧翻页奇特

### ISSUE THREAD

**Issue by shadowman2022** [XIU2/UserScript#249]
翻页的时候不是舒服的连页，而是诡异的……
![Snipaste_2022-07-10_18-56-21](https://user-images.githubusercontent.com/98646778/178142313-92bf0e25-ef8e-4f94-be5f-7ded1a1aa070.png)
![Snipaste_2022-07-10_19-01-37](https://user-images.githubusercontent.com/98646778/178142314-660893f5-147e-48a8-ac44-16d3d1777c14.png)
![msedge_lFjQZ1RnoT](https://user-images.githubusercontent.com/98646778/178142316-23f83412-89cb-423a-a9eb-3c8ad2ed1aed.gif)
😢 希望改进

**Comment by XIU2** [comment]
这些动态加载内容的网页，只能这样添加支持，常规方案是无法添加支持的。

**Comment by snowman** [comment]
但是现在只能显示最新一页, 之前的被刷没了
