### ISSUE TITLE
[功能请求]知乎美化: 隐藏浏览回答时页面上方的标题

### ISSUE THREAD

**Issue by StephanoGeorge** [XIU2/UserScript#25]
[功能请求]知乎美化: 隐藏浏览回答时页面上方的标题.
谢谢

**Comment by XIU2** [comment]
你的意思是，在浏览回答的时候，向下翻顶部显示的回答标题吗？
向上翻又变成显示知乎网页顶栏。

看了下可以实现，即向下翻时隐藏知乎顶栏，向上翻时保持原样（显示知乎顶栏）。

**Comment by StephanoGeorge** [comment]
好的. 谢谢
另外我觉得在浏览回答时, 问题标题与知乎顶栏, 都没什么用.

XIU2 ***@***.***> 于2021年3月12日周五 下午8:29写道：

**Comment by XIU2** [comment]
顶栏还是有用的，毕竟搜索、查看通知、私信、个人资料、设置等都是很常用的功能。

如果每次要使用这个功能必须要返回顶部，那就太麻烦了。

**Comment by XIU2** [comment]
OK，你去更新下吧。

#### 2021年03月12日，版本 v1.0.7
1. **新增** [浏览回答向下翻时自动隐藏标题]（默认关闭）。

****

如果你想要**向下翻、向上翻**时都隐藏顶栏，那么请修改脚本第 <kbd>92</kbd> 行：
``` css
header.is-hidden {
/* 上面的改为下面：*/
header.is-hidden, header.is-fixed {

```
