### ISSUE TITLE
希望制作一个论坛自动回帖功能的脚本（或者自动签到）

### ISSUE THREAD

**Issue by happyfanyiming** [XIU2/UserScript#252]
https://www.hd1tj.net/plugin.php?id=yinxingfei_zzza:yinxingfei_zzza_hall

这个论坛是个影视论坛，但是下载资源需要金币，希望能制作一个顶贴的脚步 这样不用手动回帖那么辛苦啦 谢谢

**Comment by XIU2** [comment]
兴趣不大，制作签到类脚本顺利的话往往最少需要两天（需要分析签到过程，然后编写代码，第二天再测试）。

脚本请求 是用来给我提供脚本思路灵感的，我想要的是那种大家都用的上的，而不是给单个人私人定制的。

**Comment by happyfanyiming** [comment]
你好 有个油猴插件叫魂签，就是专门用于签到的，至少它只能签到一部分网址，你可以弄个类似它这样的 支持更多的的网址签到类型。







在 2022-07-12 07:25:39，"XIU2" ***@***.***> 写道：

兴趣不大，制作签到类脚本顺利的话往往最少需要两天（需要分析签到过程，然后编写代码，第二天再测试）。

脚本请求 是用来给我提供脚本思路灵感的，我想要的是那种大家都用的上的，而不是给单个人私人定制的。

**Comment by XIU2** [comment]
没希望，通用的签到脚本是无法实现的，顶多支持一部分常见的论坛签到机制。

**Comment by heroboy** [comment]
魂签其实不是通用签到脚本，类是类似于可以定时执行的userscript，做在浏览器里面可以免除自动登录，免除手动复制cookie这种麻烦的事情。
