### ISSUE TITLE
[知乎增强] 专栏免登录功能失效

### ISSUE THREAD

**Issue by glatavento** [XIU2/UserScript#253]
如题，Linux 下的 Firefox 中，专栏免登录功能失效。

专栏界面如图所示：
![图片](https://user-images.githubusercontent.com/76601050/179336349-1768b586-968f-4af9-9368-1c8fd705539f.png)

作为参考，问题界面如图所示：
![图片](https://user-images.githubusercontent.com/76601050/179336364-da612947-ea8c-466e-9bae-e1aa778efbd7.png)

TamperMonkey 界面如图所示（问题界面和专栏界面都是这样）：
![图片](https://user-images.githubusercontent.com/76601050/179336293-06de1713-6117-45cf-87c6-d818f80f8b16.png)

Chromium 中测试正常。

运行环境：
```
OS: Manjaro 21.3.3 Ruah
Kernel: x86_64 Linux 5.15.53-1-MANJARO
DE: KDE 5.96.0 / Plasma 5.24.6
WM: KWin
Browser: Mozilla Firefox 102.0.1
Tamper Monkey: 4.17.6161
```

**Comment by glatavento** [comment]
追加：Violent Monkey 功能正常，所以对我来说这个问题大概解决了

**Comment by XIU2** [comment]
我在 Firefox + Tampermonkey + 隐私窗口下试了下，我这边能正确移除登录弹窗。
