### ISSUE TITLE
[知乎增强] 导致知乎无法登录

### ISSUE THREAD

**Issue by zhj9709** [XIU2/UserScript#254]
昨晚发现知乎搜索出现问题，然后换浏览器发现知乎没登录的时候也有问题。

![image](https://user-images.githubusercontent.com/13991774/179883511-a960d3b9-e879-4eab-91bb-4c1c49a85950.png)
知乎未登录时，打开知乎，就会是上图的页面

关闭所有代理软件、广告屏蔽插件，最后发现把知乎增强脚本关了没有此问题

**Comment by XIU2** [comment]
已更新脚本，排除登陆页了。
