### ISSUE TITLE
希望制作一个 一键在新标签页打开当前页面里所有选中链接 功能的脚本

### ISSUE THREAD

**Issue by perrierfox** [XIU2/UserScript#257]

**Comment by perrierfox** [comment]
看到了您写的在新标签页中打开链接的脚本，但存在一种情景，即在当前页面中有多个链接都需要打开，希望能实现1、选中当前页面的某个区域，2、一键打开该区域中的所有链接，3、均是在新标签页中打开。

**Comment by XIU2** [comment]
“选中当前页面的某个区域” 这点我就不知道该如何实现。
说实话，这种情况需要的人并不普遍，你还是 `Ctrl + 鼠标左键` 来新标签页打开链接吧。

**Comment by perrierfox** [comment]
您好，您的邮件我已收到，我会尽快向您回复。裴孟华 谨上

**Comment by perrierfox** [comment]
多谢您的回应，我找到一个chrome插件“linkclump”已经实现这个功能了，再次感谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "XIU2/UserScript"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 下午5:33
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [XIU2/UserScript] 希望制作一个 一键在新标签页打开当前页面里所有选中链接 功能的脚本 (Issue #257)





 
“选中当前页面的某个区域” 这点我就不知道该如何实现。
 说实话，这种情况需要的人并不普遍，你还是 Ctrl + 鼠标左键 来新标签页打开链接吧。
