### ISSUE TITLE
[自动无缝翻页] RARBG

### ISSUE THREAD

**Issue by Marce1ek** [XIU2/UserScript#258]
![QQ截图20220801025428](https://user-images.githubusercontent.com/99329516/182041080-21bb1bd8-a262-4804-91b4-98b234beeac2.jpg)
只能翻到这页，再往下滚滚轮就没反应了，edge和chrome都是这样🥺

**Comment by XIU2** [comment]
我连续翻了 11 页，没有复现你描述的问题。

你再出现该问题时，按下 F12 打开开发者工具，选择 Console（又叫控制台），能看到翻页失败的原因，把这些原因展开后截图发给我看看。

另外，请提供详细的复现步骤，比如从哪个 URL 地址开始，往下翻到第几页就一定会卡住之类的。

![01](https://user-images.githubusercontent.com/54703944/182083772-4a20a62b-dfb4-4477-bc01-769ed3930067.png)

**Comment by Marce1ek** [comment]
https://rarbgprx.org/torrents.php
试了几次 翻到第几页卡住不是固定的 这回在第一页就卡住了
![QQ截图20220801191255](https://user-images.githubusercontent.com/99329516/182136062-02aabd2b-c3e3-482e-bd0f-c8061a50b497.jpg)
[rarbgprx.org-1659352422203.log](https://github.com/XIU2/UserScript/files/9233395/rarbgprx.org-1659352422203.log)

**Comment by XIU2** [comment]
依靠这个错误还无法判断具体原因，远程协助吧。

下载远程协助软件（这个是只有被控功能的单文件版，用完即删），告诉我你的设备代码、临时密码（我看到后会帮你删除）。  
https://dl.todesk.com/windows/ToDesk_Lite.exe

**Comment by XIU2** [comment]
或者你尝试把下面这段翻页规则，复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存试试（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）。

``` json
"RARBG": {
	"host": "/rarbg/",
	"url": "if(document.title.indexOf('RARBG') > -1 && fun.lp() == '/torrents.php'){return true}",
	"style": "body{background-repeat-y: repeat;}",
	"blank": 3,
	"pager": {
		"nextL": "#pager_links>a[title='next page']",
		"pageE": "table.lista2t tr.lista2",
		"replaceE": "#pager_links"
	}
}
```

**Comment by XIU2** [comment]
我找到原因了，已经修复了。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

**Comment by Marce1ek** [comment]
刚看到，加进去之后可以了
