### ISSUE TITLE
[自动无缝翻页] 翻页排版问题

### ISSUE THREAD

**Issue by rcyggdra** [XIU2/UserScript#259]
https://fourpetal.com/（原Switch520，域名已更新）
翻页排版出现问题，第二页只在最右侧单列显示且无法翻页到第三页之后
Win10 64Bit Chromium 102.0.5005.167

**Comment by XIU2** [comment]
这个网站原来是独立规则，但是因为换了域名，所以匹配到了通用规则，导致出了问题。

复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

```
	"Switch520": {
		"host": ["fourpetal.com","fourpetal.com"],
		"url": "return (!fun.indexOF('.html'))",
		"blank": 3,
		"pager": {
			"nextL": "a.next",
			"pageE": ".row.posts-wrapper>div",
			"replaceE": "ul.page-numbers"
		}
	}
```
