### ISSUE TITLE
吾爱破解论坛 增强

### ISSUE THREAD

**Issue by TommyMerlin** [XIU2/UserScript#26]
打开首页会疯狂打开无数个积分窗口。
![Snipaste_2021-03-13_08-58-25](https://user-images.githubusercontent.com/32566324/111013445-6a08c180-83da-11eb-8a4c-e301c92a5a55.png)

**Comment by XIU2** [comment]
今天凌晨的时候我就发现了，所以凌晨 1 点多的时候我就更新脚本了。

不过每个人脚本管理器扩展检查更新时间可能不一定，你手动去更新/升级下脚本就行了。

**Comment by TommyMerlin** [comment]
好的 感谢

**Comment by XIU2** [comment]
@TommyMerlin 论坛恢复签到功能后，又出了点问题，已经修复了（v1.2.4）。
