### ISSUE TITLE
[Github 增强 - 高速下载] “連接.台灣” 已过期

### ISSUE THREAD

**Issue by wordlesswind** [XIU2/UserScript#260]
![image](https://user-images.githubusercontent.com/9050713/183850698-7b986be2-0ebc-4525-a781-f171d3e35819.png)

TWNIC WHOIS：https://twnic.tw/whois_n.cgi?query=%E9%80%A3%E6%8E%A5.%E5%8F%B0%E7%81%A3

联系人邮箱的域名“zeng.tw”不存在，应该是不会续费了，可以去除。

**Comment by XIU2** [comment]
已更新移除，原来已经挂了这么长时间了么。。。
我发现我这边运营商的 DNS 还有缓存，导致我前几天排查更新加速源时都没发现（指定原 IP 的话，依然可以访问）。
