### ISSUE TITLE
[Github 增强] ghdl.z-o.top现不可用

### ISSUE THREAD

**Issue by feizhuqwq** [XIU2/UserScript#261]
z-o.top因反代github遭到netcraft举报钓鱼网站，z-o.top全域遭到cloudflare封禁，ghdl.z-o.top也将失效，正在尝试申诉
cloudflare也因此封禁了我的账户

Cloudflare received a phishing report regarding:

z-o.top

Below is the report we received:

Reporter: Anonymous
Reported URLs:

https://dos.z-o.top/

Logs or Evidence of Abuse: Hello,

We have discovered a phishing attack located on your network:

https://dos.z-o.top/ [104.21.7.56]

This attack targets our customer, GitHub, website URL [https://github.com/.](https://github.com/)

Would it be possible to have the fraudulent content, and any other associated fraudulent content, taken down as soon as you are able to?

Additionally, please keep the fraudulent content safe so that our customer and law enforcement agencies can investigate this incident further once the site is offline.

More information about the detected issue is provided at https://incident.netcraft.com/a9894d02abf9/

Many thanks,

Netcraft

Phone: +44(0)1225 447500
Fax: +44(0)1225 448600
Netcraft Issue Number: 34792760

 We have restricted access to the phishing-related content until it has been removed.

Regards,

Cloudflare Trust & Safety

**Comment by XIU2** [comment]
你这个 dos.z-o.top 是干啥的？

**Comment by feizhuqwq** [comment]
是的，dos.z-o.top是反代的github全站，导致了z-o.top的全域和cloudflare账号都被封禁
我已经提交申诉，但现在netcraft和cloudflare依然没有给我任何回复

**Comment by XIU2** [comment]
国外效率很低，一件小事都能拖拖拉拉一两个星期。。。

**Comment by feizhuqwq** [comment]
chrome 现在也将 dos.z-o.top 标记为危险，和之前的 github.com.cnpmjs.com 是一样的
看来 chrome 使用了 netcraft 的数据库

**Comment by feizhuqwq** [comment]
> chrome 现在也将使用 s.zo.top 使用标记为危险，和之前的 github.com.cnpmjs.com 是一样的 chrome 的数据库了 netcraft 的

**Comment by feizhuqwq** [comment]
chrome 现在也将 dos.z-o.top 标记为危险，和之前的 github.com.cnpmjs.com 是一样的
看来 chrome 使用了 netcraft 的数据库

**Comment by feizhuqwq** [comment]
netcraft 已经关闭了 issue 但理由不是误封禁而是钓鱼网页已被删除
cloudflare 仍未响应我的邮件
可能只能更换域名解决了

Hi, 

Thank you for notifying us. We have checked the reported URL and confirmed
that the phishing page has been removed. As a result, we now consider the
issue resolved, and have removed the URL from our blocklist.

Kind Regards
Netcraft

**Comment by XIU2** [comment]
惨。。。
我的一个域名因为流量太大，被 Cloudflare 限速了（即通过我的域名 Cloudflare CDN 的任何流量都被限制为 X KB/s），虽然邮件写着会持续直到流量平息什么，但实际上压根不会恢复，而我也只是个 free 用户，所以连个申诉的地方都没有。。。

**Comment by feizhuqwq** [comment]
free 用户，只能哭了

**Comment by feizhuqwq** [comment]
看来 cloudflare 已经不是以前的 cloudflare 了，不给我们薅了

**Comment by XIU2** [comment]
可能是因为我是 free 用户吧，我看别人讨论时的截图，比我要多很多都没事，不过对方是付费用户。。。
看来白嫖还是有上限的~

> 后来看了下发现 Cloudflare 说的免费无限流量，指的是防御，而不是网站流量，毕竟流量成本较高。。。

**Comment by feizhuqwq** [comment]
域名更改为 ghdl.feizhuqwq.cf

**Comment by XIU2** [comment]
OK，感谢提供~

**Comment by XIU2** [comment]
@hacamer 一般人不用担心，达不到我这个量（平均一天 10TB 大概相当于以平均每秒 1Gb 的速度全天 24 小时的跑）。
是我当初给我另一个开源项目调用的：https://github.com/XIU2/CloudflareSpeedTest/issues/168
被限速后，已经让使用者尽量自建了，同样也有很多人自建并分享给我，现在相当于几十个人自建的帮我负载均衡。

**Comment by PencilNavigator** [comment]
可以尝试去Cloudflare的Discord找员工申诉，有些好心的员工会给你case提权的。
https://discord.gg/cloudflaredev

**Comment by feizhuqwq** [comment]
由于几个月前 Freenom 无条件在域名到期前回收了我的 [feizhuqwq.cf](https://ghdl.feizhuqwq.cf/) 域名和其他一系列我在 Freenom 注册的域名，导致解析失效，反复和 Freenom 联系无果，因此弃用 feizhuqwq.cf
现在服务通过付费域名重新部署：[https://dl.ghpig.top/](https://dl.ghpig.top/)

**Comment by XIU2** [comment]
OK 感谢更新！

当初 Freenom 因为被起诉导致好几个免费域名后缀被收回，我这边大家分享的公益加速源也一下子挂了好多。。。

**Comment by feizhuqwq** [comment]
现在提供负载均衡源 https://dl-slb.ghpig.top/
基于权重轮询

**Comment by XIU2** [comment]
感谢分享。

不过，原来的 `dl.ghpig.top` 是要弃用了么？
你这个 负载均衡、权重轮询 是什么意思？是这个新的已经做好了服务器负载均衡，还是说是让我同时用这两个来负载均衡（目前脚本是每次打开网页都随机 4 个美国的加速源来负载均衡的）。

**Comment by feizhuqwq** [comment]
`dl.ghpig.top` 并没有弃用，它是负载均衡池的加速源之一，`dl-slb.ghpig.top` 基于 302 重定向实现负载均衡，收集了许多公开的加速源，稳定性较好的加速源会有更高的权重，系统运行在 Cloudflare Workers 上（如果后期请求过大可能会使用 Nginx 自建），每天会检查一次加速源可用性，但由于 CF 服务器在国外，所以无法检测到被 GFW 等情况（后期可能会优化检测算法）

- 如果使用脚本进行负载均衡，那么两个都可以添加
- 也可以只保留一个美国 `dl-slb.ghpig.top`，因为它的负载均衡池中包含了脚本中大部分的可用加速源，其中包括了大量的 CF Workers 源

另外，事实上 `dl.ghpig.top` 和 `dl-slb.ghpig.top` 经过了路由优化，电信走 CF 美国，联通走 CF 日本，移动走 CF 欧洲
