### ISSUE TITLE
[知乎美化] 宽屏显示功能，回答页的关注键错位

### ISSUE THREAD

**Issue by jingjue** [XIU2/UserScript#263]
![image](https://user-images.githubusercontent.com/71930132/184655266-afc09c49-3ee5-4fd0-917d-6c04a030b4d6.png)
这个关注键应该在最右边吧

**Comment by XIU2** [comment]
这是知乎最近才添加的，原来是没有的，自然还没有适配优化。

**Comment by XIU2** [comment]
已更新脚本，将 [关注] 按钮移动在最右侧。

> 因为我还在折腾其他脚本，为了统一更新，所以该脚本更新延迟了一个小时。
