### ISSUE TITLE
[3DM论坛美化] 正常图片不显示

### ISSUE THREAD

**Issue by K2M74** [XIU2/UserScript#264]
https://bbs.3dmgame.com/thread-6325161-1-1.html

开启脚本后游戏截图变成空白。

![image](https://user-images.githubusercontent.com/50667472/185039464-42611c12-0f90-4323-82cc-b8066c0cfa68.png)

关闭后正常。

![image](https://user-images.githubusercontent.com/50667472/185039396-60283c3c-0837-4a71-b7f2-fe8194b03475.png)

**Comment by XIU2** [comment]
你编辑脚本，搜索 `img[border="0"].zoom` 将其改为：
```
a>img[border="0"].zoom
```
保存即可。
