### ISSUE TITLE
[Github 增强] 增加Raw文件加速源

### ISSUE THREAD

**Issue by BNQDZJ** [XIU2/UserScript#265]
增加Raw文件加速源 git.poker 由XPoet提供 Cloudflare CDN

**Comment by XIU2** [comment]
你这是直接反代 Github 网站并套了 Cloudflare CDN 么？
不建议这样干，参考 #261 
如果要做加速源的话，建议搭建 https://github.com/hunshcn/gh-proxy 项目，这个没有风险。
