### ISSUE TITLE
[吾爱破解增强] 希望添加“按发表时间排序”功能

### ISSUE THREAD

**Issue by junyuwsda** [XIU2/UserScript#271]
大佬的脚本很棒！
不知道吾爱破解自身有无这功能，我没找到

吾爱破解的默认帖子是按回复时间应该，这就造成了一打开开头都是已经看过的帖子
希望增加一个按最新发表帖子时间排序，这样按时间来看就不会重复了（精品软件区）

**Comment by XIU2** [comment]
![01](https://user-images.githubusercontent.com/54703944/186626615-77492452-4c29-4527-93bf-498d5f50c6df.png)
