### ISSUE TITLE
[自动无缝翻页] 在某个 GitHub 用户 的 stars 页面翻页效果不对劲

### ISSUE THREAD

**Issue by dsy4567** [XIU2/UserScript#273]
https://github.com/2659170494?tab=stars
![image](https://user-images.githubusercontent.com/84607814/187672707-a2176724-50ae-43f0-b2cd-7d54d55c673d.png)
![$HQE2S3Q573@SFU{G9X(J`M](https://user-images.githubusercontent.com/84607814/187673006-98a4ae3b-1f1b-458e-8033-293afbd8e3d2.png)
如图所示, 左边没有翻页, 右边一直翻

**Comment by XIU2** [comment]
Github 在右边加了个 Starred topics 导致的。

已更新修复。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
