### ISSUE TITLE
大佬你好，可以添加一个俄区的油猴插件吗？

### ISSUE THREAD

**Issue by CC12581** [XIU2/UserScript#274]
这是俄区的网站：https://byrut.org/

**Comment by XIU2** [comment]
什么意思？
请按照 Issues 格式模板填写，注明哪个脚本。

> 如果你指的是 [自动无缝翻页]，那么早就支持该网站了，且我当前测试也没有失效，请确保是最新外置翻页规则。

**Comment by CC12581** [comment]
好的，感谢回复！！！
