### ISSUE TITLE
希望开发能高亮网页关键词句的脚本

### ISSUE THREAD

**Issue by KJH-x** [XIU2/UserScript#277]
### 功能需求（即你要什么样的功能）
> 高亮某些字词，就像chrome搜索时的样子，但是搜索只能同时高亮一种字符串，希望能有高亮多个自定义字符串的脚本，对于快速浏览的速度有较大提升

### 预期目标（即你希望该功能是什么样子的，如果能提供 示例/截图/代码 就更好了~）
> 就类似于网站的代码高亮
> 自定义需要高亮的字符串

十分感谢大佬的各种脚本，望拨冗考虑！

**Comment by XIU2** [comment]
这个 Issues 模板是针对现有脚本提功能建议的。

我已经不再接受 新脚本请求了。

另外，你这种需求，只能依靠遍历网页内容实现，效率很低，也没什么好的办法。

**Comment by KJH-x** [comment]
好的，打扰了
