### ISSUE TITLE
[Github 增强] Github releases 单个版本界面展开后不显示高速下载解析

### ISSUE THREAD

**Issue by Huaxidesu** [XIU2/UserScript#279]
> 单个releases版本中项目过多以后，github会收起文件，只展示部分，此时插件正常显示各个下载节点，但是当展开后就不会显示插件的下载节点了,例如 https://github.com/SoftEtherVPN/SoftEtherVPN_Stable/releases 项目

> 
![屏幕截图 2022-09-19 225918](https://user-images.githubusercontent.com/45794248/191049580-885f2cbb-758b-4da4-a99d-f8e99cea65a1.png)
![屏幕截图 2022-09-19 225949](https://user-images.githubusercontent.com/45794248/191049595-d3eb4e0d-d06f-4456-98cf-23a41e856bdc.png)

**Comment by XIU2** [comment]
看了下，是 Github Releases 改版了，列表内容不在网页中，点击展开后才会动态加载列表。

而当前脚本也只是打开网页时运行一次，所以才会出现你遇到的情况。

我稍后研究下。

**Comment by XIU2** [comment]
已修复，目前脚本会监控网页元素变化，在 Github 动态加载文件列表后第一时间就会紧跟着插入加速下载按钮。
