### ISSUE TITLE
[知乎增强 / 知乎美化] 在 Mac Safari Tampermonkey 下无法使用

### ISSUE THREAD

**Issue by NightAsker** [XIU2/UserScript#28]
如题，测试环境为tampermonkey 4.11.6117，Mac safari 14.0.3，知乎美化和知乎增强无法正常使用，效果无法展现

**Comment by XIU2** [comment]
遗憾的是，我没有 MAC 设备，也就没办法在 safari 环境下做测试排除问题。。。

**Comment by XIU2** [comment]
如果你想要解决该问题的话，我可以尝试**远程协助**来帮你看看。

毕竟如果不能亲自上手检查，我是无法获取问题原因并解决的。

**Comment by qveinole** [comment]
从Greasy Fork上来的，兄弟我知道你这个也是用爱发电不容易，但你没跑过Safari应该在页面上标注出来吧。。Safari安了结果只显示暗黑模式，然后也关不掉了...

**Comment by XIU2** [comment]
刚才有个热心人士让我远程协助看了下 MAC，发现这个问题疑似是 **知乎 与 Safari 兼容性问题**。
同样的脚本，在其他网站上就可以正常运行，但是**在知乎上就无法运行**，我测试了十几个脚本都是如此。

对于这种兼容性问题，我无能为力。。。
