### ISSUE TITLE
[自动无缝翻页] 添加"百度开发者"网站的支持

### ISSUE THREAD

**Issue by cheakin** [XIU2/UserScript#280]
url: https://kaifa.baidu.com/
介绍: 开发者搜索是百度针对开发者群体开发的垂类搜索，打造一个小而美的垂类，意在让开发者能够更加简单高效的检索到需要的内容， 为平时的工作，学习提供帮助。

**Comment by XIU2** [comment]
动态加载内容的无法添加支持。

https://greasyfork.org/zh-CN/scripts/419215/discussions/125786
