### ISSUE TITLE
[Github增强] Raw 文件加速源

### ISSUE THREAD

**Issue by BNQDZJ** [XIU2/UserScript#281]
jsd.eagleyao.com
回源jsdelivr
腾讯云CDN
由ayao提供
缓存3天

**Comment by XIU2** [comment]
缓存 1 年确实时间有点长。。。
而且时间长了的话，光缓存的文件就能占不少存储空间。

**Comment by BNQDZJ** [comment]
> 缓存 1 年确实时间有点长。。。 而且时间长了的话，光缓存的文件就能占不少存储空间。

所以在沟通希望能减少到7天或者1天，但到目前还没有回应

**Comment by 54ayao** [comment]
那就cdn侧强行缓存3天用户浏览器缓存1天吧

**Comment by 54ayao** [comment]
![Screenshot_2022-09-25-13-15-22-161_com android chrome](https://user-images.githubusercontent.com/86733666/192129438-aa77d579-6dc5-4ae3-b517-4c16d038f207.jpg)
好了

**Comment by XIU2** [comment]
@54ayao 感谢提供公益加速源，已经更新脚本加上了，greasyfork 介绍中也注明了你的 Github 主页~
