### ISSUE TITLE
[新标签页打开链接] 水木社区打开失效

### ISSUE THREAD

**Issue by adyliu** [XIU2/UserScript#282]
### 水木社区无法打开新链接

https://www.mysmth.net/nForum/mainpage

水木社区是ajax后填充的内容，打开新链接的方法都失效了。
请教下这种ajax后加载的内容怎么解决呢？

[TargetBlank.user.js](https://github.com/XIU2/UserScript/blob/master/TargetBlank.user.js)

**Comment by XIU2** [comment]
该脚本是有个人提需求我临时写的，非常简陋，我自己也不用，也懒得费劲折腾。

建议你安装我的另一个 [自动无缝翻页] 脚本，其中我写的有 水木社区 的翻页规则，刚刚我给这翻页规则加了强制新标签页打开的规则，测试了没啥问题，如果你已经装的有了，那就更新一下外置翻页规则。

**Comment by adyliu** [comment]
更新了规则，可用。

感谢快速回复和支持。
