### ISSUE TITLE
[自动无缝翻页] 希望支持 Github releases 页面的翻页

### ISSUE THREAD

**Issue by strange-qwq** [XIU2/UserScript#283]
如题，示例页面：
https://github.com/JetBrains/kotlin/releases -> https://github.com/JetBrains/kotlin/releases?page=2

**Comment by XIU2** [comment]
这个页面本来就支持，我看了下是 Github 更新网页结构导致规则失效了。

已经更新规则修复了。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

**Comment by XIU2** [comment]
@opkhkh 经过测试，均没有失效，如果你那边用不了，应该是其他因素导致的，根据最近的反馈情况，多半还是 CSP 的问题，似乎一些人的 Tampermonkey 没有正常移除网站的 CSP 限制，导致脚本无法运行。

随便找了下好几个，但具体为什么没有正常移除 CSP，我就不清楚了，有些人换个浏览器就正常了，明明都是同样的 Tampermonkey 版本（包括有个人和我同样的浏览器+Tampermonkey 版本 也不行），因此我觉得问题还是出在 Tampermonkey 上？

#441 
https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5/discussions/266499
https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5/discussions/263562

**Comment by XIU2** [comment]
@opkhkh Tampermonkey 较新的版本去掉了 是 这个选项，因为考虑到大家版本可能不一样，所以我介绍里写的是让大家设置为 `是 或 全部移除`，我这边 Tampermonkey v5.1.1 设置一直都是 `是`，倒是没啥问题。

你这个看起来可能是旧版本升级到新版本 Tampermonkey 后，因为新版本移除了该选项，导致出了 BUG ？
我稍后更新一下脚本介绍里的 Tampermonkey 设置说明吧，干脆都让改为 全部移除 算了。

****

至于 Greasy Fork 的反馈页面，脚本自然不可能限制翻页次数什么的，毕竟这有什么意义？
我这边滚轮连续滚动脚本自动翻了 20 页，没有遇到卡住的问题。
你遇到的卡住问题，应该是网络问题引起的，可能是超时（默认 5000ms），也可能是触发了该网站的访问频率限制（但我刚才没遇到）。
