### ISSUE TITLE
[脚本名称] 希望对样式脚本提供用户样式版本

### ISSUE THREAD

**Issue by Crystal-RainSlide** [XIU2/UserScript#284]
### 功能需求
> 希望对样式脚本提供用户样式 UserCSS 版本，具体参见 [UserCSS](https://github.com/openstyles/stylus/wiki/Usercss)。可以直接在 [发布你编写的样式 - Greasy Fork](https://greasyfork.org/zh-CN/script_versions/new?language=css) 提交，也可以注册个帐号，提交到 https://userstyles.world/ 上。

### 预期目标
> 用 [Stylus](https://github.com/openstyles/stylus) 管理用户样式，支持用户样式的自定义选项功能等。

**Comment by XIU2** [comment]
美化类脚本或者 CSS 样式，我现在已经不写了（不在发布新的了，现在纯自用，我用的也是 Stylus），已有的也基本停更了。

因为这类需求都非常个性化，即完全按照我个人喜好、审美设计修改的，发布出来就会有很多人因喜好、审美差异而不断地提需求。。。所以我还是自用吧。
