### ISSUE TITLE
[Github增强]希望添加无缝翻页功能（GitHub首页 More）

### ISSUE THREAD

**Issue by buiawpkgew1** [XIU2/UserScript#285]
![image](https://user-images.githubusercontent.com/71136405/195967403-d6a9133e-d29a-4d56-bbd7-667d20faea0b.png)

**Comment by XIU2** [comment]
脚本早就已经支持了。
![01](https://user-images.githubusercontent.com/54703944/195967528-67273ec3-9094-445a-babc-4ddebc6f9dfa.png)

**Comment by buiawpkgew1** [comment]
没反应啊

**Comment by XIU2** [comment]
不清楚你那边的情况。
但我可以确保我这边最新脚本+最新外置翻页规则是正常的。

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/195967628-5a84745b-4fab-4c60-bfae-3b17eff3d466.png)
点击
![image](https://user-images.githubusercontent.com/71136405/195967656-5add2b74-b3a7-462c-bb66-49789750fbd7.png)

**Comment by XIU2** [comment]
下载远程协助软件（这个是只有被控功能的单文件版，用完即删），告诉我你的设备代码、临时密码。  
https://dl.todesk.com/windows/ToDesk_Lite.exe

**Comment by buiawpkgew1** [comment]
![image](https://user-images.githubusercontent.com/71136405/195967727-b6c944b1-25a5-4dc3-b8ec-c26618339342.png)

**Comment by XIU2** [comment]
合着我们两个说的都不是一个脚本。。。

请安装我的另一个脚本 [自动无缝翻页]。
