### ISSUE TITLE
[知乎增强] 净化标题消息 功能失效

### ISSUE THREAD

**Issue by huangyn-pku** [XIU2/UserScript#286]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 
在greasyfork更新之后，净化标题消息失效了， 尝试重启浏览器、关闭/打开功能，都没有用。

### 错误截图（可选，也可以是一些错误代码）
> 
<img width="1466" alt="image" src="https://user-images.githubusercontent.com/32168037/196082162-bf81b2f0-b38f-4a52-ad89-0480914f9672.png">

**Comment by XIU2** [comment]
你给我知乎发一条私信或评论，我这边现在没有消息测试不了。
https://www.zhihu.com/people/xiu2

**Comment by XIU2** [comment]
我手动模拟调试发现问题了，已修复。
简单来说就是 Tampermonkey 4.18.0 版本比以前执行更快，导致脚本执行的时候，网页还没加载完成，从而功能失效。
https://greasyfork.org/zh-CN/scripts/419081-%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA/discussions/151644

更新脚本即可。
