### ISSUE TITLE
[自动无缝翻页] 影响个别网站加载 功能问题

### ISSUE THREAD

**Issue by deyerong** [XIU2/UserScript#288]
这里有一个网站  [gmoj](gmoj.net)

我每次打开的时候都贼慢，显示老长时间的空白，后来把脚本(自动无缝翻页)关了就快了，

### 您能告诉我在哪里加上什么可以把这个网站加入黑名单吗？

**Comment by deyerong** [comment]
服了，github这个md……

网址：https://gmoj.net/

**Comment by XIU2** [comment]
我这边测试没有异常，网页秒开，无论开关脚本均无差别。

估计是其他地方的原因，比如脚本冲突什么的？

点击浏览器右上角的 Tampermonkey 图标，点击在 [自动无缝翻页] 右边的 ` > ` 按钮展开菜单，点击 `排除 gmoj.net` 即可。
这个是 Tampermonkey 的黑名单功能，这样脚本就完全不会在该网站上运行了）。
