### ISSUE TITLE
[护眼模式] 增加午休模式

### ISSUE THREAD

**Issue by tangjyan** [XIU2/UserScript#289]
### 功能需求（即你要什么样的功能）
> 很多办公室不论是白天还是晚上都是开灯的，并不需要黑暗模式，恰恰是午休的时候会关灯，这时候是整个工作时间唯一不开灯的时候，这时候最需要黑暗模式。但是目前只能通过`自定义昼夜时间`来实现。但是我设置每天的14:00|12:00为白天时间，这样逻辑上就是12:00|14:00为夜晚时间，但是程序好像并不能理解这样的设置。

### 预期目标（即你希望该功能是什么样子的，如果能提供 示例/截图/代码 就更好了~）
希望`自定义昼夜时间`可以让我设置12点到14点为夜晚就可以

**Comment by XIU2** [comment]
已更新脚本支持反向设置，即你说的 `14:00|12:00`，差点没把我绕晕。。。

**Comment by tangjyan** [comment]
> 

非常感谢！抱歉我没说清楚
