### ISSUE TITLE
彩云小翻油猴脚本

### ISSUE THREAD

**Issue by Aaronoooooo** [XIU2/UserScript#29]
以前安装过一个彩云小译的油猴脚步,聚好用,启用后只保留了一个翻译的图标,无线翻译次数,后面更换了电脑,脚本忘记备份,在greasyfork上已经找不到了,期待大佬也能整一个,

**Comment by XIU2** [comment]
凡是这种脚本或者浏览器扩展，翻译功能都是调用的翻译 API 接口(百度、有道、谷歌等)。
而这种接口有免费有付费的(按次数收费)，免费的一般要么限制频率，要么限制次数(每日)。
既然该脚本作者主动下架(删除)脚本了，肯定是翻译接口出现了问题。
而我也没有好用又免费且无限次数的翻译接口，因此你的需求我无法实现。
