### ISSUE TITLE
[知乎增强] 失效

### ISSUE THREAD

**Issue by Jiangyj-2020** [XIU2/UserScript#290]
### 问题描述
> 从前些天开始（大约是二周左右，也可能是更长的时间前），我发现打开 https://www.zhihu.com 时 [知乎增强] 插件并没有一如既往地发挥作用。在知乎的其它页面也无法生效。[原始包含] 和 [原始匹配] 项是保持开启的。

### 错误描述
> Tampermonkey 插件显示”没有运行中的脚本“。

**Comment by XIU2** [comment]
这是 Tampermonkey 4.18.0（正式版）的 BUG，已经有人 Github Issues 反馈了，BETA 版已修复，正式版将会在下个版本修复。
