### ISSUE TITLE
[脚本名称] 希望添加 XXX 功能（记得修改该标题示例，并移除该括号提示）

### ISSUE THREAD

**Issue by 7th-angle** [XIU2/UserScript#292]
<!-- [此处为注释内容] 如果是希望 [自动无缝翻页] 脚本添加某个网站的支持，https://m.shanxixse.com/小说网站，希望添加

### 功能需求（即你要什么样的功能）
> 

### 预期目标（即你希望该功能是什么样子的，如果能提供 示例/截图/代码 就更好了~）
>

**Comment by XIU2** [comment]
？

**Comment by XIU2** [comment]
不要发无意义的 Issues。

**Comment by 7th-angle** [comment]
对不起大大，没看懂这个格式，不小心点出去了，实在私密马赛 o(╥﹏╥)o&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月10日(周四) 凌晨0:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XIU2/UserScript] [脚本名称] 希望添加 XXX 功能（记得修改该标题示例，并移除该括号提示） (Issue #292)




 
不要发无意义的 Issues。

**Comment by XIU2** [comment]
嗯，我看了下，你是新注册的账号，估计不熟悉 Github 操作吧。

看了下模板内容，你把需求 `https://m.shanxixse.com/小说网站，希望添加` 写到了注释里，导致被隐藏了。。。

**Comment by 7th-angle** [comment]
对的对的，希望大大不要生气



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月10日(周四) 凌晨1:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XIU2/UserScript] [脚本名称] 希望添加 XXX 功能（记得修改该标题示例，并移除该括号提示） (Issue #292)

**Comment by XIU2** [comment]
得亏我耐心仔细看了下才发现你是操作失误，否则真把你当成捣乱的了，因为前几天就遇到个捣乱的搞得我心情很差。。。

****

复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

```
	"山西小说网": {
		"host": "m.shanxixse.com",
		"url": "/^\\/html\\/\\d+\\/\\d+\\/\\d+/",
		"pager": {
			"nextL": "js;if(fun.getCSS('#pt_next[onclick]')){return (location.origin + fun.getCSS('#pt_next[onclick]').getAttribute('onclick').replace(/^.+\\(\\[/,'').replace('])','').replaceAll('\"','').split(',').join('/'))}",
			"pageE": "#nr1>p",
			"replaceE": ".nr_page",
			"scrollD": 2000
		}
	}
```

> `scrollD` 值越大，越早触发翻页，可自行根据需求调整

**Comment by 7th-angle** [comment]
太谢谢了，哎呀大大不要和那种人生气嘛，故意闹的不是脑子有问题就是家里户口本少人了，吃点好东西睡一觉，心情就好起来了！ps.因为您我也超开心😊



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月10日(周四) 凌晨1:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XIU2/UserScript] [自动无缝翻页] 希望添加支持 m.shanxixse.com (Issue #292)




 
得亏我耐心仔细看了下才发现你是操作失误，否则真把你当成捣乱的了，因为前几天就遇到个捣乱的搞得我心情很差。。。
 
 
复制粘贴到脚本 自定义翻页规则 默认的 { } 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）
 "山西小说网": { "host": "m.shanxixse.com", "url": "/^\\/html\\/\\d+\\/\\d+\\/\\d+/", "pager": { "nextL": "js;if(fun.getCSS('#pt_next[onclick]')){return (location.origin + fun.getCSS('#pt_next[onclick]').getAttribute('onclick').replace(/^.+\\(\\[/,'').replace('])','').replaceAll('\"','').split(',').join('/'))}", "pageE": "#nr1&gt;p", "replaceE": ".nr_page", "scrollD": 2000 } }   
scrollD 值越大，越早触发翻页，可自行根据需求调整
