### ISSUE TITLE
[Github 增强] Raw 文件加速失效

### ISSUE THREAD

**Issue by SharerMax** [XIU2/UserScript#293]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
[New Code Search and Code View (Beta)](https://docs.github.com/en/repositories/working-with-files/managing-files/navigating-files-with-the-new-code-view) 启用后，Raw 文件加速失效
> 

### 错误截图（可选，也可以是一些错误代码）
<img width="1429" alt="image" src="https://user-images.githubusercontent.com/9065684/201275100-cf7ab744-0fbf-457f-a323-35633f836b90.png">

>

**Comment by XIU2** [comment]
等待该功能正式发布后再说吧。
否则我都看不到具体网页内容。

**Comment by XIU2** [comment]
对了，忘记跟你说了，9 天前的 v2.2.8 已经新增了对新版项目列表页/代码视图页的 Raw 加速支持(包括快捷下载)。。。
