### ISSUE TITLE
[自动无缝翻页] B站多处无法生效

### ISSUE THREAD

**Issue by liang0802** [XIU2/UserScript#294]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> B站无法生效如：关注列表
![image](https://user-images.githubusercontent.com/72696563/201850404-73b33a06-fca7-43e3-8f68-d2d375566caa.png)

UP主视频列表
![image](https://user-images.githubusercontent.com/72696563/201850794-401eebde-6b5c-4013-8865-2a3c34dafe39.png)

**Comment by XIU2** [comment]
这不叫无法生效，因为无效的前提是有效过，但我并没有对这些页面添加支持。

B 站目前只对搜索页添加了支持，其他页面均因动态加载内容而无法添加支持，因此我直接在脚本里排除了 B 站。

**Comment by liang0802** [comment]
OK，感谢
