### ISSUE TITLE
新标签页打开链接 打开链接 功能失效

### ISSUE THREAD

**Issue by xjl456852** [XIU2/UserScript#295]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 
打开页面:
https://search.douban.com/movie/subject_search?search_text=%E8%A5%BF%E8%A1%8C%E5%AE%A2%E6%A0%88&cat=1002
然后打开搜索结果中的任何一个结果,比如打开:
西行客栈‎ (2023)
它打开的新页面地址为:about:blank#blocked
不能正常的打开目标地址.
如果关闭 新标签页打开链接 插件,是可以正常打开链接的.

### 错误截图（可选，也可以是一些错误代码）
> 
![image](https://user-images.githubusercontent.com/8008097/203286581-8db71fd7-96fb-44c6-82dc-ff1de00b260c.png)

![image](https://user-images.githubusercontent.com/8008097/203286503-28f33f42-1496-4c7e-a9e3-10aa846ce107.png)

**Comment by XIU2** [comment]
我试了下，发现是浏览器拦截了弹出窗口（也就是点击的那个链接）

**Comment by XIU2** [comment]
不过，该脚本是别人提需求，我给顺手写的，后来发现兼容性问题很多，无法实现真正通用，而且很多网站因为各种原因而无法适配，折腾了几个版本后，我就放弃了，这是我开源脚本中唯一一个自己也没有去使用的。。。

遇到有问题的网站，建议在 Tampermonkey 脚本菜单里点击 `>` 排除该网站。
