### ISSUE TITLE
大哥，您的插件太好用了。能否增加迅雷链接识别，许多下载页面手动复制粘贴迅雷链接，手抽筋了

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#3]
非常实用的脚本咧
大哥，您的插件太好用了。能否增加迅雷链接识别，许多下载页面手动复制粘贴迅雷链接，手抽筋了

**Comment by XIU2** [comment]
emmm 你如果了解我（看过我知乎发的文章以及我的 TrackerList 项目），那你应该知道我个人是很讨厌迅雷的。。。

**Comment by XIU2** [comment]
有其他问题、需求可以重新开启问题。

**Comment by lyjhyjyes** [comment]
也对，还有其他下载工具可用，只要开ipv6就很爽

XIU2 <notifications@github.com> 于2020年10月29日周四 下午9:49写道：
