### ISSUE TITLE
[知乎美化] 希望添加 隐藏浏览知乎时顶部标题横栏 功能

### ISSUE THREAD

**Issue by johnsonz** [XIU2/UserScript#30]
请问能添加隐藏高亮显示在最顶部的标题bar选项吗？就是里面class是AppHeader的

**Comment by XIU2** [comment]
嗯。。。
不管是反馈问题，还是提交建议，记得加上 <kbd>脚本名称 及 网站</kbd>（有些脚本包含了多个网站）。

否则我都不知道你指的是什么。。。

**Comment by XIU2** [comment]
花了一会功夫，把所有 Issues 标题都给按格式修改规范了下（顺便加上了相应标签）。

**Comment by johnsonz** [comment]
没注意。。。从油猴里面点过来的。是【知乎 增强】脚本，知乎站点，鼠标往下滚动，如下图会变成标题，不知道有没有人和我一样不喜欢。。。
![zhihu](https://user-images.githubusercontent.com/2533629/112923445-e7edfc00-9140-11eb-9791-50f9a49cea6a.PNG)
我本来是在你的脚本里面直接改的，然后就自动更新，你懂的刷的一下就把我改的覆盖了

**Comment by XIU2** [comment]
这个功能已经有了，在我另一个脚本中 [知乎美化] https://greasyfork.org/zh-CN/scripts/412212

> 因为这个功能最适合用 CSS 样式去处理，所以就放到专门处理样式的 知乎美化 脚本中了。

#### 2021年03月12日，版本 v1.0.7
1. **新增** [浏览回答向下翻时自动隐藏标题]（默认关闭）。
