### ISSUE TITLE
[自动无缝翻页] 希望支持 materiality 主题

### ISSUE THREAD

**Issue by dsy4567** [XIU2/UserScript#302]
https://www.eaimty.com/theme.html

**Comment by XIU2** [comment]
除非某个系统、模板、主题应用非常广泛，否则我一般不会去添加为通用规则（即自动适配这类网站）。

你提到的这个网站主题好像有点印象，但这些年，我好像就碰到过一两次吧，感觉用的人太少了，不说这个主题，哪怕 Typecho 博客系统用的人都不多。。。

****

不过这个网站的规则，你可以先用着。

复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）
``` json
	"www.eaimty.com": {
		"host": "www.eaimty.com",
		"url": "return fun.getCSS('.mdui-btn-active+a')",
		"pager": {
			"nextL": ".mdui-btn-active+a",
			"pageE": ".mdui-card",
			"replaceE": ".page-nav",
			"scrollD": 2000
		}
	}
```

> `scrollD` 值越大，越早触发翻页，也可以省略（默认 2000，但别忘了移除上一行末尾的逗号）
