### ISSUE TITLE
[知乎美化/知乎增强] 在firefox 上必须重启tampermonkey才能生效

### ISSUE THREAD

**Issue by nankewei** [XIU2/UserScript#303]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 在firefox 上必须重启tampermonkey才能生效，而且是每次关闭浏览器后都必须重启tampermonkey才能生效！

### 错误截图（可选，也可以是一些错误代码）
> 
重启tampermonkey前
<img width="885" alt="image" src="https://user-images.githubusercontent.com/35093286/206852830-46dd0ea7-1673-4df8-851e-946bada7f6f7.png">
<img width="812" alt="image" src="https://user-images.githubusercontent.com/35093286/206852838-650431c8-29d1-457c-83b1-3e911c2be67b.png">
重启tampermonkey后
<img width="910" alt="image" src="https://user-images.githubusercontent.com/35093286/206852848-ee7c4912-b425-4c27-aa4c-736a02883ca3.png">

**Comment by XIU2** [comment]
重启 Tampermonkey？那这和我脚本有啥关系？。。。

**Comment by XIU2** [comment]
你的 Tampermonkey 是什么版本，我刚刚想起来我也遇见过这个问题，是某个版本的 BUG。
以前有好几个人反馈过：
#286 
#290 
https://greasyfork.org/zh-CN/scripts/419081/discussions/153824
https://greasyfork.org/zh-CN/scripts/419081/discussions/151644

**Comment by nankewei** [comment]
不好意思搞错了。Tampermonkey版本是最新的，红的也试过了，都不行。

**Comment by XIU2** [comment]
如果只有我的脚本不可用，那么问题多半在我脚本上，
但如果所有脚本都不可用，那么问题就多半在 Tampermonkey 上了。

另外，刚才我用 Firefox 浏览器最新版本+最新 Tampermonkey v4.18.1 版本去知乎上刷了几个网页试了下，倒是没出现你说的情况，建议你在多排查一下，Tampermonkey 导出备份一下，然后重装 Tampermonkey 后再去手动安装 知乎增强 脚本再试试，如果还不行，就去 Tampermonkey 项目反馈吧。
