### ISSUE TITLE
[Hostloc-Enhanced.user.js] 希望添加屏蔽匿名用户和屏蔽被正常用户引用的已被屏蔽用户的发言

### ISSUE THREAD

**Issue by erlkmjnhg** [XIU2/UserScript#304]
### 功能需求

>屏蔽匿名用户的发言
>屏蔽被正常用户引用的已被屏蔽用户的发言

### 预期目标

> 不会看到已屏蔽用户的任何发言

**Comment by XIU2** [comment]
你的第二个需求已实现，更新脚本即可。
- **新增** [屏蔽用户] 支持屏蔽 其他用户回复黑名单用户时所引用的部分内容

目前会将整个引用内容移除，但保留该正常用户的发言内容。
****
至于屏蔽匿名用户，较麻烦点，懒得搞，以后再说吧~
