### ISSUE TITLE
[自动无缝翻页] 碧蓝航线wiki首页自动跳转新闻页bug

### ISSUE THREAD

**Issue by FlandreCirno** [XIU2/UserScript#305]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 我是碧蓝航线b站wiki的维护，近期有用户反馈首页会自动跳转新闻页，现在查明是自动翻页脚本错误的把新闻的查看更多识别为了翻页，希望修复一下谢谢！
站点地址https://wiki.biligame.com/blhx/%E9%A6%96%E9%A1%B5

### 错误截图（可选，也可以是一些错误代码）
> 
![image](https://user-images.githubusercontent.com/35405826/207548733-2ed09a08-0291-4c8a-bb18-278d290910da.png)
![image](https://user-images.githubusercontent.com/35405826/207548777-0fab6b6c-568b-4f30-9d8c-42afceba569e.png)

**Comment by XIU2** [comment]
这个 "查看更多" 确实误伤较多，我干脆给去掉算了。。。
稍后会更新脚本的。
