### ISSUE TITLE
[v2ex增强]自动无缝翻页 功能失效

### ISSUE THREAD

**Issue by lsh1215225** [XIU2/UserScript#306]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 
第一页只能自动翻1页，但是手动点到第二页后能自动翻完
### 错误截图（可选，也可以是一些错误代码）
> 
![image](https://user-images.githubusercontent.com/20274559/207766726-d955e9bf-0c07-4667-af38-57f4a00e90d8.png)

**Comment by XIU2** [comment]
我这边测试正常，没有失效，从第一页开始，可以连续翻到第三页（末页）。
![01](https://user-images.githubusercontent.com/54703944/207767899-e5f03399-d103-43de-993b-d3d85c35bd7a.png)

**Comment by lsh1215225** [comment]
> 我这边测试正常，没有失效，从第一页开始，可以连续翻到第三页（末页）。 ![01](https://user-images.githubusercontent.com/54703944/207767899-e5f03399-d103-43de-993b-d3d85c35bd7a.png)
![image](https://user-images.githubusercontent.com/20274559/207772360-bf8d7b63-e666-4f16-a35d-73b138109e6b.png)

![Honeycam 2022-12-15 12-24-53](https://user-images.githubusercontent.com/20274559/207772376-94474358-17a1-4aca-8173-8b777e787ce9.gif)
