### ISSUE TITLE
[自动无缝翻页] 无缝翻页 功能失效

### ISSUE THREAD

**Issue by davisphper** [XIU2/UserScript#307]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 已安装扩展, 已安装脚本, 在google搜索结果页下拉到底部无法无缝翻页, 左下角也没出现"悬浮页码"

### 错误截图（可选，也可以是一些错误代码）
图一:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37396615/208919856-1e88bd0b-780c-4d5e-9cb4-1e5263b8e23c.png">
图二:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/37396615/208920357-313a87da-5c1c-4df6-8618-4c18c136a9e6.png">

**Comment by XIU2** [comment]
我这边测试正常，规则没有失效。

![01](https://user-images.githubusercontent.com/54703944/209032582-2c6c4864-8a51-4fa5-a172-435cee93637d.png)

**Comment by XIU2** [comment]
其他脚本支持的网站是否正常？
如果你截图时的 Console 内容没有被清空过的话，那么看起来脚本似乎压根就没有运行，否则正常情况下无论支持与否，脚本都会在 Console 中输出调试消息的。

**Comment by davisphper** [comment]
已解决, 扩展没启动😓
