### ISSUE TITLE
[V2ex 增强] 开关功能时通知标题文本错误

### ISSUE THREAD

**Issue by jasonz3157** [XIU2/UserScript#31]
![image](https://user-images.githubusercontent.com/48433202/113232852-8bb9e200-92d0-11eb-8add-84160b39d632.png)

显示是 吾爱破解论坛增强

**Comment by XIU2** [comment]
尴尬~
脚本菜单这段代码，我直接从我另一个脚本里复制的，忘记删掉了。。。

已经修复了。
