### ISSUE TITLE
[自动无缝翻页] 脚本添加SMF论坛的支持

### ISSUE THREAD

**Issue by rcyggdra** [XIU2/UserScript#313]
SMF论坛的网站
https://www.simplemachines.org/community/index.php?topic=584230.0

使用SMF的论坛网站
https://www.gildor.org/smf/index.php/topic,6925.0.html

希望可以适配，感谢。

**Comment by XIU2** [comment]
较冷门的论坛系统，我是不会制作通用规则的。

另外，你提的这两个网站，是使用同一个论坛系统么？我看网页元素完全不同。

**Comment by rcyggdra** [comment]
也许是下面那个网站用的是旧版的系统；
主要适配下面那个网站就可以了，它是一个UE4资源提取工具的网站。

**Comment by XIU2** [comment]
复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

```
	"gildor": {
		"host": "www.gildor.org",
		"url": "/\\/(topic|board),/",
		"blank": 3,
		"pager": {
			"nextL": "//td[@class='smalltext navPages']/b[position()>1 and text()!=' ... ']/following-sibling::a[1]",
			"pageE": "#quickModForm>table:first-child>tbody>tr, tr.windowbg",
			"replaceE": ".smalltext.navPages",
			"scrollD": 2000
		}
	}
```
> `scrollD` 值越大越早触发翻页。

****

这个论坛太旧了，写规则时发现，单靠 CSS 无法准确选中下一页 URL 的页码元素（页码分为以下五种情况，需要同时满足），白折腾半天，最后还是改用 Xpath 才完美解决了。。。
https://www.gildor.org/smf/index.php/topic,6925.0.html
https://www.gildor.org/smf/index.php/topic,6925.15.html
https://www.gildor.org/smf/index.php/topic,6925.60.html
https://www.gildor.org/smf/index.php/topic,6925.210.html
https://www.gildor.org/smf/index.php/topic,6925.240.html

**Comment by rcyggdra** [comment]
非常感谢，我也知道这网站没“下一页”的元素，只有页码，所以才劳烦你帮忙。
