### ISSUE TITLE
希望添加显示当前实际页码的功能

### ISSUE THREAD

**Issue by MrGongqi** [XIU2/UserScript#315]
你好！您这个脚本对我的帮助很大，谢谢您为此做出的努力和贡献，非常感谢！我有一个小小的请求和建议：目前该脚本是现实实际翻了多少页的功能，希望添加显示当前页码的功能，可以设置一个功能键，用户可以根据自身需要设置打开或则关闭。
因为我的请求而给您添加的额外麻烦和工作量，我深感抱歉，并感谢您将为此做出的努力，谢谢！

**Comment by XIU2** [comment]
不考虑添加，一方面是我个人不需要该功能，另一方面是该功能不是几句代码就能实现的，因此没有我个人需求去推动的话，我是懒得去折腾该功能的。
