### ISSUE TITLE
你的护眼模式简直就是删不掉的病毒，我已经不能还原回去了，删干净也没用，第一次在油猴看到这么垃圾的插件，日你妈

### ISSUE THREAD

**Issue by boilhazard** [XIU2/UserScript#316]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 

### 错误截图（可选，也可以是一些错误代码）
>

**Comment by XIU2** [comment]
你要好好说话，我还能帮你解决下问题，但既然这么没素质就算了~  
这种问题以前也有人出现过，后来我远程排查后基本上都是因为其他扩展、脚本导致的。  
你要有兴趣，可以翻翻脚本反馈页去找找解决办法：
https://greasyfork.org/zh-CN/scripts/426377-%E6%8A%A4%E7%9C%BC%E6%A8%A1%E5%BC%8F/feedback
