### ISSUE TITLE
[新标签页打开链接] 标签异常自增

### ISSUE THREAD

**Issue by Weidows** [XIU2/UserScript#318]
### 问题描述
> 关闭了其他所有脚本, 仅Tampermonkey+新标签页打开链接情况下加载, 下面链接会爆炸式自增

### 错误截图
> 可以试试这个链接: https://github.com/ShirasawaSama/CefDetectorX/discussions/17#discussioncomment-4858938

**Comment by XIU2** [comment]
什么意思？不理解，这个网页没发现什么奇怪的地方。

**Comment by Weidows** [comment]
> 什么意思？不理解，这个网页没发现什么奇怪的地方。

啊啊抱歉脚本名字写错了, 是 `新标签页打开链接`

开了自启新标签拦截了吗? 我打开这个链接会1生2, 2生4这么自己复制暴增

Edge 和 Firefox都试了, Firefox上纯干净的, 只有Tampermonkey+新标签页打开链接

**Comment by XIU2** [comment]
这个脚本我自己都不用，是当初有人需要我给随手写的，后来发现各网站情况太复杂了，难以通用化适配各网站，改来改去都不满意，因此我自己都懒得折腾了。。。

你删掉该脚本吧~
