### ISSUE TITLE
[知乎增强 & 知乎美化] Issue #303 解决方案

### ISSUE THREAD

**Issue by gsh20040816** [XIU2/UserScript#319]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
#303 解决方案：在 `// ==UserScript==` 部分加入一行 `// @sandbox JavaScript`
[此方案来源](https://github.com/Tampermonkey/tampermonkey/issues/1384#issuecomment-1151998715)
Linux 下，对最新稳定版 Tampermonkey，在 Firefox 测试有效，对 Chrome 未产生破坏性影响。

**Comment by XIU2** [comment]
找了一圈，才发现该沙盒标识是 v4.18.0 版本新加的实验性功能，因此还导致当时出现了众多问题，后来 v4.18.1 修复了。
只有在更新日志里提了一下，因此我也不清楚是否会带来其他问题，不过我还是给那几个用的人较多的脚本都给加上该标识了，让大家用一段时间看看有没有奇怪的问题出现。
