### ISSUE TITLE
[自动无缝翻页] 自动翻页无法查看google快照

### ISSUE THREAD

**Issue by My-Responsitories** [XIU2/UserScript#320]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 浏览器: Firefox 109
> 用户脚本管理器: Violentmonkey

Google搜索自动翻页出的下一页(第11+个搜索结果)点击网址右侧的"🔽"无法展示`网页快照`/`类似结果`下拉菜单

**Comment by XIU2** [comment]
这种情况就是 三角形 按钮绑定了点击事件，而脚本只是单纯的将下一页内容插入本页面，并没有去绑定这些事件，因此你点击才会没反应。

这种情况是否能解决取决于网站是如何绑定的点击事件，这个可能需要花费时间研究。

**Comment by XIU2** [comment]
尝试给规则加上 `"scriptT": 0,` 或 `"scriptT": 0,` 即插入下一页内容后，会随带着插入所有 JS 脚本元素（插入后会自动运行），也就是会执行下一页内包含的所有 JS 代码，但结果却不行，甚至还会导致前面本可以正常点击的三角形按钮也失效。。。

这样的话，该问题就很难解决了，我挨个排查试了下似乎都不行。。。

**Comment by chengnan049** [comment]
如今 Google 快照已无法查看，该 Issue 应该关闭
