### ISSUE TITLE
[自动无缝翻页 *] www.bing.com 功能Bugs

### ISSUE THREAD

**Issue by Alan996** [XIU2/UserScript#321]
### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> www.bing.com是国际版本，一直都是使用国际版本的bing，发现[自动无缝翻页 *]只适配了cn.bing.com应该是，作者帮忙添加一下国际本把。

### 错误截图（可选，也可以是一些错误代码）
> 报错，弹窗提醒拼接失败。
![image](https://user-images.githubusercontent.com/41531958/220904375-f0b0420e-ebfc-4055-af02-082f413e9c7a.png)

**Comment by XIU2** [comment]
这不是脚本的问题，而是你们那边网络环境的问题：  
https://greasyfork.org/zh-CN/scripts/419215/discussions/166512  
https://greasyfork.org/zh-CN/scripts/419215/discussions/168334
