### ISSUE TITLE
[自动无缝翻页] MAC Safari 百度无法自动无缝翻页

### ISSUE THREAD

**Issue by wujita01** [XIU2/UserScript#322]
我是safari 15.6.1，MacBook Pro，百度无法自动翻页，so bing google都可以

**Comment by XIU2** [comment]
我这边测试可以正常翻页，没发现什么问题（Chrome + Tampermonkey）。
这代表百度搜索网页规则没有变化，我写的规则也没有失效。

另外，我没有 MAC 设备或 Safari 浏览器环境，且该浏览器和 Chrome 等浏览器差异较大（例如 #107 ），因此我可能无法解决你的问题。

**Comment by wujita01** [comment]
谢谢。已经找到替代软件了。



在 2023-02-24 11:32:25，"XIU2" ***@***.***> 写道：

我这边测试可以正常翻页，没发现什么问题（Chrome + Tampermonkey）。
这代表百度搜索网页规则没有变化，我写的规则也没有失效。

另外，我没有 MAC 设备或 Safari 浏览器环境，且该浏览器和 Chrome 等浏览器差异较大（例如 #107 ），因此我可能无法解决你的问题。
