### ISSUE TITLE
[知乎增强] 屏蔽搜索发现

### ISSUE THREAD

**Issue by AugustTuan** [XIU2/UserScript#324]
### 功能需求（即你要什么样的功能）
> 
请问能否屏蔽掉右侧的搜索发现，这个区域非常干扰注意力
![image](https://user-images.githubusercontent.com/37429029/221472940-671f0369-e06c-4a8d-9a41-8862ec907c72.png)

### 预期目标（即你希望该功能是什么样子的，如果能提供 示例/截图/代码 就更好了~）
> 右侧的搜索发现可以被屏蔽掉。

**Comment by XIU2** [comment]
安装我写的另一个 知乎美化 脚本，其中的宽屏显示功能就是你要的。

**Comment by AugustTuan** [comment]
哇塞，感谢up，就我狗命，已经被这个搜索发现烦死了
