### ISSUE TITLE
[自动无缝翻页] 加上这个漫画网址 大佬

### ISSUE THREAD

**Issue by chankit141** [XIU2/UserScript#325]
https://www.cartoonmad.com/comic/1152.html

### 问题描述（必填，最好写上 复现步骤，越详细越好，特别是一些复杂的问题）
> 

### 错误截图（可选，也可以是一些错误代码）
>

**Comment by XIU2** [comment]
该网站已添加支持，但看了下是换了个域名，以前是 .cc 现在又变成 .com 了。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
