### ISSUE TITLE
[Github 增强 - 高速下载] Raw加速选项功能失效

### ISSUE THREAD

**Issue by misaka10843** [XIU2/UserScript#326]
### 问题描述

在GitHub中的功能预览中打开New Code Search and Code View，插件将无法添加按钮到Raw上

### 附加截图

![image](https://user-images.githubusercontent.com/69132853/222728557-4af7e456-498b-4c53-99ca-199caf8c2685.png)
![image](https://user-images.githubusercontent.com/69132853/222728594-61f1bb39-cb2c-4772-a7e7-d10e0d7d391f.png)

**Comment by XIU2** [comment]
已更新添加支持新版页面。
