### ISSUE TITLE
[Github加速] https://gh2.yanqishui.work 下载地址失效

### ISSUE THREAD

**Issue by PencilNavigator** [XIU2/UserScript#327]
### 问题描述

![图片](https://user-images.githubusercontent.com/85282140/222735246-2f88e93a-6cf9-45a6-8927-89fbedef224d.png)
错误链接：https://gh2.yanqishui.work/https://github.com/koi778/CloudflareSpeedTest-GUI/releases/download/CloudflareST-GUI/cloudflareST-GUI.rar

不同地址加速同一项目链接（正常下载）：https://ghps.cc/https://github.com/koi778/CloudflareSpeedTest-GUI/releases/download/CloudflareST-GUI/cloudflareST-GUI.rar

同时，访问 https://gh2.yanqishui.work/ 也会出现Worker threw exception. (Error 1101)

**Comment by PencilNavigator** [comment]
网络环境：
南方移动 IPv6，没有使用CloudflareSpeedTest进行优选。
访问其他Cloudflare网站正常。

ping记录：（会解析成gh.xiu2.xyz？）
![图片](https://user-images.githubusercontent.com/85282140/222736420-f46d6827-04e2-4e0c-ac45-a74eebf908a1.png)

**Comment by XIU2** [comment]
看来就是挂了，我目前正在对 Github 新版文件列表/代码试图页 添加支持（Raw 加速），到时候更新时我会顺便注释掉该加速源的。

**Comment by PencilNavigator** [comment]
@XIU2 有没有可能可以像隔壁CloudflareSpeedTest一样做多链接负载均衡呢？

**Comment by XIU2** [comment]
一直都是啊，目前是十几个 Release 加速源，每次随机 4 个。

**Comment by XIU2** [comment]
已更新脚本。
