### ISSUE TITLE
[知乎增强] 屏蔽盐选功能在首页推荐不生效

### ISSUE THREAD

**Issue by notgiilao** [XIU2/UserScript#328]
### 问题描述

看了下设置项适合没有针对首页盐选屏蔽的，不确定是知乎改版或其它原因

### 附加截图

![B6~%XFF~`XV 1GW19GO01XW](https://user-images.githubusercontent.com/127093130/223067152-c1c8048b-3e2d-4b7e-99f3-d11a60dd651d.png)

**Comment by XIU2** [comment]
因为压根就没有支持过，哪来的失效，你没看后面 [ ] 里写了支持范围了么？。。。

首页、搜索页无法添加支持，因为只有在你展开回答之后，知乎才会加载其内容，展开前脚本是无法通过某些特征判断该条回答是不是盐选内容。

**Comment by notgiilao** [comment]
> 因为压根就没有支持过，哪来的失效，你没看后面 [ ] 里写了支持范围了么？。。。
> 
> 首页、搜索页无法添加支持，因为只有在你展开回答之后，知乎才会加载其内容，展开前脚本是无法通过某些特征判断该条回答是不是盐选内容。

  感谢关注，因为之前没注意到首页的盐选内容，我以为是功能失效了，自己也看了支持范围才有点懵，可能以前刚好没碰上这问题。谢谢
