### ISSUE TITLE
[自动无缝翻页] 在B站部分页面自动翻页功能失效 

### ISSUE THREAD

**Issue by superbigsteam** [XIU2/UserScript#331]
### 问题描述

首先，对应页面的没有加入黑名单
比如在哔哩哔哩首页搜索“名侦探柯南”，给出的结果在综合页面可以自动翻页，但是切换到影视页面后无法自动翻页。
希望可以得到解决

### 附加截图
![image](https://user-images.githubusercontent.com/84577396/224468468-66b0a159-31dc-4acf-aa51-6df1e3618f4e.png)
![image](https://user-images.githubusercontent.com/84577396/224468654-c49fdf69-11c5-4538-92c9-853f1a9ee71e.png)
![image](https://user-images.githubusercontent.com/84577396/224468489-91e4c6ef-cb1f-4a9e-9a3d-bb40be57581d.png)
![image](https://user-images.githubusercontent.com/84577396/224468679-15374d14-8ca6-4552-8cb5-c431cc3a43b3.png)

**Comment by XIU2** [comment]
这不叫失效，因为该搜索分类我压根没有添加支持（我没有大会员因此也用不上这个，所以当初就没添加支持）。
只有我添加支持了的页面（左下角有页码按钮）突然不能自动翻页了才叫失效。

不过既然你需要，那我就添加支持了。
`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
