### ISSUE TITLE
[知乎增强] gif/动图资源失效

### ISSUE THREAD

**Issue by draftman9** [XIU2/UserScript#332]
### 问题描述

在看知乎文章时，打开知乎增强后，动图失效。关闭它时，动图就好了（可以播放了）。

测试网址： https://zhuanlan.zhihu.com/p/411848925

**Comment by XIU2** [comment]
排查了下是 [默认高清原图] 功能导致的，该功能会将所有用户上传的图片替换为原图（`data-original` 属性值），而你这个动图的原图竟然是 .jpg 的静图格式。。。导致其动不了了。
一般来说知乎的动图都需要手动点击才会动起来的（其实就是将静图 .jpg 改为了 .webp 图片格式），而你这个默认就动。。。
