### ISSUE TITLE
[知呼美化] 私信数量带上黑圈

### ISSUE THREAD

**Issue by Bryan2333** [XIU2/UserScript#333]
### 问题描述

如图
![截图 2023-03-20 12-34-56](https://user-images.githubusercontent.com/31512600/226247910-e26a3b76-a74b-42e5-836c-63e2ddbd2e75.png)

私信数量上带了个黑圈

**Comment by XIU2** [comment]
这是知乎首页活动/广告导致的，而非我脚本的问题
