### ISSUE TITLE
[Github 增强] 希望移除 github.nite07.com 镜像站

### ISSUE THREAD

**Issue by nitezs** [XIU2/UserScript#334]
### 问题描述

镜像站部署在一个小鸡上，并且这个小鸡上还有一些其他服务，但每个月只有3TB流量。
放在油猴脚本里的话流量完全不够，目前流量已经被刷超了。
希望作者能从脚本中移除

### 附加截图

![Snipaste_2023-03-21_10-50-35](https://user-images.githubusercontent.com/40469236/226507279-bfbee30b-d278-437d-ad3d-e52e8c21f139.png)

**Comment by XIU2** [comment]
OK 已移除，感谢这段时间提供的公益服务~
