### ISSUE TITLE
[自动无缝翻页] 脚本执行时出错

### ISSUE THREAD

**Issue by ybhgl** [XIU2/UserScript#335]
### 问题描述
测试所有的网页均失效，排除了脚本冲突问题，截图复现网站是：https://game.ali213.net/forum-2987-1.html
![20230326_103407](https://user-images.githubusercontent.com/35188529/227752157-3779071a-f567-428f-9670-5f5b6c7efed3.png)

**Comment by XIU2** [comment]
反馈问题请描述详细一点，就一张图是无法判断的。

**Comment by XIU2** [comment]
我测试 https://game.ali213.net/forum-2987-1.html 可以正常翻页，没有报错。

![01](https://user-images.githubusercontent.com/54703944/227752264-2617a6a0-7450-4275-af32-ec843d2c4047.png)

**Comment by XIU2** [comment]
根据你截图里的报错信息，初步判断是 SiteTypeID 函数运行出错了。

因此大概率是，自定义翻页规则 有问题，或 外置翻页规则 有问题导致的。

**Comment by ybhgl** [comment]
> 根据你截图里的报错信息，初步判断是 SiteTypeID 函数运行出错了。
> 
> 因此大概率是，自定义翻页规则 有问题，或 外置翻页规则 有问题导致的。

前几天确实弹出过一个信息，大概是说规则更新失败之类的，可能和这个有关

**Comment by XIU2** [comment]
那你就手动点击 `更新外置翻页规则` 试试（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

或者干脆完全删除脚本，重新安装一次也一样。

**Comment by ybhgl** [comment]
重新安装问题依旧，Tampermonkey里面没有显示脚本的那几个选项，只有图中的那一行
![屏幕截图 2023-03-26 105009](https://user-images.githubusercontent.com/35188529/227752551-f027d729-85fc-4fa2-a312-87ccc90e4076.png)
完全删除后安装解决

**Comment by XIU2** [comment]
直接去重新安装是不行的，脚本配置不会清空，需要完全删除再去安装。

我排查了下外置翻页规则分流地址，发现了一个分流地址存在问题（失效了，而且还会返回一个 JSON 格式的错误，导致被脚本当成正常规则内容写入脚本配置了。。。），稍后我会更新脚本去移除该分流地址的。
