### ISSUE TITLE
[自动无缝翻页] 添加对jsproxy等代理工具的支持

### ISSUE THREAD

**Issue by dsy4567** [XIU2/UserScript#337]
### 功能需求

https://github.com/EtherDream/jsproxy

希望在使用此类代理工具时可以翻页

### 预期目标

通过为类似代理服务编写规则或要求用户手动配置来决定是否使用使用已有的翻页规则

**Comment by XIU2** [comment]
这种反代后的网页和直接访问网页本身结构没啥区别，因此你只需要自行添加域名记录。
参考 #176 中的 `继承标识 inherits 使用说明`
