### ISSUE TITLE
[知乎增强] 自动签到失效了

### ISSUE THREAD

**Issue by Naco** [XIU2/UserScript#339]
### 问题描述

有些日子了，希望能修复

**Comment by XIU2** [comment]
知乎增强 脚本没有自动签到功能。

**Comment by Naco** [comment]
抱歉抱歉，说错了，是V2EX的脚本。

**Comment by XIU2** [comment]
![01](https://user-images.githubusercontent.com/54703944/231030133-26f32753-26cd-4f2a-ac75-31d0208f3af9.png)

刚才访问了下 V2EX，没有问题，可以正确自动签到。

**Comment by Naco** [comment]
卸载重装之后的确没有再报错了，谢谢。
