### ISSUE TITLE
52破解页面美化问题

### ISSUE THREAD

**Issue by wanghongkun1** [XIU2/UserScript#34]
会自动开启屏蔽悬赏贴，脚本中的选项功能无法使用了，两个功能都是控制帖子内自动翻页的

**Comment by XIU2** [comment]
什么？

**Comment by XIU2** [comment]
请确保你已经更新到最新版本的脚本了。

**Comment by wanghongkun1** [comment]
1.0.6，是最新的

**Comment by XIU2** [comment]
你连脚本都看岔了。

[屏蔽导读悬赏贴] 功能是 [吾爱破解论坛增强] 脚本的，而不是 [吾爱破解论坛美化] 脚本的。
增强脚本是 1.2.5，美化脚本是 1.0.6

![03](https://user-images.githubusercontent.com/54703944/113480873-3137a600-94c9-11eb-8a0d-6d77d3346f2f.png)

![02](https://user-images.githubusercontent.com/54703944/113480872-2f6de280-94c9-11eb-8eaf-5f2f700d207c.png)

**Comment by wanghongkun1** [comment]
啊，对不起，看错了；不过我的论坛美化脚本，隐藏版规的选项不管是开还是关都会把版规隐藏了

**Comment by XIU2** [comment]
[吾爱破解论坛美化] 的 [隐藏版规] 功能依然开关正常。

我建议你把这两个脚本重新安装试试。

![04](https://user-images.githubusercontent.com/54703944/113481040-f3874d00-94c9-11eb-85e5-bf848a183f8f.png)
![05](https://user-images.githubusercontent.com/54703944/113481041-f4b87a00-94c9-11eb-833e-3de0da8b7404.png)

**Comment by XIU2** [comment]
有意思的是，在刚才给你截图的过程中，我突然发现 [屏蔽导读悬赏贴] 功能有漏网之鱼。。。

看了下代码，是我很早以前写的，重写了一遍完善了该功能，虽然你可能用不到~

#### 2021年04月03日，版本 v1.2.6
1. **修复** [屏蔽导读悬赏贴] 功能有漏网之鱼的问题。
