### ISSUE TITLE
[知乎增强] 首页视频屏蔽 功能失效

### ISSUE THREAD

**Issue by pengqian089** [XIU2/UserScript#340]
### 问题描述

我刷知乎基本在看首页的内容，搜索之类的视频屏蔽有没有失效还不清楚。

### 附加截图

![20230410043826](https://user-images.githubusercontent.com/13491546/230795428-ec5411f5-9760-4f1c-aacc-6bfd1d060c28.png)

**Comment by XIU2** [comment]
应该是昨天的更新 `修复 屏蔽视频后首页推荐页再次点击推荐后网页报错的问题` 导致的。

不过我刚才首页刷了半天，连一个视频都没遇到，遇到的全都是视频回答，因此我只是把昨天关于屏蔽视频的改动恢复了（屏蔽视频回答的改动依然保留），你更新脚本试试吧。

**Comment by pengqian089** [comment]
> 应该是昨天的更新 导致的。`修复 屏蔽视频后首页推荐页再次点击推荐后网页报错的问题`
> 
> 不过我刚才首页刷了半天，连一个视频都没遇到，遇到的全都是视频回答，因此我只是把昨天关于屏蔽视频的改动恢复了（屏蔽视频回答的改动依然保留），你更新脚本试试吧。

第一页确实没有视频，但是往下翻，就会偶尔出现视频了

**Comment by XIU2** [comment]
不清楚，我来来回回翻了 10 分钟一个都没遇到，全都是 `视频回答`，可能是我运气不好吧~
