### ISSUE TITLE
[知乎增强] 屏蔽指定类别（视频） 功能失效

### ISSUE THREAD

**Issue by amorphobia** [XIU2/UserScript#341]
### 问题描述

现在貌似不能完全屏蔽视频类别

### 附加截图

![图片](https://user-images.githubusercontent.com/523025/231398785-45c1d23e-7874-42ff-933d-ce62d97e2d88.png)

**Comment by forevergoagent** [comment]
我也是
![image](https://user-images.githubusercontent.com/33625825/231471496-4887a584-0c14-4b58-b90b-b775459613a9.png)

**Comment by XIU2** [comment]
不知道为什么，我这边首页一个 `视频` 都刷不到，只能刷到视频回答。。。

**Comment by pengqian089** [comment]
> 不知道为什么，我这边首页一个 `视频` 都刷不到，只能刷到视频回答。。。 搜索页倒是能碰到，但都可以正常屏蔽掉。
> 
> 你们是最新版本的脚本吗？如果是最新版本的话，尝试去[安装测试旧版本](https://greasyfork.org/zh-CN/scripts/419081-%E7%9F%A5%E4%B9%8E%E5%A2%9E%E5%BC%BA/versions)的脚本，看是从哪个版本开始失效的，如果试了一圈也没找到能正常屏蔽的，则说明是网页改动导致的功能失效（而非某个版本的代码改动导致的功能失效）。

2.2.8版本确认是可以有效屏蔽首页视频的

**Comment by XIU2** [comment]
@pengqian089 感谢测试，已经找到问题并修复了，你更新脚本试试吧。
确定修复后吱一声~
