### ISSUE TITLE
[知乎增强] 希望添加 宽屏 功能

### ISSUE THREAD

**Issue by freedomspiritJohn** [XIU2/UserScript#342]
### 功能需求

希望增加一个宽屏的功能，把右侧的无用的东西都替换掉。这样同一屏上可阅读的内容就会变多

### 预期目标

![image](https://user-images.githubusercontent.com/129288685/231433427-70620866-cd5e-49d4-944e-eca8724ca02e.png)

把右边侧栏删除然后替换成文章，
参考图：
![image](https://user-images.githubusercontent.com/129288685/231433366-1f6a2347-e348-4289-80b0-60eafe66b5b0.png)

**Comment by XIU2** [comment]
该功能在 `知乎美化` 脚本里（叫做 `宽屏显示`）。

知乎增强针对的是功能，知乎美化针对的是样式。
