### ISSUE TITLE
[知乎增强] 增加知乎网页版个人收藏夹搜索功能

### ISSUE THREAD

**Issue by zhangliang3-1** [XIU2/UserScript#345]
### 功能需求

希望能够在知乎的网页版中，增加可以搜索个人收藏夹内容的功能。虽然知乎APP上面有这个功能，但是在使用网页版的时候无法对自己收藏的内容进行搜索，即使是针对标题的搜索也没有。

### 预期目标

类似知乎APP中能够搜索收藏夹内容的程度

**Comment by XIU2** [comment]
对该功能没啥兴趣，因此暂不考虑~
如无必要，该脚本不会新增功能了，仅仅保持维护，主要是我已经很长时间不怎么玩知乎了，而该脚本是我当初经常玩知乎是为了方便而写的，现在我也只是偶尔看看罢了。。。
