### ISSUE TITLE
[Github 增强] 希望添加【搜索时指定用户并过滤掉对方仓库中的项目】功能

### ISSUE THREAD

**Issue by yy35959199** [XIU2/UserScript#347]
### 功能需求

使用github搜索时，经常搜索到某些反华群体的仓库，里面添加了一堆检索关键词，但是实际是完全无关的内容，只有大量虚假信息，纯纯恶心人，还影响搜索效率
希望能添加一个功能，可以输入指定的用户名，然后在使用github的检索时，把这些用户的项目从搜索结果中移除

### 预期目标

在github搜索结果的界面中，可以点击按键，弹出文本框，输入指定用户的用户名，点击添加，会将这个ID存到油猴脚本的配置中
而后在搜索时，过滤器脚本会从搜索结果中，把这些人的项目从页面上直接移除掉

**Comment by XIU2** [comment]
该脚本全称是 `Github 增强 - 高速下载`，因此该脚本只会专注于 `高速下载` 这方面，不考虑添加其他和下载无关的功能。

> 主要是精力有限，懒得添加、维护更多功能了。。。

**Comment by yy35959199** [comment]
> 该脚本全称是 `Github 增强 - 高速下载`，因此该脚本只会专注于 `高速下载` 这方面，不考虑添加其他和下载无关的功能。
> 
> > 主要是精力有限，懒得添加、维护更多功能了。。。

好的……不好意思OTZ
