### ISSUE TITLE
[脚本名称] 希望添加 xxx 功能（记得修改该标题示例，并移除该括号提示）

### ISSUE THREAD

**Issue by 3XC1T3D** [XIU2/UserScript#349]
### 功能需求

Hi,

i installed your script :) it's awesome! The dark mode works perfectly :)

But i got the Problem, that i dont understand Chinese :D it is possible that you release a english translation?

I am searching a script which only makes the dark mode type 2 - all the other option i dont need. Perhaps you could minify it and translate it to english?

### 预期目标

English translation and minified only to Dark Mode Type 2

**Comment by XIU2** [comment]
The script is for my own use, so there are no plans to make an English version.
You might consider using Google Translate to translate all Chinese in the script to English (22 Chinese sentences in total).

The script has three modes, but the switching mode is global (that is, it affects all web pages, and it is not supported to specify a certain mode for a certain web page separately), so you can use mode 2 without switching mode, so it can be used. It doesn't differ from your needs.

If you don't want to see the toggle mode option, you can edit the script to find the `['menu_darkModeType', '点击切换模式', '点击切换模式', 2],` and comment it (add ` // ` to the beginning of the line)
