### ISSUE TITLE
GitHub的代理全部坏了？

### ISSUE THREAD

**Issue by Z-fly** [XIU2/UserScript#35]

**Comment by XIU2** [comment]
试了下，目前 [Github 增强 - 高速下载] 脚本一切正常。

如果你不能用，请详细描述并提供截图。

**Comment by Z-fly** [comment]
> 试了下，目前 [Github 增强 - 高速下载] 脚本一切正常。
> 
> 如果你不能用，请详细描述并提供截图。

![image](https://user-images.githubusercontent.com/10470892/113649653-6575b700-96c1-11eb-8ba3-c207a07a0592.png)
之前是不行，先可以了
