### ISSUE TITLE
[脚本名称] xxx 功能失效（记得修改该标题示例，并移除该括号提示）

### ISSUE THREAD

**Issue by DarkStarCrashesPouringItsLIghtIntoAshes** [XIU2/UserScript#350]
### 问题描述

Not really an issue or bug report, but why is this updated pretty much every single day?  I'll be in my browser just chilling and a new tab will pop up saying that this has updated.  Happens almost every single day.  Anywho, I appreciate the work y'all put in this.  But it would be cool to find a way to make it so that a new tab doesn't open in my browser every time that it updates.

**Comment by XIU2** [comment]
Tampermonkey - Settings - Userscript Update - Don't ask me for simple script updates
