### ISSUE TITLE
[自动无缝翻页] 希望添加 申请支持 https://paipai.jd.com/auction-list 

### ISSUE THREAD

**Issue by bbevil** [XIU2/UserScript#351]
### 功能需求

申请支持 https://paipai.jd.com/auction-list 

### 预期目标

能购买京东7天无理由退货的网站，因为穷所以需要天天守着这个网站。万望大佬成全！

**Comment by XIU2** [comment]
京东淘宝等网站都是动态加载内容的，且有较强的反爬机制（该脚本本质上就是个爬虫，虽然只爬取下一页），因此均无法添加支持。
