### ISSUE TITLE
[Autopage] 希望简单适配下安卓“无限之书”浏览器！

### ISSUE THREAD

**Issue by KnIfER** [XIU2/UserScript#353]
### 问题描述

无限之书（见酷安话题）通过[webview-gm](https://github.com/wbayer/webview-gm)执行脚本，并没有隔离windows，GM_XXX 等方法也不挂在window对象上面，而是直接写在脚本内容之前。

所以，希望能简单适配下，将window.GM_openInTab 替换为 直接的 GM_openInTab ！不然，有些页面链接都点不了。。。

**Comment by XIU2** [comment]
不会考虑适配，因为这些脚本全都是我自写自用的，我用什么就适配什么。

如果只是简单的改一下部分油猴函数名，你自己就能替换，而该脚本本身也没什么更新的了，平时主要是更新外置翻页规则罢了。

**Comment by KnIfER** [comment]
nb
