### ISSUE TITLE
[Github 增强 - 高速下载] 希望与 "Github Material Icons Extension" 插件适配

### ISSUE THREAD

**Issue by HRxiaohu** [XIU2/UserScript#354]
### 功能需求

在与 [Github Material Icons Extension 插件](https://github.com/Claudiohbsantos/github-material-icons-extension) 一同使用时会出现如图的显示错误 ，希望能增加适配。
![image](https://github.com/XIU2/UserScript/assets/63327671/b98c5c39-8eac-4aa2-8625-1fe110201c70)

[插件仓库地址](https://github.com/Claudiohbsantos/github-material-icons-extension)
[插件 Chrome 商店地址](https://chrome.crxsoso.com/webstore/detail/material-icons-for-github/bggfcpfjbdkhfhfmkjpbhnkhnpjjeomc)

### 预期目标

插件显示正常

**Comment by XIU2** [comment]
我的置顶 Issues 写的很清楚：
**不接受 与其他脚本/扩展 `功能冲突` 的相关问题反馈** #146

**Comment by HRxiaohu** [comment]
@XIU2 那能否增加一个按钮，让用户选择是否开启单文件快速下载功能？
