### ISSUE TITLE
[Github 增强 - 高速下载] 添加单文件快速下载功能的关闭按钮

### ISSUE THREAD

**Issue by HRxiaohu** [XIU2/UserScript#355]
### 功能需求

希望可以增加一个按钮，让用户选择是否开启单文件快速下载功能。

### 预期目标

让用户选择是否开启单文件快速下载功能。

**Comment by XIU2** [comment]
已添加 [项目列表单文件快捷下载 (☁)] 开关选项，更新脚本即可。
