### ISSUE TITLE
[知乎美化] 顶栏字体显示不全

### ISSUE THREAD

**Issue by Alexius66** [XIU2/UserScript#357]
### 问题描述

当开启知乎美化后顶栏的消息和私信文字消失

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/73510996/1b5dc034-ed33-453b-97fb-95cc0d329405)
![image](https://github.com/XIU2/UserScript/assets/73510996/c1410cb0-3392-41db-8630-a1c8d3c46f74)

**Comment by XIU2** [comment]
不是消失，而是颜色变白了。

关闭 `知乎美化` 脚本后，首页就是这样了：
![01](https://github.com/XIU2/UserScript/assets/54703944/48258568-4d6d-4789-b9b5-452a6ff714a0)

因为 `知乎美化` 脚本会屏蔽这个首页活动大图广告，同时也会把顶部横栏的样式改回默认的：
![02](https://github.com/XIU2/UserScript/assets/54703944/21fb73b0-f976-4bb9-b94f-5834c8bfb5a0)

但是最近知乎给下面的文字加了个 `color: #FFFFFF !important;` 样式强制文字为白色从而导致的该问题。

我已经加了个样式来强制其显示为灰色（默认颜色），更新脚本即可。

**Comment by quarkquartet** [comment]
已经更新到最新的1.5.5版本，搜索框文字似乎依然是白色的，见图
<img width="1225" alt="image" src="https://github.com/XIU2/UserScript/assets/26316540/9a727efd-0630-4663-a256-b365846e7505">

Firefox 114.0.2 + tampermonkey。

**Comment by XIU2** [comment]
@quarkquartet 前几天更新修复了（你这个评论的邮件通知被归到垃圾邮件了。。。现在才看到
