### ISSUE TITLE
[知乎美化] 宽屏模式右键空白处有bug

### ISSUE THREAD

**Issue by freedomspiritJohn** [XIU2/UserScript#358]
### 问题描述

当我开启宽屏模式后，在空白处右击不仅没有右键菜单，而且还会回到网页顶端。希望可以修复这个bug。

### 附加截图

![GIF 2023-6-21 21-15-22](https://github.com/XIU2/UserScript/assets/129288685/fb502a5f-6803-4bf5-a5af-04863133dfaf)

**Comment by XIU2** [comment]
这不是 BUG，这是 `知乎增强` 的右键两侧空白处返回顶部的功能。

> 你这个评论的邮件通知被归到垃圾邮件了。。。现在才看到

**Comment by freedomspiritJohn** [comment]
> 这不是 BUG，这是 `知乎增强` 的右键两侧空白处返回顶部的功能。
> 
> > 你这个 Issues 的邮件通知莫名其妙被归到垃圾邮件了。。。现在才看到

不好意思，才发现是功能增强。解决了
