### ISSUE TITLE
[知乎增强] 希望添加 推荐页中屏蔽盐选回答 功能

### ISSUE THREAD

**Issue by longjieCh** [XIU2/UserScript#359]
### 功能需求

[知乎增强] 中添加 **推荐页中屏蔽盐选回答** 功能
1、当前 **知乎增强** 脚本中，只在`问题页、搜索页`屏蔽盐选。但目前知乎中，由于存在过多的广告营销回答，其搜索回答的功能渐渐已经无法起到搜索问题答案的作用。
2、目前网页端，经常会访问推荐页，可以查看往日的回答或者热点动态，但推荐页中经常会隐藏着很多 盐选回答。

希望能够在推荐页也能屏蔽此类 盐选回答。

### 预期目标

希望能够在**推荐页**也能屏蔽此类 盐选回答。

最后，谢谢作者的付出

**Comment by XIU2** [comment]
无法实现 https://greasyfork.org/zh-CN/scripts/419081 功能介绍中已经写了：

盐选回答屏蔽范围：问题页（对于首页、搜索页，因为点击展开后才会加载内容，因此无法在展开前判断该回答是否为盐选内容）
