### ISSUE TITLE
从昨夜 v2ex.com 再被墙了

### ISSUE THREAD

**Issue by locpriv** [XIU2/UserScript#36]
从昨夜 v2ex.com 再被墙了. 这次好像是 dns 污染了 https://twitter.com/NP_tokumei/status/1380925575859118080
被 DNS 污染 + SNI 阻断

**Comment by XIU2** [comment]
是啊，昨天晚上（十一点）我就注意到了，当时我还在 V2EX 发了帖子呢，虽然被隐藏了。。。

不过你这个问题和我这个项目有什么关系。

**Comment by locpriv** [comment]
对，为了我也用V2EX 增强脚本
