### ISSUE TITLE
[自动无缝翻页] 必应搜索页出现问题

### ISSUE THREAD

**Issue by hetintin** [XIU2/UserScript#360]
### 问题描述

在必应搜索结果出来后，点进搜索结果页等待10秒左右（或者直接在其他新窗口页面等待10秒钟），返回原必应搜索结果页面（原搜索结果页面并没关闭的情况下），经常出现自动回到顶部，每次都得重新找之前的结果之后的搜索结果，翻页多了后，使用体验极差！！！

**Comment by XIU2** [comment]
国内版还是国际版？

**Comment by XIU2** [comment]
我试了下可以复现，禁用脚本后也能复现。
这显然是 必应 自身的机制或 BUG，该问题我无法解决，你应该向 必应 反馈该问题。。。

**Comment by xxxqq55** [comment]
> 我试了下可以复现，禁用脚本后也能复现。
> 
> > 搜索任意内容后，滚动到网页底部，然后切换到其他标签页 10 秒左右，再去看必应标签页，就会发现回到顶部。
> 
> 这显然是 必应 自身的机制或 BUG，该问题我无法解决，你应该向 必应 反馈该问题。。。

我用edge打开bing现在无法翻页，但我试了其他chrome，没这个问题，我已近关闭了其他所以插件，排除是兼容问题了。能问下这是什么原因吗

**Comment by xxxqq55** [comment]
重新安装也试过了

**Comment by XIU2** [comment]
@xxxqq55 我在 Edge 上试了下，必应国内版和国际版都能正常翻页（Tampermonkey v5.1.1）。

你确定按照我说的改 Tampermonkey 扩展配置了么？
[#Tampermonkey v5.0.0 后脚本在 部分网站 无法正常运行？](https://github.com/XIU2/UserScript#tampermonkey-v500-%E5%90%8E%E8%84%9A%E6%9C%AC%E5%9C%A8-%E9%83%A8%E5%88%86%E7%BD%91%E7%AB%99-%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C)

**Comment by xxxqq55** [comment]
额我用的暴力猴，但我在chrome上没出现问题

**Comment by xxxqq55** [comment]
![屏幕截图 2024-09-08 154424](https://github.com/user-attachments/assets/6b13aceb-c134-4103-8624-8b968367c3a5)
以前能正常使用，但今天发现（也可能有一周了）无法翻页，我看了下控制台，弹了个错误

**Comment by xxxqq55** [comment]
这是不是介绍了说的要安装油猴改设置的原因？

> @xxxqq55 我在 Edge 上试了下，必应国内版和国际版都能正常翻页（Tampermonkey v5.1.1）。
> 
> 你确定按照我说的改 Tampermonkey 扩展配置了么？ [#Tampermonkey v5.0.0 后脚本在 部分网站 无法正常运行？](https://github.com/XIU2/UserScript#tampermonkey-v500-%E5%90%8E%E8%84%9A%E6%9C%AC%E5%9C%A8-%E9%83%A8%E5%88%86%E7%BD%91%E7%AB%99-%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C)

**Comment by XIU2** [comment]
@xxxqq55 我平时主用的是 Tampermonkey，所以我写的这些使用说明也是以 Tampermonkey 为准的。

不过我刚才在 Edge 上用 Violentmonkey 2.20.0 测试了下没有问题呀，必应可以正常翻页。

你这个报错就是因为必应的 CSP 安全策略阻止了脚本运行，但 Violentmonkey 是没有 CSP 设置的呀，毕竟 Tampermonkey 是为了适配 Manifest V3 才主动调整限制了自己。

**Comment by xxxqq55** [comment]
@XIU2 难道要重新安装edge试试？

**Comment by XIU2** [comment]
@xxxqq55 你先装个 Tampermonkey 试试吧，如果 Tampermonkey 也不行的话（记得装完后要按照我的说明修改 CSP 配置项），那可能问题就和这些油猴脚本管理器扩展没啥关联了。

**Comment by xxxqq55** [comment]
@XIU2 安完能用，但这是为啥呀，为啥就edge出问题，难道是更新了什么？

**Comment by XIU2** [comment]
@xxxqq55 那说明你那边 Edge 浏览器没有问题，脚本也没有问题。
脚本运行在你那边的 Violentmonkey 上会有问题，但运行在我这边的 Violentmonkey 又没问题。

> 而前面，我这边也确认了 Edge、Violentmonkey、脚本、规则 均没有问题，而你那边只有脚本运行在 Violentmonkey 中出现了问题，可能关键点是在 Violentmonkey 上，但同样的版本，Violentmonkey 在你那边 Chrome 和我这边 Edge 又都正常，所以这就是很奇怪了。。。

我也不清楚原因，你重新安装 Violentmonkey + 关闭其他所有**扩展、脚本**还也不行的话，可能就是毫无头绪的疑难杂症了？

**Comment by xxxqq55** [comment]
@XIU2  寄，我感觉是我按了个屏蔽csdn网站插件的问题，之前可能屏蔽的操作太快，被搞了，🛌🤓，谢谢你的帮忙

**Comment by xxxqq55** [comment]
@XIU2 操，不能忍了，怎么翻页在github上也出现这问题了，昨天还好好的，今天控制台就说--当前网页规则 "url" 有误，请检查！这到底是啥情况呀，我真的麻了

**Comment by XIU2** [comment]
https://greasyfork.org/zh-CN/scripts/419215-%E8%87%AA%E5%8A%A8%E6%97%A0%E7%BC%9D%E7%BF%BB%E9%A1%B5/discussions/263562

**Comment by xxxqq55** [comment]
@XIU2 看了下好像还是没啥解决办法，但我想到个问题，我能安装CSP Unblock这些扩展，来使用吗？会不会有其他问题？

**Comment by XIU2** [comment]
我不清楚，因为我这边测试是都没问题的。。。

Tampermonkey 5.1.1

**Comment by xxxqq55** [comment]
@XIU2 我看你说不清楚为什么，那我把弹出错误那段判读支持那段代码调试过程，录给你会有帮助吗

**Comment by XIU2** [comment]
我知道和该问题相关的代码是什么。

上面我发给你的链接里，我给另一个人解释的很清楚了，就是因为网站 CSP 策略阻止了脚本运行各翻页规则中的 `url` 子规则（该子规则是脚本用来匹配当前网页是否支持），而正常情况下，Tampermonkey 新版本按照我的要求设置后（旧版本默认就是这个不用改），Tampermonkey 就会默认移除网站的 CSP 限制了，但问题是你们那边似乎 Tampermonkey 没有正常工作去移除网站 CSP 限制，导致脚本无法正常运行。

而同样的设置，同样的 Tampermonkey 版本，我这边又一切正常。

这才是我觉得奇怪的地方，我这边不管是 Edge 还是 Chrome（准确说是 CentBrowser 第三方修改版）都正常，但上面链接里，只有在 Edge 上不行，也有和我一样用 CentBrowser 的也不行，因此我觉得和浏览器没太大关系，应该还是哪里出了问题，导致 Tampermonkey 工作异常。

但这种 Tampermonkey 问题我就无法解决了，你们可能需要去 Tampermonkey 官方项目里向作者反馈试试。

**Comment by YujiaCheng1996** [comment]
新版chrome无论什么脚本都可能报错，于是配合Header Editor插件加头：
for (const a in val) {
	if (val[a].name.toLowerCase() === 'content-security-policy' && (val[a].value === 'script-src-attr' || val[a].value === 'script-src-attr ')) {
		val[a].value = `script-src-attr 'unsafe-inline'`;
		break;
	}
}

**Comment by XIU2** [comment]
@YujiaCheng1996 正常来说 Tampermonkey 会移除 CSP 的，我这边也正常，但就是部分人出问题，搞不懂为啥无效。
