### ISSUE TITLE
[自动无缝翻页] 希望添加 scriptcat自动翻页 功能

### ISSUE THREAD

**Issue by laboriouslyx** [XIU2/UserScript#362]
### 功能需求

我想让你给  https://scriptcat.org/search?keyword=%E7%99%BE%E5%BA%A6%E7%BD%91%E7%9B%98  添加自动翻页

### 预期目标

就是和百度一样，自动翻页

**Comment by XIU2** [comment]
该网站以前有人提过，但我看这网站压根没几页，完全没有翻页价值，就懒得写，但既然你到这里提了，就顺手给你写了个算了。

复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

```
	"scriptcat": {
		"host": "scriptcat.org",
		"url": "/^\\/search/",
		"pager": {
			"nextL": "li[class$='-pagination-next']>a",
			"pageE": "ul[class$='-list-items']>div",
			"replaceE": "ul[class$='pagination']",
			"scrollD": 2000
		}
	}
```
