### ISSUE TITLE
进入知乎 系统监测到您的网络环境存在异常，为保证您的正常访问，请点击下方验证按钮进行验证。在您验证完成前，该提示将多次出现  开始验证

### ISSUE THREAD

**Issue by snomgq** [XIU2/UserScript#364]
### 问题描述

进入知乎
系统监测到您的网络环境存在异常，为保证您的正常访问，请点击下方验证按钮进行验证。在您验证完成前，该提示将多次出现

开始验证

能否把这个屏蔽，正常进入知乎

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/71303231/889b7c45-8505-49a5-93d2-3734c3643b24)

**Comment by XIU2** [comment]
不验证是无法进入知乎的，这是知乎认为你的网络有问题，或者你的行为可疑，自动触发的验证机制，无法屏蔽的，否则这么容易绕过去验证个寂寞。。。
