### ISSUE TITLE
[自动无缝翻页] 希望添加白名单功能

### ISSUE THREAD

**Issue by IMBAepsilon** [XIU2/UserScript#365]
### 功能需求

希望可以通过白名单选择支持哪些网站（我尝试直接修改脚本匹配网页，但是没成功，对于脚本@match的写法还是不太明白，匹配到了但是规则也没法更新就卡住了）

### 预期目标

希望在启用白名单匹配的时候，脚本仅在指定列表的网站生效
（大概做成可以和黑名单模式切换使用那样？）

**Comment by XIU2** [comment]
Tampermonkey 自己就能做到。

编辑脚本，左上角 `设置`，翻到下面找到并取消勾选 `原始匹配` ，然后自己添加 `用户匹配` 就行了。
