### ISSUE TITLE
[自动翻页] 希望添加mojeek.com 的翻页功能

### ISSUE THREAD

**Issue by tomobs** [XIU2/UserScript#367]
### 功能需求

https://www.mojeek.com

挺好用的,看了例子没学会,抱歉:(

### 预期目标

就是能翻页...

**Comment by XIU2** [comment]
复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

```
	"mojeek": {
		"host": "www.mojeek.com",
		"url": "/^\\/search/",
		"pager": {
			"nextL": "//div[@class='pagination']/ul/li/a[text()='Next']",
			"pageE": ".results-standard>li",
			"replaceE": ".pagination",
			"scrollD": 1000
		}
	}
```

建议在搜索设置里勾选 [Open in New Tab]（即搜索结果新标签页打开），来提高自动翻页后的使用体验。

**Comment by tomobs** [comment]
成, 谢谢啦 , 加个old.reddit的好吗, 已支持

**Comment by XIU2** [comment]
复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

``` json
	"old.reddit.com": {
		"host": "old.reddit.com",
		"url": "return(fun.lp()=='/'||(fun.indexOF('/r/')&&!fun.indexOF('/comments/'))||fun.indexOF(/^\\/new|top|rising|controversial\\//))",
		"blank": 3,
		"pager": {
			"nextL": ".next-button>a",
			"pageE": "#siteTable>*:not(.nav-buttons)",
			"replaceE": ".nav-buttons",
			"scrollD": 2000
		}
	}
```

翻页后加载的新内容中的一些按钮可能会失效，比如分享啥的。

**Comment by tomobs** [comment]
谢谢啦 太nb了! 本来我是用两个翻页脚本然后这个exclude那个include的, 这下我就能把那个删了🤪

**Comment by swathigrate** [comment]
> Copy and paste to script `自定义翻页规则`Default `{ }`Intermediate save (script menu inside the Tampermonkey extension icon in the upper right corner of the browser)
> 
> ```json
> 	"old.reddit.com": {
> 		"host": "old.reddit.com",
> 		"url": "return(fun.lp()=='/'||(fun.indexOF('/r/')&&!fun.indexOF('/comments/'))||fun.indexOF(/^\\/new|top|rising|controversial\\//))",
> 		"blank": 3,
> 		"pager": {
> 			"nextL": ".next-button>a",
> 			"pageE": "#siteTable>*:not(.nav-buttons)",
> 			"replaceE": ".nav-buttons",
> 			"scrollD": 2000
> 		}
> 	}
> ```
> 
> Some buttons in the new content loaded after turning the page may be invalid, such as sharing.

Hello sir , is it work on  [reddit](https://www.reddit.com/) .. 
Actually reddit showing next button at  bottom of the page.. if it is possible just fix it.... Thank you
