### ISSUE TITLE
[知乎美化] 暗黑模式个人资料页输入框全黑色

### ISSUE THREAD

**Issue by quarkquartet** [XIU2/UserScript#368]
### 问题描述

如图。
<img width="1062" alt="image" src="https://github.com/XIU2/UserScript/assets/26316540/f06e730f-ae04-4e4c-b33a-3eee8f660159">

这个是知乎个人资料编辑界面，可以看到输入框背景色和字体都是黑色的，导致看不见。

**Comment by XIU2** [comment]
已更新优化。

该问题其实是知乎自己的问题，我这个脚本一直在帮知乎补“漏洞”。。。
该脚本是启用了知乎自己的暗黑模式（夜间模式），并在此基础上调色、调对比度等让其看起来更舒服（仿照的 Github 配色）。

但知乎对自己的暗黑模式（夜间模式）一点都不上心，很多知乎的网页都没有适配，一些地方也会出现冲突的问题（比如你提的这个，你把该脚本关了就能发现这是知乎自己的样式冲突导致的）。
