### ISSUE TITLE
[自动无缝翻页] Google搜索结果翻页后图片显示不正常

### ISSUE THREAD

**Issue by monlite** [XIU2/UserScript#369]
### 问题描述
系统：macOS Monterey 12.6.8
Chrome： 114.0.5735.198
Tampermonkey：v4.19.0
自动无缝翻页：v6.5.4

复现步骤：使用Google搜索关键字“Apple”，第一页图片显示正常，自动翻页后，从第二页开始搜索结果中的图片全部不显示。

### 附加截图

![Xnip2023-07-29_13-07-15](https://github.com/XIU2/UserScript/assets/20237633/184ce4d7-47f9-4d31-922a-050e75c2787a)
似乎是图片源替换不正确导致的：
<img width="907" alt="image" src="https://github.com/XIU2/UserScript/assets/20237633/a8106267-79ba-4216-b939-7cef4fd25869">

**Comment by XIU2** [comment]
这种显然是网页加载完成后，谷歌才后续动态加载的图片，网页本身不包含这些图片 src 地址。
