### ISSUE TITLE
[知乎增强] 脚本链接错误

### ISSUE THREAD

**Issue by ztm0929** [XIU2/UserScript#370]
### 问题描述

大佬的知乎增强脚本链接是不是写错了？
注释在脚本原文里的是 https://greasyfork.org/scripts/4122051
实际可以安装的是 https://greasyfork.org/scripts/419081，
前者打开提示404，大佬看看是否需要在脚本原文里修改过来👀

### 附加截图

![CleanShot 2023-07-31 at 03 46 58@2x](https://github.com/XIU2/UserScript/assets/34964951/28c590a9-c1ff-43a9-ba9e-492dcb1045b5)

**Comment by XIU2** [comment]
不是写错，只是后来我删了重发了，导致后面 ID 变了。
而且这个只是命名空间，所以没啥影响，也不能改，改了的话，以前安装的人就没办法自动更新脚本了。
