### ISSUE TITLE
[知乎增强] 屏蔽盐选 功能失效

### ISSUE THREAD

**Issue by 2128588541222** [XIU2/UserScript#371]
### 问题描述

进入知乎之后，油猴脚本显示已启用，但是再首页timeline上仍然可以刷到盐选文章。
环境火狐浏览器115.0.3 (64 位)

**Comment by XIU2** [comment]
就真的没人看我写的功能说明吗？

> 盐选回答屏蔽范围：问题页（对于首页、搜索页，因为点击展开后才会加载内容，因此无法在展开前判断该回答是否为盐选内容）
