### ISSUE TITLE
[知乎美化] 专栏排版错误

### ISSUE THREAD

**Issue by Dead-Universe** [XIU2/UserScript#373]
### 问题描述

知乎美化和知乎增强一起用的，专栏文章下方的工具栏在没有滚动前排版错误。
运行环境：Edge浏览器【版本 115.0.1901.188 (正式版本) (64 位)】，Tampermonkey【v4.19.0】
截图文章地址：https://zhuanlan.zhihu.com/p/637179187

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/60636914/e754759d-0a11-452e-b132-cefe7f1b5f6a)
![image](https://github.com/XIU2/UserScript/assets/60636914/3d710e9b-41de-4314-89c0-1ce1fd0d0863)

**Comment by Dead-Universe** [comment]
补充：浏览器版本【版本 115.0.1901.188 (正式版本) (64 位)】，Tampermonkey【v4.19.0】

**Comment by XIU2** [comment]
这是知乎自身的 BUG，和我脚本无关。

你把脚本都关了（记得先关闭知乎美化脚本的暗黑模式功能），然后 F12 打开开发者工具，按下 F5 刷新后选中元素你看一下就知道了，只不过因为知乎官方的白色、黑色主题下，悬浮的工具条和网页背景颜色都是一样的（都是白色、黑色），所以看不出来该问题。
