### ISSUE TITLE
[知乎增强] 净化搜索热门功能有时失效

### ISSUE THREAD

**Issue by kidder2000** [XIU2/UserScript#377]
### 问题描述

在知乎的“https://www.zhihu.com/question/XXX”页面，仍然能看见搜索栏的热搜，在热榜(hot)和关注(follow)页没有这种情况

### 附加截图

![功能已开启](https://github.com/XIU2/UserScript/assets/95905216/1fe62b63-6c09-4812-ac15-6fe0c7db4a48)

![热搜还在](https://github.com/XIU2/UserScript/assets/95905216/6c16fd56-97b9-4f94-8158-85e80d7d319f)

**Comment by XIU2** [comment]
已更新修复，看了下是问题页的此处网页元素不一样导致的，不知道啥时候变得。。。
