### ISSUE TITLE
[Github 增强 - 高速下载] "添加git clone命令"功能失效

### ISSUE THREAD

**Issue by guoiaoang** [XIU2/UserScript#379]
### 问题描述

[Github 增强 - 高速下载](https://greasyfork.org/zh-CN/scripts/412245-github-增强-高速下载) 这个脚本，勾选 `添加git clone` 命令后，界面显示包含 `git clone` 字符串，但点击后面的复制按钮时却不包含，希望可以统一一下。

Microsoft Edge：版本 115.0.1901.188 (正式版本) (64 位)
[篡改猴](https://microsoftedge.microsoft.com/addons/detail/iikmkjmpaadaobahmlepeloendndfphd) : 版本4.19.0
[Github 增强 - 高速下载](https://greasyfork.org/zh-CN/scripts/412245-github-增强-高速下载)  : 版本2.4.2

**Comment by XIU2** [comment]
已更新修复。

该问题其中只局限于第一个默认的( `github.com` )复制按钮，只改了前面输入框内的值，忘记改后面复制按钮的值了，不过后续脚本添加的加速源则都是统一的。
