### ISSUE TITLE
[Github 增强-高速下载]脚本无法使用

### ISSUE THREAD

**Issue by dyxang** [XIU2/UserScript#38]
如题，没有显示下载按钮了
最新版

**Comment by XIU2** [comment]
请提供更多信息，我这边使用一切正常。

你用的是什么浏览器？用的是 Tampermonkey 脚本管理器扩展吗？都是什么版本？
是最近突然不能用了，还是一直都不能用？

请尝试重新安装脚本（完全卸载，再去安装，新版本 Tampermonkey 有个脚本回收站，记得卸载干净）。
如果有必要可以提供远程协助来排查问题。

**Comment by dyxang** [comment]
> 请提供更多信息，我这边使用一切正常。
> 
> **是最近突然不能用了，还是一直都不能用？**
> 
> > 一般来说，无论是程序还是脚本都不会无缘无故的失效，出现问题说明是某些因素产生了变动导致的，不过很显然 Github 网页没有变动（否则所有人都会无法使用了），而脚本上次更新都是一个月前了，自然也不会是脚本更新导致的最近失效。
> 
> **你用的是什么浏览器？用的是 Tampermonkey 脚本管理器扩展吗？都是什么版本？**
> 
> 请尝试**重新安装脚本**（完全卸载，再去安装，新版本 Tampermonkey 有个脚本回收站，记得卸载干净）。
> 如果有必要可以提供**远程协助**来排查问题。

整理半天又是控制台又是清空缓存啥的，结果发现是我的插件没启用……问题解决
![image](https://user-images.githubusercontent.com/36600710/117092182-1db18080-ad90-11eb-8e88-b1c7cfb1e9c3.png)
但是没启用插件又显示“×已启用”我还以为是出啥问题了
