### ISSUE TITLE
申请支持https://bbs.saraba1st.com/，贴内无法翻页，帖子目录正常

### ISSUE THREAD

**Issue by Waldenmuxi** [XIU2/UserScript#381]
### 问题描述

申请支持https://bbs.saraba1st.com/，贴内无法翻页，帖子目录正常

**Comment by XIU2** [comment]
测试帖子内正常可以翻页。

请注意打开脚本菜单里（右上角 Tampermonkey 图标内）的 `帖子内自动翻页 (社区类网站)` 选项
