### ISSUE TITLE
[自动无缝翻页] 自动翻页功能无法被uBlacklist过滤

### ISSUE THREAD

**Issue by KIL011** [XIU2/UserScript#383]
### 问题描述

开发者您好：
在chrome浏览器中同时使用自动无缝翻页（篡改猴）与uBlastlist时，谷歌搜索的第一页可以被uBlastlist过滤，但从第二页开始过滤失效。

**Comment by XIU2** [comment]
#146 
很正常，因为网页自身并不支持 自动无缝翻页脚本 这样的动态加载下一页内容，因此你说的这些脚本或扩展压根就没有考虑在网页动态加载内容时进行过滤，因此才会失效，这种情况你找我没用，因为这种情况只能对方兼容我，而我做不到兼容对方。

当然，这种功能本质上的冲突，对方一般也不会管，就像我也不会管一样（ #146
