### ISSUE TITLE
[Github 增强] 样式出现问题

### ISSUE THREAD

**Issue by xbcen** [XIU2/UserScript#384]
### 问题描述

https://github.com/作者/项目/blob/main/文件
最近github在这种链接搞了Code 55% faster with GitHub Copilot的东西，与插件下载位置冲突

### 附加截图

![屏幕截图 2023-09-01 220221](https://github.com/XIU2/UserScript/assets/138562024/999f463a-7a52-4c55-89ad-196d6bd871f7)

**Comment by XIU2** [comment]
我咋没有看到，你给个 URL 示例我看看。

另外，如果只是文字的话，则无所谓，没啥影响，因为要解决的话显然是弊大于利的。

**Comment by xbcen** [comment]
https://github.com/XIU2/UserScript/blob/master/DuckDuckGo-Enhanced.user.js
![image](https://github.com/XIU2/UserScript/assets/138562024/4c8eddfe-7d2e-4846-bd54-a8ff4ebed0e2)

**Comment by XIU2** [comment]
我这边没有显示。
![01](https://github.com/XIU2/UserScript/assets/54703944/c01dd9da-ec5b-4331-a04d-e55add74fd74)

**Comment by Mishasama** [comment]
![image](https://github.com/XIU2/UserScript/assets/54498172/61e6bc44-9968-44a5-afe7-4e8cedfc1c92)
![image](https://github.com/XIU2/UserScript/assets/54498172/4f16bfb3-5b95-4fd5-9645-a5edefc7ff2b)
问题确认，没有显示估计是需要开启新版面的功能预览。

1. 如果不嫌麻烦要多点一下鼠标，甚至不兼容触摸屏的话可以考虑改成下拉菜单的样式。（这样比较美观和节省空间）
如果要实现完全兼容的话则可以根据网页窗口的尺寸和是否触控模式来判定具体要显示的样式。
2. 如果想维持目前的样式设计，可以考虑使用固定尺寸的框架，通过拖动操作来移动过长的选项。（这个能同时兼容鼠标和触摸的操作）

不过这么一来要多做不少工作呢……😅

**Comment by XIU2** [comment]
没有必要。

**Comment by xbcen** [comment]
Ok，谢谢
