### ISSUE TITLE
[自动无缝翻页] 自动翻页功能在安卓平板chrome浏览器失效

### ISSUE THREAD

**Issue by KIL011** [XIU2/UserScript#385]
### 问题描述

通过adguard（v4.0 nightly 38）在安卓12平板（联想小新pad12.6-国际版rom）中安装自动翻页功能。

在chrome浏览器（版本号116.0.5845.163，启用桌面版网站）中，进行谷歌搜索无法自动翻页。
注：在翻到页面最下方会显示少女正在祈祷中，然后消失，并不会自动翻页。

但在安卓13手机及PC段均正常使用。

### 附加截图

![Screenshot_20230903-130825](https://github.com/XIU2/UserScript/assets/67146465/2eba6b66-0a0a-47a1-8059-0b688a7a37b8)

**Comment by XIU2** [comment]
> "翻到页面最下方会显示少女正在祈祷中"

你用的不是我的脚本吧，这是另一个同类脚本显示的内容。

**Comment by KIL011** [comment]
把其他脚本卸载干净后，没有显示正在祈祷中了，但还是无法正常自动翻页

**Comment by KIL011** [comment]
![Uploading Screenshot_20230903-150927.png…]()

**Comment by KIL011** [comment]
![Screenshot_20230903-150927](https://github.com/XIU2/UserScript/assets/67146465/da63838b-8a0b-41cf-9296-c9f018d198e5)

**Comment by XIU2** [comment]
是只有谷歌不行还是都不行？

如果是只有谷歌不行，那么可能是这个环境下的谷歌网页有差异导致规则失效。
如果是全都不行，那可能的原因就很多了，关键是 adguard 我没用过（我记得是付费的），无法复现排查。

**Comment by KIL011** [comment]
貌似找到原因了：同样的设备（无论安卓手机还是安卓平板），只要开启桌面版网站，就会导致翻页功能失效。

**Comment by KIL011** [comment]
可能与网站无关，估计是浏览器自身的问题

**Comment by XIU2** [comment]
不清楚，因为我压根没有考虑兼容移动设备和 adguard 等自带的油猴脚本管理器。

我分享的所有脚本都是自用的，因此我用啥就兼容啥，而我只在电脑浏览器上用，且我只用 Tampermonkey 所以只兼容 Tampermonkey 油猴脚本管理器 + 支持该扩展的桌面浏览器，Violentmonkey 扩展也是因为其自身兼容 Tampermonkey 而因此也跟着兼容了。

所以我不会保证在其他油猴脚本管理器、浏览器上能用，也不考虑去兼容，因为兼容是最麻烦的事情，而我自己压根用不上，因此也没有动力和时间精力去搞兼容。

**Comment by KIL011** [comment]
好的了解，作者辛苦了
