### ISSUE TITLE
[知乎美化] 调整图片最大高度功能出现问题

### ISSUE THREAD

**Issue by pheotry** [XIU2/UserScript#386]
### 问题描述

只限制了高度，宽度没有变，导致图片被压扁。
图一打开限制高度。
图二正常状态

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/43376740/fd373db0-20de-4159-ab1e-98cf4171383f)
![image](https://github.com/XIU2/UserScript/assets/43376740/018bc9ed-e7d9-470e-991f-bdeaaa942085)

**Comment by XIU2** [comment]
已更新修复 因知乎更新导致的 [调整图片最大高度] 比例失常的问题
