### ISSUE TITLE
[知乎美化]调整图片最大高度 功能失效

### ISSUE THREAD

**Issue by xelnaga8080** [XIU2/UserScript#387]
### 问题描述

图片都被压扁了，将该功能关闭后恢复正常。

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/52519548/563b2012-d3cb-4506-af5b-291c521ab5a6)
![image](https://github.com/XIU2/UserScript/assets/52519548/faefd108-1f79-4db2-8906-e1f708e8a1ec)

**Comment by XIU2** [comment]
#386
