### ISSUE TITLE
[知乎增强] 希望添加移除底部【推荐阅读】功能

### ISSUE THREAD

**Issue by KIL011** [XIU2/UserScript#388]
### 功能需求

请问作者是否可以默认移除底部【推荐阅读】模块

### 预期目标

移除整个模块即可

**Comment by XIU2** [comment]
没看到，你发个 URL 地址 + 截图我看看。

不过，一般这种情况你直接用 广告屏蔽扩展 屏蔽掉就行了。

**Comment by KIL011** [comment]
例如，URL：https://zhuanlan.zhihu.com/p/644035305
![image](https://github.com/XIU2/UserScript/assets/67146465/38d70859-b737-45c8-b9a9-e2e1cc415196)

**Comment by XIU2** [comment]
看了下没有，排查了下发现是我的另一个 [知乎美化] 脚本已经屏蔽这玩意了。
![01](https://github.com/XIU2/UserScript/assets/54703944/3759ab48-c506-4fb5-bb3e-37c2478ad9c7)

**Comment by KIL011** [comment]
好的谢谢 我看下源码
