### ISSUE TITLE
老大，你好，油猴所有链接在新标签页打开的脚本，能不增加指定网站在当前页打开链接的功能

### ISSUE THREAD

**Issue by ednykissyou** [XIU2/UserScript#389]
### 功能需求

指定网站的页面链接在当前标签页打开。

### 预期目标

老大，你好，油猴所有链接在新标签页打开的脚本，能不增加指定网站在当前页打开链接的功能
我在下载外国一个英文站时，总是在新标签页打开链接，每次都要关闭两个页面，多了就有点烦，还易关错。
如果能在当前页打开链接就好了。
还有能够指定特定网站。

**Comment by XIU2** [comment]
脚本介绍页面开头写了：

> 注意！该脚本是当初给别人随手写的，后来发现各网站差异太大、太复杂了，难以通用化适配各网站，改来改去都不满意，因此目前该脚本处于停更阶段（懒得研究折腾了）。。。
