### ISSUE TITLE
[脚本名称] xxx 功能失效（记得修改该标题示例，并移除该括号提示）

### ISSUE THREAD

**Issue by pyatang** [XIU2/UserScript#392]
### 问题描述

google 翻页异常，如下所示

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/11601755/18433f7f-d020-4dec-87dc-9162cb491202)

**Comment by XIU2** [comment]
没有复现，但我发现 谷歌搜索 已经原生支持了和我脚本类似的无缝翻页功能，在搜索设置里叫做 `连续滚动` 应该是默认开启的。

你在谷歌搜索网页下，点击浏览器右上角 Tampermonkey 扩展的脚本菜单中的 `✅ 已启用 (点击对当前网站禁用)` 来对谷歌搜索网页单独禁用。

**Comment by pyatang** [comment]
ok

**Comment by leic4u** [comment]
这个连续滚动的按钮，对我好像不起作用，不管开还是关，我搜索页面都是显示页面，而且无法自动滚动。能把规则加回来吗，默认禁用，让像我这样连续滚动不工作的这类用户手动开启。

**Comment by XIU2** [comment]
@leic4u 我这边测试谷歌自带的自动翻页功能正常。

无法自动翻页的话，你能看到网页底部单独的 下一页 按钮吗？（不是以前带页码的那种）

如果你能看到，那么说明问题不在谷歌身上，而可能在于你浏览器某些配置有问题导致的。

**Comment by leic4u** [comment]
> @leic4u 我这边测试谷歌自带的自动翻页功能正常。
> 
> 无法自动翻页的话，你能看到网页底部单独的 下一页 按钮吗？（不是以前带页码的那种）
> 
> 如果你能看到，那么说明问题不在谷歌身上，而可能在于你浏览器某些配置有问题导致的。 建议排查浏览器扩展、脚本，尝试用无痕窗口或换个没装扩展的浏览器试试。

我打错别字啦。😂

> 不管开还是关，我搜索页面都是显示页面。

不管连续滚动的设置选项我开还是关，搜索页面上都是显示「页码」。不是查看更多结果。

而且我测试了下，我开无痕模式（不登录）时，开启连续滚动，是可以正常自动翻页的。
但在无痕模式中，用我自己的账号登录后，开启连续滚动，就无法自动翻页了，页面上显示的就只是页码了。

这说明是我账号的问题，跟浏览器、插件应该没关系。😂

**Comment by XIU2** [comment]
@leic4u 这种奇怪的疑难杂症，建议向谷歌反馈下，否则原生支持的效果自然会比我脚本支持的效果好。
不过在解决之前，你可以先用着原先的谷歌翻页规则，复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）：

```json
"谷歌搜索 - 手机版": {
	"host": "/^www\\.google\\./",
	"url": "return (fun.lp() == '/search' && !fun.indexOF('tbm=isch', 's') && (fun.indexOF('sclient=mobile', 's') || fun.isMobile()))",
	"pager": {
		"type": 2,
		"nextL": "a[aria-label='查看更多'], a[aria-label='See more' i]",
		"isHidden": true
	}
},
"谷歌搜索": {
	"host": "/^www\\.google\\./",
	"url": "return (fun.lp() == '/search' && !fun.indexOF('tbm=isch', 's'))",
	"history": true,
	"pager": {
		"nextL": "#pnnext",
		"pageE": "id('search')/div | //style[not(contains(text(), 'table,div,span,p{display:none}'))]",
		"replaceE": "#navcnt, #rcnt div[role='navigation']",
		"scrollD": 2500
	},
	"function": {
		"bF": "if (!fun.indexOF('tbm=nws', 's')){pageE.forEach(function (one) {fun.getAllCSS('a[aria-label][href*=\"https://www.youtube.com/watch?v=\"]').forEach(function (one1) {let img = fun.getCSS('img', one1); if (img) img.src = `https://i.ytimg.com/vi/${one1.href.split('?v=')[1]}/mqdefault.jpg`;})});};return pageE"
	}
}
```

**Comment by leic4u** [comment]
> @leic4u 这种奇怪的疑难杂症，建议向谷歌反馈下，毕竟原生支持的效果自然会比我脚本支持的效果好。
> 
> > 不过谷歌自带的这个功能明显比较保守，要翻到网页最底部才会开始加载下一页内容，有明显的割裂感。
> 
> 不过在解决之前，你可以先用着原先的谷歌翻页规则，复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）：
> 
> ```json
> "谷歌搜索 - 手机版": {
> 	"host": "/^www\\.google\\./",
> 	"url": "return (fun.lp() == '/search' && !fun.indexOF('tbm=isch', 's') && (fun.indexOF('sclient=mobile', 's') || fun.isMobile()))",
> 	"pager": {
> 		"type": 2,
> 		"nextL": "a[aria-label='查看更多'], a[aria-label='See more' i]",
> 		"isHidden": true
> 	}
> },
> "谷歌搜索": {
> 	"host": "/^www\\.google\\./",
> 	"url": "return (fun.lp() == '/search' && !fun.indexOF('tbm=isch', 's'))",
> 	"history": true,
> 	"pager": {
> 		"nextL": "#pnnext",
> 		"pageE": "id('search')/div | //style[not(contains(text(), 'table,div,span,p{display:none}'))]",
> 		"replaceE": "#navcnt, #rcnt div[role='navigation']",
> 		"scrollD": 2500
> 	},
> 	"function": {
> 		"bF": "if (!fun.indexOF('tbm=nws', 's')){pageE.forEach(function (one) {fun.getAllCSS('a[aria-label][href*=\"https://www.youtube.com/watch?v=\"]').forEach(function (one1) {let img = fun.getCSS('img', one1); if (img) img.src = `https://i.ytimg.com/vi/${one1.href.split('?v=')[1]}/mqdefault.jpg`;})});};return pageE"
> 	}
> }
> ```

好的，我稍后也向 Google 搜索反馈下我账号的这个问题。

再次感谢秀儿大佬！
