### ISSUE TITLE
[自动无缝翻页] 申请支持 theqoo.net

### ISSUE THREAD

**Issue by alphavvv** [XIU2/UserScript#395]
### 功能需求

theqoo.net是一个韩网论坛 对kpop或者其它内容感兴趣的人会看 它在帖子内部有个倒着展开的更多回复 看的时候很不方便 楼层多的话要倒着点好几次 希望打开的时候能直接展开全部回复 从第一楼开始
希望作者能够适配theqoo🙏

韩网三大论坛：theqoo & dcinside & pann

### 预期目标

例如此处有四百楼 为了看到一楼要点三次展开回复
![image](https://github.com/XIU2/UserScript/assets/83694637/a85e27a5-307a-423f-8ddd-3d2f5766308f)

**Comment by XIU2** [comment]
连续点击这个 加载更多 按钮没问题，但问题是点击 加载更多 时，该网站会在网页上面加载新内容，导致网页滚动条位置会变化，你还需要重新拉上去看 1 楼，该问题我没法解决。

该规则是把触发间隔调的很低，触发高度调的很高，这样在打开网页后滚动网页时，会直接一口气点击好几次 加载更多 按钮，但问题如上所说无法解决。
```
	"theqoo": {
		"host": "theqoo.net",
		"url": "/^\\/.+\\/\\d+$/",
		"pager": {
			"type": 2,
			"nextL": ".show_more:not([style='display: none;'])",
			"interval": 100,
			"scrollD": 9999
		}
	}
```
