### ISSUE TITLE
[知乎增强] 希望添加“用户回答搜索”功能

### ISSUE THREAD

**Issue by bilibiliworld** [XIU2/UserScript#396]
### 功能需求

就是希望实现https://www.zhihu.com/question/38420057/answer/2404955192
里所描述的情况
就是在某个用户的回答里进行搜索，虽然可以通过谷歌实现，但是感觉不太方便

### 预期目标

![v2-027c6f84a3eddacb23a025c597a15d26_r](https://github.com/XIU2/UserScript/assets/70128832/131245f2-b5cf-489f-a07b-c55b25754279)
类似这样

**Comment by XIU2** [comment]
这种不能通过简单读取、修改网页就能实现的功能是不考虑添加的，太麻烦了。
