### ISSUE TITLE
[Nodeseek增强]大佬有兴趣添加Nodeseek增强功能吗？

### ISSUE THREAD

**Issue by uxfion** [XIU2/UserScript#397]
### 功能需求

大佬有计划添加[Nodeseek](https://www.nodeseek.com/)的增强功能吗？

目前主流的服务器/技术方面的论坛有：

- [Hostloc](https://hostloc.com/)
- [V2EX](https://www.v2ex.com/)
- [Nodeseek](https://www.nodeseek.com/)

前两个大佬已经支持了，我自己也正在用，真的很好用，真心希望也对Nodeseek支持一下🤩

### 预期目标

![image](https://github.com/XIU2/UserScript/assets/44778029/ef2e7157-c638-4144-bcf6-775dbb113e00)

**Comment by XIU2** [comment]
目前本项目已经不再支持 新脚本请求 了。
因为我写的这些脚本全都是我自用的，我在使用某些网站的过程中产生了需求，于是自给自足解决需求而写了这些脚本，并顺便分享出来，所以写什么脚本、添加什么功能完全取决于我是否需要，我经常用的脚本也会更新频繁、及时维护。
