### ISSUE TITLE
[Github 增强 - 高速下载] 新增自建Raw加速源

### ISSUE THREAD

**Issue by PencilNavigator** [XIU2/UserScript#398]
### 功能需求

Workers反代了jsdelivr建的加速源。

https://cdn.54188.cf/
如访问IP不为中国和埃及，会自动302至cdn.jsdelivr.net

### 预期目标

使用方式同正常jsdelivr链接。
e.g.
链接：https://github.com/Atlas-OS/Atlas/releases/download/0.2.0/Atlas.Playbook.22H2.v0.2.apbx
其jsdelivr链接为：https://cdn.jsdelivr.net/atlas/0.2.0/Atlas.Playbook.22H2.v0.2.apbx
使用本反代为：https://cdn.54188.cf/atlas/0.2.0/Atlas.Playbook.22H2.v0.2.apbx

只用将cdn.jsdelivr.net替换为cdn.54188.cf即可。

**Comment by XIU2** [comment]
jsdelivr 还支持 releases ？ 这我倒是不知道。。
不过我试了下发现好像有点不对劲，你这个 URL 里只指定了 项目名 而没有指定用户名，似乎是固定指向这项目的，我尝试用我的项目文件，但都无法访问下载：

https://cdn.jsdelivr.net/CloudflareSpeedTest/v0.2.0/CloudflareST_darwin_amd64.zip
https://cdn.jsdelivr.net/XIU2/CloudflareSpeedTest/v0.2.0/CloudflareST_darwin_amd64.zip

你确定这种 URL 格式适用于所有 Gtihub 项目吗？还是说我使用姿势有问题？

**Comment by PencilNavigator** [comment]
你的使用姿势有问题。这个是我参与的一个项目，我和jsdelivr联系了后由他们提供的定制端点（custom endpoint）反代github release。并不是所有项目都支持。

举个例子：
下面的链接是我找jsdelivr定制的端点，上面的链接是github端点（也就是所有项目都可以使用的端点），可以看出明显区别。
https://cdn.jsdelivr.net/gh/Atlas-OS/Atlas@main/img/banner.png
https://cdn.jsdelivr.net/atlas/0.2.0/Atlas.Playbook.22H2.v0.2.apbx

而且标题也说了是raw，前面那个例子只是用来举例如何替换jsdelivr链接为我反代链接的。我这个链接反代的是JSD，所以jsdelivr能干的，这个就能干。

关于定制端点，理论上只要你项目满足一定条件就可以申请。CloudflareST我看了下应该是可以满足申请定制端点的要求的，你可以试试（还可以解决测速文件的问题）。

**Comment by XIU2** [comment]
就是因为你标题写着 Raw 但内容却是 releases 整的我很迷惑。。。
既然不适用于所有项目的 releases，那你举这个例子就不太恰当，容易让人迷惑误解。。。

****

对于 Raw 加速的话，我会把你提供的这个公益加速源加入备用节点，因为目前 Raw 加速源暂时够用，因此我把一些欧美地区的加速源都暂时注释掉当作备用了，主用亚洲的。

**Comment by PencilNavigator** [comment]
用了一些取巧的办法，在不动域名NS的情况下把这个链接指向了几个韩国Oracle节点（反代CF）。
用itdog.cn测了下延迟，还不错，感觉可以添加。
![图片](https://github.com/XIU2/UserScript/assets/85282140/9df3efc2-c0c6-4d29-9075-042f4838aca0)

**Comment by XIU2** [comment]
挺好，不过问题是。。。你这个域名解析的 4 个 IP 中，三个都被墙了。。。
```
129.154.204.25
132.145.89.240
146.56.146.131

158.180.95.52
```

**Comment by PencilNavigator** [comment]
@XIU2 原cdn.54188.cf 更为 jsdelivr-cdn.prpservice.990989.xyz，使用方法同jsdelivr。
TTL为86400s（一天）。

**Comment by XIU2** [comment]
我试了下，发现用这个会被 301 重定向到 `gcore.jsdelivr.net` 。。
而脚本加速源列表里已经有 `gcore.jsdelivr.net` 了（不过默认注释了，因为这个域名早就变成 Cloudflare CDN 了

**Comment by PencilNavigator** [comment]
> 我试了下，发现用这个会被 301 重定向到 `gcore.jsdelivr.net` 。。 而脚本加速源列表里已经有 `gcore.jsdelivr.net` 了（不过默认注释了，因为这个域名早就变成 Cloudflare CDN 了

Rules配置错了，已修复。敏感/不合规项目会301重定向至这个。

**Comment by XIU2** [comment]
我换了个浏览器测试（为了避免浏览器 301 缓存的干扰），还是会重定向到 `gcore.jsdelivr.net` 。。。
我测试用的文件都是该项目或 CFST 项目里的文件。

**Comment by PencilNavigator** [comment]
https://jsdelivr-cdn.prpservice.990989.xyz/gh/AdguardTeam/HostlistsRegistry@main/assets/filter_55.txt

现在应该好了

**Comment by XIU2** [comment]
OK，确实可以了，稍后会更新脚本的（目前正在顺手优化下 raw、release 的按钮样式）

**Comment by pencilnav** [comment]
@XIU2 因为项目命名更改，更换了下url
https://jsdelivr-cdn.pencilnavrp.990989.xyz/

用法同上，ttl仍为86400

有针对移动用户的HKG优选IP，电联无效(多数到SJC，少部分LAX)

**Comment by XIU2** [comment]
OK，已经更新了~
