### ISSUE TITLE
吾爱论坛自动翻页功能失效

### ISSUE THREAD

**Issue by Spider-DT** [XIU2/UserScript#4]
尝试了下脚本，发现翻页失效
浏览器是谷歌80内核

**Comment by XIU2** [comment]
经过测试，脚本自动翻页功能正常。
> 只要吾爱破解论坛没有大更新网页框架，就不会出现失效。

你用的是什么浏览器？用的是不是 Tampermonkey  这个脚本管理器扩展（我的脚本安装页面写了必须是这个）？

**Comment by Spider-DT** [comment]
百分浏览器， 油猴管理
[https://img04.sogoucdn.com/app/a/100520146/e48a67ed05bf864d732917d64b57b1f8](url)

**Comment by XIU2** [comment]
我用的也是百分浏览器（Cent Browser）。
你说的油猴管理是哪个？油猴是国内对脚本管理器的统称，并不是具体的某个脚本管理器。

我去测试了下导读，确实可以自动翻页。

**Comment by XIU2** [comment]
截图为证，导读列表中，每个标题后面都有 [参与] 二字，这是自动翻页到底部。
![1](https://user-images.githubusercontent.com/54703944/99241069-512b3d80-2838-11eb-81b6-fce23f59b1b2.png)

这是导读第一页。
![2](https://user-images.githubusercontent.com/54703944/99241170-73bd5680-2838-11eb-8c68-2d16a4478f3e.png)

**Comment by Spider-DT** [comment]
是我说的不清楚，当然是Tamper，我传个图给你看看，滑到底页没见到自动翻页啊，是我不会用？！！
![Snipaste_2020-11-16_18-13-35](https://user-images.githubusercontent.com/60735795/99241199-7f108200-2838-11eb-9887-ed42cb46635c.png)

**Comment by XIU2** [comment]
你这个网页的 URL 发给我看看。

**Comment by Spider-DT** [comment]
https://www.52pojie.cn/forum.php?mod=guide&view=newthread

**Comment by XIU2** [comment]
看了下，并没有添加这个页面的自动翻页支持。  
估计我当初忘了，当时只添加了导读的最新热门和最新精华。

等我几分钟更新。

**Comment by XIU2** [comment]
你去更新一下 v1.1.3 版本吧。
https://greasyfork.org/zh-CN/scripts/412680

**Comment by Spider-DT** [comment]
我看【最新发表】比较多，谢谢了
![timg](https://user-images.githubusercontent.com/60735795/99242061-ab78ce00-2839-11eb-8f8c-0ef512b04a5f.png)

**Comment by XIU2** [comment]
如果帮到你的话，点个 ⭐ 再走吧~

另外，如果没有问题的话，就关闭该 Issues 吧。

**Comment by Spider-DT** [comment]
加☆，好评
