### ISSUE TITLE
feature request: 知乎增强：屏蔽专栏的扫码登录提醒

### ISSUE THREAD

**Issue by ivysrono** [XIU2/UserScript#40]
![图片](https://user-images.githubusercontent.com/2649544/117317282-f48e0e80-aebb-11eb-88fe-18120bd14249.png)

专栏文章页面，未登录模式下会弹出。

**Comment by XIU2** [comment]
我在隐身模式下访问知乎专栏、文章页面，都没有弹出登录提示。

你是所有文章都会提示还是只有部分文章？

你用的是什么浏览器？用的是 Tampermonkey 脚本管理器吗？

**Comment by XIU2** [comment]
我详细测试了下，确实脚本正常工作。

在开启 [知乎增强] 脚本后，不会显示登录提示，关闭脚本并刷新后，就会显示登录提示。

**Comment by ivysrono** [comment]
抱歉，我的错误，刚测试的时候知乎增强被关闭了。
