### ISSUE TITLE
[Github 增强] 韩国加速源 https://ghproxy.com 需要改进

### ISSUE THREAD

**Issue by Innocence** [XIU2/UserScript#401]
### 问题描述

**https://ghproxy.com**   很慢，而只要变成    **https://gh-proxy.com**   速度就拉满

### 附加截图

下载同一个文件

![2023-10-30_225605](https://github.com/XIU2/UserScript/assets/1294867/2eee58b1-080a-4207-b43a-84fa47b6d517)
![2023-10-30_225622](https://github.com/XIU2/UserScript/assets/1294867/8dbd75af-aacc-4297-884c-7cafdcc67935)

**Comment by XIU2** [comment]
这不属于反馈问题，而是功能建议，即申请脚本添加你说的这个 `gh-proxy.com` 加速源。

**Comment by XIU2** [comment]
已更新脚本添加该加速源，感谢分享~

**Comment by Innocence** [comment]
> 这不属于反馈问题，而是功能建议，即申请脚本添加你说的这个 `gh-proxy.com` 加速源。
> 
> 这两个公益加速源其实用的都是免费的甲骨文 `Oracle` 服务器，不过前者是美日韩欧等地混合的（负载均衡），后者则只有韩国。因此可能是你的网络环境下韩国更友好一些。

哦，好的，原来如此。
