### ISSUE TITLE
[知乎增强]免登录功能失效

### ISSUE THREAD

**Issue by ztx5** [XIU2/UserScript#406]
### 问题描述

浏览器搜索知乎打开之后一直是登录界面

Google浏览器版本 119.0.6045.160（正式版本） （64 位）

油猴里面也不显示知乎增强插件

点进工具管理是打开状态

版本是2.2.13，重装了插件也不行。

请帮忙解决，谢谢。

**Comment by XIU2** [comment]
我只能解决脚本自身问题，对于其他的问题恕我无能为力。

另外，该脚本的 `移除登录弹窗（免登录）` 功能指的是：

- 在访问知乎问题、文章页时，如果你没有登陆，知乎会弹出的登录提示，脚本会移除登录弹窗。

> 注意：知乎首页必须登录后才能看（手机版 UA 可绕过，但油猴脚本无法改 UA），移除登录弹窗仅限于问题、文章页这种游客可以看的网页！
