### ISSUE TITLE
百度云网盘vip下载

### ISSUE THREAD

**Issue by linonly0** [XIU2/UserScript#408]
### 功能需求

希望增加百度云vip快速离线免下载app下载的脚本。此外，自动无缝翻页的脚本，在谷歌搜索界面，无法使用。
<img width="688" alt="google" src="https://github.com/XIU2/UserScript/assets/118331471/5adb4040-c4a9-460e-930b-5fd79c1bbaf0">

### 预期目标

之前是可以在谷歌搜索界面连接的，但是现在无法正常使用。此外，百度云vip下载破解，应该很多人都需要用到的，麻烦看下是否可以加该脚本，十分感谢

**Comment by XIU2** [comment]
现在已经不再接受新脚本申请了。

谷歌搜索前段时间开始，就自带无缝翻页功能了，因此我就去掉了规则。
如果你那边还是旧版的页码，那么请手动添加自定义翻页规则 #392

**Comment by linonly0** [comment]
好的，谢谢
