### ISSUE TITLE
[Github 增强] 添加快速下载链接功能失效

### ISSUE THREAD

**Issue by scattered-leaves** [XIU2/UserScript#411]
### 问题描述

今日github更新，下载板块有变，脚本无法正常添加链接

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/121725066/d93620ab-dbfc-4e2c-86b2-f26820b3be93)

**Comment by XIU2** [comment]
网页样式改变了么？但我这边看着还是旧的没变。

**Comment by scattered-leaves** [comment]
我这变了
________________________________
发件人: ***@***.*** ***@***.***> 代表 XIU2 ***@***.***>
发送时间: 2023年12月1日 22:48
收件人: XIU2/UserScript ***@***.***>
抄送: Scattered_leaves ***@***.***>; Author ***@***.***>
主题: Re: [XIU2/UserScript] [Github 增强] 添加快速下载链接功能失效 (Issue #411)


网页样式改变了么？但我这边看着还是旧的没变。

―

**Comment by XIU2** [comment]
查了下，这是 Github 提供的测试版特性 `Feature preview` 里面的 `New Repository Overview` 。

应该是你没注意提示不小心打开了。

因为只是测试版的特性，会经常改变，因此我不会第一时间更新脚本适配（工作量较大，而且需要同时兼顾当前的网页样式），建议你先点击网页右上角你的头像，点击 `Feature preview` 选择 `New Repository Overview` 点击右上角的 `Disable` 来关闭该测试版功能。

等该功能大范围测试，或者正式公测后，我会第一时间适配的。

**Comment by scattered-leaves** [comment]
额。。。是我开的，但直到昨天也没啥大变化，脚本也可以用，今天就不行了。。。。
________________________________
发件人: ***@***.*** ***@***.***> 代表 XIU2 ***@***.***>
发送时间: 2023年12月1日 23:13
收件人: XIU2/UserScript ***@***.***>
抄送: Scattered_leaves ***@***.***>; Author ***@***.***>
主题: Re: [XIU2/UserScript] [Github 增强] 添加快速下载链接功能失效 (Issue #411)


查了下，这是 Github 提供的测试版特性 Feature preview 里面的 New Repository Overview 。

应该是你没注意提示不小心打开了。

因为只是测试版的特性，会经常改变，因此我不会第一时间更新脚本适配（工作量较大，而且需要同时兼顾当前的网页样式），建议你先点击网页右上角你的头像，点击 Feature preview 选择 New Repository Overview 点击右上角的 Disable 来关闭该测试版功能。

等该功能大范围测试，或者正式公测后，我会第一时间适配的。

―
