### ISSUE TITLE
[自动无缝翻页]使用哔哩哔哩时会导致网页卡无响应 主页封面视频无法加载

### ISSUE THREAD

**Issue by HanXiMC** [XIU2/UserScript#412]
### 问题描述

当使用edge浏览器浏览哔哩哔哩网页时 开启自动翻页脚本后会时常出现网站卡死无响应 无法加载新视频 时评播放正常 但是无法在主页加载新视频 望作者抽空修复谢谢！

### 附加截图

![PixPin_2023-12-08_22-09-29](https://github.com/XIU2/UserScript/assets/109091020/b9eea801-8687-44d0-ac33-9f27999a6857)

**Comment by XIU2** [comment]
该脚本是压根不在 B 站首页运行的好吗？。。。

B 站只有搜索页是支持的，因此我只匹配了搜索页，其他页面的域名我都直接排除了。

```
// @exclude      https://t.bilibili.com/*
// @exclude      https://www.bilibili.com/*
// @exclude      https://live.bilibili.com/*
// @exclude      https://space.bilibili.com/*
// @exclude      https://manga.bilibili.com/*
// @exclude      https://member.bilibili.com/*
// @exclude      https://message.bilibili.com/*
```

你没看到截图里压根没有显示那一大串的脚本菜单么，只有当显示脚本菜单时，才代表脚本运行了。
