### ISSUE TITLE
[Github 增强 - 高速下载] Code 下载的镜像不显示了。

### ISSUE THREAD

**Issue by wgf4242** [XIU2/UserScript#413]
### 问题描述

![Snipaste_2023-12-12_11-00-50](https://github.com/XIU2/UserScript/assets/3336626/57931523-d3e6-420b-b210-4eb045f059cc)

正常红框的地方显示镜像。像下面这种竖着排列的。现在没有了。

![image](https://github.com/XIU2/UserScript/assets/3336626/98ccdddd-f43b-44da-b777-96dac2e7e7cf)

**Comment by XIU2** [comment]
#411

**Comment by jerryzcl** [comment]
![image](https://github.com/XIU2/UserScript/assets/53222092/87bed731-3f79-4a7c-a352-96f115d5da9d)
![image](https://github.com/XIU2/UserScript/assets/53222092/0e2ad3ab-9c91-411a-aa11-55c35485bec8)
关闭后依然无法显示

**Comment by XIU2** [comment]
@jerryzcl 你关的这个是 `New organization repositories view` 而不是 #411 提到的 `New Repository Overview`。
我看了下 `New Repository Overview` 已经实装为正式版了，稍后我会更新适配的，请耐心等待。

**Comment by treya-lin** [comment]
> @jerryzcl 你关的这个是 `New organization repositories view` 而不是 #411 提到的 `New Repository Overview`。 我看了下 `New Repository Overview` 已经实装为正式版了，稍后我会更新适配的（简单看了下改动较大，因此这方面代码需要完全重写了，可能需要一些时间）。

![image](https://github.com/XIU2/UserScript/assets/86940562/053ba756-8f9f-44bf-a6d8-89adec295dd1)

请问现在大家的界面都是这样完全不显示加速下载的地址了吗？

**Comment by XIU2** [comment]
@wgf4242 @jerryzcl @treya-lin @scattered-leaves 已更新适配新版界面。
