### ISSUE TITLE
[知乎美化] 适配 Greasemonkey

### ISSUE THREAD

**Issue by atbsi** [XIU2/UserScript#414]
### 问题描述

测试在 Greasemonkey 4.12 没有效果，请求适配。

**Comment by XIU2** [comment]
这些脚本都是我自用的，因此我用什么我就适配什么，我目前只用 Tampermonkey 因此也只会去适配这个。

> 因为 Violentmonkey 兼容 Tampermonkey，因此也适配了 Violentmonkey 。
