### ISSUE TITLE
[知乎增强] 希望添加屏蔽知乎首页/推荐页中，带图片的内容[文章/回答] 的功能

### ISSUE THREAD

**Issue by BrendaRansom0** [XIU2/UserScript#415]
### 功能需求

希望添加屏蔽首页/推荐页中，带图片的内容[文章/回答]的功能，让知乎的推荐保持只有纯文字内容。

### 预期目标

知乎在首页的推荐中，如果回答中带有图片，则会使得图片排版在推荐内容的左侧，同时这些内容往往多半都是广告。如果可以有一个功能，让推荐的内容在展开前，不显示图片，或者直接屏蔽推荐页中带图片的内容，就太好了。

**Comment by XIU2** [comment]
小众需求，不考虑添加该功能。

但你可以依靠 广告屏蔽扩展 来屏蔽信息流中的左侧图片.
把下面规则（选其中一个）加到广告屏蔽扩展的自定义规则中：

只屏蔽首页的：
```
zhihu.com##.Card.TopstoryItem.TopstoryItem-isRecommend .RichContent-cover
```

屏蔽所有页面的：
```
zhihu.com##.RichContent-cover
```
