### ISSUE TITLE
[Github 增强] 请求添加一个新的Raw文件加速

### ISSUE THREAD

**Issue by suixinex** [XIU2/UserScript#42]
```
https://raw.githubusercontents.com
```
>即在原地址“```https://raw.githubusercontent.com```”中加个“s”

**Comment by XIU2** [comment]
如果是 Cloudflare 的话，相比其他的 Raw 加速源而言，很没有竞争力呀。。。
那几个 Release 下载加速源其中有几个就是 Cloudflare，也支持 Raw 加速，但是我都没加到 Raw 加速源中，因为相比 [中国国内、中国香港、韩国首尔] 速度实在一般，用不上。

**Comment by suixinex** [comment]
> 如果是 Cloudflare 的话，相比其他的 Raw 加速源而言，很没有竞争力呀。。。
> 那几个 Release 下载加速源其中有几个就是 Cloudflare，也支持 Raw 加速，但是我都没加到 Raw 加速源中，因为相比 [中国国内、中国香港、韩国首尔] 速度实在一般，用不上。

地址来自网络，非本人创建，可以直接打开，打开后是Github首页，大概是镜像站吧
