### ISSUE TITLE
[Github 增强-高速下载] clone 面板的复制按钮丢失

### ISSUE THREAD

**Issue by Vixb1122** [XIU2/UserScript#421]
### 问题描述

1. 启用该脚本后会导致 clone 面板的复制按钮丢失。
2. 另外切换 clone 面板的 HTTPS、SSH、Github CLI 三个 tab 会偶先把 https 中的命令带到  Github CLI 中。

### 附加截图

![image](https://github.com/XIU2/UserScript/assets/17810492/42fc88de-71ed-43cb-ad4d-a1118da30be8)
![image](https://github.com/XIU2/UserScript/assets/17810492/0bd0f805-0228-4c99-801f-35f7f7bc00bc)

**Comment by XIU2** [comment]
1. 不是丢失，而是隐藏了
`因为现在插入按钮后并不会像以前一样直接就支持了点击复制，还需要手动添加点击事件，考虑到文字框本身点击后就能直接复制了，因此我懒得搞按钮点击事件了，就干脆直接隐藏起来算了`
2. 这个 BUG 是已知的
`只有在切换到 Github CLI 或者从这个切换到其他的才会触发 BUG，HTTPS 与 SSH 之间切换是没有问题的。不过我没有什么好方法来解决，但考虑到一般没多少人会点 Github CLI 所以也就不管了`

这两年 Github 的网页改了好多，而且大量改用了随机类名，导致我脚本适配非常困难费劲，一些影响不大的问题我就不再费劲研究如何解决了，目前这个脚本已经无法做到 Github 网页改版之前的那样完美了。。。

**Comment by XIU2** [comment]
考虑到可能还会有人提这两个问题，我还是把这个 Issues 保持打开状态吧，这样后来的人也能看到原因

**Comment by richex-cn** [comment]
我这点击输入框不能复制，好像不是 GitHub 官方支持的点击复制，代码好像也没有复制逻辑，目前好像只能点击后手动复制了。

**Comment by XIU2** [comment]
@richex-cn 看了下不知道为啥又没了，不过问题不大，我手动加上点击事件即可。

已更新脚本，修复 [Git Clone/SSH] 文字无法点击直接复制的问题
