### ISSUE TITLE
[蓝奏云网盘增强] 希望添加 查看文件上传时间的功能

### ISSUE THREAD

**Issue by MalikWilliams1greher** [XIU2/UserScript#425]
### 功能需求

现在蓝奏云更新之后 看不到上传日期了不好判断软件新旧程度

### 预期目标

希望能加一个上传时间

**Comment by XIU2** [comment]
我这边不管是后台，还是分享/下载页面都可以看到文件的上传地址。

**Comment by MalikWilliams1greher** [comment]
有没有一种可能时间只是在前端被隐藏了呢？

**Comment by XIU2** [comment]
前面我打错字了，不是上传地址而是上传时间，我这边可以正常看到，没有发现上传时间被隐藏的情况。

**Comment by MalikWilliams1greher** [comment]
> 前面我打错字了，不是上传地址而是上传时间，我这边可以正常看到，没有发现上传时间被隐藏的情况。

https://xinning-chuping.lanzouy.com/b0116s2ti  大佬你看这个链接 你那边能看到上传时间嘛 我这边看不到

**Comment by XIU2** [comment]
这种会员专用的分享链接页面，我以前没注意过有没有显示文件上传时间，我看了下网页中也没隐藏起来的时间信息，因此不管以前有没有现在肯定是彻底没有了，而且也无法靠脚本来恢复。

**Comment by MalikWilliams1greher** [comment]
好的吧 谢谢哥了
