### ISSUE TITLE
https://cdn.jsdelivr.ren/gh 加速源更换说明

### ISSUE THREAD

**Issue by 54ayao** [XIU2/UserScript#426]
### 问题描述

关于这个 //['https://cdn.jsdelivr.ren/gh', '其他 1', '[新加坡、香港、日本等]（CDN 不固定） - 该公益加速源由 [ayao] 提供&#10;&#10; - 缓存：有'], // 域名无解析 
换成了好久了 https://cdn.jsdelivr.us/gh   ren是国内腾讯云注册商，容易被hold  us是海外安全一点 所以停了ren 
jsd,cdn.zzko.cn 审核系统只审核 图片 判断违规了才会处理 先加速后审核一般情况下是被动通报 压缩包审核系统是不会知道是什么的

**Comment by XIU2** [comment]
OK，感谢提醒和公益分享，已经更新脚本啦~

**Comment by XIU2** [comment]
好像挂了。。。
```
cdn.jsdelivr.us 使用了不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
```

**Comment by 54ayao** [comment]
嗯嗯，晚点我看看

**Comment by 54ayao** [comment]
> 好像挂了。。。
> 
> ```
> cdn.jsdelivr.us 使用了不受支持的协议。
> ERR_SSL_VERSION_OR_CIPHER_MISMATCH
> ```

![image](https://github.com/user-attachments/assets/8991e00c-3636-4e8a-83c5-b2afa4b29da0)
辛苦再试试看

**Comment by XIU2** [comment]
不辛苦~
感谢修复分享！
