### ISSUE TITLE
[护眼模式] 希望模式3将滚动条设置成暗色

### ISSUE THREAD

**Issue by zetaloop** [XIU2/UserScript#427]
### 功能需求

模式3下，将网页滚动条设置为和网页颜色匹配的暗色风格。
如果不能和网页背景色一致的话，至少是暗色的。

目前是这样的：
![image](https://github.com/XIU2/UserScript/assets/36418285/908b77de-a110-4f63-a10a-a84a236d014b)

### 预期目标

希望是这样的：
![image](https://github.com/XIU2/UserScript/assets/36418285/789fd416-fec8-4236-8447-cb9133022d77)

**Comment by zetaloop** [comment]
`color-scheme: dark`：在改变滚动条的同时，会改变文字等的配色方案，导致文字看不清。
`scrollbar-color: dark`：目前 Edge 121 测试不支持直接设置成暗色风格，可能只有火狐能用。
应该只能手动设置滚动条颜色了

**Comment by XIU2** [comment]
我试了下，这个 `scrollbar-color` 兼容性太差，只有目前最新的 121 内核才勉强支持，所以干脆改成固定颜色样式的深色滚动条算了，正好我平时也自用一个深色的滚动条样式（配色取自 Github），就给加到脚本里了，你可以更新试试。
