### ISSUE TITLE
[V2ex 增强] 优化建议

### ISSUE THREAD

**Issue by BonjourYY** [XIU2/UserScript#43]
希望可以给V2EX的网站评论添加楼中楼的功能，以便可以更直观的展示回复。
参考插件：[V2EX Pro](https://greasyfork.org/zh-CN/scripts/397787-v2ex-pro)
但是这个插件有一个Bug，原作者没有修复。就是评论过多导致缩进的问题。
Bug展示：[原作者插件存在的Bug](https://greasyfork.org/zh-CN/scripts/397787-v2ex-pro/discussions/66660)

然后我这边找到一个其他的插件修复了这个Bug，插件名叫 [V2EXcellent.js](https://greasyfork.org/zh-CN/scripts/14182-v2excellent-js)
但是这个插件有些功能做的并没有V2EX Pro的好用，比如V2EX给评论设置了默认倒序展示。
所以希望作者可不可以结合这两款插件，做一个更好用的版本。

知道作者开发一个插件不容易，特别感谢作者为开源社区所贡献的力量。

**Comment by XIU2** [comment]
我知道 V2EXcellent 这个脚本，当初也有人跟我推荐过该脚本的楼中楼功能，但是我看了下感觉有点麻烦，就懒得折腾了。。。
