### ISSUE TITLE
[Github 增强] 提供一个raw cdn节点

### ISSUE THREAD

**Issue by XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxX0** [XIU2/UserScript#430]
### 功能需求

https://raw.cachefly.998111.xyz/XIU2/UserScript/master/README.md

https://[raw.githubusercontent.com/XIU2/UserScript/master/README.md](https://raw.githubusercontent.com/XIU2/UserScript/master/README.md)

反代raw的cachefly cdn节点，亚洲有日本 香港等节点，缓存时间：12小时。

### 预期目标

为公益项目尽点力，正常情况下会长期维护下去。

**Comment by XIU2** [comment]
感谢公益分享，已添加~

**Comment by XIU2** [comment]
额，`*.cachefly.998111.xyz` 证书到期 2 个月了好像。。。
