### ISSUE TITLE
[知乎增强] 希望添加移除搜索页右侧栏功能

### ISSUE THREAD

**Issue by mcthesw** [XIU2/UserScript#433]
### 功能需求

在知乎的搜索页（ https://www.zhihu.com/search?q=关键词 ）右侧有个“搜索发现”栏目，里面自动生成的搜索语句往往质量低下，没有什么帮助，希望能够增添移除这个栏目的选项

### 预期目标

移除红框所在区域的侧栏
![image](https://github.com/XIU2/UserScript/assets/61224072/a8eed7b0-9977-4bd1-994f-5ef71889d68a)

**Comment by XIU2** [comment]
另一个 [知乎美化] 脚本里有 `宽屏显示` 功能，就是用来因此侧栏的。

**Comment by mcthesw** [comment]
感谢
