### ISSUE TITLE
[自动无缝翻页] 开启脚本后煎蛋自带吐槽组件异常&BBS页面自动翻页功能失效

### ISSUE THREAD

**Issue by XDU-ZZ** [XIU2/UserScript#435]
### 问题描述

吐槽组件异常复现步骤
1.开启脚本，访问受影响的煎蛋页面（问答/树洞/无聊图/随手拍）
2.滚动网页至自动翻页出现的内容
3.点击帖子右下角吐槽标签，无反应
4.回到开头原网页应当显示的内容，点击帖子右下角吐槽标签，可正常出现

BBS页面自动翻页功能失效，进入BBS页面可见

**Comment by XIU2** [comment]
看了下是煎蛋网网页略有变动，导致规则无法完美适配引起的问题，已经更新修复了。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

另外，BBS 页面我记得之前（我当初写规则时，好几年前了）应该是没有的吧，刚才看了下 BBS 页面及帖子内都是动态加载的，无法添加支持，因此直接给排除了。
