### ISSUE TITLE
[蓝奏云网盘 增强]希望添加 导出用户文件列表文本 功能

### ISSUE THREAD

**Issue by zaregoto** [XIU2/UserScript#44]
[功能请求]蓝奏云网盘 增强: 希望作者能增加一个导出用户文件列表文本的功能

**Comment by XIU2** [comment]
你指的是后台里的文件列表信息？

**Comment by zaregoto** [comment]
好的，感谢作者！
之前查找相关信息时也有看到一些蓝奏云解析相关的有提到文件列表，不过自己不懂编程，就放弃去折腾了。然后想起之前在油猴有看到百度网盘-生成文件树的脚本，就想着蓝奏云也有相关脚本就好了。

**Comment by XIU2** [comment]
如果是导出当前文件夹的文件列表很简单，但是如果要导出整个网盘所有文件，并制作成文件树，那就挺麻烦的了。

**Comment by zaregoto** [comment]
是指像根目录这种一个文件夹里又包含有文件夹的要导出全部文件列表很麻烦吗？

**Comment by XIU2** [comment]
你要的这种，需要遍历网盘内所有文件夹和文件。
能做到，但是需要一些时间，我个人对着功能不感兴趣再加上我比较懒，所以不是很想费这劲。。。

**Comment by zaregoto** [comment]
好的，感谢作者！
