### ISSUE TITLE
[Github 增强-高速下载] 导致页面无法切换

### ISSUE THREAD

**Issue by nb5p** [XIU2/UserScript#442]
### 问题描述

脚本开启后，会导致 Github 的一种类型页面切换无法进行，问题已经持续一段时间了。具体表现为顶部进度条缓慢走，无法加载出来。测试地址：[other/Autopage](https://github.com/XIU2/UserScript/tree/master/other/Autopage) 点击左侧文件树中的任何文件，都是此现象，如果使用浏览器的刷新，是不会影响加载的。

Chrome 123.0.6312.106 (Official Build) (arm64)
Violentmonkey 2.18.0
Github 增强 - 高速下载 2.5.19

**Comment by XIU2** [comment]
无法复现，我这边按照你的复现步骤，点击左侧文件树的任何文件（比如其他各个油猴脚本文件），都可以快速加载，没有发现顶部进度条缓慢的问题。

另外，按理说脚本里的代码是不会影响网页加载速度的，因为脚本是在网页加载完成后才会执行。

**Comment by nb5p** [comment]
抱歉，没有仔细测试。经过二分法排除发现是与 Cubox 兼容性问题。我已知晓兼容性问题不会修复。
