### ISSUE TITLE
[Github 增强 - 高速下载] 希望增加对指定目录的下载

### ISSUE THREAD

**Issue by zhxxkeke** [XIU2/UserScript#448]
### 功能需求

把目录的图标也修改成云朵的图标，点击下载指定的目录文件

### 预期目标

我已经知道实现的逻辑了
大致就是 访问api https://api.github.com/repos/{owner}/{repo}/contents/{+path} 比如 https://api.github.com/repos/XIU2/UserScript/contents/other/Autopage 来实现用第三方库 jszip和FileSaver.js 来打包下载 代码太烂 递归调用 写不好 希望大佬添加上去 感谢

**Comment by XIU2** [comment]
这种方法几年前就有人提了，但缺陷很多，所以我不会考虑添加，除非 Github 自身支持直接下载目录了。
