### ISSUE TITLE
[知乎增强] 知乎新加了个限制 不登录状态下强行折叠长回答 且实际只加载开头一部分内容

### ISSUE THREAD

**Issue by SamulePope** [XIU2/UserScript#451]
### 问题描述

昨晚出现的问题。即使开着插件，在长回答与长知乎文章中仍重新出现了“展开阅读全文”的按钮，同时，由于登录弹窗已经被屏蔽，点击该按钮不会有任何反应。已经测试过不是与其他插件冲突，关掉其他插件问题仍然出现。

平台与版本:win10 , edge, tampermonkey v5.1.1, 知乎增强 2.3.1

### 附加截图

![屏幕截图 2024-05-23 084814](https://github.com/XIU2/UserScript/assets/59117120/1580743a-1846-4b64-9e71-f78232d7c907)

**Comment by XIU2** [comment]
经过测试无法复现你描述的问题。

**Comment by SamulePope** [comment]
谢谢解答。请问是否有办法解除该限制？

**Comment by XIU2** [comment]
我上面不是已经回答了吗？被折叠的长回答内容压根只加载了开头内容，网页中不存在剩余内容，这种情况下脚本是无法处理的。

**Comment by SamulePope** [comment]
好的，谢谢！

**Comment by be-engineer** [comment]
真的太恶心了，直接从搜索结果中屏蔽掉算了
