### ISSUE TITLE
知乎增强的已经用不了，官方更新增加必须登录才能查看全部回答，所以就算屏蔽的跳登录 还是看不了 哎 官方恶心人啊

### ISSUE THREAD

**Issue by sangxinbingkk** [XIU2/UserScript#453]
### 功能需求

知乎增强的已经用不了，官方更新增加必须登录才能查看全部回答，所以就算屏蔽的跳登录 还是看不了 哎 官方恶心人啊

### 预期目标

知乎增强的已经用不了，官方更新增加必须登录才能查看全部回答，所以就算屏蔽的跳登录 还是看不了 哎 官方恶心人啊

**Comment by XIU2** [comment]
#451

**Comment by minusmulticoloredper** [comment]
有一个办法可解，在手机浏览器上使用知乎app的UA访问，UA可以去知乎app抓，改UA可以用浏览器扩展或者使用支持修改UA的浏览器，电脑端的话暂时无解。
