### ISSUE TITLE
[自动无缝翻页] 支持Google搜索视频和新闻等的无缝翻页

### ISSUE THREAD

**Issue by fengfeifang** [XIU2/UserScript#454]
### 功能需求

无缝翻页在Google搜索的视频和新闻等部分不会生效，等于是搜的是视频的话，就需要拉到最下面然后手动翻页

### 预期目标

希望能够在搜索视频的时候和搜索网页一样，自动翻页

**Comment by XIU2** [comment]
已添加 谷歌搜索 的新闻、视频、图书 支持。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
