### ISSUE TITLE
[吾爱破解论坛 增强] 自动翻页功能出现乱码

### ISSUE THREAD

**Issue by holll** [XIU2/UserScript#455]
### 问题描述

第一页是正常显示，第二页开始所有中文字符都显示为��л����

### 附加截图

![乱码](https://cfimg.520131420.xyz/file/59a8006ba9d5817f9060c.png)

**Comment by XIU2** [comment]
我这边测试脚本翻页工作正常，没有乱码。

**Comment by holll** [comment]
![image](https://github.com/XIU2/UserScript/assets/36074987/061ff0ab-25b5-4673-897b-ff9e340a307e)
那看起来是一个在特殊情况下才会被触发的bug

**Comment by XIU2** [comment]
凡是乱码都属于编码不一致导致的问题，但是这论坛的编码好像没变，一直都是 GBK（基于 DZ 论坛系统的限制，一般也不会随便修改，否则兼容性问题够网站喝一壶的了），而脚本上次更新已经是一年前了。

你是在任意帖子内都会乱码吗？尝试禁用其他脚本、扩展后该问题还存在吗？

**Comment by XIU2** [comment]
另外 greasyfork 上的这个脚本的相关反馈，因为前几年有人恶意捣乱，天天差评举报骂人什么的（一开始我还会举报这些人，后来因为 greasyfork 注册门槛太低，就放弃了），搞得我很烦，就干脆给屏蔽了，所以平时压根看不到。

**Comment by holll** [comment]
尝试禁用了其他扩展程序，只保留该脚本，问题仍然存在。既然脚本和论坛都没更新，我怀疑问题出在浏览器上了，因为更新的只有浏览器。我看了下代码，是通过脚本自动点击页码来实现翻页的？

**Comment by XIU2** [comment]
另外，你可以尝试一下我的另一个 `自动无缝翻页` 脚本，这个脚本是专门负责无缝翻页的（也就是从我这几个早期增强类脚本中独立出来，并完善了下），看看是否工作正常，两者原理是意义的，不过 `自动无缝翻页` 脚本更完善一些，因为针对的是大量网站（而且还有很多通用规则的），所以也针对网站编码问题特殊处理过，你试一试看是否乱码（记得先禁用 吾爱增强脚本，避免翻页功能重复出错）。

**Comment by holll** [comment]
`自动无缝翻页`脚本能正常显示，那就这样吧，能用就行了

**Comment by XIU2** [comment]
没事，我可以把 `自动无缝翻页` 对于编码处理的部分改改，加到 `[吾爱破解论坛 增强]` 脚本内，稍后我会更新一下，你可以帮我测试一下。

**Comment by XIU2** [comment]
我更新该脚本了，你更新一下试试（记得测试之前先把 `自动无缝翻页` 脚本禁用了，免得闹乌龙）

**Comment by holll** [comment]
可以正常显示了
