### ISSUE TITLE
[V2EX 增强] 自动签到失败 

### ISSUE THREAD

**Issue by dnslin** [XIU2/UserScript#456]
### 问题描述

自动签到失败

**Comment by XIU2** [comment]
该脚本签到功能正常，我这边依靠已经连续签到 1118 天没断过了。

![01](https://github.com/XIU2/UserScript/assets/54703944/a01c1bdd-f978-4dd8-adec-19df90368e97)
![02](https://github.com/XIU2/UserScript/assets/54703944/240a6022-1fe6-41b1-8f17-7756bc0ba8d3)

**Comment by dnslin** [comment]
问题是不止我一个人出现了这个问题 ，我这边稳定每天复现 我怎么样能自己排查

**Comment by XIU2** [comment]
在首页也无法自动签到吗？

按理说，我这边依然能正常签到，说明签到接口是没有变化的，否则应该所有人都会失效。

****

是突然有一天开始无法签到了，还是从一开始就不行？
如果是某一天突然失效了，那么应该是你这段时间做了什么导致的。

应该是你那边某个因素干扰影响到脚本后台签到了，你用的什么浏览器？尝试关闭其他所有脚本、扩展后再试试能否签到。

**Comment by dnslin** [comment]
从某一天开始就再也没法签到了，chrome最新版本 就几个星期前出现的这种情况 尝试重新安装也没法还原，在首页也不行 提示 联系作者

**Comment by XIU2** [comment]
我用的 Chrome 不是最新版的，但是我在最新版内核的 Edge 上测试，脚本是工作正常的可以自动签到的，不过测试时顺便发现了一个小问题（修复 [自动签到] 功能在非 `www.v2ex.com` 域名下当天首次访问非首页时可能出现的问题）更新修复了，不过和你遇到的问题应该没啥关系。

你在 Edge 浏览器上试试看能否自动签到吧。

**Comment by dnslin** [comment]
感谢 我自己多测试下 我尝试禁用了一些插件 但是不起作用 我待会试试 edge 感谢作者

**Comment by rayae** [comment]
同样的问题

**Comment by XIU2** [comment]
对了，你们是否按照 [#Tampermonkey v5.0.0 后脚本在 部分网站 无法正常运行？](https://github.com/XIU2/UserScript#tampermonkey-v500-%E5%90%8E%E8%84%9A%E6%9C%AC%E5%9C%A8-%E9%83%A8%E5%88%86%E7%BD%91%E7%AB%99-%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C) 的说明修改过 Tampermonkey？

**Comment by rayae** [comment]
> 对了，你们是否按照 [#Tampermonkey v5.0.0 后脚本在 部分网站 无法正常运行？](https://github.com/XIU2/UserScript#tampermonkey-v500-%E5%90%8E%E8%84%9A%E6%9C%AC%E5%9C%A8-%E9%83%A8%E5%88%86%E7%BD%91%E7%AB%99-%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C) 的说明修改 Tampermonkey？
> 
> 因为近期，有很多反馈 某脚本、某功能，或者脚本在某个网站不能用的，排查后大都是因为没有按照我的说明修改 Tampermonkey 设置导致的（Tampermonkey 新版本为了 Manifest V3 的原因修改了一些重要的默认项，需要手动改回去）

是这么个配置，但是依然签到失败

**Comment by dnslin** [comment]
可能是节点的问题还是怎么样 它自己好了
