### ISSUE TITLE
[Github 增强] 希望添加 github artifacts 下载加速功能

### ISSUE THREAD

**Issue by liaoke01** [XIU2/UserScript#457]
### 功能需求

对于一些临时文件或者一些大文件需要通过artifacts下载,此功能非常有用

### 预期目标

希望支持

**Comment by XIU2** [comment]
这是什么？没用过。。。

脚本添加什么加速，不是我决定的，而是脚本里的那些加速源决定的，如果那些加速源不支持你说的这个东西的话，我是无法解决的。

**Comment by YujiaCheng1996** [comment]
github actions里面的生成产物，好像是要登录才能下载的，流式传输的，应该没有能代理的。

**Comment by liaoke01** [comment]
> 这是什么？没用过。。。
> 
> 脚本添加什么加速，不是我决定的，而是脚本里的那些加速源决定的，如果那些加速源不支持你说的这个东西的话，我是无法解决的。

就是github action中的构建文件,不知道加速源支不支持,目前好像没有能对此进行加速的源
