### ISSUE TITLE
[知乎增强] 希望添加直接点击用户名就能拉黑功能

### ISSUE THREAD

**Issue by jdAction** [XIU2/UserScript#458]
### 功能需求

点击拉黑按钮后，点击用户名即可直接拉黑， 现在是手动复制效率有点低，批量拉黑后点击保存。

### 预期目标

![image](https://github.com/XIU2/UserScript/assets/87454525/d12c32ca-fa9a-4f19-9ac0-70dc34204346)

**Comment by XIU2** [comment]
其实以前我在 用户信息悬浮框（鼠标指向用户头像时显示的）中添加的有 `屏蔽用户` 按钮，不过后来知乎大改动后都失效了，这个就一直搁置没去修复，既然你提了这个，那我就研究了一会尽量给修复了，你更新脚本试试吧。

**Comment by jdAction** [comment]
> 其实以前我在 用户信息悬浮框（鼠标指向用户头像时显示的）中添加的有 `屏蔽用户` 按钮，不过后来知乎大改动后都失效了，这个就一直搁置没去修复，既然你提了这个，那我就研究了一会尽量给修复了，你更新脚本试试吧。

可以根据属性名去匹配div 就不用每次做适配了,全局搞一下用户姓名的配置到配置文件里,以后它再改就直接改下配置文件重新就行,看看思路可以不?谢谢大佬了

**Comment by jdAction** [comment]
看到已经有功能了，谢谢大佬。
