### ISSUE TITLE
Tampermonkey v5.2.0以后safari浏览器失效

### ISSUE THREAD

**Issue by matesoul** [XIU2/UserScript#459]
### 问题描述

Tampermonkey v5.2.0以后safari浏览器功能似乎全部失效了，开发者模式也开了，请问还需要设置什么吗？

### 附加截图

<img width="454" alt="image" src="https://github.com/XIU2/UserScript/assets/33011406/2ac80cd6-36d5-4764-94d5-6c74e0e4becc">

**Comment by XIU2** [comment]
这你应该向 Tampermonkey 作者反馈询问。。。
