### ISSUE TITLE
护眼脚本优化建议

### ISSUE THREAD

**Issue by RoyRao2333** [XIU2/UserScript#46]
您好，请问护眼模式的模式三可以把背景色做得更黑一点吗？然后颜色的色差大一点，不然看起来不好分辨。
具体可以参照GitHub和dark reader的黑暗模式，谢谢！

**Comment by XIU2** [comment]
抱歉，最近一个星期没在线，今天上来一看堆积了一堆 Issues...

模式三依靠的是负片（反色）模式，多黑取决于网站背景颜色及负片（反色）百分比。

你可以找个网站，按下 F12 ，选择 Elements 中的 <html> 标签，在右侧找到如下图所示的 CSS 样式。
修改 80% 为合适的百分比（0~100），找到合适的百分比后，去修改脚本中第 105、106 行中的 80% 即可。

![01](https://user-images.githubusercontent.com/54703944/122199285-7d8d6200-cecc-11eb-969c-8a3a3ba0621c.png)

**Comment by XIU2** [comment]
提醒一下，前段时间脚本更新后，已经可以自定义当前模式数值了。
