### ISSUE TITLE
[自动无缝翻页] xenforo论坛 帖子页不启用

### ISSUE THREAD

**Issue by garyvalue** [XIU2/UserScript#460]
### 问题描述

例如
https://www.blackhatworld.com/seo/adepti-ads-conquering-the-affiliate-marketing-industry.1549661/
版块页是正常的，但是帖子页不启用
![9F$}_MX@_FVC}LI)6Q9T6XD](https://github.com/XIU2/UserScript/assets/38098459/a367db5a-868d-4094-b6b3-8a76dda76286)

**Comment by XIU2** [comment]
已更新，优化了 [XenForo 论坛] 通用规则匹配方式。
你更新一下脚本即可。

该问题是因为当初写这个论坛系统的通用规则时，我找了几个使用 XenForo 的论坛（包括官方论坛），看到他们的 URL 特征都一样，所以只按照了 URL 特征来匹配规则（区分是帖子列表还是帖子内、搜索页什么的），你说的这个论坛帖子内，因为 URL 不包含 `/threads/` 或 `/t/` 导致没匹配上，应该是网站自己改了默认的 URL 路径（改成了 `/seo/`），鉴于此，我就优化了下匹配方式，在没有匹配到 URL 特征时会额外匹配网页元素特征。
