### ISSUE TITLE
[自动无缝翻页] 申请添加支持 mybb 网站

### ISSUE THREAD

**Issue by garyvalue** [XIU2/UserScript#461]
### 申请添加支持的 网站名称

mybb

### 申请添加支持的 网页地址

https://community.mybb.com/
国外的论坛程序
开源地址
https://github.com/mybb/mybb

**Comment by XIU2** [comment]
如果你只要该网站添加支持的话，我可以随手给你写个规则。

但如果你要的是给 mybb 这个论坛程序写通用规则的话（即适配所有使用 mybb 的论坛），除官方论坛外，你还需要再**提供几个使用 mybb 程序的论坛地址**，用于对比、验证，才能写出通用规则。

**Comment by garyvalue** [comment]
Websites using MyBB
https://trends.builtwith.com/websitelist/MyBB
你看下这些是否可行

**Comment by XIU2** [comment]
已更新脚本，新增 [MyBB] 论坛系统支持(通用规则)，我随便找了 5 个论坛测试了下都没问题，你更新叫试试吧。
