### ISSUE TITLE
[自动无缝翻页] 最新版 6.6.15 safari bing 不稳定 只能翻两页而且还很慢！

### ISSUE THREAD

**Issue by Swqka** [XIU2/UserScript#463]
### 问题描述

自动翻页 最新版 6.6.15 safari bing 不稳定 只能翻两页而且还很慢！

**Comment by XIU2** [comment]
我测试 必应翻页正常，但我没有 safari 浏览器（及相关设备）。

我只能保证目前的必应翻页规则没问题，如果是 safari 浏览器的问题，或者你用的脚本管理器的问题，那我无法解决。

另外，`而且还很慢！` 这不属于脚本自身问题。

**Comment by XIU2** [comment]
问题解决了就好~ 👌
