### ISSUE TITLE
[Github 增强]https://download.yzuu.cf/，https://gh.h233.eu.org/链接失效

### ISSUE THREAD

**Issue by QiBowen2008** [XIU2/UserScript#465]
### 问题描述

第一个502错误，第二个ERR_EMPTY_RESPONSE，国内IP，山东电信

**Comment by XIU2** [comment]
第一个确实 502 了，我拍查了下，还有两个和这个同一个来源分享者的也都 502 了。。。
至于第二个，这个是我自建的，我测试能访问，如果你不能访问，可能是你当地运营商屏蔽了 `eu.org` 这个免费域名，也可能是因为我用的是 Cloudflare CDN（国内部分地区会干扰）。

前者我会联系分享者确认情况，稍后我会看情况更新。
