### ISSUE TITLE
[自动无缝翻页] 申请添加支持 forgejo next 网站

### ISSUE THREAD

**Issue by xtexChooser** [XIU2/UserScript#466]
### 申请添加支持的 网站名称

forgejo next

### 申请添加支持的 网页地址

https://next.forgejo.org/{explore,issues,pulls,releases,tags}
（只要把codeberg.org的改一下域名就好啦，毕竟都是运行的 forgejo
（也可以顺便把 git.exozy.me 加了，也也也是forgejo
（或者 git.projectsegfau.lt 和 git.envs.net 和 demo.gitea.com，这三个是gitea，前几年forgejo从gitea软分叉后面变成硬分叉，分叉之后改动不大，规则可以直接用。

**Comment by XIU2** [comment]
已更新，新增 [Forgejo/Gitea git 托管系统] 通用规则（如 codeberg、gitea 网站）。

你更新脚本即可，另外外置翻页规则里的 codeberg 规则我也删除了，你最好也更新下外置规则（因为我在写通用规则的时候，发现 codeberg 或者说这个系统好像更新了，explore 等页面的元素变了，所以旧 codeberg 规则在一些页面已经失效）。
