### ISSUE TITLE
[Github 增强] 脚本在 Safari 下无法使用

### ISSUE THREAD

**Issue by xiangsanliu** [XIU2/UserScript#47]
![2021-06-22T13:29:20](https://cdn.jsdelivr.net/gh/xiangsanliu/images@master/uPic/2021-06-22T13:29:20.png)

真心不想放弃safari呀😂

**Comment by XIU2** [comment]
我也想解决，但是我无法去解决，没有办法上手排查，问题出在哪里我都不知道。。。

**Comment by xiangsanliu** [comment]
emmm，那好吧。。。😂
非常感谢。

**Comment by XIU2** [comment]
我没有 MAC 设备，也没有 Safari 浏览器。。。

**Comment by xiangsanliu** [comment]
知乎增强也用不了，可能真的要转chrome/edge了。（泪目）

**Comment by XIU2** [comment]
F12 - Console 有没有脚本报错？

**Comment by xiangsanliu** [comment]
![2021-06-22T13:46:27](https://cdn.jsdelivr.net/gh/xiangsanliu/images@master/uPic/2021-06-22T13:46:27.png)

**Comment by xiangsanliu** [comment]
就看到这些

**Comment by XIU2** [comment]
你点一下那个 UserScript:0 看看具体是什么

**Comment by xiangsanliu** [comment]
![2021-06-22T13:50:45](https://cdn.jsdelivr.net/gh/xiangsanliu/images@master/uPic/2021-06-22T13:50:45.png)
好像也看不出啥

**Comment by xiangsanliu** [comment]
我把这个脚本禁用了，还是会有这个错误。
![2021-06-22T13:53:11](https://cdn.jsdelivr.net/gh/xiangsanliu/images@master/uPic/2021-06-22T13:53:11.png)

**Comment by XIU2** [comment]
和其他 Issues 情况一样，用不了却没有任何报错，这毫无头绪。。。

**Comment by xiangsanliu** [comment]
确实难搞，甚至准备放弃Safari。。。

**Comment by XIU2** [comment]
刚才有个热心人士让我远程协助看了下，发现 Safari 是可以正常运行 [Github 增强] 脚本的呀~

**Comment by xiangsanliu** [comment]
他的应该是beta版本吧，目前我用的是最新的release版本，还是用不了的。

![2021-08-13T14:11:52](https://cdn.jsdelivr.net/gh/xiangsanliu/images@master/uPic/2021-08-13T14:11:52.png)

另外，大佬如果有空想调试一下的话，我也可以提供远程。😂

**Comment by xiangsanliu** [comment]
![2021-08-13T15:00:50](https://cdn.jsdelivr.net/gh/xiangsanliu/images@master/uPic/2021-08-13T15:00:50.png)
补图

**Comment by XIU2** [comment]
OK 那远程看看吧，你装个：
https://www.todesk.com/download.html
记得给权限什么的。

**Comment by xiangsanliu** [comment]
OK，麻烦先给我邮箱发封邮件(xiangsanliu.temp@outlook.com)，我把设备代码给你。

**Comment by XIU2** [comment]
估计你只有升级系统（Safari）才能解决该问题了（但无法解决知乎脚本无法使用的问题）。。。
要么就放弃转用 Chrome 等浏览器~

**Comment by xiangsanliu** [comment]
是的，我最近在用edge了，无BUG，但是没有Safari丝滑。等正式的系统出来再看。
感谢大佬啦。

On Aug 13, 2021, at 15:41, XIU2 ***@***.******@***.***>> wrote:



估计你只有升级系统（Safari）才能解决该问题了（但无法解决知乎脚本无法使用的问题）。。。
要么就放弃转用 Chrome 等浏览器~

**Comment by XIU2** [comment]
OK，你等什么时间升级到 15.0 时再去测试下吧~
