### ISSUE TITLE
[知乎增强] 展开阅读全文功能失效，点击也不能展开

### ISSUE THREAD

**Issue by DbuyCN** [XIU2/UserScript#472]
### 问题描述

知乎网站，无法展开阅读全文，鼠标点击也不行啊。是不是网站升级了，功能失效。

### 附加截图

![image](https://github.com/user-attachments/assets/bbf78d06-32d8-47eb-bcd1-cc46e8390d1b)

**Comment by XIU2** [comment]
这**不属于脚本功能失效**，因为这是知乎前段时间**新增的限制**，脚本压根没有针对该限制的功能。

脚本有个类似的功能是 `移除登录弹窗`，该功能只是单纯的移除登录弹窗，也并没有失效，但现在已经没有意义了。

****

脚本介绍页开头就写了：

https://greasyfork.org/zh-CN/scripts/419081

> **注意！最近知乎对`未登录的游客`新增了限制，强制折叠回答，需要登录后才能展开查看，而且因为网页上实际只存在回答的开头一部分内容，因此无法通过强制展开来显示剩余内容，该问题没有什么简单的方法可以解决，至于切换到关怀版什么的虽然可以看到完整内容，但是操作不便而且关怀版网页样式过于别扭，最重要的是这种漏洞随时都可能补上。**

> **目前脚本的 `移除登录弹窗` 功能虽然工作正常，但已经没有意义了，因为该功能只是单纯的移除登录弹窗罢了，并`不能绕过登录限制`。**

**Comment by minusmulticoloredper** [comment]
有一个办法可解，在手机浏览器上使用知乎app的UA访问，需要的话自己去知乎App抓，电脑端的话暂时无解。

**Comment by minusmulticoloredper** [comment]
有一个办法可解，在手机浏览器上使用知乎app的UA访问，UA可以去知乎app抓，电脑端的话暂时无解。

**Comment by be-engineer** [comment]
各种限制越来越多了
