### ISSUE TITLE
[知乎美化] 希望添加 首页直达收藏 功能

### ISSUE THREAD

**Issue by baishui-official** [XIU2/UserScript#473]
### 功能需求

开启知乎美化脚本后首页右侧个人界面被隐藏了，现在想要看收藏需要先点进个人主页再点收藏。如果可以在首页加上一个直达收藏的入口就完美了~

### 预期目标

在首页顶栏添加收藏入口，或者首页右侧板块设置单独个性化开关？

**Comment by XIU2** [comment]
所以，为什么你不直接将 知乎收藏 页添加为浏览器 `书签` 呢？

https://www.zhihu.com/collections/mine
