### ISSUE TITLE
[自动无缝翻页] GitHub commit 页面第二页之后的内容不显示 ci 与签名情况

### ISSUE THREAD

**Issue by cscnk52** [XIU2/UserScript#474]
### 问题描述

GitHub commit 页面第二页及以后页面 ci 与签名显示失效，查看调试工具发现是该api地址返回相关情况，是否可以做出相关适配呢？
api 地址： https://github.com/XIU2/UserScript/commits/deferred_commit_data/main?original_branch=main

### 附加截图

![image](https://github.com/user-attachments/assets/e34a3b77-a62d-4a12-892e-ff40fbce762f)
![image](https://github.com/user-attachments/assets/2d9c379b-5924-41a8-83f5-694c99826c6d)

**Comment by XIU2** [comment]
这些东西都是后续网页动态加载后才会显示出来的（也就是你说的这个 API）。

如果只是单纯为了看到截图里 灰色遮罩动画 下实际内容的话，理论上可以改用翻页模式 6 来实现（即用 iframe 来加载下一页内容，动态内容都加载完成后，再提取出来插入到当前网页下），但可惜 **Github 禁止了通过 iframe 访问**。

> 而且就算 Github 没有禁止，这样插入的内容也只是元素本身，而没有相应的事件（比如左边的 `√ 4 / 4` 点击是能触发事件加载具体信息的，但翻页模式 6 这样插入后的这个元素点击是不会有反应的，除非 Github 是采用的事件委托方式才有可能）。

****

如果你指的是，让我解析 API，手动给每个 Commit 加上这些东西的话，那就别想了，我是不会干这种吃力不讨好的事情的，一般除了容易一些漫画类网站，其他动态加载内容网站，我宁愿不做也不会费劲逆向手动实现，**具体可见 #468 我写了一大段**。

****

今天我看一个仓库的 Commits 页面想要找到某条 Commit，但觉得手动翻页烦人，于是就又检查了下 Commits 页面，发现又变回静态加载内容的了（主体内容是静态的，个别比如你提的这个还是动态），于是顺手重新添加支持了（当然网页规则已经和以前不同了），并检查其他 Github 规则把失效的 搜索规则 也顺手修复了。

所以对于我来说，我添加 Commits 页面支持，只是为了方便寻找某条 Commit 时不需要手动翻页，对于你提到的问题，我自然是注意到了（毕竟我写规则都追求尽善尽美，甚至有时候还会为此加规则来屏蔽网站的广告），但就如上面所说，我发现无法简单解决该问题，而该问题又不是那么重要（我个人角度来讲），于是我就忽略了该问题更新了规则。

**Comment by XIU2** [comment]
当然，如果你看着这个 **灰色遮罩动画** 不顺眼的话，也可以直接把它屏蔽掉。

复制粘贴到脚本 `自定义翻页规则` 默认的 `{ }` 中间保存（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单）

```
    "Github - Commits": {
        "style": "[class*=LoadingSkeleton-sc-]",
        "inherits": true
    }
```

> 该规则是一个继承规则（inherits），会与同名规则合并（重复的子规则也会被覆盖，即自定义规则优先级最高），作用就是加了个自定义网页样式，即给网页添加了个 `[class*=LoadingSkeleton-sc-] {display: none !important;}` 样式（如果只是单纯屏蔽，某个元素，那么可以省略 `{display: none !important;}` 不写，脚本会自动加上）。

**Comment by cscnk52** [comment]
感谢感谢，很用心的回复。
