### ISSUE TITLE
[翻页] B站搜索页翻页异常

### ISSUE THREAD

**Issue by xxxqq55** [XIU2/UserScript#475]
### 问题描述

B站每页搜索有隐藏没显示的搜索。好像脚本并没有去管这个。导致最后内容应该会接近一半的被隐藏，

### 附加截图

这是正常显示的搜索
![屏幕截图 2024-09-10 102039](https://github.com/user-attachments/assets/25100446-d58e-4087-b045-76e51b0ce907)
标了颜色的这个搜索就没显示
![屏幕截图 2024-09-10 102118](https://github.com/user-attachments/assets/d70a0183-fbca-450d-a367-11f552d173a6)

**Comment by xxxqq55** [comment]
我把标了颜色的显示出来，来个对比
![屏幕截图 2024-09-10 102726](https://github.com/user-attachments/assets/3b655591-b788-4169-b8ad-e443627cdd71)

**Comment by XIU2** [comment]
你提的这个我早就注意到，并特殊处理了。

这是目前的 B 站搜索页规则：
```json
	"bilibili - 搜索页": {
		"host": "search.bilibili.com",
		"url": "fun.isUrlC(); return ((fun.lp() == '/all' || fun.lp() == '/video' || fun.lp() == '/pgc' || fun.lp() == '/article') && !fun.getCSS('ul.video-list') && !fun.getCSS('#article-list'))",
		"style": ".to_hide_md:not(.to_hide_xl) {display: initial !important;}",
		"history": true,
		"pager": {
			"type": 6,
			"nextL": "js; return fun.getNextEP('.vui_pagenation--btn-num.vui_button--active+button.vui_pagenation--btn-num','page=',/page=\\d+/)",
			"pageE": ".video-list-item,.media-list>div,.video-list>div",
			"replaceE": ".vui_pagenation--btns",
			"loadTime": 600,
			"scrollD": 3000
		}
	}
```

规则中有个 `"style": ".to_hide_md:not(.to_hide_xl) {display: initial !important;}",` 子规则，就是处理你说的这个问题的。
让 Class 含有 .to_hide_md 但又不含有 .to_hide_xl 的强行显示出来，同时含有这两个的则依旧不显示，因为同时含有的元素和下一页的重复了（下一页已经存在这几个结果了，不过顺序相比这个是打乱的）。

**Comment by xxxqq55** [comment]
![屏幕截图 2024-11-10 221419](https://github.com/user-attachments/assets/ad1a1f96-4355-43b9-bc36-ab221e82672c)
![屏幕截图 2024-11-10 221431](https://github.com/user-attachments/assets/8bc8fcf3-133c-44f4-9ec3-abefaf365c47)
@XIU2 这是啥情况，好像是一直重复的一个分页，我不是从第一页开始加载无缝的，从后面几页，3，4，开始的。这情况正常吗

**Comment by XIU2** [comment]
@xxxqq55 我看了下，B站搜索页有了一些小改动，我已经更新适配了，你 `更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

**Comment by xxxqq55** [comment]
> @xxxqq55* 我看了下，B站搜索页有了一些小改动，我已经更新适配了，你 `更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

能不能发我一份，我改过自定义，好像看不了新规则

**Comment by XIU2** [comment]
@xxxqq55 脚本外置翻页规则就在这个文件里啊：
https://github.com/XIU2/UserScript/blob/master/other/Autopage/rules.json

**Comment by xxxqq55** [comment]
@XIU2 B站搜索页面，加载出来的搜索结果，鼠标悬停时，B站自带的封面预览功能失效，这个能修复吗？

**Comment by XIU2** [comment]
@xxxqq55 我这边正常，鼠标悬停预览没有失效。

**Comment by xxxqq55** [comment]
这是我特意在chrome浏览器展示的，（我日常用edge）。悬停只有在第一页起作用，后面的搜索结果都失效了

https://github.com/user-attachments/assets/6f22c1b0-e95c-4189-878f-9cf153c1c220

**Comment by xxxqq55** [comment]
https://github.com/user-attachments/assets/eab37dd5-3568-4aea-b1e3-99249c495336    
@XIU2 不知道上个视频你能不能看见，传了个低码率的视频

**Comment by XIU2** [comment]
但我这边确实是正常的，第二页第三页都没问题。

**Comment by xxxqq55** [comment]
@XIU2 我好像发现规律了，加载的再多，只有第一页和最后一页的能预览

**Comment by xxxqq55** [comment]
就算关闭翻页后，看最后一页有预览，但只要打开翻页刷新后，刚刚的预览就会失效，只能预览后面新加载的信息
