### ISSUE TITLE
[自动无缝翻页] https://orionfeedback.org此网站失效 

### ISSUE THREAD

**Issue by Wei-Winter** [XIU2/UserScript#478]
### 问题描述

只出现页码，但是不能翻页。pc和手机我都试了只显示页码不会翻页，使用的暴力猴

**Comment by XIU2** [comment]
准确说这不能算失效，一开始支持后来因为什么原因不支持了才算失效，而该网站比较特殊，一开始就不支持，脚本误判以为是支持的，所以显示了页码。。。

起初添加 Flarum 论坛支持的时候，不管是官方论坛还是其他第三方使用该系统的论坛，列表页都是有个 `Load More` 按钮的，点击之后就会自动加载下一页内容，我找了好些个使用这个系统的论坛都是这种，我以为都一样，所以我写规则时只写了针对这种情况的规则，也没有做判断，所以导致这个网站脚本也显示了页码但实际并不支持的情况，你这个网站比较特殊，改成了带页码，需要手动翻页的。。。

这种特殊情况，我需要额外添加支持，稍后会更新的。

**Comment by XIU2** [comment]
已更新脚本。

- **新增** [Flarum 论坛] 通用规则对带页码的列表页的支持
