### ISSUE TITLE
[知乎增强] 希望能增加一个屏蔽视频功能

### ISSUE THREAD

**Issue by zxdposter** [XIU2/UserScript#48]
知乎 增强 希望能增加一个屏蔽视频功能

知乎的看视频体验太差了，质量也不行，上班的时候也不方便看，还不如屏蔽掉，希望能够增加一个。

**Comment by XIU2** [comment]
给你个我自用的规则吧：
```
www.zhihu.com##div.ZVideoItem.ContentItem:upward(2)
```

把这个规则加到任何**广告屏蔽扩展**的**自定义规则**列表中（静态规则）。

**Comment by zxdposter** [comment]
@XIU2 我用的是AD block Plus，是下面这样添加吗？我加了没有作用
![image](https://user-images.githubusercontent.com/13846260/123729357-6d5f8480-d8c7-11eb-84e2-303e2405b286.png)

**Comment by XIU2** [comment]
应该是这个，你访问首页信息流看看还有没有视频就知道了。
> 我平时用的是 uBlock Origin，对你这个不太熟。

**Comment by zxdposter** [comment]
adblock plus 规则是
```
zhihu.com#?#:-abp-has(> div > div.ZVideoItem.ContentItem)
```

**Comment by XIU2** [comment]
又有好几个人想要这个功能，刚好和我要做的另一个功能有一定重叠，我还是给加上吧~

v1.6.7 **新增** [屏蔽指定类别（视频/文章等）] 功能~

希望不会对迟来的更新感到失望~
特此通知~

**Comment by zxdposter** [comment]
@XIU2 adblock 我试过体验不是很好，要等好几秒才能屏蔽，从您这里屏蔽可能更方便快捷

**Comment by XIU2** [comment]
@zxdposter 我用的 uBlock Origin 去屏蔽视频信息流的话，没有你说的情况，看都看不到，就像完全不存在一样。
不过现在脚本已经有这个功能了，我就改用脚本这个了。
