### ISSUE TITLE
[自动无缝翻页] 申请添加支持https://gwas.mrcieu.ac.uk/ 网站

### ISSUE THREAD

**Issue by cathy-nx** [XIU2/UserScript#481]
### 申请添加支持的 网站名称

open gwas

### 申请添加支持的 网页地址

首页：https://gwas.mrcieu.ac.uk/
搜索页：https://gwas.mrcieu.ac.uk/datasets/?trait__icontains=blood
搜索页：https://gwas.mrcieu.ac.uk/datasets/?gwas_id__icontains=met-b

**Comment by XIU2** [comment]
已添加支持（搜索页）。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单
