### ISSUE TITLE
[Github 增强 - 高速下载] 360极速浏览器X64，插件删除无效

### ISSUE THREAD

**Issue by zhuyongzhe** [XIU2/UserScript#483]
### 问题描述

[Github 增强 - 高速下载] 360极速浏览器X64，插件安装后删除无效，油猴完成删除操作，但页面还有悬浮图标，等待解决！

**Comment by XIU2** [comment]
#482 

请勿重复发 Issues。

另外，`Github 增强 - 高速下载` 没有 `悬浮图标` 之类的功能。
