### ISSUE TITLE
[自动无缝翻页脚本] 豆瓣小组讨论翻页之后页面内容显示有瑕疵

### ISSUE THREAD

**Issue by windtoostrong** [XIU2/UserScript#484]
### 问题描述

自动无缝翻页脚本在豆瓣上使用时遇到一个动态图片加载的问题
例子：https://www.douban.com/group/topic/290122944 搜索 2024-07-25 00:32:51 的回帖内容（在网页端第二页）
预期行为与手动翻页或手动直接打开https://www.douban.com/group/topic/290122944/?start=100 时一致，显示内容是动图
实际上使用脚本自动翻页时，页面在该位置只有一张静态图片，不确定是不是动态图片豆瓣有专门的js在渲染页面时处理了。感谢查看！

### 附加截图

静态图片：<img width="547" alt="image" src="https://github.com/user-attachments/assets/bb92c781-44e7-4227-a712-9f8ce9829c04">
动态图片：<img width="557" alt="image" src="https://github.com/user-attachments/assets/40da3490-9e81-4a75-9f0a-c1d231894c5a">

**Comment by XIU2** [comment]
这确实是由 JS 生成的，而且实际上不是 GIF 文件，反而是 MP4 视频文件（可能是网站存储时做了格式转换）。

网页初始内容下，此处确实只是一个 JPG 静态图片，然后网页 JS 会给这些图片加上 GIF 文字标识，并对该标识添加点击事件，点击后会创建一个 video 视频标签来代替该图片元素。

好在这个操作比较简单，视频文件地址其实就是图片地址的格式后缀换成 .mp4 罢了，因此只需要在脚本翻页后，对这种特殊的图片额外处理一下替换为视频即可。

****

已经更新优化 [豆瓣 - 小组/讨论区 - 帖子内] 规则支持显示 GIF 动图了。

`更新外置翻页规则` 即可（浏览器右上角 Tampermonkey 扩展图标内的脚本菜单

**Comment by windtoostrong** [comment]
感谢作者，测试了已解决！
