### ISSUE TITLE
[Github 增强] 安装了DevSidecar-1.8.9-node17，为什么会出现此插件

### ISSUE THREAD

**Issue by zhuyongzhe** [XIU2/UserScript#485]
### 问题描述

[Github 增强]

**刚安装完系统，没有安装油猴**

![没有安装油猴](https://github.com/user-attachments/assets/1d422f9e-8a59-4319-9fc2-0e146ff87d0c)

**360极速浏览器自带扩展程序，也没有安装**

![360极速浏览器自带扩展程序](https://github.com/user-attachments/assets/fc4a1570-8da2-4371-9968-8bb421c94ab7)

**安装了DevSidecar-1.8.9-node17，又自己出现，怎么回事？这个软件集成了你的插件吗？**

![安装完DevSidecar就出现](https://github.com/user-attachments/assets/17482a7c-4d96-4cf1-ba3d-8e8c2c449209)

**Comment by XIU2** [comment]
是，这个软件集成了我的脚本，这个软件介绍里写了呀。
