### ISSUE TITLE
[知乎美化] 希望添加调整图片最大高度增加自定义高度的选项 

### ISSUE THREAD

**Issue by qasd93991** [XIU2/UserScript#487]
### 功能需求

希望添加调整图片最大高度增加自定义高度的选项 ，默认的高度还是觉得图片太大，希望再小一些，最好可以自定义。

### 预期目标

如题

**Comment by XIU2** [comment]
https://greasyfork.org/zh-CN/scripts/412212-%E7%9F%A5%E4%B9%8E%E7%BE%8E%E5%8C%96/discussions/262866
