### ISSUE TITLE
[护眼模式] Safari下晚上自动切换功能可能失效

### ISSUE THREAD

**Issue by oxoxoxox** [XIU2/UserScript#489]
### 问题描述

isDaytime()函数的实现，在Safari下会因为new Date().getHours()在早上的时间段只返回一位数字，导致导致最终得到的time数字NaN。
Chrome下没有这个问题。

建议将第一行代码
```
let nowTime = new Date('2022-03-07 ' + new Date().getHours() + ':' + new Date().getMinutes() + ':00').getTime()/1000, time = GM_getValue('menu_customTime').split('|');
```

改为
```
let hours = new Date().getHours().toString().padStart(2, '0');
let minutes =  new Date().getMinutes().toString().padStart(2, '0');
let nowTime = new Date('2022-03-07 ' + hours + ':' + minutes + ':00').getTime()/1000, time = GM_getValue('menu_customTime').split('|');
```

这样可以同时兼容Safari和Chrome

**Comment by XIU2** [comment]
我这边没有 MAC/IOS 设备无法测试，不过我网上搜了下，看别人说的是因为 Safari 不支持 `2022-03-07` 这样的年月日格式。

只要改成 `2022/03/07` 或者标准的 `2022-03-07T00:00:00Z` 格式就能解决（这两种格式所有浏览器都支持）。

你把代码改成下面这样试试吧，如果没问题，我就更新脚本。
```
let nowTime = new Date('2022/03/07 ' + new Date().getHours() + ':' + new Date().getMinutes() + ':00').getTime()/1000, time = GM_getValue('menu_customTime').split('|');
time[0] = new Date('2022/03/07 ' + time[0] + ':00').getTime()/1000;
time[1] = new Date('2022/03/07 ' + time[1] + ':00').getTime()/1000;
```

**Comment by oxoxoxox** [comment]
> 我这边没有 MAC/IOS 设备无法测试，不过我网上搜了下，看别人说的是因为 Safari 不支持 `2022-03-07` 这样的年月日格式。
> 
> 只要改成 `2022/03/07 00:00:00` 或者标准的 `2022-03-07T00:00:00Z` 格式就能解决（这两种格式所有浏览器都支持）。
> 
> 你把代码改成下面这样试试吧，如果没问题，我就更新脚本。
> 
> ```js
> let nowTime = new Date('2022/03/07 ' + new Date().getHours() + ':' + new Date().getMinutes() + ':00').getTime()/1000, time = GM_getValue('menu_customTime').split('|');
> time[0] = new Date('2022/03/07 ' + time[0] + ':00').getTime()/1000;
> time[1] = new Date('2022/03/07 ' + time[1] + ':00').getTime()/1000;
> ```

这种修改方案也可以，实测Safari和Chrome也都能正常工作。

**Comment by XIU2** [comment]
OK，已更新修复了。
