### ISSUE TITLE
[Github 增强] 希望添加 净化搜索时广告号 功能 

### ISSUE THREAD

**Issue by chixiaome** [XIU2/UserScript#490]
### 功能需求

合并github搜索时净化返回内容，去除返回中cirosantilli等广告号仓库的功能
![image](https://github.com/user-attachments/assets/5abc1300-48a4-4fb2-bebd-a79a01e506f5)

### 预期目标

搜索结果中去掉他们
示例油猴项目https://github.com/BonjourFeng/Github-Search-Purification

**Comment by XIU2** [comment]
该脚本完整名字是 [Github 增强 - 高速下载]，因此属于单一功能的脚本，主要负责下载加速方向，不会考虑添加其他功能的。
