### ISSUE TITLE
[知乎 增强] 默认高清原图功能失效

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#491]
### 问题描述

win10 chrome版本 129.0.6668.71（正式版本） （64 位），油猴v5.3.2，脚本v2.3.11，右键图片另存为，非高清原图。右键新标签打开图片，才能下载高清原图。

**Comment by lyjhyjyes** [comment]
> 但是你右键图片新标签页打开，图片地址还是一样的啊。
> 
> 图片地址都是一样的，两者方式另存为的图片我这边看都一致，文件大小也完全一样。

随便打开 https://www.zhihu.com/question/568653324/answer/2875707912 chrome 129，油猴v5.3.2。脚本最新，连无痕模式只用油猴也试过，只打开油猴、油猴只开一个脚本。
再刷新话题网页，右键打开，有时候出现第一个链接。再刷新，右键打开，变成第二个。就是说，获取网页原图不稳定。
望改善
树莓派5 4H4G 英版 https://pica.zhimg.com/v2-40cbe60f695f77e74d11c401ee39add2.webp
树莓派5 4H4G 英版 https://pic1.zhimg.com/v2-8536c90b9f8431f63bf2e2b25e5f7439_r.jpg?source=2c26e567

**Comment by XIU2** [comment]
无法复现。

我的复现步骤：
1. 打开 https://www.zhihu.com/question/568653324/answer/2875707912 网页
2. 右键第一个/第二个图片新标签页打开
3. 刷新知乎网页，然后重复 2、3 步骤

第一个图片我连续重复 10 次步骤，只得到下面 3 个不同的地址（但文件实际都一样）。

https://pica.zhimg.com/v2-a3fe529d11ef45bf244ecd071ba4a926.webp
https://picx.zhimg.com/v2-a3fe529d11ef45bf244ecd071ba4a926.webp
https://pic1.zhimg.com/v2-a3fe529d11ef45bf244ecd071ba4a926.webp

第二个图片同理，我只遇到下面 2 个不同的地址。

https://pic1.zhimg.com/v2-40cbe60f695f77e74d11c401ee39add2.webp
https://picx.zhimg.com/v2-40cbe60f695f77e74d11c401ee39add2.webp

**Comment by lyjhyjyes** [comment]
> 无法复现。
> 
> 我的复现步骤：
> 
> 1. 打开 https://www.zhihu.com/question/568653324/answer/2875707912 网页
> 2. 右键第一个/第二个图片新标签页打开
> 3. 刷新知乎网页，然后重复 2、3 步骤
> 
> 第一个图片我连续重复 10 次步骤，只得到下面 3 个不同的地址（但文件实际都一样）。
> 
> https://pica.zhimg.com/v2-a3fe529d11ef45bf244ecd071ba4a926.webp https://picx.zhimg.com/v2-a3fe529d11ef45bf244ecd071ba4a926.webp https://pic1.zhimg.com/v2-a3fe529d11ef45bf244ecd071ba4a926.webp
> 
> 第二个图片同理，我只遇到下面 2 个不同的地址。
> 
> https://pic1.zhimg.com/v2-40cbe60f695f77e74d11c401ee39add2.webp https://picx.zhimg.com/v2-40cbe60f695f77e74d11c401ee39add2.webp
> 
> 另外，说明一下，该功能就一句代码（为方便你看我给加了换行）：
> 
> ```js
> document.querySelectorAll('img[data-original][data-original-token][data-lazy-status]:not([data-original-xiu]):not(.comment_sticker):not(.Avatar)').forEach(function(one){
>     one.src = 'https://' + one.dataset.original.split('/')[2] + '/' + one.dataset.originalToken + '.webp'; 
>     one.dataset.originalXiu = 'true';
> });
> ```
> 
> 脚本找到未处理过的图片后，会替换图片的 src 地址，而新的 src 地址（原图无水印）则是脚本拼接得来的。
> 
> 也就是 `https://` + 该图片的 `data-original` 属性值内的域名信息 + `/` + 该图片的 `data-original-token` 属性值内的路径信息（也就是 `v2-40cbe60f695f77e74d11c401ee39add2` 这玩意） + `.webp`
> 
> ```
> https://   pic1.zhimg.com   /   v2-40cbe60f695f77e74d11c401ee39add2   .webp
> ```
> 
> > 另外，就算知乎该图片的 `data-original` 和 `data-original-token` 属性值都莫名其妙错乱了，那么得到的也必然是一个 `.webp` 结尾的图片 src 地址（当然图片地址不正确的话会导致图片直接显示为加载失败，但图片元素的 src 是不会变的）
> 
> 而你得到的 `https://pic1.zhimg.com/v2-8536c90b9f8431f63bf2e2b25e5f7439_r.jpg?source=2c26e567` 显然是该图片的 `data-original` 属性完整值，然而只有在**今年 6 月 23 日 v2.3.2 版本之前**，脚本才是直接把图片的 src 地址替换为该图片的 `data-original` 属性完整值（当时该功能还未升级为 无水印原图），当时的代码为：
> 
> ```js
> document.querySelectorAll('img[data-original]:not(.comment_sticker):not(.Avatar)').forEach(function(one){
>     if (one.src != one.dataset.original) {
>         one.src = one.dataset.original
>     }
> });
> ```
> 
> 我不清楚你那边是怎么回事，为什么脚本代码会反复横跳？该功能的新旧代码是完全不同的，不可能存在互串的情况。
> 
> 所以就目前我测试分析得出的结果来看，大概率是你那边出现了什么问题，有什么因素导致了该问题，这不是一个普遍存在的脚本 BUG，目前没有除了你之外的人遇到该问题（包括我也无法复现）。
> 
> 你的问题，给我的感觉就好像你那边**同时安装了新旧版本**的 `知乎增强` 脚本，然后**新旧脚本同时运行**引起的问题一样（从代码角度来看，如果同时运行确实会导致该情况出现），我建议你好好排查一下。
> 
> 你可以换个浏览器，然后安装 Tampermonkey 扩展（如果已经有了就删除重装），然后只安装 Tampermonkey + 知乎增强脚本再试试。

document.querySelectorAll('img[data-original][data-original-token][data-lazy-status]:not([data-original-xiu]):not(.comment_sticker):not(.Avatar)').forEach(function(one){
    one.src = 'https://' + one.dataset.original.split('/')[2] + '/' + one.dataset.originalToken + '.webp'; 
    one.dataset.originalXiu = 'true';
});
修改了以上代码，一切正常了。不知道为什么没有更新代码

**Comment by XIU2** [comment]
感觉应该是你那边的脚本管理器什么的出现问题了？
我建议你直接重装脚本（彻底删除脚本，再去安装，注意 Tampermonkey 的回收站）。

你直接手动修改脚本代码内容的话，会影响脚本更新的。
