### ISSUE TITLE
[自动无缝翻页] 功能失效（记得修改该标题示例，并移除该括号提示）

### ISSUE THREAD

**Issue by FlootingDream** [XIU2/UserScript#498]
### 问题描述

失效网站：https://cn.bing.com/search

**Comment by XIU2** [comment]
[Tampermonkey v5.0.0 后脚本在 部分网站 无法正常运行？](https://github.com/XIU2/UserScript#tampermonkey-v500-%E5%90%8E%E8%84%9A%E6%9C%AC%E5%9C%A8-%E9%83%A8%E5%88%86%E7%BD%91%E7%AB%99-%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E8%BF%90%E8%A1%8C)

**Comment by XIU2** [comment]
如果你按照要求配置完 Tampermonkey 还是不行，那么你尝试更新脚本试试，因为刚才我把 [必应搜索] 的规则改到了脚本内置规则中，来尝试解决部分用户/浏览器因为 CSP 而无法使用的问题。
