### ISSUE TITLE
[知乎增强]建议增加一键拉黑功能

### ISSUE THREAD

**Issue by Lounode** [XIU2/UserScript#50]
如题，希望能在个人信息旁边增加一个屏蔽按钮，就像「哔哩哔哩 - 屏蔽指定内容」这个插件一样，更方便使用

**Comment by XIU2** [comment]
看了下，可以实现，我想的是把屏蔽按钮放到鼠标指向用户名/头像时悬浮的用户信息中。

**Comment by Lounode** [comment]
@XIU2 感谢作者了，笔芯0v0

**Comment by XIU2** [comment]
需要在用户主页的右边，关注按钮旁边也加上 [屏蔽] 按钮吗？

**Comment by XIU2** [comment]
效果是这样：
![01](https://user-images.githubusercontent.com/54703944/126109329-a9345437-eac1-4f75-8d2f-8b774b993ef8.png)

**Comment by XIU2** [comment]
不过我发现，展开的评论中，鼠标指向用户名/头像是有这个悬浮信息框的。
但是弹窗式的评论中，没有这种选项框。。。

**Comment by XIU2** [comment]
已经更新了。
如上图所示在评论区会显示 [屏蔽用户] 按钮，同样用户信息悬浮框也有 [屏蔽用户] 按钮，用户主页也有~

**Comment by ipez** [comment]
最新的脚本没有这个功能了，是后来移除了吗？
