### ISSUE TITLE
[ 新标签页打开链接]新版远景论坛无法新标签页打开了

### ISSUE THREAD

**Issue by bqlxz2018** [XIU2/UserScript#500]
### 问题描述

新版远景论坛https://bbs.pcbeta.com/无法新标签页打开了

**Comment by XIU2** [comment]
1. 该脚本因为各种兼容性问题无法完美解决已经处于停更状态
2. 该论坛帖子列表页有个 `新窗` 选项，勾选后就能新标签页打开帖子了（所有 Discuz! 论坛都这样）
