### ISSUE TITLE
油猴请求添加翻译功能

### ISSUE THREAD

**Issue by midikafeijuren** [XIU2/UserScript#501]
### 功能需求

能不能直接加一个内置的翻译功能,非常有用,其他的浏览器扩展的翻译不好用,可以腾讯翻译的接口吧,我没查过,总之非常有用

### 预期目标

直接在油猴的那个悬浮图标里加一个开启整页翻译的功能,默认打开,要不然跳转网页还得重弄

**Comment by XIU2** [comment]
1. 我已经不再接受新脚本制作请求了
2. 已经有类似功能的油猴脚本和浏览器扩展了（沉浸式翻译、[kiss-translator](https://github.com/fishjar/kiss-translator)）
