### ISSUE TITLE
[知乎美化] 收益分析界面暗黑模式有问题

### ISSUE THREAD

**Issue by quarkquartet** [XIU2/UserScript#502]
### 问题描述

<img width="1113" alt="image" src="https://github.com/user-attachments/assets/4494ae68-0f0a-4311-ae80-f2b197fd8146" />

在创作中心-收益分析-致知计划-内容分析界面，深色背景下回答内容标题依然为黑色，如图。

在mac的firefox和safari都尝试过，都有同样的问题。

**Comment by XIU2** [comment]
我暂时还进不去这个页面，你先把知乎美化脚本禁用，然后看看这里颜色是否正常。

如果正常，那么说明是脚本对知乎自带的暗黑模式样式微调方面的问题
如果依旧，那么说明是知乎自带的暗黑模式本身就存在该问题（这种问题我遇到好几次了），那我就需要针对性去微调此处样式。

**Comment by quarkquartet** [comment]
<img width="1073" alt="image" src="https://github.com/user-attachments/assets/d1c76b26-e693-4e1e-b798-7bce65b53820" />

OK 已经试了知乎自带的深色模式，一样的问题。那看来是知乎自己的问题了。浅色模式是对的。

另外附一张别的截图：知乎这里的数据分析图表的纵坐标应该是标了数值的，深色模式下数值标记全部黑色字符，一个也看不见。也是知乎自带的问题（因此用插件后问题同样继续存在）。

**Comment by XIU2** [comment]
知乎自带的暗黑模式可能用的人比较少，因此知乎自己都不上心，像这种问题有很多，以前经常有人向我反馈，然后我去给知乎“打补丁”修复。。。

**Comment by quarkquartet** [comment]
懂，真是辛苦作者了。。。怪不得知乎不敢公开发布开启暗黑模式的按钮。。。

**Comment by XIU2** [comment]
等我找个问题回答一下（我还不能随便敷衍水回答），开通一下这个 `致知计划`，稍后会更新脚本修复的。

**Comment by XIU2** [comment]
图标标尺文字颜色的话我倒是解决了，但是那个收益明细，我这边因为还是空的，所以压根看不到内容。。。
