### ISSUE TITLE
[自动无缝翻页] 希望添加 可以直接顶端或者底端 功能

### ISSUE THREAD

**Issue by leonhart118** [XIU2/UserScript#503]
### 功能需求

在自动翻页的时候，可以在每页的分隔处可以直接点击到顶端或者底端

### 预期目标

在自动翻页的时候，可以在每页的分隔处可以直接点击到顶端或者底端

**Comment by XIU2** [comment]
该脚本叫做 `自动无缝翻页`，重点之一是 `无缝`，这是完全按照我自己的需求编写的脚本我自写自用的（顺便分享出来给大家用），因此从始至终都不会在两页内容中间插入任何东西的。
