### ISSUE TITLE
大佬球球帮忙康康我双语字幕jio本的代码，音画字不同步，是啥毛病

### ISSUE THREAD

**Issue by warmilk** [XIU2/UserScript#52]
https://github.com/warmilk/UserScript/blob/main/userscript.js

https://greasyfork.org/zh-CN/scripts/419149-youtube%E7%A7%BB%E5%8A%A8%E7%AB%AF%E4%B8%AD%E8%8B%B1%E5%8F%8C%E8%AF%AD%E5%AD%97%E5%B9%95/code

**Comment by XIU2** [comment]
抱歉，这方面我并不熟悉~
