### ISSUE TITLE
[Github 增强] 安装以后部分页面返回上一页需要点击两次

### ISSUE THREAD

**Issue by zzhzero** [XIU2/UserScript#54]
似乎是载入的时候增加了一次刷新，第一次点返回是返回刷新操作，第二次点返回才能真正返回网页。

**Comment by XIU2** [comment]
这确实是已知问题，当初更新时修复了一个问题但又造成了一个问题。
- 修复 通过浏览器前进/后退后，Raw 快捷下载图标不显示的问题

**Comment by XIU2** [comment]
努努力，折腾半天找到了另一种替代方案，没有这种前进/后退需要点击两次的缺陷了~

#### 2021年07月22日，版本 v1.5.6
1. **修复** 之前某次更新后导致浏览器前进/后退需要点击两次的问题。
