### ISSUE TITLE
您好，有道云笔记剪报功能无法使用，请问能修改某脚本实现功能吗

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#55]
本人大量笔记保存在有道云笔记，不太想切换其他笔记。
原作者脚本https://greasyfork.org/zh-CN/scripts/412098，官方建议的剪报功能小书签http://note.youdao.com/web-clipper-chrome.html
chrome90只需关闭chrome://flags/#same-site-by-default-cookies和chrome://flags/#block-insecure-private-network-requests就能使用剪报功能。
91和92没有了chrome://flags/#same-site-by-default-cookies选项，关闭chrome://flags/#block-insecure-private-network-requests以及chrome://flags/#block-insecure-private-network-requests和chrome://flags/#schemeful-same-site，无法使用剪报功能。
大佬您好，本人习惯使用网页版保存笔记，新版本不能使用剪报功能十分遗憾。

**Comment by XIU2** [comment]
我没用用过有道云笔记，也没有账号，不是很清楚。。。

**Comment by lyjhyjyes** [comment]
> 我没用用过有道云笔记，也没有账号，不是很清楚。。。

哦哦，明白了

**Comment by lyjhyjyes** [comment]
> 我没用用过有道云笔记，也没有账号，不是很清楚。。。

使用web clipper拓展已经搞掂。还能支持其他云笔记
