### ISSUE TITLE
[知乎增强] 翻页时如果当前页面含有被屏蔽的用户，网页会报错

### ISSUE THREAD

**Issue by Lounode** [XIU2/UserScript#56]
在使用脚本的过程中屡次出现需要刷新网页才能看答案的情况，于是打开f12看了一眼，报错如下：
![image](https://user-images.githubusercontent.com/48127874/126945373-4a9771b9-7254-459e-ae56-4f6c90777cc1.png)
![image](https://user-images.githubusercontent.com/48127874/126945393-12d82415-dd17-4fca-b097-65ce438f949f.png)

**Comment by XIU2** [comment]
目前我没有遇到过需要屡次刷新才能看到回答的情况。

很长一片的那个 init.js 是知乎自己的报错。
只有 userscript.html?.... 的才是油猴脚本报错，这两个油猴脚本的报错都是 [置顶显示时间] 功能报错，提示找不到元素（原本位于底部的时间元素）。
应该是因为什么原因，导致元素丢失，因此导致 [置顶显示时间] 功能找不到元素而报错。

关闭脚本后是否正常？
你脚本设置是什么样的？
单独关闭各个功能后，依次查看网页是否正常。请提供完整复现步骤供我排错。

**Comment by XIU2** [comment]
我去你这问题下，往下翻了一段后，随便找了个人屏蔽了下。
然后刷新网页，继续往下翻，直到知乎自动加载更多内容并且脚本检测屏蔽这个用户后，没有出现网页报错情况。
网页显示正常，其他回答显示正常。
![01](https://user-images.githubusercontent.com/54703944/127074989-3d4c7606-b859-4daa-ae3a-23f211402a3f.png)

**Comment by XIU2** [comment]
对了，昨天我对 [知乎增强] 脚本大更了一次，涉及到了 [屏蔽用户]、[屏蔽关键词] 等功能，你更新后再试试说不定就正常了~

**Comment by XIU2** [comment]
怎么都是提 Issues 后就不吭声了呢？。。。
