### ISSUE TITLE
[知乎增强 / 知乎美化] 希望加入几个功能

### ISSUE THREAD

**Issue by MC-dusk** [XIU2/UserScript#57]
希望“知乎增强”：
1. 加入视频下载功能，参考https://greasyfork.org/zh-CN/scripts/398195 （其实两个脚本的知乎功能大部分重合）
2. 自动展开问题描述，比如https://www.zhihu.com/question/474974103 
3. 深色模式适配“问题日志”，比如https://www.zhihu.com/question/474974103/log

**Comment by XIU2** [comment]
1. 关于视频下载
我看了下你说的这个脚本是完整引用另一个脚本的： https://greasyfork.org/zh-CN/scripts/39206
这个脚本只有一个单独的知乎视频下载功能，你完全可以安装这个脚本。

2. 自动展开问题描述
这个虽然我不感兴趣（很多问题描述很长），但因为很简单，所以我会加上，只不过会默认关闭。

3. 深色模式适配“问题日志”
这个我尽量，但不如知乎原生支持的好，这个依然会加到另一个知乎美化脚本里。

**Comment by XIU2** [comment]
知乎增强 脚本已更新支持 [展开问题描述] 功能（默认关闭）。

**Comment by XIU2** [comment]
知乎美化 脚本已更新，[暗黑模式 1] 已支持 [问题日志页]。

**Comment by MC-dusk** [comment]
好的，非常感谢！
