### ISSUE TITLE
希望增加雪球投资论坛自动翻页支持

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#58]
https://xueqiu.com/1459805993/143725727 
雪球是讨论度很高的投资论坛
您好，我在greasyfork反馈过，但它的回复追踪不太好，所以重新发了一次

**Comment by XIU2** [comment]
这好像只有评论需要翻页吧？

**Comment by XIU2** [comment]
看了下这个评论翻页是 JS 动态加载的，对此我无能为力。
