### ISSUE TITLE
知乎增强脚本：希望当发布时间与编辑时间为同一天时自动合并

### ISSUE THREAD

**Issue by Alphabet1226** [XIU2/UserScript#6]
![image](https://user-images.githubusercontent.com/51783873/100077833-ccff3880-2e7d-11eb-8293-3609a4c67839.png)
![image](https://user-images.githubusercontent.com/51783873/100077924-e6a08000-2e7d-11eb-9cb8-655fa548c254.png)

**Comment by XIU2** [comment]
不是很有必要，目前脚本只是把他的位置移到了顶部。  
你想要它合并，但有的人想要分开。。。

**Comment by Alphabet1226** [comment]
脚本不只是移动到了顶部，而是强行分离出了两个日期，原版是只保留编辑日期，鼠标停留显示发布日期的。
我并不是想让它完全合并，只是建议当这两个日期一模一样时合并。
分开的初衷是为了直观地看到两个时间的差异，但当二者重合时就失去了意义并且成为累赘，徒增分辨成本。
甚至您让这两个日期左对齐排两行都能更加直观地对比。
![image](https://user-images.githubusercontent.com/51783873/100458638-0f837800-30ff-11eb-8dc5-eed7658d9e85.png)
![image](https://user-images.githubusercontent.com/51783873/100458615-072b3d00-30ff-11eb-909a-0b6510ebc7ae.png)

**Comment by XIU2** [comment]
目前脚本是，如果发布后没有编辑过，则只显示发布时间。  
如果编辑过了，哪怕是相差一秒，也会同时显示发布时间和编辑时间。

**Comment by XIU2** [comment]
你更新一下 v1.1.5 版本吧，我单独做了个开关，在浏览器右上角 Tampermonkey 扩展图标里。

> 如果没有编辑过，则只会显示发布时间。另外**原版只显示日期**，开启该功能后，会**显示具体时间（XX:XX）**。

### 2020年11月28日，版本 v1.1.5
1. 新增 [完整显示时间] 脚本菜单开关。
