### ISSUE TITLE
[知乎增强] 建议使用 `MutationObserver` 而非已废弃的 `document.addEventListener('DOMNodeInserted', )`

### ISSUE THREAD

**Issue by CCRcmcpe** [XIU2/UserScript#60]
`document.addEventListener('DOMNodeInserted', )` 已废弃，如果重构，换用 `MutationObserver` 可使性能得到改善。参见 https://developer.mozilla.org/en-US/docs/Web/API/MutationEvent

**Comment by CCRcmcpe** [comment]
也可参考 https://github.com/CCRcmcpe/UserScript/commit/27ea4b73c69df80c7fa849b71f56a3de5e716226，使用了 `MutationObserver`。

**Comment by XIU2** [comment]
我是业余选手，平时都是边查边写的，对这些情况并不熟悉，我会研究看看的~

**Comment by XIU2** [comment]
知乎增强脚本里面的都改成 MutationObserver 了。
