### ISSUE TITLE
[自动无缝翻页] 希望添加支持一个网站

### ISSUE THREAD

**Issue by Ln-G0179** [XIU2/UserScript#61]
希望作者能添加一个漫画网站（https://www.gufengmh8.com/）古风漫画网的漫画页面自动翻页，感谢大佬

**Comment by XIU2** [comment]
我随便找了个漫画看了下，发现这网站自带了自动无缝翻页功能，只不过默认关闭了。
右上角的 `阅读方式→`，默认是 `分页阅读`，点击右边的 `下拉阅读` 就切换为自动翻页啦。

**Comment by Ln-G0179** [comment]
作者大大，就是那个，我知道这个下拉阅读，我想要的是每一话结束自动接下一话，可以吗？感谢大佬，大佬辛苦

**Comment by Ln-G0179** [comment]
我之前忘回复了，今天看才发现关闭了，我以为关闭就是不能用了，大佬海涵。

**Comment by XIU2** [comment]
看了下，这个网站里的图片都是动态加载的。
不过代码比较简单，应该可以实现，只是比较费时间。

另外，另一个重复的 Issues 我就关闭了。

**Comment by XIU2** [comment]
已更新支持 [古风漫画网]。
为了支持这个网站（动态加载内容），我花了一两个小时写了一套新的机制。。。
平时支持其他网站（非动态加载内容），只需要最低几分钟就能写完规则。

**Comment by Ln-G0179** [comment]
大佬辛苦，非常感谢。

**Comment by Ln-G0179** [comment]
大佬是真的牛批，好用极了
