### ISSUE TITLE
[自动无缝翻页] 关于之前的网站添加

### ISSUE THREAD

**Issue by Ln-G0179** [XIU2/UserScript#62]
（https://www.gufengmh8.com/）古风漫画网，作者你好，我想说的是话与话之间也自动翻页，就是一话结束自动接上下一话，可以吗，作者大大，感谢大佬，大佬辛苦。

**Comment by XIU2** [comment]
同一个需求请在同一个 Issues 中回复，不要重复发。

**Comment by Ln-G0179** [comment]
上一个被关闭了

**Comment by XIU2** [comment]
关闭了也可以继续回复呀。
因为你迟迟没有回复，我才给关闭了。
