### ISSUE TITLE
小建议：能不能把一些脚本合并为论坛美化脚本，让常用论坛都能获得适配

### ISSUE THREAD

**Issue by FCSDFSDVXDFG** [XIU2/UserScript#63]

**Comment by XIU2** [comment]
你可能注意到我现在已经不写  XXX 美化 油猴脚本了。
主要原因就是这些美化都是**完全按照我个人审美、需求**写的，并不适用于所有人，所以总是有人提出意见，但这些样式类修改比较杂乱（可以细分成几十 甚至上百个），不可能给每个样式都加个开关。

所以我现在虽然还是依然会对一些网站调整样式，但仅为自用，不再公开了~
另外对于样式美化，我不再使用油猴脚本去插入网页了，而是改用**专门修改网站样式的 Stylus** 了。
两者的偏向不同，前者是插入运行 JS，后者则是插入 CSS，因此为了解决油猴脚本插入 CSS 样式会一闪而过的问题，我改用了后者。
