### ISSUE TITLE
[知乎增强] 希望修复 Violentmonkey 下部分功能无法使用的问题

### ISSUE THREAD

**Issue by SSSJJP** [XIU2/UserScript#64]
作者大大好
我是用暴力猴安装知乎增强这个插件的，最近我发现用不了了。
* 一键收起回答
* 区分问题和文章
等功能目前赢不了希望能修复

![屏幕截图 2021-08-10 222702](https://user-images.githubusercontent.com/32217058/128885084-84d0c3cb-4f82-4dd4-bacf-9c955fb459f1.png)
![Uploading 屏幕截图 2021-08-10 222702.png…]()

**Comment by XIU2** [comment]
好吧，因为我的脚本都是基于 Tampermonkey 设计编写的，我尽量支持 Violentmonkey。

**Comment by XIU2** [comment]
已更新，你看看还有没有问题。
之所以在 Violentmonkey 下部分功能无法使用，主要是 Violentmonkey 加载脚本比 Tampermonkey 更早，而此时网页中部分元素还没加载出来，导致脚本报错，功能失效~

#### 2021年08月11日，版本 v1.5.4
1. **修复** 在 Violentmonkey 下部分功能无法使用的问题。
2. **修复** 部分功能在单独回答页点击 [全部回答] 跳转到全部回答页时没有运行的问题。
3. **优化** 代码。
