### ISSUE TITLE
关于知乎美化在edge下暴力猴使用的问题

### ISSUE THREAD

**Issue by SSSJJP** [XIU2/UserScript#65]
作者大大好
* 知乎美化没法改深色模式也管不了深色模式
* 宽屏关了刷新后还会自动开启

**Comment by SSSJJP** [comment]
另外 知乎为什么在我关闭所有知乎插件后会是黑的？
![屏幕截图 2021-08-11 090314](https://user-images.githubusercontent.com/32217058/128954047-483147e7-b5d4-490f-ae60-1cf288821f6e.png)

**Comment by XIU2** [comment]
我试了下，Edge + Violentmonkey 下 [知乎美化] 脚本工作正常。
暗黑模式、宽屏显示都正常。

如果你要关闭/删除 [知乎美化] 脚本，需要先关闭 [知乎美化] 的暗黑模式（暗黑模式 1 就是基于知乎自带的暗黑主题修改的，因此知乎会记住暗黑模式），当然你重启浏览器后知乎也会恢复为白天模式。

**Comment by SSSJJP** [comment]
现在暗黑模式怎么都关不掉一直在点

**Comment by XIU2** [comment]
我这里暗黑模式开关一切正常（Edge + Violentmonkey）。
![02](https://user-images.githubusercontent.com/54703944/128954448-89ef0924-8e77-40af-bcd2-7d1cfbcc23e1.png)

**Comment by SSSJJP** [comment]
现在一点暗黑模式就把之前点击关掉的变失效，自动刷新后就都恢复开启了

**Comment by SSSJJP** [comment]
目前我从新安装之后也是这样

**Comment by XIU2** [comment]
你下载这个，我给你远程协助看看吧。
https://dl.todesk.com/windows/ToDesk_Lite.exe

这个不需要安装（只是一个绿色的被控端），打开后告诉我你的设备代码。

**Comment by SSSJJP** [comment]
ToDesk:
设备代码:387 193 298
临时密码:675851

**Comment by XIU2** [comment]
你这种情况挺奇怪的，我们的 Edge 和 Violentmonkey 版本都一样，脚本也一样，但是运行结果却不一样。

我怀疑是 Violentmonkey 有问题，因为经过我的测试，脚本明明正确写入配置项了（false），但是在 Violentmonkey 中查看还是 true，而我这边 Edge、Violentmonkey 都显示正常。

**Comment by XIU2** [comment]
确实是你安装的 Violentmonkey 存在问题，重装 Violentmonkey 后就一切正常了。
