### ISSUE TITLE
您好，能否帮忙写个脚本，让今日头条网页版的地址恢复原样，去除后缀

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#68]
OpenWrt官方软件源太慢？更换源并测试国内镜像哪家好
https://www.toutiao.com/i6954726382291223070/?tt_from=weixin&utm_campaign=client_share&wxshare_count=1&timestamp=1628708298&app=news_article&utm_source=weixin&utm_medium=toutiao_android&use_new_style=1&req_id=202108120258180102120740692312D35C&share_token=52481e4e-db27-4b07-ad5c-98239bef86ff&group_id=6954726382291223070
您好，今日头条创作者的内容不错，基本上我不用知乎、微信，改用头条了。win10 chrome92下，登录账户下，头条地址出现后缀，太烦了，不能愉快的复制以及分享。更重要是看过的文章，我会点收藏，表示已看。长链接和短链接不一样，经常会忘记已看、已保存。
恳请大神自动净化头条长链接

**Comment by XIU2** [comment]
你的意思是把：
```
https://www.toutiao.com/i6954726382291223070/?tt_from=weixin&utm_campaign=client_share&wxshare_count=1&timestamp=1628708298&app=news_article&utm_source=weixin&utm_medium=toutiao_android&use_new_style=1&req_id=202108120258180102120740692312D35C&share_token=52481e4e-db27-4b07-ad5c-98239bef86ff&group_id=6954726382291223070
```
这个 URL 改成下面这样吗？
```
https://www.toutiao.com/i6954726382291223070/
```

很简单，代码就一句话，给你写了个油猴脚本：

```
// ==UserScript==
// @name         今日头条
// @version      1.0.0
// @author       X.I.U
// @description  移除无用 URL 信息（lyjhyjyes 定制版~）
// @match        https://www.toutiao.com/*/?*
// @icon         https://sf3-cdn-tos.douyinstatic.com/obj/eden-cn/uhbfnupkbps/toutiao_favicon.ico
// @grant        none
// @license      GPL-3.0 License
// @run-at       document-start
// @namespace    https://github.com/XIU2/UserScript
// ==/UserScript==

(function() {
    'use strict';
    if (/^\/[a-z]*\d+\/$/.test(location.pathname) && location.search) {location.href = location.origin + location.pathname;}
})();
```

去 Tampermonkey 中点击 **[已安装脚本]** 左边的 `[+]` 然后将复制的脚本内容覆盖进去，按下 `Ctrl + S` 保存即可。

有什么其他问题可以跟我说。

**Comment by lyjhyjyes** [comment]
谢谢了，已经成功修改地址😙

XIU2 ***@***.***> 于2021年8月13日周五 上午8:04写道：
