### ISSUE TITLE
新增需求提问，具体描述如下

### ISSUE THREAD

**Issue by baibai92** [XIU2/UserScript#7]
请问，新增需求是只针对脚本列表里的脚本提出的新需求，还是可以有其他的需求。如果可以有不止是下方脚本的需求（另外的网站），我再展开描述，谢谢你

**Comment by XIU2** [comment]
不管是已有脚本，还是新脚本都可以提。   
当然我是业余的，所以并不是什么脚本都会写，但是你只管提就行了。

**Comment by baibai92** [comment]
谢谢。
1.虎牙直播，斗鱼直播，企鹅电竞直播免登录最高清晰度

2.获取直播流链接,使用PotPlayer打开

说明：1.现在这几个直播都要强制登录或者下载软件才能最高清晰度，我想看高清直播却并不想注册账号。经测试找到了几个还能用的参考下。

虎牙：https://greasyfork.org/zh-CN/scripts/385220-%E8%99%8E%E7%89%99%E5%85%8D%E7%99%BB%E9%99%86-%E4%BF%AE%E5%A4%8D%E7%89%88（这个我用的是反馈里的一个人发的代码）
斗鱼：https://greasyfork.org/zh-CN/scripts/388373-%E6%96%97%E9%B1%BC%E5%85%8D%E7%99%BB%E9%99%86
这两个好像是拦截登录弹窗达到高清直播，企鹅电竞没找到

2.获取直播流用potplayer打开，参考https://greasyfork.org/zh-CN/scripts/402279-%E8%99%8E%E7%89%99plus（只找到虎牙）
使用potplayer打开可以有效避免各种广告，弹幕，礼物等的流量，速度更快，延迟低，专注看直播


我只想安安静静的看直播，没有其他需求。找了很多插件去试，插件不全，功能多样，没有一个聚合在一起的满足2个需求的。

**Comment by baibai92** [comment]
题外话：https://greasyfork.org/zh-CN/scripts/417216-%E5%B1%8F%E8%94%BDhtml5%E6%92%AD%E6%94%BE%E5%99%A8p2p%E4%B8%8A%E4%BC%A0 不知道这个是不是真的

**Comment by XIU2** [comment]
既然已经有了满足你要求的脚本，为什么还要我写？  
我平时不看直播的。  

至于那个 P2P 上传很正常，好几年前就应用了，国内的点播视频网站也用到了，都是为了降低流量成本。

**Comment by baibai92** [comment]
1.免登录最高清晰度 虎牙直播，斗鱼直播有了，企鹅电竞没有
2.获取直播流用potplayer打开只有虎牙有，斗鱼和企鹅电竞都没有（或者我没找到）
3.我找到的脚本不全，,只是个参考，我确实需要一个**整合的脚本**，在虎牙，斗鱼，企鹅电竞都能生效，并满足“1.虎牙直播，斗鱼直播，企鹅电竞直播免登录最高清晰度   2.获取直播流链接,使用PotPlayer打开”这两点。

**Comment by XIU2** [comment]
我看了下 企鹅电竞 的单纯的移除登陆弹窗是没用的。  
至于获取直播流，需要去找直播流解析方法，这个找起来很麻烦，而且也不一定能直接用 potplayer 播放。

**Comment by baibai92** [comment]
也许企鹅电竞没人做这也是一方面。
至于分析直播流，上面的，https://greasyfork.org/zh-CN/scripts/402279-%E8%99%8E%E7%89%99plus（虎牙）里面有代码可以参考，还有斗鱼直播流分析我在greasyfork也看到了，仅供参考，虽然我看不懂代码。。。
https://github.com/wbt5/real-url这个是有人对直播流的分析，应该有帮助
最后的最后，如果大佬不愿意做的话，直接把我这个问题关闭了。我就不用每过段时间来看看了==

**Comment by XIU2** [comment]
emmm 我这个人不太会拒绝人，首先我不是大佬，我只能算个入门，JavaScript 脚本是花几个小时临时自学的，和我学的其他语言一样，都是为了平时遇到一些需求时可以自己解决，所以实际上还是个菜鸡。  

你说的这些功能或许我能做出来。但简单的还好，如果遇到复杂又不感兴趣（平时都没看过直播），就没有动力去做（我写的其他脚本和软件大都是自己产生了需求为动力催动我去写的），再加上不知道怎么拒绝就...  

那我就先关闭了，等我哪天突然感兴趣了，再研究~
