### ISSUE TITLE
知乎增强 功能请求：从主页打开 answer 页时，重定向至 question 页

### ISSUE THREAD

**Issue by liangjiancang** [XIU2/UserScript#71]
如题所示

**Comment by XIU2** [comment]
但这样有个问题，重定向到问题页后，第一个回答并不是你从主页等地方点开的那个回答。

**Comment by liangjiancang** [comment]
这个其实没关系。我要反问一下：如果你在主页看到一个回答，觉得感兴趣，为什么不在主页把这个回答看完呢？如果选择点进去，肯定是为了看全部回答吧？

或者参考知乎旧版 APP 的做法？点问题部分的文字进去是问题，点回答部分的文字进去是回答。
![Snipaste_2021-08-13_19-48-17](https://user-images.githubusercontent.com/42267675/129352805-5e925e67-b4ac-43b1-a072-1e9933f40c1f.png)

**Comment by XIU2** [comment]
这样吧，我现在正在吃饭，一会还有事情要忙。
你先用开发者工具在标题后面设计一下按钮样式（A 标签，和标题这个 A 标签并列），我对样式设计不擅长（从 [区分问题文章] 功能可以看出来），随后我再去写代码什么的。

**Comment by liangjiancang** [comment]
其实要求也不用这么高啦，我也没什么设计感，你让我瞎搞顶多设计成这个样子。
![000](https://user-images.githubusercontent.com/42267675/129357845-72746e0b-aabf-451c-ab83-09a7c6b2c81b.png)

如果你有现成的设计图给我参考，我可以帮你搞定样式的问题，也免得搞出来你不喜欢。

**Comment by XIU2** [comment]
emmm 如果我有现成的设计，我早就直接抄了~

**Comment by XIU2** [comment]
这功能完全可以把 [区分问题文章] 代码复制一份稍微改改。
刚好我发现 [区分问题文章] 的实现方式已经过时了（以前很菜的时候，还不知道可以监控网页插入事件，于是曲线救国依靠监听 xhr 事件来向后续加载信息流添加标签）。刚才顺便给改成了 MutationObserver 了。

这个功能明天再折腾吧，功能代码很简单，就是要想一想如何设计样式什么的。。。

**Comment by liangjiancang** [comment]
既然能用简单的方案实现就太好了，谢谢作者的辛勤劳动

**Comment by XIU2** [comment]
已更新，设计样式半天，最后发现还是知乎自身的 [赞同] 样式比较搭配。

![11](https://user-images.githubusercontent.com/54703944/129433698-565f1be1-0784-494d-b51c-c83dfa391065.png)
