### ISSUE TITLE
[知乎增强]功能请求：屏蔽首页上的视频内容。

### ISSUE THREAD

**Issue by YagamiMirai** [XIU2/UserScript#73]
希望能屏蔽掉那种短视频的内容（即点击链接为https://www.zhihu.com/zvideo/开头的内容）

不好做的话可以当我没提…

**Comment by XIU2** [comment]
这种需求，用广告屏蔽扩展更好点，屏蔽规则见这个 Issues：
[\[知乎增强\] 希望能增加一个屏蔽视频功能](https://github.com/XIU2/UserScript/issues/48)

**Comment by YagamiMirai** [comment]
好的谢谢

**Comment by XIU2** [comment]
又有好几个人想要这个功能，刚好和我要做的另一个功能有一定重叠，我还是给加上吧~

v1.6.7 **新增** [屏蔽指定类别（视频/文章等）] 功能~

特此通知~
