### ISSUE TITLE
您好，可否帮忙写脚本收集网页标题、地址、发布时间、作者

### ISSUE THREAD

**Issue by lyjhyjyes** [XIU2/UserScript#77]
恩山https://www.right.com.cn/forum/
koolshare  https://koolshare.cn/portal.php
https://www.csdn.net/ 
www.toutiao.com
52pojie.cn
本人喜欢复制粘贴，用word整理资料。请问能否一次性帖子的标题、地址、发布时间和作者。目前我用vimium复制标题和地址，手动选择发布时间和作者，配合ditto粘贴。效率有点低。
能否抽空写个脚本，一次性提取

**Comment by XIU2** [comment]
描述再具体点。
比如在哪些页面，想要得到什么结果，最好给出示例。

**Comment by lyjhyjyes** [comment]
> 描述再具体点。
> 比如在哪些页面，想要得到什么结果，最好给出示例。
您好啊，能收集4项信息即可，日期和用户不同网站默认不同，最好都是标题 地址 用户 时间顺序）
最新Openwrt带的samba-4.11文件共享设置 - OPENWRT专版 - 恩山无线论坛 - Powered by Discuz!
https://www.right.com.cn/forum/thread-2129509-1-1.html
yumeimm 发表于 2020-1-6 12:35 

比如这样子，恩山的。

华为WiFi6 AirEngine系列AC+AP打造家庭无线网络,单线复用观看IPTV - 华为数通WLAN专区-AirEngine&CloudEngine - KoolShare - 源于玩家 服务玩家
https://koolshare.cn/thread-195902-1-1.html
夜半点灯 2021-6-9 21:36:39 


基于 RT-Thread的麦克纳姆轮小车循迹运动控制算法开发和研究_TsinghuaJoking-CSDN博客
https://blog.csdn.net/zhuoqingjoking97298/article/details/119702937?utm_medium=distribute.pc_feed_v2.none-task-blog-yuanlijihua_default_tag-1.pc_personrecdepth_1-utm_source=distribute.pc_feed_v2.none-task-blog-yuanlijihua_default_tag-1.pc_personrec
卓晴2021-08-14 17:17:41
（这个csdn劳烦写短链接的脚本了）

长图丨尺牍情深！习近平总书记这样与青年谈心
https://www.toutiao.com/a6996254448729227815/
新华社 2021-08-14 20:37·

分享一款选择就是复制的小工具Dragking V1.3 - 『精品软件区』 - 吾爱破解 - LCG - LSG |安卓破解|病毒分析|www.52pojie.cn
https://www.52pojie.cn/thread-1491855-1-1.html
ElEzUs 2021-8-10 21:47 


网页宽屏
https://greasyfork.org/zh-CN/scripts/411260
作者sakura-flutter 创建日期2020-09-13  02:09:15最近更新2021-07-18  04:09:11
（这个greasyfork和sleazyfork 普通复制地址带中文，粘贴后变成英文和数字后缀，https://greasyfork.org/zh-CN/scripts/411260-%E7%BD%91%E9%A1%B5%E5%AE%BD%E5%B1%8F，希望能脚本短链接）

愤怒！愿高血压战胜禽兽胡所长【扫黑风暴第4期】_哔哩哔哩_bilibili
https://www.bilibili.com/video/av377279297
工藤新医heart 2021-08-14 19:19:13 （b站的用户名手动复制太难了）

【k2路由刷机】让K2小内存机，焕发又一“春” - YouTube
https://www.youtube.com/watch?v=TgvN_aw7F4I&t
瑞安的极客日记 2020年5月17日 
（youtube保存到书签是https://www.youtube.com/watch?v=TgvN_aw7F4I&t=47s，记录了47秒位置，不需要）

本人喜欢收集软件和教程，分享给家庭群使用。
再次劳烦了，祝周末愉快。

**Comment by XIU2** [comment]
你这要求支持的网站还挺多啊，这就不是几行代码能写完的了。
需要根据不同网站编写规则（标题、作者、时间 所在的元素位置）。

另外，你这一天一个脚本请求。。。

**Comment by lyjhyjyes** [comment]
> > 描述再具体点。
> > 比如在哪些页面，想要得到什么结果，最好给出示例。
> > 您好啊，能收集4项信息即可，日期和用户不同网站默认不同，最好都是标题 地址 用户 时间顺序）
> > 最新Openwrt带的samba-4.11文件共享设置 - OPENWRT专版 - 恩山无线论坛 - Powered by Discuz!
> > https://www.right.com.cn/forum/thread-2129509-1-1.html
> > yumeimm 发表于 2020-1-6 12:35
> 
> 比如这样子，恩山的。
> 
> 华为WiFi6 AirEngine系列AC+AP打造家庭无线网络,单线复用观看IPTV - 华为数通WLAN专区-AirEngine&CloudEngine - KoolShare - 源于玩家 服务玩家
> https://koolshare.cn/thread-195902-1-1.html
> 夜半点灯 2021-6-9 21:36:39
> 
> 基于 RT-Thread的麦克纳姆轮小车循迹运动控制算法开发和研究_TsinghuaJoking-CSDN博客
> https://blog.csdn.net/zhuoqingjoking97298/article/details/119702937?utm_medium=distribute.pc_feed_v2.none-task-blog-yuanlijihua_default_tag-1.pc_personrecdepth_1-utm_source=distribute.pc_feed_v2.none-task-blog-yuanlijihua_default_tag-1.pc_personrec
> 卓晴2021-08-14 17:17:41
> （这个csdn劳烦写短链接的脚本了）
> 
> 长图丨尺牍情深！习近平总书记这样与青年谈心
> https://www.toutiao.com/a6996254448729227815/
> 新华社 2021-08-14 20:37·
> 
> 分享一款选择就是复制的小工具Dragking V1.3 - 『精品软件区』 - 吾爱破解 - LCG - LSG |安卓破解|病毒分析|www.52pojie.cn
> https://www.52pojie.cn/thread-1491855-1-1.html
> ElEzUs 2021-8-10 21:47
> 
> 网页宽屏
> https://greasyfork.org/zh-CN/scripts/411260
> 作者sakura-flutter 创建日期2020-09-13 02:09:15最近更新2021-07-18 04:09:11
> （这个greasyfork和sleazyfork 普通复制地址带中文，粘贴后变成英文和数字后缀，https://greasyfork.org/zh-CN/scripts/411260-%E7%BD%91%E9%A1%B5%E5%AE%BD%E5%B1%8F，希望能脚本短链接）
> 
> 愤怒！愿高血压战胜禽兽胡所长【扫黑风暴第4期】_哔哩哔哩_bilibili
> https://www.bilibili.com/video/av377279297
> 工藤新医heart 2021-08-14 19:19:13 （b站的用户名手动复制太难了）
> 
> 【k2路由刷机】让K2小内存机，焕发又一“春” - YouTube
> https://www.youtube.com/watch?v=TgvN_aw7F4I&t
> 瑞安的极客日记 2020年5月17日
> （youtube保存到书签是https://www.youtube.com/watch?v=TgvN_aw7F4I&t=47s，记录了47秒位置，不需要）
> 
> 本人喜欢收集软件和教程，分享给家庭群使用。
> 再次劳烦了，祝周末愉快。

搜索引擎是怎么作恶的？人人都该知道的搜索真相！ - 西瓜视频
https://www.ixigua.com/6911529177510314510?logTag=d336dcf2bc52e2c7683f
Topbook 2020-12-29 · 原创
（西瓜视频搜索出来的视频，需要短链接解析，用户名复制容易点到头像）

是你篮球的主页 - 抖音
抖音主页需要短链接，貌似和腾讯一样比较难处理。
投球前，顶不顶肘。#乔丹 #科比 #投篮 #篮球 #上热门 @DOU+ - 抖音
https://www.douyin.com/video/6996086118068374819

是你篮球 2021-08-14
（容易点到头像复制）
就是这些了，主要获取信息的渠道

**Comment by XIU2** [comment]
我虽然鼓励大家提需求，但主要目的是想找到一些**很多人有共同需求的脚本功能方向**。
这样才会用的人更多，我就会获得**成就感**（写脚本的主要动力）。
但是对于这类**需求面太窄**的脚本，基本上只有你一个人会用（相当于私人定制），完全没有成就感。

虽然没什么难度，但是不同于前面两个脚本，像这个脚本，你后面肯定会增加网站支持的，但是你不会写规则，到时候还是要我来帮你一个人**维护脚本**，这违背了我的初衷（我个人是很懒的，只有**感兴趣**的才会有足够动力去做）。

**Comment by XIU2** [comment]
**求人不如求己**，如果你有很多脚本需求，完全可以自学 JavaScript，入门很简单的。

我个人不喜欢依靠别人，能自己解决的就自己解决，**自给自足**，因此我业余**自学**了十几种编程语言，学的越多越容易入门其他语言（几个小时）。而学习的动力就是我**个人平时产生的需求推动**我去学习/编写脚本、软件等等。

我写过的脚本、软件（包括没公开的），基本上全都是我**以我个人需求**编写的，顺便分享出来看看有没有人需要。

> 我写了不少脚本、软件，其中一部分也没什么人用，就是因为需求面窄（需求面更窄的我就干脆不公开了，纯自用），依靠别人帮我写的话怕是遥遥无期了~

**Comment by lyjhyjyes** [comment]
明白。 可否分享一些您觉得好的JavaScript的学习书籍。
只要不涉及硬件，抽空可以学一下

XIU2 ***@***.***> 于2021年8月15日周日 下午3:30写道：

**Comment by XIU2** [comment]
我从来没看过书籍、视频的。。。
