### ISSUE TITLE
[护眼模式] 与其他脚本冲突-B站专栏失效

### ISSUE THREAD

**Issue by MC-dusk** [XIU2/UserScript#80]
RT，同时使用https://github.com/MotooriKashin/Bilibili-Old 脚本，在B站专栏页面，护眼模式显示有问题。
例如：https://www.bilibili.com/read/cv12691765 
![image](https://user-images.githubusercontent.com/52311860/129551372-3949629e-a5e3-4f9c-8a13-2085f3ae656f.png)

**Comment by XIU2** [comment]
我不会去解决这种脚本之间互相冲突的问题，因为这是无穷无尽的，永远也不可能解决完。

**Comment by XIU2** [comment]
我去看了下，是因为这个脚本重写了专栏页，导致把我脚本插入的 CSS 样式给**清除**了。

想要解决这个冲突，就只能添加一个延迟判断或定时循环判断，而这会影响到**所有使用者/网站**（因为我的脚本无法知道你是否安装了这个脚本），并且该冲突影响范围太小。
因此我**不会修复这个冲突**，如果是**某个网站**出现这种情况，我才会去修复（例如同样情况的 远景论坛）。

**Comment by MC-dusk** [comment]
经人推荐试用了一下https://www.baiduyun.wiki/tool/install-darkmode.html 发现解决了专栏深色模式的冲突，现在直接三个脚本一起上即可
