### ISSUE TITLE
[知乎增强] 希望添加 类别过滤 功能

### ISSUE THREAD

**Issue by aoweiie** [XIU2/UserScript#81]
希望在综合选项卡下，能过滤话题，视频，用户，杂志，相关搜索等类别
![image](https://user-images.githubusercontent.com/36393630/129835850-c53c44e2-c75a-48ec-b00d-7e254902021d.png)

![image](https://user-images.githubusercontent.com/36393630/129835961-6bff348f-4b74-4882-9eb6-282b9cea9ca8.png)

**Comment by XIU2** [comment]
这功能可以实现，不过这个功能分为这么多类别，依靠简陋的脚本菜单开关的话，就有点太多了，我需要设计一套简单的多选开关方案，这需要一定时间。

**Comment by XIU2** [comment]
你要的功能已经实现了，不过不局限于搜索页，还包括首页~  
**新增** [屏蔽指定类别（视频/文章等）] 功能。
