### ISSUE TITLE
[蓝奏云网盘增强] 希望添加功能，自动把lanzous换成lanzoux

### ISSUE THREAD

**Issue by 2370177068** [XIU2/UserScript#82]
希望添加功能，自动把lanzous和lanzoui换成lanzoux
有时候访问别人链接时lanzous打不开，每次都要手动修改，有点麻烦，想要这个功能

**Comment by XIU2** [comment]
脚本只有在网站开始加载后，才能运行，如果网站都打不开那么就不会运行。

因此你这种需求有两种方案：
- 一、用脚本替换所有网页下的蓝奏云分享链接  
**优点**：只需要一个脚本就行了  
**缺点**：效率低下  
- 二、用专门用于**链接重定向**的浏览器扩展去重定向为可用的蓝奏云分享链接。
**优点**：效率高  
**缺点**：需要再安装一个浏览器扩展并配置规则

我目前用的是第二种方案。

****

**扩展名称**： URLRedirector
**下载地址**： https://pan.lanzoui.com/i3Hwtkcoari

安装后（[离线安装扩展教程](https://zhuanlan.zhihu.com/p/276027099)）点击浏览器右上角**扩展图标 - [齿轮]**（设置，另外记得顺便勾选 **[重定向]**）。

进入设置页面后，点击 `[+]` 来新增一个规则，内容如下：

||||
|----|----|----|
规则描述 | lanzou|随便写
地址示例 | https://xx.lanzoux.com/xx | 可选，只是用来确定规则匹配结果是否正确的
原始地址 | (.*).lanzou(.*).com/(.+) | 匹配规则
目标地址 | https://pan.lanzoui.com/$3 | 要重定向的目标地址
排除地址 | pan.lanzoui.com | 排除目标地址自身域名

<img src="https://user-images.githubusercontent.com/54703944/130339908-f1920dd2-3797-4afb-8385-a2f832953907.png" width="50%">

点击 `[确认]`，然后再点击右上角的 `[保存]`。

最后，记得在浏览器右上角**扩展图标 - 勾选 [重定向]**，这个是扩展的规则总开关。  
![2](https://user-images.githubusercontent.com/54703944/130339554-e423aaba-68ac-47a8-8d2f-84ce36aedab5.png)

**Comment by maboloshi** [comment]
@lxgz12345 lxgz12345 
可以自己写一个私有的重定向脚本
```js
// ==UserScript==
// @name        自定义重定向
// @namespace   XXXXXX
// @match        *://*.lanzous.com/*
// @match        *://*.lanzoux.com/*
// @match        *://*.lanzoui.com/*
// @exclude-match  *://pan.lanzoui.com/*
// @grant       none
// @version     1.0
// @author      xxx
// @description 根据自己的需要设置重定向
// @run-at      document-start
// ==/UserScript==
if (window.location.href.match(/^https:\/\/(.*).lanzou(.).com/)) {
  window.location.href = window.location.href.replace(/^https:\/\/(.*).lanzou(.).com/, 'https://pan.lanzoui.com');
}
```

**Comment by XIU2** [comment]
@maboloshi  油猴脚本在网页加载后才能运行，如果都打不开网页，那就没办法运行并重定向了呀。。。
所以我的油猴脚本才没有集成该功能。

**Comment by maboloshi** [comment]
原来如此 我就凭自己的重定向脚本 改了一下 未测试 抱歉哈
