### ISSUE TITLE
[自动无缝翻页] 希望新增这些站点

### ISSUE THREAD

**Issue by worqq** [XIU2/UserScript#83]
这次工作量蛮大的，如果可以的话可以慢慢添加，万分感谢！！greasyfork反馈被审核了0.0
麻烦帖个二维码吧，虽然不是土豪，请楼主喝杯咖啡也算略表感激之情。

https://www.ithome.com/list/
https://www.thewindowsclub.com/
https://www.expreview.com/
https://winaero.com/category/windows-11/
https://www.th-sjy.com/
https://www.pc521.net/
https://blog.iccfish.com/
https://www.isharepc.com/
http://www.dugubest.com/all
https://www.ghxi.com/category/all/pcsoft
https://github.com/XIU2?tab=stars
https://microsoftedge.microsoft.com/addons/search/%E5%9B%BE%E7%89%87
https://chrome.zzzmh.cn/#ext
https://pic.netbian.com/new/
https://yskhd.com/
https://www.iconfont.cn/search/index?searchType=icon&q=qq
https://www.pixiv.net/users/9685977/artworks
https://www.yinfans.net/
https://www.kisssub.org/
https://cn.pornhub.com/video
https://www.mypianku.net/mv/
https://www.yikm.net/
http://www.mubolin.cn:99/

下面都是一个网站，只不过经常被封所以很多备用域名，添加几个也可以
http://btbtt11.com
http://btbtt12.com
http://btbtt13.com
http://btbtt14.com
http://btbtt15.com
http://btbtt16.com
http://btbtt17.com
http://btbtt18.com
http://btbtt20.com
http://www.btbtt11.com
http://www.btbtt12.com
http://www.btbtt13.com
http://www.btbtt14.com
http://www.btbtt15.com
http://www.btbtt16.com
http://www.btbtt17.com
http://www.btbtt18.com
http://www.btbtt19.com
http://www.btbtt20.com
https://btbtt11.com
https://btbtt12.com
https://btbtt13.com
https://btbtt14.com
https://btbtt15.com
https://btbtt16.com
https://btbtt17.com
https://btbtt18.com
https://88btbtt.com
https://btbtt20.com
https://www.btbtt11.com
https://www.btbtt13.com
https://www.btbtt14.com
https://www.btbtt15.com
https://www.btbtt17.com
https://www.btbtt19.com
https://www.btbtt16.com
https://www.btbtt12.com
https://www.88btbtt.com
https://www.btbtt18.com
https://www.btbtt20.com

**Comment by XIU2** [comment]
你这里面还有机场网站啊，什么鬼。
另外我还看到了色情网站，这不会去添加的（Greasyfork 虽然允许，但是有限制）。

总之我会挑选一些去添加支持的，但不可能是所有（或大部分）。

**Comment by XIU2** [comment]
有空了，开始帮你搞~
暂时筛选出了这 14 个网站：
- [x] IT 之家
- [x] 超能网
- [x] 极简插件
- [ ] 小霸王其乐无穷
- [ ] 乐软博客
- [ ] th_sjy 汉化
- [ ] 不忘初心博客
- [ ] 果核剥壳
- [ ] TheWindowsClub
- [ ] Winaero
- [ ] 音范思
- [ ] 爱恋动漫 BT
- [ ] 片库
- [ ] 彼岸图库

> 以上网站只是初步筛选，接下来在制作规则时，如果遇到**难以制作**的可能会选择放弃该网站~

我会在完成一个后勾选相应网站，一口气做几个后再去更新脚本。

**Comment by XIU2** [comment]
已添加 iconfont 支持。

**Comment by XIU2** [comment]
后续又添加了不少，比如：
github、pixiv、pornhub（最近开始支持这类网站了，但都分到外置翻页规则中了）。

**Comment by XIU2** [comment]
因为提 NSFW 的人太多了，所以我后来整了个 `自定义翻页规则`、`外置翻页规则`，并同意制作 NSFW 网站翻页规则了。

你提的部分 NSFW 网站，几个月前添加支持了，今天翻 Issues 看到顺便跟你说一下~

**Comment by XIU2** [comment]
@opkhkh 已更新添加其他页面的支持了。
