### ISSUE TITLE
Safari支持

### ISSUE THREAD

**Issue by ppttvs** [XIU2/UserScript#84]
大佬有没有精力适配一把Safari的兼容性呀，有的站能用有的用不了😂

**Comment by XIU2** [comment]
我没有 MAC 设备，即没有 Safari 浏览器可供我测试。
另外 Safari 的兼容性问题比较多，已经超出我能处理的能力范围了。

比如我发现并不是我的知乎脚本在 Safari 的知乎上用不了，而是所有脚本在 Safari 的知乎上都用不了，其他浏览器都正常。

**Comment by ppttvs** [comment]
> 我没有 MAC 设备，即没有 Safari 浏览器可供我测试。
> 另外 Safari 的兼容性问题比较多，已经超出我能处理的能力范围了。
> 
> 比如我发现并不是我的知乎脚本在 Safari 的知乎上用不了，而是所有脚本在 Safari 的知乎上都用不了，其他浏览器都正常。

自动翻页百度能用，游民和知乎都用不了🤣

**Comment by ppttvs** [comment]
找了好几个自动翻页的 都是Safari不能用...

**Comment by XIU2** [comment]
知乎所有油猴脚本都用不了，这属于知乎与 Safari 之间兼容性的问题，就算我新建一个脚本，只写一句控制台输出文字的代码也无法运行。

**Comment by ppttvs** [comment]
> 知乎所有油猴脚本都用不了，这属于知乎与 Safari 之间兼容性的问题，就算我新建一个脚本，只写一句控制台输出文字的代码也无法运行。

好吧  可惜了 还是Chrome大法算了

**Comment by XIU2** [comment]
我以前见 Tampermonkey 的作者吐槽过，Safari 一更新，就有一大片油猴脚本失效~
