### ISSUE TITLE
能否做一个屏蔽用户和关键词的NGA论坛的插件呀？

### ISSUE THREAD

**Issue by lancolor0214** [XIU2/UserScript#86]
类似全球主机论坛这个插件一样的 只要能用在NGA论坛就可以了

**Comment by XIU2** [comment]
兴趣不大。

不管是 `[知乎增强]`、`[全球主机论坛增强]` 还是其他的 `[... 增强]` 脚本，都是因为我**经常访问浏览**这些网站，才有**兴趣和动力**去制作这些论坛的独立脚本。
对于其他我不感兴趣或不看的网站，自然也**没有兴趣和动力**去折腾了，毕竟编写这些针对性的功能都是很**费时间**的，而且不经常去使用这些脚本功能的话（也就是经常浏览这些网站），也无法发现这些脚本的问题或需要优化的地方。
