### ISSUE TITLE
知乎首页点击推荐网站会崩溃

### ISSUE THREAD

**Issue by cxneol** [XIU2/UserScript#87]
1.打开知乎网站
2.多次点击推荐选项
3.网页崩溃
![QQ截图20210902134731](https://user-images.githubusercontent.com/48684655/131788929-d24131fb-5b34-447a-b48b-ad20f99786e2.png)

**Comment by XIU2** [comment]
定位到是 [屏蔽指定类别] 代码导致的，具体原因和解决办法我需要研究下什么。

**Comment by XIU2** [comment]
已经更新修复了。

**Comment by cxneol** [comment]
l

**Comment by XIU2** [comment]
看起来你似乎是想隐藏这个 Issues，但是修改标题和内容是没用的，因为都是可以查看修改前内容的。
如果你需要的话，我可以帮你删除这个 Issues。
