### ISSUE TITLE
[无缝翻页] 支持 GitHub Stars

### ISSUE THREAD

**Issue by H4M5TER** [XIU2/UserScript#88]
https://github.com/username?tab=stars

**Comment by XIU2** [comment]
看了下发现 Github 这个页面竟然不是动态加载的，那就没什么问题了，稍后添加支持~

**Comment by XIU2** [comment]
已更新添加支持。

**Comment by H4M5TER** [comment]
这两天试了一下 似乎在成功追加了几页(因为上一页按钮可以点)之后失效了

**Comment by XIU2** [comment]
你提供一个 URL 让我试试，我当初添加时，只在我的 Stars 页面试了下，但是就两页。。。

**Comment by XIU2** [comment]
已更新。
我发现我们两个的 Stars 页面元素略有差异（你的多了个右侧列），调整了一下翻页规则，测试后我们两个的都能正常翻页了。

**Comment by H4M5TER** [comment]
速度好快 给力
