### ISSUE TITLE
[护眼模式] 在部分网页中会将图片进行反色

### ISSUE THREAD

**Issue by breathiness** [XIU2/UserScript#89]
在 [泰拉通讯枢纽](https://arknightscommunity.drblack-system.com/) 还有[MEW](https://mew.fun/)中主页的图片都会显示为反色模式。  
这个可以优化一下吗？

![图片](https://user-images.githubusercontent.com/11361630/132150259-683fc606-0219-4df5-8088-66568bf6e23f.png)
![图片](https://user-images.githubusercontent.com/11361630/132152596-1ac854f2-fdf4-475a-8fd5-af0bdcf67220.png)

**Comment by XIU2** [comment]
这个是**模式三无法解决的缺陷**。
虽然我配置了 img video 元素再次反色（相当于 360° 又回来原本样子了），但是这只对大部分网站有效。
部分网站，比如你这个网站，会因为自身样式的问题导致 img 没有被再次反色回去。

这类网站只能针对性的解决，比较蛋疼，因此我平时主要还是使用 **模式二**。

**Comment by breathiness** [comment]
好吧，我跟网站那边反馈一下。看看能不能从他们那边解决😂

**Comment by XIU2** [comment]
这你就别指望。。。
估计它们也不会因为这个而修改网页架构。

**Comment by XIU2** [comment]
纯 CSS 方式是没有解决办法，但是刚才想了想还有个 JS+CSS 的解决方法。
不过感觉效率很低。。。

那就是遍历网页的所有元素（成百上千），检查每个元素是否有背景图片，如果有就添加 `filter: invert(1)` 样式使其再次反色。
不过缺陷也很多，比如：
1. 效率低下
2. 该元素内的其他元素也会被再次反色回去
3. 如果网页会自动无缝加载下一页，或者说网页元素会动态变化，脚本就需要重新遍历一遍，但是脚本毕竟不是人，无法完全区分是否需要重新遍历，这就会导致**大量重复**的去执行遍历代码，**浪费大量系统资源**。

总归，想要**解决一个问题**，就会**引出更多问题**，越想越复杂，越想越麻烦~
