### ISSUE TITLE
能否给Github里Actions的云编译文件添加下载加速？

### ISSUE THREAD

**Issue by wuelliott** [XIU2/UserScript#9]
Github里Actions的云编译文件下载超过40M的文件，经常会中断，导至下载的压缩包文件不完整，有时下载十几二十兆也会中断，希望能给添加个加速下载的通道。感谢！

**Comment by XIU2** [comment]
给个地址让我看看。

**Comment by wuelliott** [comment]
https://github.com/wuelliott/lede/actions/runs/416767514
OpenWrt_firmware这个60M左右的文件，我这边经常下到30-40M左右就中断了。

**Comment by XIU2** [comment]
因为我的 Github 高速下载脚本，本质上是把那些提供 Github 文件加速下载的网站整合并将高速下载地址显示到网页中。  

而我经过测试，目前这些加速网站都不支持 `pipelines.actions.githubusercontent.com` 文件加速...  

这样的话，我就没什么办法了。

**Comment by wuelliott** [comment]
明白了，感谢答复！

**Comment by XIU2** [comment]
不过很奇怪，这个域名明明是用的微软香港服务器，为什么速度会这么慢。。。

**Comment by wuelliott** [comment]
我用谷歌云香港的梯子也下不动

**Comment by XIU2** [comment]
如果挂了梯子都不行，那可能是这个服务器自身问题？  

毕竟香港梯子链接香港服务器正常情况下不可能出现速度瓶颈。  

而且我以前也用过一段时间微软的香港服务器，速度很快的，这个微软香港服务器不知道为什么那么慢。

**Comment by wuelliott** [comment]
英文不好，不懂该如何反馈。

**Comment by XIU2** [comment]
奇怪，我下载到 60.0 MB 时，突然就结束了，而且没有提示网络错误、下载中断等情况。

但实际上却没有下载完整。

![1](https://user-images.githubusercontent.com/54703944/102845316-43c12e80-4448-11eb-87b3-50819bfc22d9.png)

**Comment by wuelliott** [comment]
是的，就是这种情况。

**Comment by XIU2** [comment]
不对，我试了下，压缩包是可以打开的，也可以正常解压，压缩包测试也通过，没有问题。

**Comment by wuelliott** [comment]
60M就是完整的了，网面上的是未压缩的大小。

**Comment by XIU2** [comment]
我是联通，用的是 Chrome 浏览器，我还打开了浏览器隐藏的多线程下载功能。

`chrome://flags/#enable-parallel-downloading`

**Comment by wuelliott** [comment]
![image](https://user-images.githubusercontent.com/42060326/102845732-2476d100-4449-11eb-8c02-c42a6ddd3d00.png)
我是用的IDM下载，电信网

**Comment by XIU2** [comment]
你试过单纯的浏览器单线程下载吗？  

会不会是你的网络问题（当地电信运营商）？

**Comment by wuelliott** [comment]
试过，用的新版EDGE，单线程下载的文件更小。这个Actions里的文件好像是不支持多线程的。

**Comment by wuelliott** [comment]
现在这样我也怀疑是电信的问题。

**Comment by XIU2** [comment]
奇怪，我把浏览器的多线程下载功能关了后，发现下载速度暴涨。。。

多线程下载是 300~400KB/s，单线程怎么就 几MB/s 了呢。。。

![3](https://user-images.githubusercontent.com/54703944/102845989-c8f91300-4449-11eb-891d-94154f4a11bc.png)

**Comment by XIU2** [comment]
对了，才看到这个文件下载时是没有提供**文件总大小**，是**实时压缩下载**的吗？

没有文件总大小，就无法多线程下载，因为多线程下载是等份分割文件再去同时并行下载，不知道文件大小就没办法等份分割文件。

**Comment by wuelliott** [comment]
是实时压缩的，所以下载时显示不了文件大小。

**Comment by XIU2** [comment]
我又把浏览器多线程下载功能打开了，测速结果和关闭是一样的。

毕竟无论是打开还是关闭，这个文件都是单线程下载。。。

至于你的问题，我可能帮不了你，很可能是网络问题（电信），不过你说挂梯子都不行，那就很奇怪。

**Comment by wuelliott** [comment]
谢谢你的答复解惑，我找出问题的原因了，是路由里酸酸乳造成的，把下载地址的域名放到梯子外边，用直接电信网去下载就可以了。再次感谢这么好用的脚本！

**Comment by XIU2** [comment]
能帮到你就好~  
那我关闭该 Issues 了，有什么问题可以重新开启。
