### ISSUE TITLE
[蓝奏云网盘增强] 自定义分享链接域名 功能失效

### ISSUE THREAD

**Issue by D33274D7C6** [XIU2/UserScript#91]
蓝奏云网盘增强 自定义分享链接域名只能修改成www.lanzoui.com 其他都不行

**Comment by XIU2** [comment]
我改了几个域名，都一切正常，没有问题。
你说的不行是什么样的？
你是在脚本菜单 `[自定义分享链接域名]` 中修改的吗？别告诉我你跑到蓝奏云个人中心里去修改了。。。

**Comment by XIU2** [comment]
不吭声就默认为是乌龙，有问题可以继续在本 Issues 下回复。
