### ISSUE TITLE
[知乎增强] 希望添加"去除标签页标题中的消息提示"功能

### ISSUE THREAD

**Issue by HeronZhang** [XIU2/UserScript#92]
当登录知乎账号后，打开知乎回答页面，页面的标题前面就会显示（XX私信/XX消息）。使得同时打开多个知乎标签页时候没办法通过标签页标题区分不同的页面。

所以希望可以添加一个把标题中的（XX私信/XX消息）去掉的功能。

![image](https://user-images.githubusercontent.com/35218132/133219537-1cbe6075-927c-4310-b13a-ba216ceafa8d.png)

**Comment by XIU2** [comment]
这个功能的难点主要是如何去实现监控标题的变化。
另一个就是，因为涉及私信、消息，所以我需要别人和我配合才能测试功能。。。

**Comment by XIU2** [comment]
脚本已经更新，新增 `[净化标题消息]` 功能。
正好有个人私信问我问题，我就顺便试验了下解决了。

**Comment by HeronZhang** [comment]
感谢~
