### ISSUE TITLE
[Github 增强] Clone下载功能失效

### ISSUE THREAD

**Issue by whx1024** [XIU2/UserScript#94]
![2021-09-19 (2)](https://user-images.githubusercontent.com/30387816/133913577-2a610590-f51a-4022-bc4a-6c8fd30c8b72.png)
多地址的clone失效
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36 Edg/93.0.961.52

**Comment by XIU2** [comment]
已修复，是 Github 网页变动了，将这个 Code 元素延迟加载了（导致脚本执行的时候找不到元素）。
解决方法也很简单，延迟添加这部分加速下载按钮即可~
