### ISSUE TITLE
[护眼模式] 部分网页会出现局部未覆盖完全

### ISSUE THREAD

**Issue by breathiness** [XIU2/UserScript#95]
使用模式三时部分页面在刚打开的状态是整页都是正常的护眼模式。但是往下翻页后会有一部分会变成白色。  

archwiki 可以稳定触发：<https://wiki.archlinux.org/>

![图片](https://user-images.githubusercontent.com/11361630/133975841-b046729c-7a08-40ff-97e3-8eaa16247b09.png)

这种情况是可以修复的吗？

**Comment by XIU2** [comment]
我试了下，无法触发你说的问题。
![01](https://user-images.githubusercontent.com/54703944/133983261-ccb9d8ef-5c94-4fcc-8c4f-790b009e8208.png)

**Comment by breathiness** [comment]
我这边是稳定触发的，测试了 windows 和 linux 系统的 firefox 都有同样的问题。如图：
![2021-09-20](https://user-images.githubusercontent.com/11361630/134026328-7b61d672-c0ce-4060-9a07-9afd4c76464d.gif)

**Comment by XIU2** [comment]
Firefox 浏览器呀。。。
我是用 Chrome/Edge 浏览器测试的。

这个问题本质还是这两类浏览器的**执行 CSS 标准不一致**导致的。
同一个 CSS 滤镜样式在这两类浏览器上表现结果不一样，这种 CSS 标准问题我无法解决。。。

**Comment by breathiness** [comment]
好的，了解了😂
