### ISSUE TITLE
[全球主机交流论坛 增强] 希望能优化回复\发帖的位置

### ISSUE THREAD

**Issue by imsgj** [XIU2/UserScript#96]
脚本有自动翻页的功能,希望把回复\发帖的功能移到固定地方,或添加一个随屏幕滚动的回复\发帖按钮,不然的话想回复\发帖很麻烦

**Comment by XIU2** [comment]
论坛一直就有啊。。。
帖子内网页右侧悬浮的 [快速回复] 按钮：
![01](https://user-images.githubusercontent.com/54703944/134113950-904a1211-e072-4311-b86e-b82aa3e4670a.png)

至于发帖，你右键点击网页左右两侧空白处，就会快捷回到顶部了，你再去点左上角的发帖按钮就行了。
毕竟大家大都是看帖、回帖的，很少有天天发帖的。
