### ISSUE TITLE
希望制作一个为网站创建小地图导航的脚本

### ISSUE THREAD

**Issue by breathiness** [XIU2/UserScript#99]
希望能增加为所有网页添加类似文本编辑器小地图导航的功能。  
目前我是在 GitHub 找到了有个几年前的项目是实现了这个功能的。但是只支持 chrome 扩展，Firefox 没办法使用。这个可以通过脚本实现功能吗？

GitHub：<https://github.com/imagentleman/mobiusjs>

演示网站：<http://imagentleman.github.io/>

chrome 插件：<https://chrome.google.com/webstore/detail/mobius/hodeaeahgdlapjmmblhdhhplckchmbaf>

**Comment by XIU2** [comment]
Get 不到这个点。。。
试了下这个网站感觉挺别扭的。。。

**Comment by breathiness** [comment]
主要还是为了快速预览网页内容。替代浏览器的滚动条。  
那个网页的操作方式确实有点怪。但是好处是在浏览网页时可以不需要点击拖动滚动条。直接鼠标移动就能快速移动。  
我自己也是更习惯 VScode 那种方式。主要是这个东西是真的没有其他替代品了啊。只找到这个项目。
![图片](https://user-images.githubusercontent.com/11361630/134765144-d65fdfa5-6eea-43eb-8b53-295669550b54.png)

**Comment by XIU2** [comment]
抱歉，我对这功能兴趣不大，没有什么动力去研究，毕竟这功能也不是随手就能写出来的。。。

**Comment by breathiness** [comment]
好的，了解了
